po-ui/po-angular

- projects/ui/src/lib/services/po-language/po-language.service.ts
***
[DTHFUI-1229](http://jiraproducao.totvs.com.br/browse/DTHFUI-1229)
- [DTHFUI-1253](http://jiraproducao.totvs.com.br/browse/DTHFUI-1253) - o provedin do PoLanguageService deve ser configurado como root
***
**Situação:** o *providedIn* do `PoLanguageService` não está configurado como *root*.
**Solução:** realizado definição do *providedIn* como *root*.
**Simulação:** *buildar o projeto UI e utiliza-lo em uma aplicação que utilize o serviço `i18n`.
> Além do próprio Portal que pode ser utilizado para teste, nos anexos da tarefa há uma aplicação que também pode ser utilizada para teste.
***
> po-language/DTHFUI-1229 - o provedin do PoLanguageService deve ser configurado como root

- projects/templates/src/lib/components/po-page-background/po-page-background.component.ts
- projects/templates/src/lib/components/po-page-login/po-page-login-base.component.spec.ts
- projects/templates/src/lib/components/po-page-login/po-page-login-base.component.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.service.spec.ts
- projects/ui/src/lib/services/po-language/po-language.service.spec.ts
**[DTHFUI-835](http://jiraproducao.totvs.com.br/browse/DTHFUI-835)**
DTHFUI-1259 - po-page-login - adicionar a opção de tradução para o idioma russo.
**Situação**
Necessária a opção de idioma russo para traduzir as strings da página po-page-login
**Solução**
- Criada nova opção de idioma para tradução das literais.
**Simulação**
- Ideal é testar utilizando o sample labs do UI ou o portal.
> po-page-login/DTHFUI-835 - opção de tradução para o idioma russo

- projects/ui/src/lib/components/po-field/po-select/po-select.component.spec.ts
- projects/ui/src/lib/components/po-field/po-select/po-select.component.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.service.spec.ts
- projects/ui/src/lib/services/po-language/po-language.service.spec.ts
**DTHFUI-963 ([JIra](http://jiraproducao.totvs.com.br/browse/DTHFUI-963))**
DTHFUI-1242 po-select - Codificação
DTHFUI-1282 po-select - Testes unitários
**Situação**
O scroll não estava obedecendo a opção informada por meio da propriedade vinculada ao ngModel.
**Solução**
Foram revisadas as chamadas de métodos referentes ao cálculo de altura do scroll para quando houver um valor atribuído por meio do ngModel.
**Simulação**
Basta definir um valor para o ngModel do select e testar scroll ao carregar a tela.
> po-select/DTHFUI-963 - scroll dos itens não funciona quando o valor é atribuído por meio do ngModel

- CONTRIBUTING.md
- docs/pull-request-template.md
**Documentation**
**DTHFUI-1265**
O Portinari não possui uma documentação de como contribuir.
Foram criados dois arquivos para facilitar a contribuição e definir as regras para criação de branchs, commits e pull requests:
- CONTRIBUTING.md
- pull-request-template.md
**Simulação**
Pode validar entrando na branch e visualizando no VS Code os documentos.
> docs(documentation): adiciona Contributing

- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.ts
**PO-LOOKUP**
**DTHFUI-1286**
Ao informar um código 0 a descrição do registro está ficando em branco.
O componente permite informar um código 0 e ao filtrar a descrição aparece corretamente.
**Simulação**
Acessar uma API que tenha retorno o value como 0.
• Para simulação, utilizei o pacote json-server para simular uma API (https://www.npmjs.com/package/json-server);
Arquivo json:
```
{
  "lookup": {
    "items": [{
      "label": "00000",
      "value": 0
    }, {
      "label": "11111",
      "value": 1
    }, {
      "label": "22222",
      "value": 2
    }],
    "hasNext": true
  }
}
```
Arquivo app.component.html
```
<thf-lookup …
```
> fix(lookup) corrige descrição dos registros

- projects/ui/karma.conf.js
- projects/ui/src/lib/components/po-navbar/po-navbar-actions/po-navbar-action-popup/po-navbar-action-popup.component.spec.ts
- projects/ui/src/lib/components/po-navbar/po-navbar-actions/po-navbar-action-popup/po-navbar-action-popup.component.ts
- projects/ui/src/lib/components/po-navbar/po-navbar-actions/po-navbar-action/po-navbar-action.component.html
- projects/ui/src/lib/components/po-navbar/po-navbar-actions/po-navbar-action/po-navbar-action.component.spec.ts
- projects/ui/src/lib/components/po-navbar/po-navbar-actions/po-navbar-action/po-navbar-action.component.ts
- projects/ui/src/lib/components/po-navbar/po-navbar-actions/po-navbar-actions.component.spec.ts
- projects/ui/src/lib/components/po-navbar/po-navbar-actions/po-navbar-actions.component.ts
- projects/ui/src/lib/components/po-navbar/po-navbar-base.component.spec.ts
- projects/ui/src/lib/components/po-navbar/po-navbar-base.component.ts
- projects/ui/src/lib/components/po-navbar/po-navbar-item-navigation/po-navbar-item-navigation-icon/po-navbar-item-navigation-icon.component.html
- projects/ui/src/lib/components/po-navbar/po-navbar-item-navigation/po-navbar-item-navigation-icon/po-navbar-item-navigation-icon.component.spec.ts
- projects/ui/src/lib/components/po-navbar/po-navbar-item-navigation/po-navbar-item-navigation-icon/po-navbar-item-navigation-icon.component.ts
- projects/ui/src/lib/components/po-navbar/po-navbar-item-navigation/po-navbar-item-navigation.component.html
- projects/ui/src/lib/components/po-navbar/po-navbar-item-navigation/po-navbar-item-navigation.component.spec.ts
- projects/ui/src/lib/components/po-navbar/po-navbar-item-navigation/po-navbar-item-navigation.module.ts
- projects/ui/src/lib/components/po-navbar/po-navbar-items/po-navbar-item/po-navbar-item.component.html
- projects/ui/src/lib/components/po-navbar/po-navbar-items/po-navbar-item/po-navbar-item.component.spec.ts
- projects/ui/src/lib/components/po-navbar/po-navbar-items/po-navbar-item/po-navbar-item.component.ts
- projects/ui/src/lib/components/po-navbar/po-navbar-items/po-navbar-items.component.spec.ts
- projects/ui/src/lib/components/po-navbar/po-navbar-logo/po-navbar-logo.component.spec.ts
- projects/ui/src/lib/components/po-navbar/po-navbar-logo/po-navbar-logo.component.ts
- projects/ui/src/lib/components/po-navbar/po-navbar.component.html
- projects/ui/src/lib/components/po-navbar/po-navbar.component.spec.ts
- projects/ui/src/lib/components/po-navbar/po-navbar.component.ts
- projects/ui/src/lib/components/po-navbar/po-navbar.module.ts
**PO NAVBAR**
**DTHFUI-1065**
Não haviam testes unitários e o código precisava de melhorias.
A logo do navbar está com espaçamento correto, refactor do código e testes unitários adicionados.
**Simulação**
Utilizar a [PR do repositório style](https://github.com/portinariui/portinari-style/pull/5)
Validar diversas situações do navbar:
- com menu do usuário
- sem menu do usuário
- abrindo mobile e depois crescendo
- abrindo grande e depois entrando em mobile
- varios itens da navbar (navegação)
- sem logo
- com logo
- quando tem menu de usuário em telas menores que 768px:
deve criar um subItem de menu chamado "navbar links" no menu do …
> test(navbar): adiciona testes unitários ao componente

- projects/ui/src/lib/components/po-menu/po-menu.component.ts
- projects/ui/src/lib/components/po-navbar/po-navbar-base.component.spec.ts
- projects/ui/src/lib/components/po-navbar/po-navbar-base.component.ts
- projects/ui/src/lib/components/po-navbar/po-navbar.component.spec.ts
- projects/ui/src/lib/components/po-navbar/po-navbar.component.ts
**PO NAVBAR**
**DTHFUI-1150**
Ao utilizar  po-menu e po-navbar juntos e com logo mantém as duas logos.
Ao utilizar  po-menu e po-navbar com logo mantém a logo apenas no po-navbar
**Simulação**
Exemplo de código:
```
<po-navbar
p-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Barbie_Logo.svg/1200px-Barbie_Logo.svg.png"
p-shadow
[p-items]=" [ { label: 'Home'}, { label: 'Settings'}, { label: 'Our Products'}, { label: 'About us'}]"
[p-menu]="userMenu">
</po-navbar>
<div class="po-wrapper">
<po-menu #userMenu
p-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Barbie_Logo.svg/1200px-Barbie_Logo.svg.png" …
```
> feat(navbar): remove a logo do menu utilizado com navbar

- projects/templates/src/lib/components/po-page-blocked-user/po-page-blocked-user-contacts/po-page-blocked-user-contacts.component.spec.ts
**PO PAGE BLOCKED USER CONTACTS**
**DTHFUI-1129**
Os testes do componente estavam quebrando por causa de um setTimeout e por isso os testes estavam sendo pulados.
Foi verificado que os testes não estão mais quebrando, por isso foi retirado o "x" dos testes unitários.
**Simulação**
Executar os comandos de testes várias vezes e em  diferentes sistemas operacionais.
> test(page-blocked-user-contacts): remove o x do describe

- projects/ui/src/lib/components/po-table/po-table-subtitle-footer/po-table-subtitle-footer.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-subtitle-footer/po-table-subtitle-footer.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-airfare/sample-po-table-airfare.component.ts
**PO TABLE**
**DTHFUI-864**
Quando utilizado dentro de um po-tab o botão `visualizar legenda` sempre ficava visível e quando dava resize ele desaparecia.
Apenas fica visível quando necessário (se não houver espaço para os itens)
**Simulação**
Utilizar o sample `thf-table-airfare` dentro de um po-tab, validar também o funcionamento fora do tab para validar se nada aconteceu.
Exemplo de código:
```
<po-tabs>
<po-tab p-label="Totvs Tabs 1">
<sample-po-table-airfare></sample-po-table-airfare>
</po-tab>
</po-tabs>
```
> fix(table): corrige a exibição do botão de visualizar legenda

- projects/ui/src/lib/components/po-button-group/po-button-group.component.spec.ts
- projects/ui/src/lib/components/po-button/po-button.component.html
- projects/ui/src/lib/components/po-button/po-button.component.spec.ts
- projects/ui/src/lib/components/po-button/po-button.module.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.spec.ts
- projects/ui/src/lib/components/po-loading/po-loading-icon/po-loading-icon.component.html
- projects/ui/src/lib/components/po-loading/po-loading-icon/po-loading-icon.component.spec.ts
- projects/ui/src/lib/components/po-loading/po-loading-icon/po-loading-icon.component.ts
- projects/ui/src/lib/components/po-loading/po-loading.component.html
- projects/ui/src/lib/components/po-loading/po-loading.component.spec.ts
- projects/ui/src/lib/components/po-loading/po-loading.module.ts
- projects/ui/src/lib/components/po-menu/po-menu-filter/po-menu-filter.component.html
- projects/ui/src/lib/components/po-menu/po-menu-filter/po-menu-filter.component.spec.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.spec.ts
- projects/ui/src/lib/components/po-menu/po-menu.module.ts
- projects/ui/src/lib/components/po-modal/po-modal.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-default/po-page-default.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-detail/po-page-detail.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-edit/po-page-edit.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.spec.ts
- projects/ui/src/lib/directives/po-tooltip/po-tooltip.directive.spec.ts
PO LOADING
DTHFUI-796
Em conexões 3g foi detectada uma lentidão no carregamento do ícone de carregamento de conteúdo. 
- Criação do componente `po-loading-icon`;
- Chamado componente em :`po-button`, `po-menu-filter` e `po-loading`;
- Definida propriedade `p-neutral-color` em `po-loading-icon` para estabelecer a cor do ícone de carregamento;
- Redefinidos todos imports para o módulo do `po-button` nos testes unitários que o requerem pois dava erro relacionado ao novo componente criado e importado dentro do componente `po-button`; 
**Simulação**
Favor testar em dispositivos diversos em especial simulando uma conexão 3g. No Chrome …
> fix(loading): trata o ícone de carregamento para conexões 3g

- projects/ui/src/lib/components/po-table/po-table.component.html
**PO-TABLE**
**DTHFUI-1221**
O clicar na action da linha da table, o menu abre por baixo da borda da tabela no iPad.
Alterada a hierarquia do componente de popup para que o mesmo fique acima do componente de tabela quando for aberto.
**Simulação**
Executar sample labs, incluir um 2~3 itens e definir o `Actions`, clicar nas _actions_ do item da tabela e verificar sobreposição.
> fix(table): corrige sobreposição do popup em dispositivos mobile iOS

- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.html
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
- projects/ui/src/lib/components/po-modal/po-modal.component.html
- projects/ui/src/lib/components/po-modal/po-modal.component.spec.ts
**PO-COMBO**
**DTHFUI-1421**
Quando habilita a propriedade t-click-out na modal e tem um combo dentro, ao selecionar uma opção no combo a modal fecha automaticamente.
Ao selecionar um item no combo, não deve fechar a modal, a mesma deverá permanecer aberta até que o usuário feche clicando nas ações ou utilizando o click-out.
**Simulação**
Abaixo como reproduzir.
````
<po-button
p-label="Open modal"
(p-click)="modal.open()">
</po-button>
<po-modal #modal
p-title="Totvs Modal"
[p-click-out]="true">
<po-combo
name="combo"
p-label="Totvs Combo"
[p-options]="[{ value: 'Option 1' }, { value: 'Option 2' }]">
</po-combo>
</po-modal>
```` …
> fix(modal): corrige fechamento da modal ao selecionar uma opção no combo

- angular.json
- projects/app/src/app/app.module.ts
**APP COMPONENT**
**DTHFUI-1290**
Ao utilizar o repositório do portinari para executar os samples, ele não consegue encontrar os códigos fontes utilizando `@portinari/portinari-ui`, por exemplo.
Para conseguir utilizar, está sendo necessário alterar de `@portinari/portinari-ui ` para colocar o caminho relativo.
Outro problema que acontece é que em alguns componentes, não estava sendo encontrado os componentes internos. Por exemplo, ao utilizar o sample do ` po-button`, ele não conseguia encontrar o loading e acabava gerando erro no console.
O que estava gerando estes erros era a forma como o módulo estava sendo importado no …
> fix(app): corrige os erros ao utilizar os samples

- projects/templates/src/lib/components/po-modal-password-recovery/po-modal-password-recovery-base.component.ts
- projects/templates/src/lib/components/po-modal-password-recovery/po-modal-password-recovery.component.spec.ts
- projects/templates/src/lib/components/po-modal-password-recovery/po-modal-password-recovery.component.ts
- projects/templates/src/lib/components/po-page-change-password/po-page-change-password.component.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.ts
- projects/templates/src/lib/components/po-page-login/interfaces/po-page-login-literals.interface.ts
- projects/templates/src/lib/components/po-page-login/po-page-login-base.component.ts
- projects/templates/src/lib/components/po-page-login/po-page-login.component.ts
- projects/templates/tsconfig.lib.json
- projects/ui/src/lib/components/po-calendar/po-calendar-base.component.ts
- projects/ui/src/lib/components/po-calendar/po-calendar.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range.component.html
- projects/ui/src/lib/components/po-field/po-datepicker/po-calendar/po-calendar.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-calendar/po-calendar.component.ts
- projects/ui/src/lib/components/po-field/po-radio-group/po-radio-group.component.html
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.ts
- projects/ui/src/lib/components/po-navbar/po-navbar-items/po-navbar-item/po-navbar-item.component.ts
- projects/ui/src/lib/components/po-page/po-page-edit/po-page-edit.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-edit/po-page-edit.component.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.ts
- projects/ui/src/lib/components/po-slide/po-slide-item/po-slide-item.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-toolbar/po-toolbar.component.html
- projects/ui/tsconfig.lib.json
**BUILD**
**DTHFUI-1427**
Ao compilar uma aplicação com AOT que contem o atributo fullTemplateTypeCheck no tsconfig ocorre erros de acesso no HTML.
Adicionada a propriedade fullTemplateTypeCheck no tsconfig.lib.json das bibliotecas **templates** e **ui** e corrigidos diversos erros de acesso no HTML. 
Desta forma, o usuário pode também adicionar esta mesma propriedade em seus projetos e executar --prod.
**Simulação**
Pode-se verificar o comportamento adicionando a propriedade mencionada acima na master e tentar roda `ng build ui` e `ng build templates`. Posteriormente, baixe a branch e execute o mesmo comando. Posteriormente, aplique …
> fix(build): corrige erros de compilação com --prod

- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.html
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.ts
**PO-DATEPICKER**
**DTHFUI-904**
Evento p-change só é chamado ao selecionar o valor e sair do campo
- O evento p-change passa agora a ser disparado assim que selecionar um novo valor. 
- Para alterações de valor diretamente no input o disparo ainda prevalece ao sair do campo (blur).
- Foi removido o evento (p-change) do template assim como o método `eventOnChange` pois nunca era chamado. Quem já faz a mesma função que o método removido é o método `controlChangeEmitter`. 
**Simulação**
Basta definir um evento p-change e checar o disparo na seleção de datas
> fix(datepicker): corrige disparo do p-change

- projects/ui/src/lib/components/po-field/po-decimal/po-decimal.component.spec.ts
- projects/ui/src/lib/components/po-field/po-decimal/po-decimal.component.ts
**PO-DECIMAL**
**DTHFUI-914**
O componente po-decimal aceita os caracteres "ç, [, ], {, }, !, ? e `".
O componente não aceita mais os valores citados acima.
**Simulação**
Utilizar qualquer um dos samples com o componente.
> fix(decimal): corrige aceitação de valores inválidos

- projects/ui/src/lib/components/po-page/po-page-list/po-page-list-base.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list-base.component.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.ts
- projects/ui/src/lib/components/po-page/po-page.module.ts
- projects/ui/src/lib/components/po-progress/samples/sample-po-progress-publication/sample-po-progress-publication.component.ts
**PO-PAGE-LIST**
**DTHFUI-1563**
***
***
O componente não traduz as literais de acordo com a linguagem definida no serviço I18N.
Implementado no componente o serviço `I18N` que busca a linguagem definida na aplicação, que agora passa traduzir as literais de acordo com essa linguagem retornada por este serviço.
**Simulação**
*Buildar* o projeto com a branch e, incluir nas dependências do Portal, definindo uma nova `language` nas definições do serviço de linguagem do mesmo.
> feat(page-list): traduz "busca avançada" com a linguagem utilizada no I18n

- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.ts
**PO-DATEPICKER**
**Fixes DTHFUI-1495**
***
***
Ao selecionar uma data no `po-datepicker` em modo mobile, o mesmo retorna o foco para o campo, abrindo caixa de texto do dispositivo móvel, fazendo com que o usuário sempre tenha que realizar o *blur* para fechar a caixa de texto.
Agora ao selecionar uma data no componente `po-datepicker` em modo mobile, o *overlay* do calendário é fechado e não abre a caixa de texto, possibilitando que o usuário tenha uma experiencia mais amigável.
**Simulação**
Utilizar os *samples*.
> fix(datepicker): corrige foco no campo após selecionar data no mobile

- projects/ui/src/lib/components/po-navbar/po-navbar.component.spec.ts
**PO-NAVBAR**
**DTHFUI-1674**
***
***
Ao executar os testes unitários ocorre o seguinte erro:
`PoNavbarComponent: Methods: validateMe nuLogo should set 'menu.logo' as 'undefined' and call 'menu.changeDetector.detec tChanges' if has 'logo' and 'menu.logo' FAILED`
Todos os testes são validados com sucesso.
**Simulação**
executar o comando `npm run test` ou `npm run test:dev` para executar mais rápido.
> test(navbar): corrige a falha no teste do método `validateMenuLogo`

- projects/ui/src/lib/components/po-field/po-field.module.ts
- projects/ui/src/lib/components/po-field/po-upload/interfaces/po-upload-file-restriction.interface.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.component.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-drag-drop/po-upload-drag-drop.directive.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-file-restrictions/po-upload-file-restrictions.component.html
- projects/ui/src/lib/components/po-field/po-upload/po-upload-file-restrictions/po-upload-file-restrictions.component.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-file-restrictions/po-upload-file-restrictions.component.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.html
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.ts
- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-labs/sample-po-upload-labs.component.html
- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-labs/sample-po-upload-labs.component.ts
- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-resume-drag-drop/sample-po-upload-resume-drag-drop.component.html
- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-resume/sample-po-upload-resume.component.html
- projects/ui/src/lib/utils/util.spec.ts
- projects/ui/src/lib/utils/util.ts
**PO UPLOAD**
**DTHFUI-788**
Não são exibidas as informações referente às restrições dos arquivos e nem notificação caso o arquivo esteja inválido por formato, tamanho ou quantidade.
São exibidas as restrições via texto fixo, abaixo da area de drag drop e o botão de selecionar arquivo.
São exibidas notificações informando as restrições ao selecionar arquivos inválidos por formato, tamanho ou quantidade.
**Simulação**
Buildar o projeto com esta _branch_ e executar no portal.
> feat(upload): exibir informações referente as restrições dos arquivos

- projects/ui/src/lib/components/po-progress/po-progress-base.component.spec.ts
- projects/ui/src/lib/components/po-progress/po-progress-base.component.ts
- projects/ui/src/lib/components/po-progress/po-progress.component.html
- projects/ui/src/lib/components/po-progress/po-progress.component.spec.ts
- projects/ui/src/lib/components/po-progress/po-progress.component.ts
- projects/ui/src/lib/components/po-progress/samples/sample-po-progress-labs/sample-po-progress-labs.component.html
- projects/ui/src/lib/components/po-progress/samples/sample-po-progress-labs/sample-po-progress-labs.component.ts
**PO PROGRESS**
**DTHFUI-1863**
Atualmente não é possível executar um evento de tentar novamente caso ocorra algum erro no progresso.
Adiciona o evento de "tentar novamente" caso a barra de progresso ficar com status de Error e informar um evento na nova propriedade (p-retry).
**Simulação**
Executar portal com esta branch.
> feat(progress): adiciona evento de tentar novamente

- projects/ui/src/lib/components/po-field/po-field.module.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-base.component.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-body/po-rich-text-body.component.spec.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-body/po-rich-text-body.component.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-literals.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.component.html
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.component.spec.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.component.ts
- projects/ui/src/lib/utils/util.ts
**PO-RICH-TEXT**
**Fixes DTHFUI-1718**
***
***
Não é possível alterar a cor do texto para destacar determinados trechos do texto do documento ou até mesmo o texto como um todo.
Adicionada a função de alterar a cor do texto através de um novo botão na toolbar do componente, no qual executará as funções nativas de seleção de cores do navegador e aplicará ao texto selecionado e/ou as próximas digitações.
**Simulação**
Executar o(s) *sample(s)*.
***
Style*: https://github.com/portinariui/portinari-style/pull/22
> feat(rich-text): possibilita que usuário mude a cor do texto

- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-item/po-multiselect-item.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-item/po-multiselect-item.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-item/po-multiselect-item.component.ts
**PO MULTISELECT**
**DTHFUI-1857**
Ao informar `p-options` com valores numéricos muito grandes,
não era possível abrir o mesmo no Internet Explorer.
A propriedade value da tag li não deveria ser utilizada
quando a mesma estiver abaixo da tag ul, isso acabava causando problemas no IE.
Portanto foi removido a propriedade value da tag li no componente PoMultiSelectItem
**Simulação**
- Utilizar PoMultiselect com valores númericos grandes.
``` 
app.component.html
<po-multiselect
class="po-md-4"
p-label="Conta transitória"
name="multiselect"
[(ngModel)]="multiselect"
[p-options]="multiselectOptions">
</po-multiselect> …
```
> fix(multiselect): corrige comportamento do componente no IE

- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-heroes-reactive-form/sample-po-combo-heroes-reactive-form.component.html
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-heroes-reactive-form/sample-po-combo-heroes-reactive-form.component.ts
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-heroes/sample-po-combo-heroes.component.html
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-heroes/sample-po-combo-heroes.component.ts
**PO-COMBO**
**Fixes DTHFUI-865**
***
***
Nos samples Heroes, se não houver opção selecionada no THF_Combo e clicar em 'Saiba Mais', o link redireciona para busca do Google para os termos null e undefined. O método knowMore() espera um herói como parâmetro para concatenar com a URL porém está recebendo undefined / null.
Exibirá o link para click apenas se houver alguma opção selecionada no `po-combo`.
**Simulação**
Executar os *samples* no portal ou localmente.
> fix(combo): corrige comportamento dos exemplos heroes

- projects/templates/karma.conf.js
- projects/templates/src/lib/components/po-page-blocked-user/po-page-blocked-user-contacts/po-page-blocked-user-contacts.component.spec.ts
- projects/templates/src/lib/components/po-page-blocked-user/po-page-blocked-user-reason/po-page-blocked-user-reason.component.spec.ts
- projects/ui/src/lib/components/po-field/po-checkbox-group/po-checkbox-group-base.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range.component.spec.ts
**PO-CHECKBOX-GROUP**
**DTHFUI-1611**
O texto fica sobreposto quando há quebra de linha em textos muito grandes.
Foi corrigido no CDN e conforme a instrução do UX foi adicionada documentação para sugestão de boas práticas ao desenvolvedor indicando a utilização de somente 1 coluna para opções com textos muito grandes.
**Simulação**
Buildar o projeto e testar no portal.
**Obs:**
Possui PR no `portinari-style` e também no `portinari-theme`.
> fix(checkbox-group): ajusta texto sobreposto.

- projects/ui/src/lib/components/po-toolbar/po-toolbar-base.component.spec.ts
- projects/ui/src/lib/components/po-toolbar/po-toolbar-base.component.ts
- projects/ui/src/lib/components/po-toolbar/po-toolbar-profile/po-toolbar-profile.component.html
- projects/ui/src/lib/components/po-toolbar/po-toolbar-profile/po-toolbar-profile.component.spec.ts
- projects/ui/src/lib/components/po-toolbar/po-toolbar-profile/po-toolbar-profile.component.ts
- projects/ui/src/lib/components/po-toolbar/samples/sample-po-toolbar-logged/sample-po-toolbar-logged.component.html
- projects/ui/src/lib/components/po-toolbar/samples/sample-po-toolbar-logged/sample-po-toolbar-logged.component.ts
**PO-TOOLBAR**
**DTHFUI-1936**
***
***
O problema ocorre dada a falta de definição da propriedade `p-profile` tendo a definição de uma `p-profile-actions` definida no mesmo contexto.
Agora o componente permite utilizar a propriedade `p-profile-actions` sem que haja um `p-profile` definido.
**Simulação**
É possível simular o problema removendo a definição de `p-profile` no _sample logged_ do componente.
Style: https://github.com/portinariui/portinari-style/pull/38
> fix(toolbar): corrige o funcionamento sem o p-profile

- projects/templates/src/lib/components/po-page-login/po-page-login-base.component.spec.ts
- projects/templates/src/lib/components/po-page-login/po-page-login-base.component.ts
**PAGE-LOGIN**
**DTHFUI-1516**
Ao utilizar literals.title e literals.loginHint com undefined ocorria erro no componente, fazendo com que o mesmo não carregue por completo e impossibilitando seu uso.
Alterado a comparação de valores para que não ocorra o erro quando ambas propriedades estiverem com undefined.
**Simulação**
- Utilizar o page-login com [p-literals]="{ title: undefined, loginHint: undefined }".
> fix(page-login): corrige erro ao usar title e loginHint com undefined

- projects/ui/src/lib/components/po-field/po-field.module.ts
- projects/ui/src/lib/components/po-field/po-upload/interfaces/po-upload-literals.interface.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.component.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-drag-drop/po-upload-drag-drop-area-overlay/po-upload-drag-drop-area-overlay.component.html
- projects/ui/src/lib/components/po-field/po-upload/po-upload-drag-drop/po-upload-drag-drop-area-overlay/po-upload-drag-drop-area-overlay.component.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-drag-drop/po-upload-drag-drop-area/po-upload-drag-drop-area.component.html
- projects/ui/src/lib/components/po-field/po-upload/po-upload-drag-drop/po-upload-drag-drop-area/po-upload-drag-drop-area.component.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-drag-drop/po-upload-drag-drop-area/po-upload-drag-drop-area.component.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-drag-drop/po-upload-drag-drop.component.html
- projects/ui/src/lib/components/po-field/po-upload/po-upload-drag-drop/po-upload-drag-drop.component.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-drag-drop/po-upload-drag-drop.directive.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-drag-drop/po-upload-drag-drop.directive.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.html
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.ts
- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-labs/sample-po-upload-labs.component.html
- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-labs/sample-po-upload-labs.component.ts
**Upload**
**DTHFUI-787**
Como usuário eu gostaria de poder selecionar uma pasta para que o componente carregasse todos os arquivos de uma única vez.
• Criada propriedade `t-directory` para opção de seleção de diretórios;
• Quando habilitada a `t-directory`, o comportamento de seleção permite apenas seleção de diretórios;
• Tratamento para as literais para que alternem entre diretórios e arquivos;
• Tratamento específico para o browser IE pois não suporta essa funcionalidade. Para esse caso, o comportamento prevalecido é de seleção de arquivos.
• Plus: tratado encapsulamento dos itens selecionados para dentro de um container caso a …
> feat(upload): adiciona opção para envio de pastas

- projects/ui/src/lib/components/po-field/index.ts
- projects/ui/src/lib/components/po-field/po-lookup/interfaces/po-lookup-filter.interface.ts
- projects/ui/src/lib/components/po-field/po-lookup/interfaces/po-lookup-filtered-items-params.interface.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.html
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-basic/sample-po-lookup-basic.component.html
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-hero-reactive-form/sample-po-lookup-hero-reactive-form.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-hero/sample-po-lookup-hero.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-labs/sample-po-lookup-labs.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-sw-films/sample-po-lookup-sw-films.service.ts
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup.service.ts
- projects/ui/src/lib/components/po-field/po-lookup/services/po-lookup-filter.service.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/services/po-lookup-filter.service.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
**LOOKUP**
**DTHFUI-1742**
Atualmente não é repassado a coluna ordenada para o serviço.
Repassa a coluna ordenada como parametro no método getFilteredItems caso usar serviço ou inclui diretamente na URL.
Foi depreciado o método getFilteredData e criado o novo método getFilteredItems.
**Simulação**
- Utilizar Samples do Lookup do Portal
- Clicar em alguma coluna para ordenar e realizar os filtros (busca/carregar mais resultados)
- Verificar se a URL está sendo construída corretamente e se os parâmetros estão chegando corretamente no serviço customizado.
> feat(lookup): inclui coluna de ordenação na chamada do serviço 

- projects/ui/src/lib/components/po-tag/enums/po-tag-icon.enum.ts
- projects/ui/src/lib/components/po-tag/po-tag-base.component.spec.ts
- projects/ui/src/lib/components/po-tag/po-tag-base.component.ts
- projects/ui/src/lib/components/po-tag/po-tag.component.html
- projects/ui/src/lib/components/po-tag/po-tag.component.spec.ts
- projects/ui/src/lib/components/po-tag/po-tag.component.ts
- projects/ui/src/lib/components/po-tag/samples/sample-po-tag-labs/sample-po-tag-labs.component.html
- projects/ui/src/lib/components/po-tag/samples/sample-po-tag-labs/sample-po-tag-labs.component.ts
**PO-TAG**
**DTHFUI-1762**
***
***
O componente não permite utilizar as paletas de cores, ícones e navegar através do teclado.
Agora o componente permite a utilização da paleta de cores, além de ícones e navegação através do teclado.
**Simulação**
Utilizar sample labs.
Style: https://github.com/portinariui/portinari-style/pull/39
> feat(tag): permitir o uso da paleta de cores e ícones

- projects/ui/src/lib/services/po-notification/po-notification-base.service.spec.ts
- projects/ui/src/lib/services/po-notification/po-notification-base.service.ts
- projects/ui/src/lib/services/po-notification/po-notification.interface.ts
- projects/ui/src/lib/services/po-notification/po-notification.service.spec.ts
- projects/ui/src/lib/services/po-notification/po-notification.service.ts
- projects/ui/src/lib/services/po-notification/samples/sample-po-notification-labs/sample-po-notification-labs.component.html
- projects/ui/src/lib/services/po-notification/samples/sample-po-notification-labs/sample-po-notification-labs.component.ts
**PoNotificationService**
**DTHFUI-1979**
Atualmente o serviço não permite alterar o tempo de duração de uma notificação.
Serviço permite através de uma nova propriedade **duration** na interface **PoNotification**, informar a duração em milisegundos da notificação.
Ou através do método setDurationDefault, alterar o tempo padrão de todas as notificações.
**Simulação**
Ao apresentar uma duração, o tempo é sempre de 10 segundos.
Ao definir o tempo através da propriedade, a duração passa a se manter no tempo definido pelo usuário;
Ao definir o tempo através do método, todas as notificações (mesmo sem passar a duração), passam a ter o …
> feat(notification): permitir alterar tempo de duração

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
Fixes DTHFUI-2091
**po-dynamic-form-fields**
**DTHFUI-2091**
Retorna "field.property" quanto utilizado um componente lookup  
Retorna o valor informado na propriedade property do array de  campos do dynamic-form
**Simulação**
> fix(dynamic-form): name ignorado quando utilizado po-lookup

- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-list-base.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.html
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-basic/sample-po-page-dynamic-table-basic.component.html
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.component.ts
**PAGE DYNAMIC TABLE**
**DTHFUI-1743**
Não era possível saber qual coluna estava sendo ordenada ao realizar a requisição de paginação dos resultados.
Inclui coluna ordenação na requisição de paginação dos resultados.
Caso for decrescente será enviada: order=-name
Caso for ascendente será enviada: order=name
**Simulação**
Utilizar samples do componente, ordenar colunas e filtrar registros para avaliar a inclusão do queryParam "order";
> feat(page-dynamic-table): inclui coluna de ordenação na requisição

- package.json
- projects/storage/ng-package.json
- projects/storage/package.json
- projects/storage/src/lib/drivers/lokijs/po-loki-driver.spec.ts
- projects/storage/src/lib/drivers/lokijs/po-loki-driver.ts
- projects/storage/src/lib/services/po-storage-config.interface.ts
- projects/storage/src/lib/services/po-storage.service.spec.ts
- projects/storage/src/lib/services/po-storage.service.ts
- projects/sync/src/lib/services/po-schema/po-schema.service.spec.ts
- projects/sync/src/lib/services/po-schema/po-schema.service.ts
**PO-STORAGE**
**DTHFUI-1367**
O LocalForage do po-storage apenas aceita os drivers: 'websql', 'indexeddb' e 'localstorage'.
Agora o localForage do po-storage passa a aceitar um novo driver 'lokijs' que permite salvar os dados em memória aumentando consideravelmente a performance de leitura e gravação dos dados.
**Simulação**
Foi enviado um link com duas aplicações que foram feitas no thf, uma para rodar localmente e a outra é uma aplicação no ionic para poder testar nos dispositivos.
> feat(storage): adiciona po-loki-driver no storage

- projects/ui/src/lib/components/po-tag/po-tag-base.component.spec.ts
- projects/ui/src/lib/components/po-tag/po-tag-base.component.ts
- projects/ui/src/lib/components/po-tag/po-tag.component.html
- projects/ui/src/lib/components/po-tag/po-tag.component.spec.ts
- projects/ui/src/lib/components/po-tag/po-tag.component.ts
- projects/ui/src/lib/components/po-tag/samples/sample-po-tag-bank-account/sample-po-tag-bank-account.component.html
- projects/ui/src/lib/components/po-tag/samples/sample-po-tag-labs/sample-po-tag-labs.component.html
- projects/ui/src/lib/components/po-tag/samples/sample-po-tag-labs/sample-po-tag-labs.component.ts
**TAG**
**DTHFUI-1763**
Criada nova propriedade booleana `p-inverse`, permite a inversão de cores no componente.
Valor default false.
Possibilita uma representação de status ativo e inativo.
A cor do texto vira a cor do fundo e a cor do fundo vira a cor do texto e da borda.
**Simulação**
Basta testar nos Samples do componente `po-tag` no portal do portinari.
> feat(tag): permite inversão de cores

- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/test/po-dynamic-form-stub-component.ts
**po-page-dynamic-edit**
****
O formulário dynamicForm não era carregado corretamente causando o seguinte erro
ERROR TypeError: Cannot read property 'form' of undefined
quando usuário selecinonava as opções de salvar ou salvar novo
Alterada a importação do ViewChild utilizando a flag static como false
Ver (https://angular.io/api/core/ViewChild)
**Simulação**
No exemplo na documentação(https://portinari.io/documentation/po-page-dynamic-edit) clique em salvar no exemplo Portinari Page Dynamic Edit - User, a ação não será executada e aparecerá o erro ERROR TypeError: Cannot read property 'form' of undefined no console.
> fix(page-dynamic-edit): corrige importação do DynamicForm

- projects/templates/src/lib/components/po-page-login/interfaces/po-page-login-literals.interface.ts
- projects/templates/src/lib/components/po-page-login/po-page-login-base.component.spec.ts
- projects/templates/src/lib/components/po-page-login/po-page-login-base.component.ts
- projects/templates/src/lib/components/po-page-login/po-page-login-popover/po-page-login-popover.component.html
- projects/templates/src/lib/components/po-page-login/po-page-login-popover/po-page-login-popover.component.spec.ts
- projects/templates/src/lib/components/po-page-login/po-page-login-popover/po-page-login-popover.component.ts
- projects/templates/src/lib/components/po-page-login/po-page-login.component.html
- projects/templates/src/lib/components/po-page-login/po-page-login.component.spec.ts
- projects/templates/src/lib/components/po-page-login/po-page-login.component.ts
**PO-PAGE-LOGIN**
**DTHFUI-2053**
- Ao modificar o idioma no seletor do template, as literais title e loginHint não respeitam a customização.
- As literais do popover relacionado ao excesso de tentativas não eram definidas na interface poPageLogin.
- Reestruturação do método getLiterals para que faça atruição correta dos objetos. Método renomeado para **assignLiterals** para uma melhor compreensão;
- Nova propriedade **pageLoginLiterals** para que a propriedade **p-literals** seja preservada;
- Repassados métodos relacionados com a concatenação das propriedades **title** e **loginHint** para fora do base;
- Refatoração do componente …
> fix(page-login): corrige literais customizadas ao trocar de idioma

- projects/ui/src/lib/components/po-field/po-url/po-url.component.spec.ts
- projects/ui/src/lib/components/po-field/po-url/po-url.component.ts
**URL**
**DTHFUI-2142**
O componente invalida links encurtados que contenham caracteres maiúsculos.
Incluída validação no regex de `port and path` e `query string` e agora considera caracteres tanto maiúsculos quanto minúsculos.
**Simulação**
Pode ser testado no portal.
Exemplo de links para teste:
- https://www.youtube.com/watch?v=E0ujHj-2z7M
- https://youtu.be/E0ujHj-2z7M
> fix(url): corrige validação de links que contenham caracteres maiúsculos

- projects/ui/src/lib/components/po-chart/po-chart-types/po-chart-circular/po-chart-circular-series.interface.ts
- projects/ui/src/lib/components/po-chart/po-chart-types/po-chart-circular/po-chart-circular.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-types/po-chart-circular/po-chart-circular.ts
- projects/ui/src/lib/components/po-chart/po-chart.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart.component.ts
**CHART**
**DTHFUI-2210**
Ao usar o chart somente com series zeradas, a animação entra em loop infinito.
Os gráficos circulares ignoram as series com valor `zero` na renderização do chart, porém mantém a exibição na legenda.
**Simulação**
Simular no sample labs do portal.
>  fix(chart): corrige animação em loop em series com valores zerados 

- projects/ui/src/lib/components/po-field/po-combo/po-combo-option-template/po-combo-option-template.directive.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-option-template/po-combo-option-template.directive.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.html
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-transfer/sample-po-combo-transfer.component.html
- projects/ui/src/lib/components/po-field/po-field.module.ts
**COMBO**
**DTHFUI-1893**
A lista de opções do combo segue o guideline proposto pelo UX.
Agora é possível definir um template customizado através da diretiva `po-combo-option-template`.
**Simulação**
O Sample Banking Transfer contempla a nova funcionalidade.
> feat(combo): permite customizar a lista de opções

- projects/ui/src/lib/components/po-table/po-table-column-icon/po-table-column-icon.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-column-icon/po-table-column-icon.component.ts
- projects/ui/src/lib/components/po-table/po-table-column-icon/po-table-column-icon.interface.ts
- projects/ui/src/lib/components/po-table/po-table-icon/po-table-icon.component.html
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
**PO-TABLE**
**DTHFUI-2398**
***
***
Os ícones estão sempre sendo exibidos independente dos valores.
Exibir só os ícones que estão sendo listados no registro.
**Simulação**
No sample de componentes, remover a definição do array na propriedade *favorite* da coluna e manter apenas uma string.
> fix(table): corrige exibição dos ícones de acordo com o valor da coluna

- projects/ui/src/lib/components/po-field/index.ts
- projects/ui/src/lib/components/po-field/po-datepicker/enums/po-datepicker-iso-format.enum.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker/samples/sample-po-datepicker-labs/sample-po-datepicker-labs.component.html
- projects/ui/src/lib/components/po-field/po-datepicker/samples/sample-po-datepicker-labs/sample-po-datepicker-labs.component.ts
**DATEPICKER**
**DTHFUI-2017**
Atualmente o formato de saída do model se ajusta conforme o formato de entrada.
- Definida nova propriedade `p-iso-format` para controle de formato de saída do model independentemente do valor de entrada recebido;
- Definido enum `PoDatepickerIsoFormat` para set de valor para a propriedade `p-iso-format`.
Obs.: Definido com o time que `PoDatepickerIsoFormat` seria mais apropriado e intuitivo do que definição `boolean` para `p-iso-format`.
**Simulação**
Sample Labs contém radio group para definição de saída do model.
> feat(datepicker): permite definir saída do model

- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-body/po-rich-text-body.component.html
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-body/po-rich-text-body.component.spec.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-body/po-rich-text-body.component.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-literals.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-modal/po-rich-text-modal.component.spec.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-modal/po-rich-text-modal.component.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.component.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text.component.html
- projects/ui/src/lib/components/po-field/po-rich-text/samples/sample-po-rich-text-recipe/sample-po-rich-text-recipe.component.ts
- projects/ui/src/lib/enums/po-key-code.enum.ts
- projects/ui/src/lib/utils/util.ts
**PO RICH TEXT**
**DTHFUI-2141**
Atualmente o usuário depois de criar um link, ele não consegue editá-lo no rich-text.
Ao utilizar a função de criar um link, o usuário pode selecionar a palavra
e editar este link que foi criado.
- Ao selecionar um texto com um link e clicar no botão 'link', a modal deve abrir com os dados relacionados ao link;
- deve permitir alterar tanto o link como o texto de exibição;
- mesmo que o usuário selecione parte do texto que contém o link, deve ser levado em consideração todo o texto usado para a exibição do link;
- a regra relacionada ao texto de link prevalece a mesma, ou seja, se o usuário não …
> feat(rich-text): permite que o usuário edite um link adicionado

- projects/ui/src/lib/components/po-tree-view/po-tree-view-base.component.spec.ts
- projects/ui/src/lib/components/po-tree-view/po-tree-view-base.component.ts
- projects/ui/src/lib/components/po-tree-view/po-tree-view-item-header/po-tree-view-item-header.component.html
- projects/ui/src/lib/components/po-tree-view/po-tree-view-item-header/po-tree-view-item-header.component.spec.ts
- projects/ui/src/lib/components/po-tree-view/po-tree-view-item-header/po-tree-view-item-header.component.ts
- projects/ui/src/lib/components/po-tree-view/po-tree-view-item/po-tree-view-item.component.html
- projects/ui/src/lib/components/po-tree-view/po-tree-view-item/po-tree-view-item.component.spec.ts
- projects/ui/src/lib/components/po-tree-view/po-tree-view-item/po-tree-view-item.component.ts
- projects/ui/src/lib/components/po-tree-view/po-tree-view-item/po-tree-view-item.interface.ts
- projects/ui/src/lib/components/po-tree-view/po-tree-view.component.html
- projects/ui/src/lib/components/po-tree-view/po-tree-view.component.spec.ts
- projects/ui/src/lib/components/po-tree-view/po-tree-view.component.ts
- projects/ui/src/lib/components/po-tree-view/po-tree-view.module.ts
- projects/ui/src/lib/components/po-tree-view/samples/sample-po-tree-view-labs/sample-po-tree-view-labs.component.html
- projects/ui/src/lib/components/po-tree-view/samples/sample-po-tree-view-labs/sample-po-tree-view-labs.component.ts
- projects/ui/src/lib/components/po-tree-view/samples/sample-po-tree-view-supermarket/sample-po-tree-view-supermarket.component.html
- projects/ui/src/lib/components/po-tree-view/samples/sample-po-tree-view-supermarket/sample-po-tree-view-supermarket.component.ts
- projects/ui/src/lib/components/po-tree-view/services/po-tree-view.service.spec.ts
- projects/ui/src/lib/components/po-tree-view/services/po-tree-view.service.ts
**Tree View**
**DTHFUI-2369**
Não permitia a seleção de item.
Adiciona a possibilidade seleção de item através da propriedade
**p-selectable** e também os eventos **p-selected** e **p-unselected.**
**Simulação**
- Utilizar os samples no portal.
> feat(tree-view): adiciona seleção de item

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-field-internal.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/samples/sample-po-dynamic-form-register/sample-po-dynamic-form-register.component.html
- projects/ui/src/lib/components/po-field/po-combo/interfaces/po-combo-filter.interface.ts
- projects/ui/src/lib/components/po-stepper/po-stepper.component.ts
- projects/ui/src/lib/services/po-i18n/po-i18n-base.service.ts
- projects/ui/src/lib/services/po-notification/po-notification-base.service.ts
- projects/ui/tsconfig.lib.json
**PO-DYNAMIC-FORM**
**DTHFUI-2415**
***
***
O componente não permite atribuir foco ao campo na inicialização ou mesmo através de um método.
Agora é possível atribuir foco ao campo desejado. Isto poderá ser feito na inicialização do componente através da propriedade `p-auto-focus` atribuindo o nome do campo à ela ou, disparando o método `focus` e passando como parâmetro o nome do campo.
**Simulação**
Utilizar os samples do *dynamic form*.
> feat(dynamic-form): permite atribuir foco nos campos

- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
**Table**
**DTHFUI-2499**
Ao abrir o detail da tabela, o colspan da linha estava sendo contado de forma incorreta,
já que quando há ações a coluna é reutilizada pelo column manager.
TH Column Manager passa a reutiliza a td das ações na contagem do colspan do detail, para que não 
amontoe as colunas.
**Simulação**
- Utilizar o Sample Po Table Air Fare
- Abrir um master detail;
> fix(table): corrige colspan quando detail estiver aberto

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/samples/sample-po-dynamic-form-register/sample-po-dynamic-form-register.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.html
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.spec.ts
**PO-LOOKUP**
**DTHFUI-2482**
***
***
- Quando existe um lookup na página o mesmo recebe o foco mesmo não sendo o primeiro elemento que deveria receber o foco.
- Abrindo o link https://portinari.io/documentation/po-dynamic-form?view=web e apertar TAB várias vezes, o mesmo vai cair em um loop infinito sem permitir que o usuário passe pelos outros elementos.
Agora o componente respeita a ordem da tabulação entre o *tabindex* dos demais elementos da tela e também remove a sobreposição da navegação entre os mesmos.
**Simulação**
https://portinari.io/documentation/po-dynamic-form?view=web
> fix(lookup): corrige comportamento focal na tabulação do html

- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-airfare/sample-po-table-airfare.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-airfare/sample-po-table-airfare.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.html
**TABLE**
**DTHFUI-1609**
Ao utilizar o thf-table há a possibilidade de incluir os registros com uma setinha para expansão dos mesmos.
Atualmente não há um evento que seja disparado ao realizar esta expansão, não sendo possível identificar qual registro exato que está sendo expandido.
- Adicionado output p-expanded: ação disparada ao expandir um registro/linha;
- Adicionado output p-collapsed: ação disparada ao expandir um registro/linha;
- Adicionado método expand: método público para expandir um registro/linha;
- Adicionado método collapse: método público para colapsar um registro/linha;
**Simulação**
Utilizar sample do componente.
> feat(table): adiciona eventos e metodos para colapsar e expandir

- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
**PO-MULTISELECT**
**DTHFUI-2524**
está disparando evento de change dentro do dynamic form na inicialização mesmo não sendo alterado, o mesmo ocorre também quando dispara uma validação de um field específico (url) + a validação para o formulário todo (url).
Não deve disparar eventos de validação se o mesmo não sofrer alteração
**Simulação**
Simular utilizando a validação dos fields e do formulário do dynamic form e verificar se está disparando evento de change no multiselect sem que o valor seja alterado.
> fix(multiselect): corrige disparo do evento change na inicialização

- projects/ui/src/lib/components/po-dynamic/index.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-load/po-dynamic-form-load.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-load/po-dynamic-form-load.service.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-load/po-dynamic-form-load.service.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-operation/po-dynamic-form-operation.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-operation/po-dynamic-form-operation.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-response.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-validation/po-dynamic-form-validation.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-validation/po-dynamic-form-validation.service.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-validation/po-dynamic-form-validation.service.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/samples/sample-po-dynamic-form-register/sample-po-dynamic-form-register.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/samples/sample-po-dynamic-form-register/sample-po-dynamic-form-register.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/samples/sample-po-dynamic-form-register/sample-po-dynamic-form-register.service.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic.module.ts
**DTHFUI-2416**
N/A
Adiciona a propriedade `p-load`, a qual, pode-se informar uma função ou uma url de um serviço, que retorne PoDynamicFormLoad, criando novos campos, atualizando-os e permitindo foca-los.
**Simulação**
- Utilizar o Sample;
- Pode-se criar um serviço no https://www.mockable.io/ e utilizar no componente;
- Importante testar funcionalidades já existentes, como p-validate;
> feat(dynamic-form): adiciona metodos para inicialização

- projects/ui/src/lib/components/po-field/po-input-generic/po-input-generic.spec.ts
- projects/ui/src/lib/components/po-field/po-input-generic/po-input-generic.ts
**po-input**
**DTHFUI-2294**
Quando é usado o mouse para colar um valor no componente po-input
com mask, o model não é atualizado.
O evento de input verifica se possui mask preenchido, se houver,
é disparado o metódo blur do mask e depois o onChange para atualizar
o model.
**Simulação**
Criar um po-input com mask e ngModel.
Copiar um valor.
Clicar com o botão direito no input e clicar em colar.
O model deve estar com o valor colado.
> fix(input): corrige o bug ao colar um texto com o mouse no input

- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor-base.service.spec.ts
- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor-base.service.ts
- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor-detail/po-http-interceptor-detail-literals.interface.ts
- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor-detail/po-http-interceptor-detail.component.html
- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor-detail/po-http-interceptor-detail.component.spec.ts
- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor-detail/po-http-interceptor-detail.component.ts
- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor-detail/po-http-interceptor-detail.interface.ts
- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor.module.ts
- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor.service.spec.ts
- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor.service.ts
- projects/ui/src/lib/interceptors/po-http-interceptor/samples/sample-po-http-interceptor-labs.component.html
- projects/ui/src/lib/interceptors/po-http-interceptor/samples/sample-po-http-interceptor-labs.component.ts
**Http Interceptor **
**DTHFUI-898**
As mensagens são concatenadas em uma string única e aparecem em um componente dialog, dificultando a visualização dos detalhes.
As mensagens são visualizadas em uma modal que possui dentro dela um accordion, que exibe os detalhes.
É possível definir um parâmetro `X-Portinari-no-Message` para não exibir mensagens de sucesso.
**Simulação**
Pode utilizar o sample lab em conjunto com o serviço que está na [PR do TFS](https://totvstfs.visualstudio.com/THF/_git/thf-sample-api-provisorio/pullrequest/17935?path=%2Froutes&_a=overview).
No sample labs utilizar o serviço com porta local: alterar de …
> feat(http-interceptor): permite exibição de múltiplas mensagens do back end

- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table-column-label/po-table-column-label.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-column-label/po-table-column-label.component.ts
- projects/ui/src/lib/components/po-table/po-table-column-link/po-table-column-link.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-column-link/po-table-column-link.component.ts
- projects/ui/src/lib/components/po-table/po-table-icon/po-table-icon.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-icon/po-table-icon.component.ts
- projects/ui/src/lib/components/po-table/po-table-subtitle-circle/po-table-subtitle-circle.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-subtitle-circle/po-table-subtitle-circle.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
**Table**
**DTHFUI-2571**
A performance do componente está um pouco lenta, devido a chamadas de funções no templates,
ngDoCheck, Differs, componentes internos sem OnPush.
Foram revistos alguns itens, tentando não
dificultar muito a revisão/funcionamento, são eles:
- OnPush em alguns componentes (de exibição) internos.
- trackBy;
- Removido chamadas de funções desnecessárias no template;
- Removido os ng-templates de dentro dos ngFor;
- Também foi reordenado as funções;
Proxímos passos:
- Componentizar mais o componente internamente; ex: po-table-header
- Avaliar a utilização apenas de dados imutáveis;;
**Simulação**
- Utilizar …
> perf(table): implementa alguns itens de performance

- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table-detail/po-table-detail.component.html
- projects/ui/src/lib/components/po-table/po-table-detail/po-table-detail.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-airfare/sample-po-table-airfare.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.ts
**TABLE**
**DTHFUI-2515**
Atualmente existe a propriedade p-checkbox que habilita na primeira coluna a opção de selecionar linhas, porém essa propriedade pode habilitar a seleção tanto através de um checkbox quanto através de um radio (caso o desenvolvedor habilite também a funcionalidade p-single-select que permite selecionar apenas uma linha da tabela).
Depreciação da propriedade p-checkbox e criação da propriedade p-selectable com a mesma funcionalidade. 
**Simulação**
Testar a funcionalidade nos samples do portal.
**PS:** Ver PR no `portinari-style`
> refactor(table): propriedade p-selectable substitui a p-checkbox

- projects/ui/src/lib/decorators/index.ts
- projects/ui/src/lib/decorators/input-boolean/input-boolean.decorator.spec.ts
- projects/ui/src/lib/decorators/input-boolean/input-boolean.decorator.ts
- projects/ui/src/lib/decorators/input-required/input-required.decorator.spec.ts
- projects/ui/src/lib/decorators/input-required/input-required.decorator.ts
- projects/ui/src/lib/decorators/property-decorator.interface.ts
- projects/ui/src/lib/decorators/utils-decorators.spec.ts
- projects/ui/src/lib/decorators/utils-decorators.ts
**Decorators**
**DTHFUI-2578**
Não existe
Implementa os novos decorators InputBoolean e InputRequired
para validação interna dos componentes.
**Simulação**
Pode substituir no po-button-base.component.ts:
```
@Input('p-disabled') set disabled(value: boolean) {
this._disabled = <any>value === '' ? true : convertToBoolean(value);
}
get disabled(): boolean {
return this._disabled;
}
```
Por:
```
@Input('p-disabled') @InputBoolean() disabled: boolean;
```
E no po-accordion-item-.component.ts:
```
@Input('p-label') label: string;
```
Por: 
```
@Input('p-label') @InputRequired() label: string;
```
> feat(decorator): novo InputBoolean e InputRequired

- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.ts
- projects/templates/src/lib/components/po-page-dynamic-search/samples/sample-po-page-dynamic-search-hiring-processes/sample-po-page-dynamic-search-hiring-processes.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
**page-dynamic-search**
**DTHFUI-2600**
Quando aplicados filtros em 'busca avançada', se o objeto do campo filtrado não tiver _label_ definido, concatena-se então o valor do campo com _undefined_
Na ausência de valor para label, deve-se concatenar o valor do campo com o valor de **property**.
**Simulação**
Basta remover um dos label do filters do sample de caso de uso SamplePoPageDynamicSearchHiringProcessesComponent.
> fix(page-dynamic-search): corrige disclaimer com label undefined

- projects/ui/src/lib/components/po-field/po-select/po-select-base.component.ts
- projects/ui/src/lib/components/po-field/po-select/po-select.component.spec.ts
- projects/ui/src/lib/components/po-field/po-select/po-select.component.ts
**Po Select**
**DTHFUI-2486**
Agora o componente também permite inicializar focado ao definir p-auto-focus.
**Simulação**
Definir p-auto-focus em algum sample do componente.
> feat(select): implementa a propriedade p-auto-focus

- projects/ui/src/lib/components/po-field/po-switch/po-switch-base.component.ts
- projects/ui/src/lib/components/po-field/po-switch/po-switch.component.spec.ts
- projects/ui/src/lib/components/po-field/po-switch/po-switch.component.ts
**Po Switch**
**DTHFUI-2485**
Agora o componente também permite inicializar focado ao definir p-auto-focus.
**Simulação**
Definir p-auto-focus em algum sample do componente.
> feat(switch): implementa a propriedade p-auto-focus

- projects/ui/src/lib/components/po-field/po-radio-group/po-radio-group-base.component.ts
- projects/ui/src/lib/components/po-field/po-radio-group/po-radio-group.component.spec.ts
- projects/ui/src/lib/components/po-field/po-radio-group/po-radio-group.component.ts
**PO-RADIO-GROUP**
**DTHFUI-2484**
***
***
Agora o componente também permite inicializar focado ao definir `p-auto-focus`.
**Simulação**
Definir `p-auto-focus` em algum *sample* do componente.
> feat(radio-group): implementa a propriedade p-auto-focus

- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
**PO-COMBO**
**DTHFUI-2485**
***
***
Agora o componente também permite inicializar focado ao definir `p-auto-focus`.
**Simulação**
Definir `p-auto-focus` em algum *sample* do componente.
> feat(combo): implementa a propriedade p-auto-focus

- projects/ui/src/lib/components/po-field/po-checkbox-group/po-checkbox-group-base.component.ts
- projects/ui/src/lib/components/po-field/po-checkbox-group/po-checkbox-group.component.spec.ts
- projects/ui/src/lib/components/po-field/po-checkbox-group/po-checkbox-group.component.ts
**PO-CHECKBOX-GROUP**
**DTHFUI-2483**
***
***
Agora o componente também permite inicializar focado ao definir `p-auto-focus`.
**Simulação**
Definir `p-auto-focus` em algum *sample* do componente.
> feat(checkbox-group): implementa a propriedade p-auto-focus

- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/samples/sample-po-multiselect-labs/sample-po-multiselect-labs.component.ts
**DTHFUI-2543**
Atualmente o componente não está validando as opções quando as mesmas são incluídas dinamicamente, pois as validações são chamadas apenas no set da propriedade.
Foi incluído o método de validação no hook ngDoCheck() e agora, mesmo com as opções incluídas dinamicamente as validações são chamadas e dessa forma o comportamento foi corrigido. 
**Simulação**
Simular no sample labs do multiselect no portal
> fix(multiselect): corrige mutabilidade no sample labs

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/samples/sample-po-dynamic-form-register/sample-po-dynamic-form-register.component.ts
**DTHFUI-2598**
Atualmente não é possível customizar as mensagens exibidas na identificação de campos inválidos.
Criada nova propriedade `errorMessage` na interface `PoDynamicFormField` que permite customizar as mensagens exibidas na identificação de campos inválidos.
**Simulação**
Simular no Sample Register do Dynamic-form no Portal, nos campos:
- Date of birth - passando uma data superior ao ano de 2010.
- Secret Key - campo validado através de uma regex.
> feat(dynamic-form): implementa a propriedade errorMessage

- projects/ui/src/lib/components/po-loading/po-loading-overlay/po-loading-overlay-base.component.ts
**LOADING OVERLAY**
**DTHFUI-2602**
Atualmente não informa a necessidade de utilizar posição relativa ao elemento pai.
Documentado a necessidade de utilizar o position: relative ao elemento pai caso utilizar a propriedade p-screen-lock como false.
**Simulação**
Avaliar documentação da propriedade p-screen-lock.
> docs(loading-overlay): documenta como utilizar p-screen-lock="false" 

- projects/ui/src/lib/components/po-field/po-decimal/po-decimal.component.spec.ts
- projects/ui/src/lib/components/po-field/po-decimal/po-decimal.component.ts
- projects/ui/src/lib/components/po-field/po-decimal/samples/sample-po-decimal-labs/sample-po-decimal-labs.component.html
- projects/ui/src/lib/components/po-field/po-decimal/samples/sample-po-decimal-labs/sample-po-decimal-labs.component.ts
**PO-DECIMAL**
**DTHFUI-1048**
**
*Descrição original:* Thf-decimal possui arredondamento estranho com quantidade máxima de números antes da vírgula.
Ao digitar .1224, é arredondado para 1223. 3233 torna-se 3232.
*Descrição:* ao usar números muito grandes a parte decimal é arredondada de forma errada, o problema ocorre tanto no model como para a exibição do valor em tela.
*Comportamento esperado:* Deve manter o mesmo valor para o model e do input, caso exista alguma limitação técnica para esse tipo de dado (number), por exemplo, um valor máximo, o mesmo deve ser documentado e corrigido para não apresentar divergências.
*Evidência/Anexos:* pode ser simulado no portal.
Agora o componente passa a tratar o número …
> fix(decimal): corrige falha no arredondamento dos decimais

- projects/templates/src/lib/components/po-page-dynamic-search/index.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-advanced-filter/po-advanced-filter-base.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-advanced-filter/po-advanced-filter-base.component.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-advanced-filter/po-advanced-filter-literals.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-advanced-filter/po-advanced-filter.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-advanced-filter/po-advanced-filter.component.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search-base.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search-base.component.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search-literals.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.html
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.module.ts
- projects/templates/src/lib/components/po-page-dynamic-search/samples/sample-po-page-dynamic-search-hiring-processes/sample-po-page-dynamic-search-hiring-processes.component.html
- projects/templates/src/lib/components/po-page-dynamic-search/samples/sample-po-page-dynamic-search-hiring-processes/sample-po-page-dynamic-search-hiring-processes.component.ts
- projects/ui/src/lib/services/index.ts
**PAGE DYNAMIC SEARCH**
**DTHFUI-2079**
Não possuia a propriedade p-literals.
Adiciona a propriedade p-literals, possibilitando customizar a tradução
padrão.
Também utiliza a linguagem definida no PoI18n para
fazer as traduções default.
**Simulação**
Utilizar documentação do portal.
> feat(page-dynamic-search): adiciona a propriedade p-literals

- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view.component.html
**Dynamic View**
**DTHFUI-2798, #258**
Ao tentar gerar o PDF de uma página que tenha mais de 1 uma página, não é gerado o arquivo corretamente, "imprimindo" apenas a 1ª página. O problema ocorre no Firefox, IE e Edge. O problema ocorre tanto usando o componente isolado ou dentro de um page.
Correção para poder imprimir todas as páginas nos navegadores Firefox, IE e Edge
**Simulação**
Utilizar o fonte do: https://stackblitz.com/edit/portinariui-sbvdnl?file=package.json
Observação: utilizar [PR do Style](https://github.com/portinariui/portinari-style/pull/78) para validar
> fix(dynamic-view): corrige impressão da página

- projects/templates/src/lib/components/po-page-login/po-page-login-base.component.ts
**Po Page Login**
**DTHFUI-2204**
Ao alterar o idioma para russo, é gerado um scroll horizontal no popover de aviso de bloqueio pois não há quebra de linha em uma das frases.
Corrigido e agora as quebras de linha funcionam normalmente.
**Simulação**
Simular utilizando o sample labs do Portal, basta preencher um valor na propriedade `Exceeded Attempts Warning` e mudar o idioma para russo.
> fix(page-login): ajusta quebra de layout no popover no idioma russo

- CONTRIBUTING.md
- HOW_TO_DOCUMENT.md
**HOW_TO_DOCUMENT**
**DTHFUI-2798**
N/A
incluído o guia HOW_TO_DOCUMENT.md que descreve como documentar os códigos-fonte e os padrões de documentação do projeto Portinari UI.
**Simulação**
N/A
> docs(how-to-document): inclusão de guia para documentação

- projects/ui/src/lib/directives/po-tooltip/po-tooltip-control-position.service.spec.ts
- projects/ui/src/lib/directives/po-tooltip/po-tooltip-control-position.service.ts
- projects/ui/src/lib/directives/po-tooltip/po-tooltip.directive.spec.ts
- projects/ui/src/lib/directives/po-tooltip/po-tooltip.directive.ts
**Tooltip**
**DTHFUI-2360**
Ao utilizar o p-tooltip diretamente em um componente como o po-combo,
acabam compartilhando o mesmo injectable, sobreescrevendo as propriedades definidas em ambos.
https://angular.io/guide/hierarchical-dependency-injection#directive-and-component
Foi criado um serviço especifico para o tooltip para não houver problemas de utilizar o mesmo injectable.
**Simulação**
```
<po-combo
name="combo"
class="po-md-6"
p-tooltip="teste do p-tooltip"
p-tooltip-position="right"
p-label="Portinari Combo"
[p-options]="[{ value: 'Option 1' }, { value: 'Option 2' }, { value: 'Option 3' }, { value: 'Option 4' }]">
</po-combo> …
```
> fix(tooltip): corrige o compartilhamento do serviço de posição

- projects/ui/src/lib/components/po-stepper/po-step/po-step.component.ts
- projects/ui/src/lib/components/po-stepper/po-stepper.component.spec.ts
- projects/ui/src/lib/components/po-stepper/po-stepper.component.ts
Incluí capacidade de verificar se pode ir para o próximo passo
com métodos assíncronos. Dessa forma, é possível
gravar no servidor antes de seguir para o próximo passo
Fixes #171
**po-stepper**
**#171**
o po-stepper/po-step não permite utilizar funções assíncronas para ir para o próximo passo, input p-can-active-next-step
Também permitir funções que retornem Promise ou Observable antes de seguir ao próximo passo no input p-can-active-next-step
**Simulação**
<po-step [p-can-active-next-step]="validate.bind(this)">
validate(step: PoStepComponent){
return true;
}
// ou delay de 2 segundo simulando assíncronicidade
validate(step: …
> feat(stepper): permite próximo passo assíncrono

- docs/guides/api.md
- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor-base.service.ts
**HTTP INTERCEPTOR**
**DTHFUI-2862**
N/A
Adiciona o documento, Guia de implementação de APIs para ser utilizado como referencia.
E melhorado a documentação do http-interceptor, adicionando exemplos dos dados informados e mencionado propriedades omitidas anteriormente.
**Simulação**
Avaliar documentação do portal.
PR PORTAL:
https://totvstfs.visualstudio.com/THF/_git/thf-portal-portinari-temp/pullrequest/21037?_a=overview
> docs(http-interceptor): melhora a documentação do funcionamento

- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.ts
**Po Page List**
**DTHFUI-2842**
Ao selecionar o idioma russo, a palavra "busca avançada" acabava não aparecendo.
Agora o usuário pode utilizar o idioma russo.
**Simulação**
Pode ser simulado no sample, basta alterar o idioma do navegador.
> fix(page-list): corrige busca avançada em russo

- projects/ui/src/lib/components/po-page/po-page-default/po-page-default.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-default/po-page-default.component.ts
- projects/ui/src/lib/components/po-page/po-page-default/samples/sample-po-page-default-dashboard/sample-po-page-default-dashboard.component.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.ts
- projects/ui/src/lib/components/po-page/po-page-list/samples/sample-po-page-list-hiring-processes/sample-po-page-list-hiring-processes.component.ts
**PO-PAGE-DEFAULT E PO-PAGE-LIST**
**DTHFUI-2848**
Hoje não é possível abrir uma url externa através dos botões de ação do componente po-page-default e do po-page-list.
Foi implementada uma validação que permite a abertura de url's externas tanto no componente po-page default quanto no po-page-list.
**Simulação**
Verificar nos samples de caso de uso do Portal:
- Po-page-default - Portinari Page Default - Dashboard
- Po-page-list - Portinari Page List - Hiring Processes
> fix(pages):  corrige comportamento dos botões de ação que não estão abrindo urls externas

- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
**Table**
**DTHFUI-2802**
Ao utilizar uma tabela sem definição de colunas e items
estava ocasionando erro no console no IE/EDGE,
decorrente do colSpan 0 que era informado, quando não possuia headers.
Componentes afetados eram:
PoLookup,
PoTable,
PoPageDynamicTable
Corrige o erro no console log disparado no IE/EDGE decorrente de um calculo incorreto
sobre o colSpan na tabela.
**Simulação**
Rodar o Portal, usar os componentes PoLookup, PoTable e PoPageDynamicTable e avaliar se o erro é disparado. (IE/EDGE)
Também é possivel usar localmente porém sem dados, exemplo:
```
<po-table></po-table>
```
> fix(table): corrige erro no console do IE/EDGE

- docs/guides/api.md
- projects/templates/src/lib/components/po-page-job-scheduler/index.ts
- projects/templates/src/lib/components/po-page-job-scheduler/interfaces/po-job-scheduler.interface.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-base.component.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.ts
- projects/templates/src/lib/components/po-page-job-scheduler/samples/sample-po-page-job-scheduler-background-process/sample-po-page-job-scheduler-background-process.component.html
- projects/templates/src/lib/components/po-page-job-scheduler/samples/sample-po-page-job-scheduler-background-process/sample-po-page-job-scheduler-background-process.component.ts
- projects/templates/src/lib/components/po-page-job-scheduler/samples/sample-po-page-job-scheduler-basic/sample-po-page-job-scheduler-basic.component.html
- projects/templates/src/lib/components/po-page-job-scheduler/samples/sample-po-page-job-scheduler-basic/sample-po-page-job-scheduler-basic.component.ts
**Page Job Scheduler**
**DTHFUI-2161**
- Não estava descrito na documentação que o usuário teria que usar o "items" envolta da requisição.
- Sample não estava funcionando corretamente
- Atualização da documentação.
- Criação de um endpoint para o sample funcionar corretamente
**Simulação**
- Utilizar a branch da [PR do sample](https://github.com/portinariui/portinari-sample-api/pull/7)
- Abrir o sample e substituir `https://portinari-sample-api.herokuapp.com/v1/scheduler` por `http://localhost:3000/v1/scheduler`
- Executar o portal para ver o sample funcionando corretamente. 
Obs.: Foi removido da documentação do Guia de Apis a parte …
> docs(page-job-scheduler): atualiza a documentação dos endpoints 

- .huskyrc
- .travis.yml
- package.json
Adiciona Travis ao repositório para validar os commits.
Detalhes das atualizações:
- separa a configuração do husky em um arquivo separado;
- adiciona arquivo de configuração do travis;
- atualiza dependências do commitlint e do husky.
> build: configuração para validar commits das PRs

- docs/guides/press-kit.md
** Portinari UI **
**DTHFUI-3033**
Criado `press-kit.md` contendo links para download da logomarca Portinari no Portal
**Simulação**
Visualizar no Portal em conjunto com a PR contida no repositótio `thf-portal-portinari-temp`
> feat(assets): cria link press kit no portal

- projects/code-editor/src/lib/components/po-code-editor/po-code-editor-register.service.ts
**PoCodeEditorRegister**
**#257**
No exemplo da documentação está faltando um virgula após declarar a "language" na construção do objeto customEditor.
Incluido a virgula que estava faltando após declarar a "language" na construção do objeto customEditor.
**Simulação**
N/A
> docs(code-editor-register): corrige objeto de exemplo customEditor

- projects/templates/src/lib/components/po-page-dynamic-edit/index.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/interfaces/po-page-dynamic-edit-metadata.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/interfaces/po-page-dynamic-edit-options.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
**DTHFUI-2615**
Como desenvolvedor eu gostaria de poder executar uma função quando o page  é inicializado para permitir que eu configure o page de acordo com o perfil do usuário.
Criada propriedade p-load: atributo que será executado quando o page for carregado:
- Function: executa a função que o desenvolvedor definiu;
- string: url que deve ser chamada via POST;
- RETORNO: o retorno para os 2 tipos é o mesmo, um objeto que contenha as ações (actions), configuração dos fields (fields), título (title) e breadcrumbs (breadcrumb);
**Simulação**
O desenvolvedor utilizará da seguinte forma
```
// load para configurar …
```
> feat(page-dynamic-edit): implementa a propriedade p-load

- CONTRIBUTING.md
**Documentation**
**DTHFUI-3035**
Na documentação de contribuição (_Contributing.md_), é mencionado que o colaborador externo deveria criar uma branch mesmo trabalhando em um fork do portinari.
Removida da documentação a obrigação de criação de branch nos forks dos contribuintes.
**Simulação**
Checar documentação Contributing.md
> docs(contributing): remove menção à branch em fork

- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.ts
- projects/ui/src/lib/components/po-field/po-input/po-input-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
- projects/ui/src/lib/components/po-field/po-textarea/po-textarea-base.component.ts
**Fields**
**DTHFUI-3090**
Apesar de depreciada, a propriedade p-focus ainda era habilitada até a versão 1.28.0.
A propriedade p-focus foi depreciada e os componentes afetados são: datepicker, decimal, email, input, login, lookup, multiselect, number, password, textarea e url
**Simulação**
Basta testar qualquer componente citado acima com a propriedade excluída.
> refactor(fields): remove propriedade p-focus

- docs/guides/migration-thf-to-portinari.md
**Documentação migration-thf-to-portinari**
**DTHFUI-3088**
Não era especificado que o pacote era apenas para a versão 1 do projeto.
Atualiza a documentação para fazer a migração da versão 4 do
THF para a versão 1 do projeto.
**Simulação**
Abrir a documentação no portal
> docs(migration-thf): atualiza para a nova versão

- projects/ui/src/lib/components/po-button-group/samples/sample-po-button-group-attendance/sample-po-button-group-attendance.component.ts
- projects/ui/src/lib/components/po-button-group/samples/sample-po-button-group-basic/sample-po-button-group-basic.component.ts
- projects/ui/src/lib/components/po-calendar/samples/sample-po-calendar-ticket-sales/sample-po-calendar-ticket-sales.component.ts
- projects/ui/src/lib/components/po-container/samples/sample-po-container-dashboard/sample-po-container-dashboard.component.ts
- projects/ui/src/lib/components/po-field/po-textarea/samples/sample-po-textarea-email-reactive-form/sample-po-textarea-email-reactive-form.component.ts
- projects/ui/src/lib/components/po-field/po-textarea/samples/sample-po-textarea-email/sample-po-textarea-email.component.ts
- projects/ui/src/lib/components/po-menu-panel/samples/sample-po-menu-panel-customer/sample-po-menu-panel-customer.component.ts
- projects/ui/src/lib/components/po-menu-panel/samples/sample-po-menu-panel-labs/sample-po-menu-panel-labs.component.ts
- projects/ui/src/lib/components/po-menu/samples/sample-po-menu-human-resources/sample-po-menu-human-resources.component.ts
- projects/ui/src/lib/components/po-menu/samples/sample-po-menu-labs/sample-po-menu-labs.component.ts
- projects/ui/src/lib/components/po-page/po-page-default/samples/sample-po-page-default-dashboard/sample-po-page-default-dashboard.component.ts
- projects/ui/src/lib/components/po-page/po-page-list/samples/sample-po-page-list-hiring-processes/sample-po-page-list-hiring-processes.component.ts
- projects/ui/src/lib/components/po-popup/samples/sample-po-popup-email/sample-po-popup-email.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-components/sample-po-table-components.component.ts
**Samples**
Atualmente é possível informar a referencia da função sem passar bind, e a mesma será executada no contexto do componente que possui a função. Isto porque o parentRef é recuperado pelos componentes relacionados.
Todos os exemplos no samples serão com a passagem de função com bind ou arrow function, 
para indicar a maneira correta ao desenvolvedor.
O modelo anterior, passando sem bind(this), será depreciada, para que na versão 3.0.0 seja removida o parentRef.
A depreciação ocorrerá em forma de CHANGELOG, onde haverá uma descrição de como deve ser a passagem de função.
**Simulação**
Testar os samples …
> refactor(samples): utiliza .bind(this) na passagem de função

- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
**combo**
Há métodos chamados dentro dos setters que estão quebrando os samples no portal.
Com a atualização de versão alguns métodos chamados via setter passaram a quebrar. Foi necessário deslocá-los para dentro do OnChanges
**Simulação**
Rodar no portal.
> fix(combo):  passa métodos para OnChanges

- projects/ui/src/lib/components/po-slide/po-slide-base.component.spec.ts
- projects/ui/src/lib/components/po-slide/po-slide-base.component.ts
- projects/ui/src/lib/components/po-slide/po-slide.component.spec.ts
- projects/ui/src/lib/components/po-slide/po-slide.component.ts
**PO-SLIDE**
Há métodos chamados dentro dos setters que estão quebrando os samples no portal.
Com a atualização de versão alguns métodos chamados via setter passaram a quebrar. Foi necessário deslocá-los para dentro do OnChanges.
**Simulação**
Rodar no portal.
> fix(slide): passa métodos para OnChanges

- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.ts
**Page List e Page Dynamic Search**
Estava gerando erro "expressionChangedAfterItHasBeenCheckedError" ao utilizar o filtro com nenhuma string.
Não está mais gerando este erro em nenhum dos dois componentes. 
**Simulação**
Samples do portal
> fix(page-list) e fix(page-dynamic-search): corrige erro ao filtrar

- projects/ui/src/lib/components/po-field/po-select/samples/sample-po-select-customer-registration/sample-po-select-customer-registration.component.html
- projects/ui/src/lib/components/po-field/po-select/samples/sample-po-select-customer-registration/sample-po-select-customer-registration.component.ts
- projects/ui/src/lib/components/po-field/po-select/samples/sample-po-select-customer-registration/sample-po-select-customer-registration.service.ts
**PO SELECT**
**DTHFUI-2685**
Os samples não estavam funcionando corretamente no portal
Atualização da url dos serviços dos samples para poder funcionar
de forma mais didática no portal.
**Simulação**
Subir o back-end da PR do po-sample-api -> npm start.
Substituir localmente no Sample Po Select Customer Registration "https://po-sample-api.herokuapp.com/v1/sampleSelect" por "http://localhost:3000/v1/sampleSelect", tanto no service quanto no html e Buildar os samples no portal.
> docs(select): atualização serviço do sample

- .travis.yml
- projects/sync/src/lib/services/po-event-sourcing/po-event-sourcing.service.spec.ts
- projects/sync/src/lib/services/po-schema/po-schema-definition/po-schema-definition.service.spec.ts
- projects/sync/src/lib/services/po-schema/po-schema.service.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-types/po-chart-dynamic-type.component.ts
- projects/ui/src/lib/components/po-field/po-input-generic/po-input-generic.ts
- tslint.json
**TSLINT**
**DTHFUI-3254**
A execução do tslint no travis estava desabilitada.
O problema ocorreu provavelmente apos v9 que adicionou @Directive nos BaseComponents,
com isso o lint estava quebrando.
Habilita a execução do tslint no travis.
Adiciona o suffixo customizado "BaseComponent" na regra "directive-class-suffix" e desabilta a regra em casos excepcionais.
**Simulação**
- Avaliar se o build no travis passou;
-  no projeto po-angular, executar: npm install && npm run lint
> build: habilita tslint no travis

- projects/templates/src/lib/components/po-page-dynamic-detail/po-page-dynamic-detail.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-detail/po-page-dynamic-detail.component.ts
- projects/templates/src/lib/components/po-page-dynamic-detail/samples/sample-po-page-dynamic-detail-user/sample-po-page-dynamic-detail-user.component.ts
**page-dynamic-detail**
**DTHFUI-3063**
Ao adicionar uma rota no botão de ação "back", ele não está redirecionando para a rota especificada, apenas voltando para a URL do histórico anterior.
Tratamento para que a ação de voltar redirecione para a rota especificada em `action.back`
**Simulação**
Adicionada rota no sample `SamplePoPageDynamicDetailUserComponent`
> fix(page-dynamic-detail): corrige ação back com string

- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
**COMBO**
**DTHFUI-3010**
Ao informar option.label com elemento HTML o mesmo estava
sendo  renderizado.
Realizado conversão dos caracteres < e > para &lt; e &gt; respectivamente.
Para que no momento da renderização, seja exibido "<" e ">", por exemplo.
**Simulação**
Utilizar o combo labs e exemplos informados na issue.
> fix(combo): corrige HTML Injection no option.label

- projects/ui/src/lib/components/po-field/po-lookup/interfaces/po-lookup-filter.interface.ts
- projects/ui/src/lib/components/po-field/po-upload/interfaces/po-upload-literals.interface.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
**DOCS**
**DTHFUI-3340**
Não exibe qual versão será feito a depreciação.
Componentes que tem depreciações:
- lookup
- upload
- table
**Simulação**
Atualizar o portal com as alterações.
> docs: informa a versão que as propriedades serão depreciadas no futuro

- package.json
- projects/code-editor/package.json
- projects/code-editor/src/lib/components/po-code-editor/po-code-editor-base.component.ts
- projects/code-editor/src/lib/components/po-code-editor/po-code-editor.component.ts
**po-code-editor**
**DTHFUI-3311**
O portal apresentava inconsistência no carregamento dos samples do `http-interceptor` e `code-editor`.
- As variáveis relacionadas ao monaco-editor haviam sido atribuidas para dentro de PoCodeEditorComponent e isso estava quebrando a correta visualização do editor de texto. Agora elas foram reatribudas para fora da classe.
- Foi também atualizado o pacote do monaco-editor para sua última versão.
**Simulação**
Avaliar o componente no portal
> fix(code-editor): corrige exibição do editor

- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-list-base.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-list-base.component.ts
**Po Page Dynamic Table**
**DTHFUI-2990, #260**
Lentidão ao abrir o gerenciador de colunas e não estava habilitando/desabilitando corretamente as colunas pelo gerenciador.
- O problema acontecia ao gerar uma nova referência no getter das colunas, pois o table acabava gerando várias detecções de mudança.
- A nova referência foi colocada no setter.
**Simulação**
- Testar o sample do portal.
- Testar com o prod do portal.
- Testar com o `p-fields`, para ver se as colunas continuam sendo colocadas corretamente.
- Testar em outros navegadores.
> fix(page-dynamic-table): corrige lentidão

- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
**po-table**
**DTHFUI-3330**
A função de selecionar um registro da tabela não está funcionando pois o radio button não está sendo exibido adequadamente.
Definidas classes css únicas para o radio-button usado no componente para tratamento de alinhamento e estilo.
**Simulação**
Testar sample labs do portal com o css [desta PR](https://github.com/po-ui/po-style/pull/100).
Revisar também po-lookup
> fix(table): corrige exibição do radio-button

- projects/templates/src/lib/components/po-page-blocked-user/po-page-blocked-user-contacts/po-page-blocked-user-contacts.component.html
- projects/templates/src/lib/components/po-page-blocked-user/po-page-blocked-user-contacts/po-page-blocked-user-contacts.component.spec.ts
- projects/templates/src/lib/components/po-page-blocked-user/po-page-blocked-user-contacts/po-page-blocked-user-contacts.component.ts
**page-blocked-user**
**DTHFUI-3195**
Os campos de contato não estavam respeitando as definições de colunagem.
- Corrigido método que verifica o dimensionamento das larguras dos campos de contatos.
- Identificado também que o ellipsis não estava funcionando se um campo excedesse a largura máxima. Verificar também a [po-style](https://github.com/po-ui/po-style/pull/101)
**Simulação**
Testar no sample labs do portal
> fix(page-blocked-user): corrige colunas de contatos

- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-base.component.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.ts
**Po Page Job Scheduler**
**DTHFUI-3046**
Ao selecionar um agendamento como sendo "single", está aparecendo na tela como 
"recorrente: sim", e na requisição POST está sendo enviado recurrent: false.
- Corrigida representação da recorrência em relação a periodicidade. Caso a periodicidade seja 'single' a recorrência sempre será falsa, caso contrário irá respeitar a definição do usuário.
**Simulação**
- Testar o sample do portal.
- Selecionar na primeira página como single, no final do processo a recorrência deve aparecer como não.
> fix(page-job-scheduler): corrige manipulação incorreta da recorrência

- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-parameters/po-page-job-scheduler-parameters.component.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.ts
**PAGE JOB SCHEDULER**
**DTHFUI-3043**
O template não estava validando os campos obrigatórios que retornavam da API,
possibilitando trocar de step mesmo com o campo obrigatório.
Valida os parâmetros ao tentar passar de step e também foi realizado tratamento para
desabilitar o botão de "Avançar" caso o formulário dos parâmetros for invalido.
**Simulação**
Utilizar o sample do template.
Selecionar o processo "process1" que possui parâmetros obrigatórios.
> fix(page-job-scheduler): corrige validação dos parametros

- projects/templates/src/lib/components/po-page-dynamic-detail/po-page-dynamic-detail.component.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/templates/src/lib/services/po-page-dynamic/po-page-dynamic-literals.interface.ts
- projects/templates/src/lib/services/po-page-dynamic/po-page-dynamic.service.spec.ts
- projects/templates/src/lib/services/po-page-dynamic/po-page-dynamic.service.ts
**Page Dynamic**
**DTHFUI-2959**
Ao retornar erro do servidor na tentativa de recuperar o metadados, 
os componentes: 
- Page Dynamic Edit
- Page Dynamic Detail
- Page Dynamic Table
Não utilizavam o metadados que possuía em cache.
Quando houver algum erro na requisição pelo metadados
e possuir cache será utilizado o mesmo.
Caso não houver cache será disparado uma notificação
informando que não foi possível recuperar o metadados
e será repassado um titulo padrão.
**OBS:** Por enquanto será exibido as duas mensagens, do proprio interceptor e do page-dynamic.
A ideia é alterar o po-notification para aceitar detalhes, será avaliado com …
> feat(page-dynamic): utiliza cache do metadados se servidor não responder

- projects/ui/src/lib/components/po-table/po-table-column-icon/po-table-column-icon.component.html
- projects/ui/src/lib/components/po-table/po-table-column-icon/po-table-column-icon.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-column-icon/po-table-column-icon.component.ts
- projects/ui/src/lib/components/po-table/po-table-icon/po-table-icon.component.html
- projects/ui/src/lib/components/po-table/po-table-icon/po-table-icon.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-icon/po-table-icon.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.service.ts
**table**
**Fixes DTHFUI-2781**
Ao usar uma coluna que permite uma ação (link, ícone) junto com a propriedade selected, ao executar uma ação a linha também era selecionada.
Se tiver a propriedade `selected` ativa e clicar sobre uma ação (link, ícone ou ações),  apenas a ação da coluna deve ser disparada, mantendo a seleção da linha inalterada. 
Exceções:
- ícones sem ação definida
- links com disabled habilitado. 
Para os casos acima a seleção de linha ainda é vigente.
**Simulação**
Validar nos samples do portal
> fix(table): previne selecionar linha ao clicar em ação

- docs/guides/api.md
- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-actions.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table-actions.service.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table-actions.service.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
**DTHFUI-2624**
A ação new vai imediatamente para a rota indicada.
Adicionada propriedade beforeNew para que o desenvolvedor possa executar uma função antes da função de new.
**Simulação**
[Anexada aplicação simples] [projeto_dynamic_templates.zip](https://github.com/po-ui/po-angular/files/4581192/projeto_dynamic_templates.zip)
As realizadas foram:
-**new** com string
-**new** com func;
-**beforeNew** com string
-**beforeNew** com func
-**beforeNew** newURL undefined
-**beforeNew** com allowAction false
Pode subir a api com https://github.com/po-ui/po-sample-api/pull/12
> feat(page-dynamic-table): adiciona propriedade beforeNew na actions

- projects/templates/src/lib/components/po-page-dynamic-detail/interfaces/po-page-dynamic-detail-actions.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-detail/po-page-dynamic-detail-actions.service.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-detail/po-page-dynamic-detail-actions.service.ts
- projects/templates/src/lib/components/po-page-dynamic-detail/po-page-dynamic-detail.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-detail/po-page-dynamic-detail.component.ts
**page-dynamic-detail**
**DTHFUI-2630**
A ação back retorna imediatamente para a rota indicada.
Adicionada propriedade beforeBack para que o desenvolvedor possa executar uma função antes da função de retorno (*back*).
**Simulação**
[Anexada aplicação simples](https://github.com/po-ui/po-angular/files/4580858/beforeBack.zip) para teste de funcionalidade. 
As realizadas foram:
-**back** com boolean;
-**back** com string
-**back** com func;
-**back** com undefined
-**beforeBack** com string
-**beforeBack** com func
-**beforeBack** newURL undefined
-**beforeBack** com allowAction false
Pode mockar a api com https://beeceptor.com/
> feat(page-dynamic-detail): adiciona action beforeBack

- projects/templates/src/lib/components/po-page-dynamic-edit/index.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/interfaces/po-page-dynamic-edit-actions.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/interfaces/po-page-dynamic-edit-before-save.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit-actions.service.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit-actions.service.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.ts
**page-dynamic-edit**
**DTHFUI-2628**
O usuário não conseguia fazer uma validação antes que a ação de salvar fosse realizada.
Adicionada propriedade beforeSave para que o desenvolvedor possa executar uma função antes da função de salvar (*save*).
**Simulação:**
Pode estar colocando este anexo no lugar da pasta app, e verificar as rotas para iniciar os testes
com a nova propriedade:
[app.zip](https://github.com/po-ui/po-angular/files/4594842/app.zip)
> feat(page-dynamic-edit): implementa a propriedade beforeSave

- projects/templates/src/lib/components/po-page-dynamic-detail/index.ts
- projects/templates/src/lib/components/po-page-dynamic-detail/interfaces/po-page-dynamic-detail-actions.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-detail/interfaces/po-page-dynamic-detail-before-back.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-detail/po-page-dynamic-detail-actions.service.ts
- projects/templates/src/lib/components/po-page-dynamic-detail/po-page-dynamic-detail.component.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/index.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/interfaces/po-page-dynamic-edit-actions.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/index.ts
- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-actions.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-before-new.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table-actions.service.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
**docs**
As interfaces PoPageDynamicDetailBeforeBack e PoPageDynamicTableBeforeNew não estavm bem destacados na documentação
Criados arquivos próprios da interfaces para aparecer no portal.
**Simulação**
Conferir a doc do portal
> docs(): destaque das interfaces beforeNew e beforeBack

- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.ts
**DTHFUI-3425**
Ao adicionar itens dinamicamente, como no seu exemplo de Labs,
o campo de busca não era apresentado e com isso
ocasionava erro ao selecionar um item.
Realizado o controle de verificação das options
dinamicamente para que o campo seja apresentado corretamente.
**Simulação**
- Gerar o Portal, e;
- Utilizar Sample Po Multiselect Labs;
> fix(multiselect): corrige exibição do campo de pesquisa

- projects/templates/src/lib/components/po-page-dynamic-detail/index.ts
- projects/templates/src/lib/components/po-page-dynamic-detail/interfaces/po-page-dynamic-detail-actions.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-detail/interfaces/po-page-dynamic-detail-before-back.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-detail/interfaces/po-page-dynamic-detail-before-remove.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-detail/po-page-dynamic-detail-actions.service.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-detail/po-page-dynamic-detail-actions.service.ts
- projects/templates/src/lib/components/po-page-dynamic-detail/po-page-dynamic-detail.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-detail/po-page-dynamic-detail.component.ts
**page-dynamic-detail**
**DTHFUI-2632**
A ação *remove* retorna imediatamente para a rota indicada após confirmação.
- Adicionada propriedade beforeRemove para que o desenvolvedor possa executar uma ação antes da função de exclusão (remove).
- Corrigido bug onde era exibido o botão de exclusão mesmo quando se tratava de um registro não encontrado. Pode simular excluindo um registro e depois retornar para a url proveniente dele.
- Ajuste pequeno na documentação de `po-page-dynamic-detail-before-back.interface.ts`
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/4645206/app.zip)
As realizadas foram:
-**remove** com …
> feat(page-dynamic-detail): adiciona action beforeRemove

- projects/templates/src/lib/components/po-page-dynamic-edit/index.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/interfaces/po-page-dynamic-edit-actions.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/interfaces/po-page-dynamic-edit-before-cancel.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit-actions.service.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit-actions.service.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.ts
**page-dynamic-edit**
**DTHFUI-2627**
A ação *cancel* retorna imediatamente para a rota indicada após confirmação.
• Adicionada propriedade **beforeCancel** para que o desenvolvedor possa executar uma ação antes da função de cancelamento (*cancel*).
• Agora a propriedade **cancel** aceita também uma função.
• Tratamento para Observables aninhados presentes em **beforeSave** e também incluídos no Subscription.
**Simulação**
[Anexado app para validações](https://github.com/po-ui/po-angular/files/4652094/app.zip). Pode usar o componente **Editar**
Pode também mockar o serviço no [beeceptor](https://beeceptor.com/). Basta criar um método …
> feat(page-dynamic-edit): adiciona action beforeCancel

- projects/ui/src/lib/components/po-modal/index.ts
- projects/ui/src/lib/components/po-modal/po-modal-service.ts
- projects/ui/src/lib/components/po-modal/po-modal.component.ts
- projects/ui/src/lib/components/po-modal/po-modal.module.ts
Além de transformar o serviço de controle da modal em singleton foram removidos
alguns imports que não estavam sendo utilizados dentro do componente.
**Modal**
**DTHFUI-3463**
Atualmente o serviço de controle do modal não é um singleton.
Transforma o serviço de controle do modal é um singleton.
**Simulação**
Rodar o projeto anexo a issue e seguir os passos no comentário da mesma.
> feat(modal): transforma serviço da modal em um singleton

- projects/templates/src/lib/components/po-page-dynamic-table/index.ts
- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-actions.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-before-remove.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table-actions.service.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table-actions.service.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/templates/src/lib/services/po-page-dynamic/po-page-dynamic.service.spec.ts
- projects/templates/src/lib/services/po-page-dynamic/po-page-dynamic.service.ts
**DTHFUI-2625**
A ação remove vai imediatamente para a rota indicada.
Adicionada propriedade beforeRemove para que o desenvolvedor possa executar uma função antes da função de remove.
**Simulação**
[projeto_dynamic_templates.zip](https://github.com/po-ui/po-angular/files/4630368/projeto_dynamic_templates.zip)
As realizadas foram:
-**remove** com boolean
-**remove** com func;
-**beforeRemove** com string
-**beforeRemove** com func
-**beforeRemove** newURL undefined
-**beforeRemove** com allowAction false
Pode subir a api com https://github.com/po-ui/po-sample-api/pull/12
> feat(page-dynamic-table): adiciona propriedade beforeRemove na actions

- projects/templates/src/lib/components/po-page-dynamic-detail/po-page-dynamic-detail.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/services/po-lookup-filter.service.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/services/po-lookup-filter.service.ts
- projects/ui/src/lib/components/po-stepper/po-stepper.component.spec.ts
**po-lookup**
**DTHFUI-3503**
Quando realizada consulta no lookup que retorna um status 404 o table fica em modo "carregando" e não faz o tratamento adequado.
Se ocorrer erro como 404 na pesquisa de um registro, remove-se o loading e exibe a mensagem de registro não encontrado. Foi também definido no cabeçalho da requisição o parâmetro `X-PO-No-Message` para dispensar a notificação de erro do interceptor.
* Adicionado *compileComponents()* nos arquivos de teste dos componentes `page-dynamic-edit` e `page-dynamic-detail` pois estavam gerando erros intermitentes.
**Simulação**
Os samples ainda apontam para a api antiga. Mas foi criada …
> fix(lookup): adiciona tratamento de erro para pesquisa

- projects/templates/src/lib/components/po-page-dynamic-detail/index.ts
- projects/templates/src/lib/components/po-page-dynamic-detail/interfaces/po-page-dynamic-detail-actions.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-detail/interfaces/po-page-dynamic-detail-before-edit.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-detail/po-page-dynamic-detail-actions.service.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-detail/po-page-dynamic-detail-actions.service.ts
- projects/templates/src/lib/components/po-page-dynamic-detail/po-page-dynamic-detail.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-detail/po-page-dynamic-detail.component.ts
**Page Dynamic Detail**
**DTHFUI-2631**
O usuário antes não conseguia fazer uma validação antes de acionar a edição. 
Adiciona propriedade `beforeEdit` para o desenvolvedor poder executar
uma função/url antes da função de edição no template.
A propriedade `edit`, agora também passa a receber uma função
além da url.
**Simulação**
- Pode ser usado como backend a branch [page-dynamic-edit/DTHFUI-2631](https://github.com/po-ui/po-sample-api/tree/page-dynamic-edit/DTHFUI-2631)
- No front, pode usar o exemplo anexado. Nele contém algumas possibilidades que podem ser testadas. 
[app-before-edit.zip](https://github.com/po-ui/po-angular/files/ …
> feat(page-dynamic-detail): adiciona propriedade beforeEdit na actions

- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/index.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-advanced-filter/po-advanced-filter-base.component.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-advanced-filter/po-advanced-filter.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-advanced-filter/po-advanced-filter.component.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search-base.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search-base.component.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search-filters.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search-options.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.html
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.ts
- projects/templates/src/lib/components/po-page-dynamic-search/samples/sample-po-page-dynamic-search-hiring-processes/sample-po-page-dynamic-search-hiring-processes.component.ts
- projects/templates/src/lib/components/po-page-dynamic-search/samples/sample-po-page-dynamic-search-hiring-processes/sample-po-page-dynamic-search-hiring-processes.service.ts
- projects/templates/src/lib/components/po-page-dynamic-table/index.ts
- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-filters.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-options.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-list-base.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.html
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.component.html
- projects/templates/src/lib/services/po-page-customization/po-page-customization.service.ts
- projects/ui/src/lib/index.ts
**PO-PAGE-DYNAMIC-SEARCH E PO-PAGE-DYNAMIC-TABLE**
**DTHFUI-1285**
Não é possível abrir os componente com algum filtro aplicado e refletindo tanto nos disclaimers quanto nos valores da modal de busca avançada.
- Criada nova propriedade `p-keep-filters` que permite manter na modal de busca avançada os valores do último filtro realizado pelo usuário.
- Criada nova propriedade `initValue` para os `filters` (po-page-dynamic-search) e para os `fields` (po-page-dynamic-table) que permite inicializar o filtro de busca avançada do componente com um valor inicial.
- Novo comportamento possibilita também ativar ou desativar a propriedade …
> feat(dynamic-search): permite manter os filtros de busca avançada e disclaimers com a ultima busca do usuário

- projects/ui/src/lib/components/po-page/po-page-filter.interface.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.html
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.ts
- projects/ui/src/lib/components/po-page/po-page-list/samples/sample-po-page-list-labs/sample-po-page-list-labs.component.html
- projects/ui/src/lib/components/po-page/po-page-list/samples/sample-po-page-list-labs/sample-po-page-list-labs.component.ts
incluido o atributo size no filtro,
conforme definição de UX da unidade
**po-page-list**
**estudo de UX - Time Saúde - Caxias**
Tamanho do filtro do page-list é fixo
É possível alterar o tamanho do filtro através da nova propriedade size da interface PoPageFilter, utilizando o número de colunas dentro do grid system (limitado em até 6 colunas para não quebrar o layout)
**Simulação**
Esta correção pode ser validada utilizando o sample labs no portal
> feat(page-list): adiciona tamanho no filtro

- projects/templates/src/lib/components/po-page-dynamic-table/index.ts
- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-actions.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-before-edit.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table-actions.service.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table-actions.service.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
**DTHFUI-2623**
A ação *edit* direciona imediatamente para a rota indicada.
• Adicionada propriedade **beforeEdit** para que o desenvolvedor possa executar uma ação antes de editar recurso (**edit**).
• Agora a propriedade **edit** aceita também uma função. Esta função pode retornar um objeto contendo o recurso para atualização da linha. Exceção feita para campos que contém o atributo `key: true`.
**Simulação**
- **edit** com string
- **edit**  com func;
- **edit** com undefined e null
- **edit** com retorno de objeto
- **edit** com retorno de objeto contendo um atributo `key`
- **beforeEdit** com string
- …
> feat(page-dynamic-table): adiciona action beforeEdit

- projects/templates/src/lib/components/po-modal-password-recovery/po-modal-password-recovery.component.spec.ts
- projects/templates/src/lib/components/po-page-background/po-page-background.component.spec.ts
- projects/templates/src/lib/components/po-page-blocked-user/po-page-blocked-user-contacts/po-page-blocked-user-contacts.component.spec.ts
- projects/templates/src/lib/components/po-page-blocked-user/po-page-blocked-user-reason/po-page-blocked-user-reason.component.spec.ts
- projects/templates/src/lib/components/po-page-blocked-user/po-page-blocked-user.component.spec.ts
- projects/templates/src/lib/components/po-page-change-password/po-page-change-password.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-detail/po-page-dynamic-detail.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-advanced-filter/po-advanced-filter.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-execution/po-page-job-scheduler-execution.component.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-parameters/po-page-job-scheduler-parameters.component.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-summary/po-page-job-scheduler-summary.component.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.spec.ts
- projects/templates/src/lib/components/po-page-login/po-page-login-base.component.spec.ts
- projects/templates/src/lib/components/po-page-login/po-page-login-popover/po-page-login-popover.component.spec.ts
- projects/templates/src/lib/components/po-page-login/po-page-login.component.spec.ts
- projects/templates/src/lib/util-test/util-expect.spec.ts
- projects/ui/src/lib/components/po-progress/po-progress.component.spec.ts
**ng-template**
dthfui 3546
Retirada função configureTestSuite poisna versão 9 o testbed foi
otimizado e essa função estava causando algumas instabilidades na
execução dos testes unitários.
Os testes foram revisados
**Simulação**
Basta rodar os testes.
> test(ng-template): Correção de testes unitários

- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
**po-table**
**DTHFUI-3438**
Quando passado o mouse sobre uma coluna do tipo label com um valor diferente dos especificados dá erro no console.
Revisada e ajustada validação para propriedade `tooltipText`
**Simulação**
Utilizar `sample-po-table-components` passando um valor diferente na propriedade `status`.
> fix(table): corrige tooltip em colunas do tipo label

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/samples/sample-po-dynamic-form-register/sample-po-dynamic-form-register.component.ts
- projects/ui/src/lib/util-test/util-expect.spec.ts
- projects/ui/src/lib/utils/util.spec.ts
- projects/ui/src/lib/utils/util.ts
**Po Dynamic Form**
**DTHFUI-3478**
O usuário não consegue controlar a forma de renderizar os campos, a não ser pela organização da posição do array. 
Adiciona a propriedade `order` na interface `PoDynamicFormField`
para poder organizar a ordem em que os campos serão renderizados, independente da posição no array.
**Simulação**
- Pode ser simulado nos samples do Dynamic Form no portal.
- Também pode ser validado os samples do: Page Job Scheduler, Page Dynamic Search e Page Dynamic Edit.
Obs.: os formulários já existentes não podem sofrer alterações.
> feat(dynamic-form): adiciona a propriedade `order` nos campos

- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/samples/sample-po-dynamic-view-employee-on-load/sample-po-dynamic-view-employee-on-load.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/samples/sample-po-dynamic-view-employee/sample-po-dynamic-view-employee.component.ts
**PO-DYNAMIC-VIEW**
**DTHFUI-3479**
O usuário não consegue controlar a forma de renderizar os campos, a não ser pela organização da posição do array.
Adiciona a propriedade order na interface PoDynamicViewField para poder organizar a ordem em que os campos serão renderizados, independente da posição no array.
**Simulação**
- Pode ser simulado nos samples do Dynamic View no portal.
- Também pode ser validado pelo Page Dynamic Detail, porém não possui samples no portal.
Obs.: os formulários já existentes não podem sofrer alterações.
> feat(dynamic-view): permite ordenar os fields exibidos

- projects/templates/src/lib/components/po-page-dynamic-table/index.ts
- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-actions.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-before-duplicate.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table-actions.service.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table-actions.service.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/templates/src/lib/utils/util.spec.ts
- projects/templates/src/lib/utils/util.ts
**DTHFUI-2622**
A ação *duplicate* direciona imediatamente para a rota indicada.
• Adicionada propriedade **beforeDuplicate** para que o desenvolvedor possa executar uma ação antes de editar recurso (**duplicate**).
• Agora a propriedade **duplicate** aceita também uma função. 
**Simulação**
Anexada [aplicação para teste](https://github.com/po-ui/po-angular/files/4766306/app.zip). Pode testar com o componente Clientes.
- **duplicate** com string
- **duplicate**  com func - recebe como parâmetro objeto contendo apenas as propriedades marcadas com `duplicate: true`.
- **duplicate** com undefined e null
- …
> feat(page-dynamic-table): adiciona action beforeDuplicate

- projects/templates/src/lib/components/po-page-dynamic-edit/index.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/interfaces/po-page-dynamic-edit-actions.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/interfaces/po-page-dynamic-edit-before-save-new.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit-actions.service.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit-actions.service.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.ts
**DTHFUI-2629**
-
Adiciona propriedade beforeSaveNew para o desenvolvedor poder executar
um evento antes da função de salvar e novo, podendo retornar um novo recurso, se possui uma nova rota e também se permite a execução da função (saveNew).
Não pode fazer o merge dos valores que são keys.
**Simulação**
- Buildar os pacotes UI e Templates
- Adicionar o [projeto](https://github.com/po-ui/po-angular/files/4771037/app.zip)
dentro de ~/po-angular/app/src/app
- Subir localmente sample-po-api ou mudar a URL no projeto.
- Criar novos registros com "save" e "saveNew" com os respectivos before (usando URL/função).
- …
> feat(page-dynamic-edit): adiciona a propriedade beforeSaveNew nas ações

- projects/templates/src/lib/components/po-page-dynamic-table/index.ts
- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-actions.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-before-remove-all.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table-actions.service.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table-actions.service.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
**DTHFUI-2626**
A ação *removeAll* deleta os registros selecionados
• Adicionada propriedade **beforeRemoveAll** para que o desenvolvedor possa executar uma ação antes de editar recurso (**removeAll**).
• Agora a propriedade **removeAll** aceita também uma função. Esta função pode retornar um objeto contendo os recursos para exclusão. 
**Simulação**
- Projeto para simulação
[app_beforeRemoveAll.zip](https://github.com/po-ui/po-angular/files/4772945/app_beforeRemoveAll.zip)
- **removeAll** com string
- **removeAll**  com func;
- **removeAll** com undefined e null
- **beforeRemoveAll** com string
- …
> feat(page-dynamic-table): adiciona propriedade beforeRemoveAll

- projects/ui/src/lib/components/po-table/po-table-column-label/po-table-column-label.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-column-label/po-table-column-label.interface.ts
- projects/ui/src/lib/components/po-table/po-table-subtitle-footer/po-table-subtitle-column.interface.ts
- projects/ui/src/lib/components/po-table/po-table-subtitle-footer/po-table-subtitle-footer.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-components/sample-po-table-components.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-components/sample-po-table-components.enum.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-components/sample-po-table-components.service.ts
**Table**
**DTHFUI-3588**
A propriedade value das interfaces PoTableColumnLabel e PoTableSubtitleColumn só aceitam valores no formato de string.
A propriedade value das interfaces PoTableColumnLabel e PoTableSubtitleColumn passam a aceitar strings e números.
**Simulação**
Usar um valor numérico em uma dessas propriedades.
Alterei o sample "PO Field Commom Components" para usar número na coluna status e usei um enum para exemplificar o uso.
> table: permitir o uso de valores numéricos para a propriedade value das interfaces PoTableColumnLabel e PoTableSubtitleColumn

- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
**combo**
**DTHFUI-3578**
A funcionalidade de filtro não está funcionando corretamente quando é usado um valor inválido (que não existe), tanto para lista fixa de opções como para listas preenchidas através de um serviço.
Ao usar um valor inexistente deve mostrar a mensagem que não encontrou nenhum dado como fazia anteriormente.
**Simulação**
Simular nos samples do portal.
Obs.: A incongruência na filtragem de itens nos samples que consomem serviço é relacionada com o backend e será tratada em uma outra tarefa.
> fix(combo): corrige filtragem dos itens

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form.component.ts
**DTHFUI-3644**
Ao comparar o valor anterior com o valor atual durante o validate, não estava sendo atualizado todo o valor do objeto, apenas a propriedade que recebeu o change, caso uma propriedade fosse alterada durante o change pelo desenvolvedor, essa propriedade não era atualizada fazendo com que o validate não fosse disparado para o desenvolvedor.
Passa a atualizar todo o objeto (model) garantindo que seja sempre disparado o change.
**Simulação**
Pode ser simulado conforme as informações anexadas a issue ou como o vídeo em anexo.
[dynamic-form-previous-value-error.mp4.zip](https://github.com/po-ui/po-angular/fil …
> fix(dynamic-form): corrige problema ao atualizar valores no validate

- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-transport/sample-po-table-transport.component.html
**PO-TABLE**
**DTHFUI-3580**
Atualmente não é possivel desabilitar o gerenciador de colunas na tabela.
Através da propriedade [p-hide-columns-manager] é possivel desabilitar o gerenciador.
**Simulação**
_PR style_: https://github.com/po-ui/po-style/pull/116
`<po-table [p-items]="items" [p-columns]="columns" p-hide-columns-manager></po-table>`
> feat(table): adiciona propriedade para remover o gerenciador

- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-before-remove-all.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
**DTHFUI-3643**
O botão de exclusão em lote ficava habilitado mesmo com nenhum item selecionado, além disso caso seja passado no beforeRemoveAll seja passado um array em branco, a função removeAll não era chamada.
Alterado o botão de exclusão em lote que ficará habilitado somente se houver um ou mais
itens para excluir. Além disso caso o beforeRemoveAll retorne um array vazio
na propriedade resources a função removeAll será chamada.
**Simulação**
- Projeto para simulação
[removeAll.zip](https://github.com/po-ui/po-angular/files/4827353/removeAll.zip)
- Também e possivel testar no portal.
> fix(page-dynamic-table): correção no tratamento da ação removeAll

- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.html
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.ts
**PO-PAGE JOB SCHEDULER**
**DTHFUI-3047**
Mesmo os dados sensíveis configurados com `secret: true` são exibidos na tela de confirmação.
Na tela de confirmação, os dados sensíveis de campos configurados como secret ficam escondidos.
**Simulação**
Pode ser verificado no sample do portal, selecionando o process 1 - Release new version.
Obs: ao enviar os dados para o servidor o valor deve ser enviado conforme o usuário digitou, deve ser escondido apenas na visualização.
> feat(page-job-scheduler): esconde informações sensíveis na tela de confirmação

- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-components/sample-po-table-components.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-components/sample-po-table-components.component.ts
**PO-TABLE**
**DTHFUI-3658**
Quando o botão "Carregar mais resultados" é clicado, não é retornado um feedback ao usuário que o mesmo esta em estado de carregamento.
Caso o usuário tenha habilitado a propriedade p-loading no PO-TABLE, assim que ele clicar no botao "Carregar mais resultados" e este disparar uma requisiçao ao servidor, enquanto a requisição não retornar com os dados, é mostrado ao usuário um loading na tabela e no botão.
**Simulação**
``` html
<po-table
[p-columns]="columns"
[p-items]="items"
[p-show-more-disabled]="showMoreDisabled"
[p-sort]="true"
(p-show-more)="showMore($event)"
[p-loading]="true"
></po-table>
``` …
> feat(table): adiciona loading ao botao carregar mais

- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.module.ts
A descrição do componente estava como search quando o correto é
table. Corrigida descrição para table.
Fixes #476, DTHFUI-3743
po-page-dynamic-table
#476
**Simulação**
> docs(page-dynamic-table): corrige descrição

- projects/ui/src/lib/components/po-table/interfaces/po-table-column.interface.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table-cell-template/po-table-cell-template.directive.ts
- projects/ui/src/lib/components/po-table/po-table-column-template/po-table-column-template.directive.ts
**Table**
- [x ] Documentação
- PoTableColumn.type não possuia os valores possiveis de utilizar, columnTemplate e cellTemplate;
- Não havia destaque dos novos templates na pagina inicial;
- O input p-property não aparecia na doc do PoTableColumnTemplate
- O type nos exemplos das documentações de templates estavam errados.
**Simulação**
- Rodar portal
> docs(table): ajusta documentação sobre templates da coluna

- docs/guides/sync-fundamentals.md
- docs/guides/sync-get-started.md
- gulpfile.js
- projects/schematics/src/build-file/build-file.ts
- projects/schematics/src/build-file/file-options.interface.ts
- projects/schematics/src/build-file/index.ts
- projects/schematics/src/index.ts
- projects/sync/README.md
- projects/sync/package.json
- projects/sync/schematics/README.md
- projects/sync/schematics/collection.json
- projects/sync/schematics/ng-add/index.ts
- projects/sync/schematics/ng-add/schema.json
- projects/sync/schematics/ng-generate/schema/files/__path__/__name@dasherize__/__name@dasherize__.constants.ts.template
- projects/sync/schematics/ng-generate/schema/index.ts
- projects/sync/schematics/ng-generate/schema/schema.json
- projects/sync/schematics/ng-generate/schema/schema.ts
**sync**
**DTHFUI-3391**
O usuário deve instalar o pacote ng-sync via npm e também adicionar o módulo manualmente. Além disso o schema para o sync também deve ser feito manualmente
Definido schematics para inclusão do pacote ng-sync na aplicação e criação do comando ng generate @po-ui/ng-sync:sync-schema
**Simulação**
Para testar com npm link::
1- É necessário alterar em `angular.json`:
` "defaultProject": "app" `
2- Executar o build do projeto `po-schematics`:
`npm run build:schematics`
3 - Incluir o caminho do *.tgz* do `ng-schematics` no `package.json` do sync:
4- Executar o build do projeto `sync`:
`npm run build:sync`
5 - …
> feat(sync): cria schematics ngAdd e ng generate

- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.ts
- projects/ui/src/lib/components/po-list-view/samples/sample-po-list-view-hiring-processes/sample-po-list-view-hiring-processes.component.ts
- projects/ui/src/lib/components/po-page/po-page-filter.interface.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.html
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.ts
- projects/ui/src/lib/components/po-page/po-page-list/samples/sample-po-page-list-hiring-processes/sample-po-page-list-hiring-processes.component.ts
- projects/ui/src/lib/components/po-page/po-page-list/samples/sample-po-page-list-labs/sample-po-page-list-labs.component.ts
**page-list**
**DTHFUI-3738**
O atributo ngModel fazia com que o frame tivesse que controlar o parentRef oque não é uma boa prática.
Foi depreciado o atributo ngModel do PageFilter, agora o conteúdo do campo do filtro é passado via parâmetro nas funções action e advancedAction
**Simulação**
É possivel realizar os testes nos samples do page-list e do dynamic search, essa foi uma refatoração e a funcionalidade para o usuário não foi alterada.
> feat(page-list): depreciação do atributo ngModel do PageFilter

- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
- projects/ui/src/lib/services/po-i18n/po-i18n-base.service.ts
- projects/ui/src/lib/services/po-i18n/po-i18n.module.ts
**Combo**
**Simulação**
```
default: {
},
contexts: {}
};
...
@NgModule({
AppComponent
],
imports: [
...
],
})
```
> feat(combo): permite traduzir as literais usando o serviço do i18n

- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.ts
**Lookup**
**Simulação**
```
default: {
},
contexts: {}
};
...
@NgModule({
AppComponent
],
imports: [
...
],
})
```
> feat(lookup): permite traduzir as literais usando o serviço do i18n

- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.ts
**Multiselect**
**Simulação**
```
default: {
},
contexts: {}
};
...
@NgModule({
AppComponent
],
imports: [
...
],
})
```
> feat(multiselect): permite traduzir as literais usando o serviço do i18n

- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.component.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-file-restrictions/po-upload-file-restrictions.component.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-file-restrictions/po-upload-file-restrictions.component.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.ts
**Upload**
**Simulação**
```
default: {
},
contexts: {}
};
...
@NgModule({
AppComponent
],
imports: [
...
],
})
```
> feat(upload): permite traduzir as literais usando o serviço do i18n

- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search-base.component.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search-options.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-options.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.html
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.component.html
- projects/ui/src/lib/components/po-disclaimer-group/index.ts
- projects/ui/src/lib/components/po-disclaimer-group/po-disclaimer-group-base.component.spec.ts
- projects/ui/src/lib/components/po-disclaimer-group/po-disclaimer-group-base.component.ts
- projects/ui/src/lib/components/po-disclaimer-group/po-disclaimer-group-remove-action.interface.ts
- projects/ui/src/lib/components/po-disclaimer-group/po-disclaimer-group.component.html
- projects/ui/src/lib/components/po-disclaimer-group/po-disclaimer-group.component.spec.ts
- projects/ui/src/lib/components/po-disclaimer-group/po-disclaimer-group.interface.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.html
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.ts
**Disclaimer Group, Page List, Page Dynamic Search e Page Dynamic Table**
**DTHFUI-2349**
Sempre que se aplicava uma busca rápida, ela sobrescrevia a busca avançada.  
Pode utilizar a basca rápida junto com a busca avançada através da propriedade `p-concat-filters`.
- Também foi adicionado este mesmo comportamento no `Page Dynamic Table`
- Deve manter o comportamento atual também quando` p-concat-filters` for `false`
- Para resolver o problema de emitir os disclaimers mais de uma vez, criamos duas propriedade p-remove e p-removeAll no disclaimer-group, para não precisar fazer esses tratamentos para diferenciar quando um disclaimer …
> feat(page-dynamic-search): implementa `p-concat-filters` 

- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
**Simulação**
```
default: {
},
contexts: {}
};
...
@NgModule({
AppComponent
],
imports: [
...
],
})
```
> feat(page-dynamic-table): permite traduzir literais usando serviço i18n

- projects/templates/src/lib/components/po-page-dynamic-detail/po-page-dynamic-detail.component.ts
**Page Dynamic Detail**
**Simulação**
```
default: {
},
contexts: {}
};
...
@NgModule({
AppComponent
],
imports: [
...
],
})
```
> feat(page-dynamic-detail): permite traduzir literais usando serviço i18n

- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.ts
**Simulação**
```
default: {
},
contexts: {}
};
...
@NgModule({
AppComponent
],
imports: [
...
],
})
```
> feat(page-dynamic-edit): permite traduzir literais usando serviço i18n

- projects/templates/src/lib/components/po-page-blocked-user/literals/i18n/po-page-blocked-user-literals.ts
- projects/templates/src/lib/components/po-page-blocked-user/po-page-blocked-user-reason/po-page-blocked-user-reason.component.ts
- projects/templates/src/lib/components/po-page-blocked-user/po-page-blocked-user.component.html
- projects/templates/src/lib/components/po-page-blocked-user/po-page-blocked-user.component.ts
**Page Blocked User**
**Simulação**
```
default: {
},
contexts: {}
};
...
@NgModule({
AppComponent
],
imports: [
...
],
})
```
> feat(page-blocked-user): permite traduzir literais usando serviço i18n

- projects/ui/src/lib/components/po-table/enums/po-table-row-template-arrow-direction.enum.ts
- projects/ui/src/lib/components/po-table/index.ts
- projects/ui/src/lib/components/po-table/po-table-row-template/po-table-row-template.directive.spec.ts
- projects/ui/src/lib/components/po-table/po-table-row-template/po-table-row-template.directive.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-transport/sample-po-table-transport.component.html
**PO-TABLE**
**FIX DTHFUI-3718**
Quando se usa a diretiva `p-table-row-template`, hoje não é possível alterar a posição da arrow do detail.
Agora foi adicionado na diretiva `p-table-row-template` a propriedade `p-table-row-template-arrow-direction` que permite que o usuário passe _LEFT_ ou _RIGHT_ definindo assim a posição desejada da arrow.
**Simulação**
Foi utilizado o sample `sample-po-table-transport.html` para mostrar o resultado da implementação.
```
<po-table p-hide-columns-manager p-sort="true" [p-columns]="columns" [p-items]="items" [p-striped]="true">
<ng-template
p-table-row-template …
```
> feat(table): implementa opção para mudar a posição do detail

- projects/templates/src/lib/components/po-page-login/interfaces/po-page-login-literals.interface.ts
- projects/templates/src/lib/components/po-page-login/po-page-login-base.component.spec.ts
- projects/templates/src/lib/components/po-page-login/po-page-login-base.component.ts
- projects/templates/src/lib/components/po-page-login/po-page-login.component.html
- projects/templates/src/lib/components/po-page-login/po-page-login.component.spec.ts
- projects/templates/src/lib/components/po-page-login/po-page-login.component.ts
**Page Login**
**DTHFUI-3709**
Atualmente o template concatenava a palavra "Bem-vindo" junto com o nome do produto. E se a literal `title` fosse adicionada
ele substituía o "bem-vindo + o nome do produto" pelo `title`.
- depreciado a propriedade `title`. Enquanto houver o suporte, o valor do `title` substituirá o valor do `p-product-name`, quando este não for preenchido. 
- criação da propriedade `welcome` que apresenta a mensagem bem-vindo
- p-product-name passa a aparecer no layout sem a concatenação com a palavra "bem-vindo".
- alterações visuais conforme o protótipo da issue.
- alteração em algumas tags semânticas visando uma …
> feat(page-login): adiciona a propriedade `welcome` nas literais

- docs/guides/migration-poui-v2.md
- docs/guides/migration-poui-v3.md
- projects/schematics/src/package-config/index.ts
- projects/schematics/src/package-config/package-config.ts
- projects/schematics/src/package-config/update-dependencies.interface.ts
- projects/sync/schematics/migrations.json
- projects/sync/schematics/ng-update/v3/changes.ts
- projects/sync/schematics/ng-update/v3/index.ts
- projects/ui/schematics/migrations.json
- projects/ui/schematics/ng-update/v3/changes.ts
- projects/ui/schematics/ng-update/v3/index.ts
**Ng Update: Components e Sync**
**DTHFUI-3715**
N/A
- Implementa ng update nos pacotes `@po-ui/ng-components` e `@po-ui/ng-sync`.
- Cria documento de migração para v3, neste documento possui as alterações que serão realizadas.
**Simulação**
[projeto-ngv10-pov2.zip](https://github.com/po-ui/po-angular/files/4938008/projeto-ngv10-pov2.zip)
[projeto-posync-v2.zip](https://github.com/po-ui/po-angular/files/4938406/new-po-sync-getting-started.zip)
- Buildar os pacotes com a versão 3
- Publicar localmente no verdaccio
- Executar o `ng update @po-ui/ng-components` em um projeto que possui o @po-ui/ng-components instalado na v2
- Executar o …
> feat(components): implementa ng update para versão 3 

- CHANGELOG.md
- CONTRIBUTING.md
docs: atualiza changelog com informações do angular 10
docs(contributing): corrige descrição do commit com breaking change
Para gerar o release e capturar corretamente as quebras de versão,
o corpo do commit deve ter:
BREAKING CHANGE ao invés de
BREAKING CHANGES
> docs: atualiza changelog com informações do angular 10

- docs/guides/sync-fundamentals.md
- projects/schematics/src/build-component/build-component.ts
- projects/schematics/src/build-file/build-file.ts
- projects/schematics/src/project/project.ts
**Schematics**
**DTHFUI-3832**
Ocorria erro ao executar o ng generate nos pacotes:
@po-ui/ng-sync
@po-ui/ng-components
@po-ui/templates
_Cannot read "ProjectType" of undefined._
Para corrigir o problema foi criado uma função no pacote @po-ui/ng-schematics
Que recupera o default path corretamente.
**Simulação**
- Buildar pacotes, utilizar npm link nos schematics, components, templates e sync.
- Rodar ng generate passando o projeto ou definir o projeto default como "app" no angular.json
- ng g @po-ui/ng-components:po-page-list listagem --project app
ou também publicar no verdaccio os pacotes  e testar em uma aplicação basica.
- ng new …
> fix(schematics): corrige erro ao executar o ng generate

- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.html
**PO-MULTISELECT**
**DTHFUI-3825**
Ao realizar uma busca que não retorne itens o campo de pesquisa desaparece. Caso o usuário queira refazer a busca ele precisa fechar o dropdown e reiniciar o processo. 
Ao realizar uma busca que não retorne itens o campo de busca permanece na tela, permitindo que o usuário refaça a busca.
**Simulação**
Nos samples do portal.
> fix(multiselect): corrige desaparecimento do campo de pesquisa

- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.html
**TABLE**
**DTHFUI-3857**
No Sample Po Table Labs o uso da propriedade p-show-more-disabled
esta incorreto.
Quando marcar a opção "Show more disabled" deve desabilitar o botão de "carregar mais resultados", e
Quando desmarcar deve habilitar o botão "carregar mais resultados".
**Simulação**
Sample Po Table Labs
> fix(table): corrige no sample o uso da propriedade showMoreDisabled

- projects/templates/src/lib/components/po-page-change-password/samples/sample-po-page-change-password-modify/sample-po-page-change-password-modify.component.ts
**PAGE CHANGE PASSWORD**
**DTHFUI-3876**
Ao utilizar o Sample Password Modify e clicar no botão alterar a senha, ocorre um erro no console e não exibe a modal de confirmação.
Ao utilizar o Sample Password Modify e clicar no botão de alterar senha, agora é exibida normalmente a modal de confirmação.
**Simulação**
Sample Password Modify do Portal.
> docs(page-change-password): corrige erro no sample password modify

- projects/templates/src/lib/components/po-page-login/interfaces/po-page-login-literals.interface.ts
- projects/templates/src/lib/components/po-page-login/po-page-login-base.component.ts
- projects/templates/src/lib/components/po-page-login/po-page-login.component.html
- projects/templates/src/lib/components/po-page-login/po-page-login.component.spec.ts
- projects/templates/src/lib/components/po-page-login/po-page-login.component.ts
- projects/templates/src/lib/components/po-page-login/samples/sample-po-page-login-labs/sample-po-page-login-labs.component.html
- projects/templates/src/lib/components/po-page-login/samples/sample-po-page-login-labs/sample-po-page-login-labs.component.ts
**PO-PAGE-LOGIN**
**DTHFUI-3712**
Não possui botão de suporte disponível aos usuários no template.
Ao atribuir valor para a nova propriedade p-support é habilitado um botão opcional de suporte que aceita tanto uma strinq que redirecionará o usuário para a url inserida, quanto uma função que será executada o clicar no botão. O label do botão está disponível nos 4 idiomas suportados e também foi inserido na interface PoPageLoginLiterals sendo possível sobrescrevê-lo conforme demais propriedades dessa interface.
**Simulação**
- Testar no Sample Labs do Portal;
- Testar a tradução;
- Testar nos diversos navegadores;
- Testar com o tema …
> feat(page-login): adiciona botão de suporte

- projects/templates/src/lib/components/po-page-dynamic-table/index.ts
- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-custom-action.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-options.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table-actions.service.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table-actions.service.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table-literals.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.html
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.component.html
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.service.ts
**Po Page Dynamic Table**
**DTHFUI-3710**
O usuário só conseguia adicionar as ações padrão do template.
Agora o usuário consegue adicionar novas ações customizadas na página e também possibilita a habilitação da seleção dos dados da tabela baseado na propriedade selectable. 
O usuário também pode utilizar através do load e do metadata.
- Também foi adicionado a correção para que o usuário possa utilizar o concatFilters e o keepFilters no endpoint de metadados. Por isso é necessários testar essa parte também. 
**Simulação**
- Pode ser utilizado o sample do portal. 
- Lembrar de testar os endpoints e o envio do resource. 
- …
> feat(page-dynamic-table): nova propriedade `p-page-custom-actions`

- projects/ui/src/lib/components/po-menu/po-menu-base.component.spec.ts
- projects/ui/src/lib/components/po-menu/po-menu-base.component.ts
- projects/ui/src/lib/components/po-menu/po-menu-filter/po-menu-filter-literals.interface.ts
- projects/ui/src/lib/components/po-menu/po-menu-filter/po-menu-filter.component.html
- projects/ui/src/lib/components/po-menu/po-menu-filter/po-menu-filter.component.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.ts
Feat(i18n-menu): implementados strings "Pesquisa" e mensagem de erro no menu label vazio em todos os idiomas, e "item nao encontrado" em russo
- [] Testes unitários
O string PESQUISAR estava hardcodeado em portugues.
A mensagem de erro quando o label do menu estava vazio, estava hardcodeado em portugues.
A string ITEM NAO ENCONTRADO nao estava implementada para o idioma russo
Todas as strings foram definidas em 4 idiomas, e o service i18nLanguage utilizado onde necessário.
**Simulação**
Acessar um componente de MENU e verificar que o idioma do placeholder PESQUISAR está no idioma selecionado no login.
Pesquisar um item inexistente e …
> feat(po-menu): implement i18n to menu and menu filter

- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-components/sample-po-table-components.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.ts
**PO-TABLE**
**DTHFUI-3911**
O loading do botão "Mostrar mais" é atrelado a propriedade `p-loading` no **PO-TABLE**, ou seja, quando a propriedade `p-loading` está **ativa**, é exibido um _loading_ na tabela e um _spinner loading_ no botão "Mostrar mais..."
Foi adicionado a propriedade `p-loading-show-more` que tem a mesma funcionalidade do `p-loading`, exceto que essa nova propriedade refere-se somente ao botão "Mostrar mais...", deixando assim os loadings independentes entre cada componente.
**Simulação**
Esta alteração esta no exemplo, **sample-po-table-components**
app.component.html
```
<po-table …
```
> feat(table): adiciona propriedade loading show more

- projects/code-editor/ng-package.json
- projects/code-editor/package.json
- projects/ui/src/lib/components/po-disclaimer-group/po-disclaimer-group-base.component.ts
- projects/ui/src/lib/components/po-menu-panel/po-menu-panel-base.component.ts
- projects/ui/src/lib/components/po-menu/po-menu-base.component.ts
- projects/ui/src/lib/components/po-modal/po-modal.component.ts
**NG-COMPONENT**
**DTHFUI-3932**
Na versão 10 o Angular passou a avaliar se o projeto utiliza CommomJS para importar módulos, que dificulta a tarefa de tree shaking. O nosso projeto usava o uuid ao mesmo tempo que também tinhamos uma função própria
Substituido o uso da função uuid pela versão do fonte utils.
A razão foi a nova validação do angular 10 sobre módulos que utilizam os imports do tipo CommonJS o warning não deve acontecer mais
**Simulação**
Executar o comando ng serve em qualquer projeto com o PO-UI v3 e Angular 10.
Repassar no portal os comonentes que foram alterados
> fix(): retirada do pacote uuid

- projects/ui/src/lib/components/po-list-view/po-list-view.component.html
- projects/ui/src/lib/components/po-list-view/samples/sample-po-list-view-hiring-processes/sample-po-list-view-hiring-processes.service.ts
- projects/ui/src/lib/components/po-list-view/samples/sample-po-list-view-labs/sample-po-list-view-labs.component.html
- projects/ui/src/lib/components/po-list-view/samples/sample-po-list-view-labs/sample-po-list-view-labs.component.ts
**PO-LIST-VIEW**
**DTHFUI-3908**
Há um desalinhamento da caixa de seleção, no Sample Labs não é possível utilizar a propriedade `p-hide-select-all` e no Sample Hiring Processes ao clicar no título do item á chamada uma url que não existe.
Foi incluída uma classe css que corrige o alinhamento da caixa de seleção. Foi atualizada as urls do sample Hiring Processes e foi corrigido o comportamento da seleção da propriedade Hide Select All no SampleLabs, após selecionar  a propriedade Select.
**Simulação**
Simular nos samples do Portal.
OBS: possui PR no [po-style](https://github.com/po-ui/po-style/pull/135).
> fix(list-view): corrige alinhamento da caixa de seleção

- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-body/po-rich-text-body.component.spec.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-body/po-rich-text-body.component.ts
**PO-RICH-TEXT**
**DTHFUI-3907**
A tentar abrir um link já carregado na inicialização do componente ou um link posteriormente colado, não é possível abrir o link.
Corrige abertura de links com CMD/ctrl de um conteúdo já carregado no componente ou um link colado posteriormente.
**Simulação**
No sample Recipe do portal é possível testar se o link da receita abre com o CMD ou Ctrl, também é possível copiar e colar um link para verificar se o mesmo também abre normalmente.
> fix(rich-text): corrige abertura de links com CMD ou Ctrl

- projects/ui/src/lib/components/po-field/po-lookup/interfaces/po-lookup-column.interface.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.ts
**po-lookup**
**DTHFUI-3935**
O input do componente não exibia o valor selecionado se a propriedade p-field-label fosse modificada após a inicialização do componente
Agora ao modificar o valor para p-field-label e selecionar um novo item para o lookup ele exibirá conforme a definição de valor da propriedade. Foi também feita uma pequena modificação sem relação com o bug na documentação.
**Simulação**
Campo 'field label' no sample labs do portal
> fix(lookup): altera p-field-label dinamicamente

- docs/guides/sync-fundamentals.md
Corrige link do repositorio do aplicativo PO Conference Application que
estava quebrado.
**guides**
**sem issue**
O link do repositorio do aplicativo PO Conference Application aponta para um endereço errado
O link do repositorio do aplicativo PO Conference Application aponta para o endereço correto
**Simulação**
Acessar a documentação dos fundamentos do Sync, ir até o final da página e acessar o repositório do aplicativo de demonstração.
> docs(sync): corrige link do repositorio de demonstração

- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.ts
**Page Job Scheduler**
**Simulação**
```
default: {
},
contexts: {}
};
...
@NgModule({
AppComponent
],
imports: [
...
],
})
```
> feat(page-job-scheduler): permite traduzir literais usando serviço i18n

- projects/templates/src/lib/components/po-page-dynamic-table/index.ts
- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-custom-table-action.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-options.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.component.html
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.component.ts
**PageDynamicTable**
**DTHFUI-3711**
N/A
Adiciona a propriedade p-table-custom-actions
que possibilita a customização das ações da tabela,
unindo-se a ações informada através da propridade p-actions
**Simulação**
Pode ser utilizado o Sample no Portal e o [Projeto APP](https://github.com/po-ui/po-angular/files/5038973/app.zip)
> feat(page-dynamic-table): adiciona a propriedade p-table-custom-actions

- projects/ui/src/lib/services/po-notification/po-toaster/po-toaster.component.spec.ts
- projects/ui/src/lib/services/po-notification/po-toaster/po-toaster.component.ts
**Notification**
**Simulação**
```
default: {
},
contexts: {}
};
...
@NgModule({
AppComponent
],
imports: [
...
],
})
```
> feat(notification): permite traduzir literais usando serviço i18n

- projects/ui/src/lib/services/po-dialog/po-dialog.component.spec.ts
- projects/ui/src/lib/services/po-dialog/po-dialog.component.ts
**Dialog**
**Simulação**
```
default: {
},
contexts: {}
};
...
@NgModule({
AppComponent
],
imports: [
...
],
})
```
> feat(dialog): permite traduzir literais usando serviço i18n

- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.ts
**datepicker**
**DTHFUI-3982**
Se preenchido o campo de data de modo incompleto e sair dele, o usuário não recebe alerta algum.
Tratada validação de campo ao sair do input. Se o campo estiver incompleto exibe mensagem de erro e o campo fica em vermelho.
**Simulação**
Sample labs
> fix(datepicker): valida input ao sair do campo

- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
**Table**
**Simulação**
```
default: {
},
contexts: {}
};
...
@NgModule({
AppComponent
],
imports: [
...
],
})
```
> feat(table): permite traduzir literais usando serviço i18n

- projects/ui/src/lib/components/po-navbar/po-navbar-base.component.spec.ts
- projects/ui/src/lib/components/po-navbar/po-navbar-base.component.ts
- projects/ui/src/lib/components/po-navbar/po-navbar.component.ts
**Navbar**
**Simulação**
```
default: {
},
contexts: {}
};
...
@NgModule({
AppComponent
],
imports: [
...
],
})
```
> feat(navbar): permite traduzir literais usando serviço i18n

- projects/ui/src/lib/components/po-disclaimer-group/po-disclaimer-group-base.component.spec.ts
- projects/ui/src/lib/components/po-disclaimer-group/po-disclaimer-group-base.component.ts
- projects/ui/src/lib/components/po-disclaimer-group/po-disclaimer-group.component.ts
**Disclaimer Group**
**Simulação**
```
default: {
},
contexts: {}
};
...
@NgModule({
AppComponent
],
imports: [
...
],
})
```
> feat(disclaimer-group): permite traduzir literais usando serviço i18n

- projects/ui/src/lib/components/po-list-view/po-list-view-base.component.spec.ts
- projects/ui/src/lib/components/po-list-view/po-list-view-base.component.ts
- projects/ui/src/lib/components/po-list-view/po-list-view.component.ts
**List View**
**Simulação**
```
default: {
},
contexts: {}
};
...
@NgModule({
AppComponent
],
imports: [
...
],
})
```
> feat(list-view): permite traduzir literais usando serviço i18n

- projects/ui/src/lib/components/po-field/po-switch/po-switch-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-switch/po-switch-base.component.ts
- projects/ui/src/lib/components/po-field/po-switch/po-switch.component.spec.ts
- projects/ui/src/lib/components/po-field/po-switch/po-switch.component.ts
**SWITCH**
implementa ChangeDetectionStrategy.OnPush no componente para deixa-lo mais performático.
E também anteriormente o componente fazia a detecção de mudança todas vez que sua view era checked (ngAfterViewChecked) fazendo que todos os componentes presentes no DOM realizasse a checkagem.
**Simulação**
- Pode-se utilizar componentes como po-table,input e colocar um get com check e imprimi-lo para verificar a diferença.
```
<component>.html
<div> ... </div>
{{ check }}
```
```
<component>.ts
get check() {
console.log('<component> check')
return '';
}
```
- Sample Portal, e;
```
app.component.html
<po-switch name="cnpj" …
```
> perf(switch): implementa ChangeDetectionStrategy.OnPush

- projects/templates/src/lib/components/po-modal-password-recovery/po-modal-password-recovery-base.component.spec.ts
- projects/templates/src/lib/components/po-modal-password-recovery/po-modal-password-recovery-base.component.ts
- projects/templates/src/lib/components/po-modal-password-recovery/po-modal-password-recovery.component.ts
**Modal Password Recovery**
**Simulação**
```
default: {
},
contexts: {}
};
...
@NgModule({
AppComponent
],
imports: [
...
],
})
```
> feat(modal-password-recovery): faz tradução de literais com serviço i18n

- projects/templates/src/lib/components/po-page-background/po-page-background.component.spec.ts
- projects/templates/src/lib/components/po-page-background/po-page-background.component.ts
- projects/templates/src/lib/components/po-page-login/po-page-login-base.component.spec.ts
- projects/templates/src/lib/components/po-page-login/po-page-login-base.component.ts
- projects/templates/src/lib/components/po-page-login/po-page-login.component.ts
Feat(combo): Remember user language selection stored in localstorage
Cada vez que abre a tela do componente po-page-login é 
necesessário selecionar o idioma de uso da aplicacao. 
Atualmente seleciona sempre o idioma do browser.
Eh carregado por default o ultimo idioma selecionado no browser, 
baseda na variavel guardada no localstorage pelo PO-login-page
**Simulação**
Acessar um componente po-Page-Login, selecionar idioma diferente 
do browser e fazer login.
Fechar a janela, acessar o login novamente e conferir que o idioma 
selecionado no passo anterior esta pre-selecionado.
> Feat(page-login): Remember language selection stored in localstorage

- projects/templates/src/lib/components/po-page-background/po-page-background.component.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-summary/po-page-job-scheduler-summary.component.spec.ts
- projects/templates/src/lib/utils/util.spec.ts
- projects/templates/src/lib/utils/util.ts
**Templates**
N/A
Remove a função browserLanguage do pacotes de templates, agora deve ser usada a função getShortBrowserLanguage ou o serviço PoLanguageService.
**Simulação**
N/A
> refactor(templates): remove função browserLanguage do utils

- projects/templates/src/lib/components/po-page-change-password/po-page-change-password.component.spec.ts
**PO-PAGE-CHANGE-PASSWORD**
**DTHFUI-4017**
Ao executar os testes de forma geral com npm run test, tem testes falhando de forma intermitente do componente po-page-change-password.
Corrigida importação dos módulos do TestBed
**Simulação**
Executar build da PR 5 vezes ou mais.
> test(po-page-change-password): correção na importação dos módulos do TestBed

- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/utils/util.spec.ts
- projects/ui/src/lib/utils/util.ts
Fixes DTHFUI-3919
**TABLE**
**DTHFUI-3919**
A ordenação com valores nulos estava incoerente.
Os itens com valores invalidos (null, undefined, NaN)
devem ficar no topo e em baixo após a ordenação.
**Simulação**
- Simular no Portal, e;
- Alterar algum sample e adicionar valores nulos em diferentes tipos de colunas (number, date, boolean)
> fix(table): corrige ordenação quando possui valores inválidos

- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-base.component.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-body/po-rich-text-body.component.spec.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-body/po-rich-text-body.component.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text.component.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text.service.spec.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text.service.ts
**PO RICH TEXT**
**DTHFUI-3787**
Ao tentar atualizar o valor do rich-text via código o valor não é atualizado.
Corrige comportamento ao atualizar o valor do componente via código.
**Simulação**
```
<po-rich-text 
name="richText"
[(ngModel)]="richText">
</po-rich-text>
<po-textarea class="po-md-6" name="model" [(ngModel)]="richText" p-label="Model" p-readonly p-rows="8"> </po-textarea>
<po-button (p-click)="mudaValorRichText()" p-label="mudar o valor do rich-text"></po-button>
```
- app.component.ts:
```
@Component({
templateUrl: …
```
> fix(rich-text): corrige atualização do model via código

- projects/ui/src/lib/components/po-field/po-combo/po-combo-filter.service.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-filter.service.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
**COMBO**
**DTHFUI-3653**
Ao ocorrer um erro na pequisa, utilizando serviço, o componente ficava no estado de carregando e apresentava notificações de erro.
Também ficava preso no estado de carregando, não sendo possível fechar o popup.
Ao ocorrer algum erro na pesquisa, apresenta-se "Dado não encontrado" e omite as notificações de erro.
**Simulação**
- Utilizar Sample Labs e passar um serviço inexistente,
> fix(combo): adiciona tratamento para retorno de erro HTTP na pesquisa

- projects/code-editor/src/lib/components/po-code-editor/interfaces/po-code-editor-registerable-suggestion.interface.ts
- projects/code-editor/src/lib/components/po-code-editor/interfaces/po-code-editor-registerable.interface.ts
- projects/code-editor/src/lib/components/po-code-editor/po-code-editor-base.component.spec.ts
- projects/code-editor/src/lib/components/po-code-editor/po-code-editor-base.component.ts
- projects/code-editor/src/lib/components/po-code-editor/po-code-editor-register.service.ts
- projects/code-editor/src/lib/components/po-code-editor/po-code-editor-suggestion.service.spec.ts
- projects/code-editor/src/lib/components/po-code-editor/po-code-editor-suggestion.service.ts
- projects/code-editor/src/lib/components/po-code-editor/po-code-editor.component.spec.ts
- projects/code-editor/src/lib/components/po-code-editor/po-code-editor.component.ts
- projects/code-editor/src/lib/components/po-code-editor/samples/sample-po-code-editor-suggestion/sample-po-code-editor-suggestion.component.html
- projects/code-editor/src/lib/components/po-code-editor/samples/sample-po-code-editor-suggestion/sample-po-code-editor-suggestion.component.ts
- projects/code-editor/src/lib/components/po-code-editor/samples/sample-po-code-editor-terraform/sample-po-code-editor-terraform.constant.ts
- projects/code-editor/src/lib/components/po-code-editor/samples/sample-po-code-editor-terraform/sample-po-code-editor-terraform.module.ts
- projects/code-editor/src/lib/index.ts
**CODE-EDITOR**
**DTHFUI-2797**
Não era possivel incluir novas sugestões ao editor
Além de adicionar a propriedade `p-suggestions` ao componente, foram
adicionados alguns testes para aumentar o coverage do componente
garantido mais qualidade ao código.
Com essa nova funcionalidade o desenvolvedor pode adicionar uma lista
de sugestões para o autocomplete (além de snippets) quando cria uma nova
sintaxe ou diretamente a uma linguagem já existentes diretamente no
componente.
**Simulação**
É possível realizar o testes nesses dois projetos
[app_terraform_2.zip](https://github.com/po-ui/po-angular/files/5144060/app_terraform_2.zip) …
> feat(code-editor): adiciona propriedade `p-suggestions`

- projects/ui/src/lib/services/po-i18n/index.ts
- projects/ui/src/lib/services/po-i18n/po-i18n-base.service.ts
- projects/ui/src/lib/services/po-i18n/po-i18n.service.ts
**I18n**
**DTHFUI-4113**
No desenvolvimento de testes unitarios em componentes que utilizam o PoI18n apresenta erros de "default is not a function" e dependencia ciclica.
Foi exportado o arquivo po-i18n-config-injection-token e declarado
a propriedade provideIn do serviço.
Também foi incluído aviso na documentação.
**Simulação**
- Utilizar o projeto em anexo, buildar o ng component e colar no node_module do projeto
[taf-thf.zip](https://github.com/po-ui/po-angular/files/5163958/taf-thf.zip)
> fix(i18n): correção para uso do componente PoI18n nos testes unitários

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/samples/sample-po-dynamic-form-register/sample-po-dynamic-form-register.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/samples/sample-po-dynamic-form-register/sample-po-dynamic-form-register.component.ts
**DTHFUI-4120**
É disparado o validate do formulário para qualquer modificação de campo.
A nova propriedade permite ao desenvolvedor restringir o disparo do validate do form para apenas os campos desejados
**Simulação**
O método `onChangeFields` do sample `PO Dynamic Form - Register` deve ser disparado somente quando modificado o field 'state'. 
Pode-se também testar no mesmo sample alterando `p-validate` recebendo `string` como valor para verificar assim o disparo da requisição.
> feat(dynamic-form): adiciona propriedade `p-validate-fields`

- docs/guides/sync-get-started.md
- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-field.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-list-base.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-list-base.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.component.ts
**DYNAMIC TABLE**
**DTHFUI-4135 e DTHFUI-4119**
- Exibe o botão "Novo" caso informar objeto que não possua a propriedade `new`;
- Não exibia o campo na busca avançada caso informasse visible: true;
O componente estava muito lento, devido aos `gets` que estavam sendo utilizados.
- Não exibe o botão "Novo" caso não informar
valor na propriedade actions.new.
- Adiciona a propriedade PoPageDynamicField. AllowColumnsManager,
que permite visualiza-lo no gerenciador de colunas
mesmo estando visible: false;
- Exibe o filtro mesmo que o campo esteja invisivel na
tabela (visible=false);
- Melhora a performance do componente, eliminando os gets …
> feat(dynamic-table): exibe o filtro mesmo que o campo esteja invisível 

- package.json
- projects/storage/package.json
- projects/storage/src/lib/services/po-storage.service.ts
**storage**
**DTHFUI-4009**
O build de projetos utilizando AppShell e que contenham pacotes do Sync e Storage instalados estava gerando erro relacionado ao LocalForage. 
Atualizado pacote do LocalForage. O adendo de importação do pacote adicionada em `po-storage.service.ts` soluciona o problema que impediu a atualização do mesmo quando foram atualizados todos pacotes do projeto.
A atualização também resolve o problema relacionado ao build em aplicações com AppShell.
**Simulação**
Primeiramente pegar atualização do LocalForage no PO Angular:
1 - `npm run build:storage`;
2 - Apontar o tgz gerado no pacote do storage no `package.json` …
> feat(storage): atualiza pacote do localForage

- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.html
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-labs/sample-po-combo-labs.component.html
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-labs/sample-po-combo-labs.component.ts
**po-combo**
**DTHFUI-2314**
Para limpar o combo, é necessário apagar todos caracteres do input.
Ao atribuir o valor true para a propriedade p-clean e selecionar um item no combo, será exibido um ícone X. Ao clicar neste ícone, o combo será limpo.
**Simulação**
Criar um po-combo com a propriedade p-clean, escolher alguma opção do combo e clicar no X ao lado da seta. O combo deve ser limpo e o ngModel deve ser atualizado
> feat(combo): adiciona a propriedade p-clean

- .github/workflows/ci.yml
- package.json
- projects/storage/schematics/ng-add/index.spec.ts
- projects/storage/tsconfig.schematics.json
**@po-ui/ng-storage**
**DTHFUI-3458**
O ng-storage não tinha testes unitários
- novos testes unitarios dos schematics do ng-storage
- adiciona o comando na esteira do CI
**Simulação**
- entrar na branch;
- npm i
- npm run test:storage:schematics
- verificar o github actions
> feat(schematics): adiciona testes unitários para o @po-ui/ng-storage

- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search-base.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search-base.component.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search-options.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.ts
- projects/templates/src/lib/components/po-page-dynamic-search/samples/sample-po-page-dynamic-search-hiring-processes/sample-po-page-dynamic-search-hiring-processes.component.html
- projects/templates/src/lib/components/po-page-dynamic-search/samples/sample-po-page-dynamic-search-hiring-processes/sample-po-page-dynamic-search-hiring-processes.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-options.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.html
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.component.html
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.component.ts
**page-dynamic-search**
**DTHFUI-4118**
O componente `po-page-list` possui propriedade para definição de largura do campo de busca porém não recebe o repasse para tal no template `page-dynamic-search`.
O desenvolvedor agora pode definir uma largura para o campo de busca rápida nos templates `page-dynamic-search` e `page-dynamic-table`.
**Simulação**
Samples de uso dos templates.
> feat(page-dynamic-search): adiciona propriedade p-quick-search-width

- .github/workflows/ci.yml
- package.json
- projects/code-editor/schematics/ng-add/index.spec.ts
- projects/code-editor/tsconfig.schematics.json
**@po-ui/ng-code-editor**
**DTHFUI-3460**
O ng-code-editor não tinha testes unitários
- novos testes unitários dos schematics do ng-code-editor
- adiciona o comando na esteira do CI
**Simulação**
- entrar na branch;
- npm i
- npm run test:code-editor:schematics
- verificar o github actions
> feat(schematics): adiciona testes unitários para o @po-ui/ng-code-editor

- projects/ui/src/lib/components/po-menu/po-menu-base.component.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.spec.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.ts
**Po Menu**
**DTHFUI-4158**
Não estava buscando os itens que tinham `subItems: []`, mas se tivesse actions ou link definidos.
Agora busca todos os itens que contenham itens link ou actions definidos, conforme documentação. 
**Simulação**
- Usar o sample labs para criar os itens;
- Ou usar essa simulação:
```
menus = [
{ label: 'angular', link: '/', subItems: [] }, // encontra
{ label: 'react', action: () => {}, subItems: [ // encontra
{ label: 'sub react sem nada' }, // não encontra
{ label: 'sub react action', action: () => {}, subItems: [] }, // encontra
{ label: 'sub react sem subitems', link: '/' }, // encontra
] },
{ label: 'vue …
```
> fix(menu): corrige pesquisa para usar itens com subItems vazio

- .github/workflows/publish_po_angular_ci.yml
- projects/code-editor/package.json
- projects/schematics/package.json
- projects/storage/package.json
- projects/sync/package.json
- projects/templates/package.json
- projects/ui/package.json
**build**
**DTHFUI-4136**
N/A
Adiciona no github actions uma ação para publicar o pacote de forma automatizada.
Substitui a tag `dev` do package.json para `next`, para a partir dali o pacote ser publicado utilizando a tag next e latest.
**Simulação**
Para chegar em um teste mais próximo, pode ser utilizado o repositório [para testes](https://github.com/samir-ayoub/po-angular-test-github-actions). Utilize esse repositório para subir as versões e executar as actions.
Altere para uma nova versão executando `npm run release`
`git commit` e `git push`
Acesse abra a aba actions do repositório, clique em `PO-UI - publish`, posteriormente em …
> build(actions): cria ação de publicação dos pacotes

- .github/workflows/ci.yml
- package.json
- projects/sync/schematics/ng-add/index.spec.ts
- projects/sync/schematics/ng-generate/schema/index.spec.ts
**SCHEMATICS**
**<DTHFUI-3459**
Não é possível executar os testes unitários dos schematics ng add e ng generate do pacote ng-sync.
Adiciona testes unitários dos schematics ng add e ng generate do pacote ng-sync.
Também adiciona no CI a execução destes testes.
**Simulação**
- entrar na branch;
- npm i
- npm run test:sync:schematics
- verificar o github actions
> feat(schematics): adiciona testes unitários para o @po-ui/ng-sync

- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-body/po-rich-text-body.component.spec.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text.component.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text.service.ts
**PO-RICH-TEXT**
**DTHFUI-4248**
O componente está compartilhando o ngModel quando tem mais de um `po-rich-text` por tela.
Corrigido o compartilhamento do model.
**Simulação**
- Nos próprios samples do portal que na master todos mostram a receita do último sample e agora está como deveria.
- Teste no app:
app.component.html:
```
<po-rich-text
class="po-md-6"
p-label="Componente 1"
name="teste"
[(ngModel)]="teste">
</po-rich-text>
<po-info class="po-md-6" p-label="Model Componente 1" [p-value]="teste"> </po-info>
</div>
<po-divider></po-divider>
<po-rich-text
class="po-md-6" …
```
> fix(rich-text): corrige compartilhamento do ngModel

- projects/templates/src/lib/components/po-page-background/po-page-background.component.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search-base.component.ts
- projects/templates/src/lib/components/po-page-login/po-page-login-base.component.ts
- projects/ui/src/lib/components/po-disclaimer-group/po-disclaimer-group-base.component.ts
- projects/ui/src/lib/components/po-disclaimer/po-disclaimer-base.component.ts
- projects/ui/src/lib/components/po-field/po-checkbox-group/po-checkbox-group-base.component.ts
- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox-base.component.ts
- projects/ui/src/lib/components/po-field/po-clean/po-clean-base.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range-base.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.ts
- projects/ui/src/lib/components/po-field/po-input/po-input-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
- projects/ui/src/lib/components/po-field/po-radio-group/po-radio-group-base.component.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-base.component.ts
- projects/ui/src/lib/components/po-field/po-select/po-select-base.component.ts
- projects/ui/src/lib/components/po-field/po-switch/po-switch-base.component.ts
- projects/ui/src/lib/components/po-field/po-textarea/po-textarea-base.component.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.component.ts
- projects/ui/src/lib/components/po-list-view/po-list-view-base.component.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table-detail/po-table-detail.component.ts
- projects/ui/src/lib/components/po-tag/po-tag-base.component.ts
- projects/ui/src/lib/components/po-widget/po-widget-base.component.ts
Ajusta a declaração incorreta nos projetos ui e templates dos eventemitter.
**< DTHFUI-4309 >**
Não permite o uso do po-ui com strict mode ativo
Permite o uso do po-ui com strict mode ativo
**Simulação**
ng new strict-po --strict=true --skipTests=true --skipInstall=true
#altera o package.json conforme guia de instalação
npm i
ng add @po-ui/ng-components
cria a function fn no home component ts
inclui no home component html <po-table (p-show-more)="fn()"></po-table>
ng build --prod
no console, Object is possibly 'undefined'
> fix(ui/templates): ajusta declaracao incorreta dos event emitter

- projects/ui/src/lib/components/po-field/po-field.module.ts
- projects/ui/src/lib/components/po-field/po-lookup/interfaces/po-lookup-advanced-filter.interface.ts
- projects/ui/src/lib/components/po-field/po-lookup/interfaces/po-lookup-filtered-items-params.interface.ts
- projects/ui/src/lib/components/po-field/po-lookup/interfaces/po-lookup-literals.interface.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.html
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-hero/sample-po-lookup-hero.component.html
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-hero/sample-po-lookup-hero.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-labs/sample-po-lookup-labs.component.html
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-labs/sample-po-lookup-labs.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup.service.ts
- projects/ui/src/lib/components/po-field/po-lookup/services/po-lookup-filter.service.ts
- projects/ui/src/lib/components/po-field/po-lookup/services/po-lookup-modal.service.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/services/po-lookup-modal.service.ts
**PO-LOOKUP**
**DTHFUI-487**
O componente atual não possui um busca avançada configurável, limitando os campos que podem ser pesquisados ou tendo que fazer o filtro simples pesquisar por todos os campos da tabela.
Adicionado uma nova propriedade, p-advanced-filters, onde permite configurar um array de PoDynamicFormField para criar uma nova tela de busca avançada, permitindo filtrar pelos campos inseridos nessa propriedade.
**Simulação**
- Arquivos necessários para simular com o app:  [app.zip](https://github.com/po-ui/po-angular/files/5245400/app.zip)
- Para o estilo do botão de busca avançada ficar correto deve-se pegar as …
> feat(lookup): inclusão da propriedade de busca avançada 

- projects/ui/src/lib/components/po-field/po-input/po-input-base.component.ts
- projects/ui/src/lib/components/po-field/po-number/po-number-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-number/po-number-base.component.ts
- projects/ui/src/lib/components/po-field/po-number/po-number.component.html
- projects/ui/src/lib/components/po-field/po-number/po-number.component.ts
**PO-NUMBER**
**DTHFUI-591**
Possibilita utilizar a letra `e` no Chrome e também possibilita utilizar todas as letras no Firefox e I.E.
Restringe o comportamento do componente a aceitar somente números em todos os navegadores suportados.
**Simulação**
Pode ser simulado nos samples do portal.
> fix(number): permitir apenas números

- projects/ui/src/lib/components/po-page/index.ts
- projects/ui/src/lib/components/po-page/po-page-default/po-page-default-base.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-default/po-page-default-base.component.ts
- projects/ui/src/lib/components/po-page/po-page-default/po-page-default-literals.interface.ts
- projects/ui/src/lib/components/po-page/po-page-default/po-page-default.component.html
- projects/ui/src/lib/components/po-page/po-page-default/po-page-default.component.ts
- projects/ui/src/lib/components/po-page/po-page-default/samples/sample-po-page-default-labs/sample-po-page-default-labs.component.html
- projects/ui/src/lib/components/po-page/po-page-default/samples/sample-po-page-default-labs/sample-po-page-default-labs.component.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list-base.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list-base.component.ts
**page-default**
**DTHFUI-1896**
Não há definição de literais para o componente page-default.
Além disso, a classe page-list-base extende a classe page-default-base e isso impacta na documentação no portal.
Definidas literais para page-default.
Removida extensão de classe e alocadas propriedades p-actions e p-title para a classe page-list-base.
**Simulação**
sample labs dos componentes
> feat(page-default): define literais para idiomas suportados

- projects/templates/src/lib/components/po-page-background/po-page-background.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-advanced-filter/po-advanced-filter-base.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-decimal/po-decimal.component.spec.ts
- projects/ui/src/lib/components/po-field/po-decimal/po-decimal.component.ts
- projects/ui/src/lib/components/po-field/po-decimal/samples/sample-po-decimal-labs/sample-po-decimal-labs.component.html
- projects/ui/src/lib/components/po-field/po-decimal/samples/sample-po-decimal-labs/sample-po-decimal-labs.component.ts
- projects/ui/src/lib/services/po-language/po-language.constant.ts
- projects/ui/src/lib/services/po-language/po-language.interface.ts
- projects/ui/src/lib/services/po-language/po-language.service.spec.ts
- projects/ui/src/lib/services/po-language/po-language.service.ts
**po-decimal**
**DTHFUI-4311**
A formatação do valor não respeita a configuração de idioma do usuário
Criada propriedade e caso ela não seja passada irá respeitar a configuração da app ou do browse.
**Simulação**
Pode ser testado no labs do portal e também no app em anexo [app.zip](https://github.com/po-ui/po-angular/files/5425392/app.zip)
> feat(decimal): cria propriedade `p-locale` para definição de formatação de separadores segundo país

- projects/ui/src/lib/components/po-popover/po-popover-base.component.ts
- projects/ui/src/lib/components/po-popover/po-popover.component.spec.ts
- projects/ui/src/lib/components/po-popover/po-popover.component.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.html
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
**PO-TABLE E PO-POPOVER**
**DTHFUI-3699**
Hoje não é possível saber quais colunas que o usuário configurou para ficar visível.
Criado evento `p-change-visible-columns` que será disparado ao alterar as colunas visíveis no gerenciador de colunas e fechar o popover do gerenciador.
**Simulação**
```
<po-table
[p-columns]="hiringProcessesColumns"
[p-items]="hiringProcesses"
(p-change-visible-columns)="myOnChangeVisibleColumns($event)"
>
</po-table>
```
- app.component.ts:
```
hiringProcesses: Array<object>;
hiringProcessesColumns: Array<PoTableColumn>;
constructor() {}
ngOnInit() {
this.hiringProcesses = …
```
> feat(table): inclui evento `p-change-visible-columns`

- projects/ui/src/lib/components/po-table/po-table-base.component.ts
Fixes DTHFUI-3699
**PO-TABLE**
**DTHFUI-3699**
A documentação da propriedade 'p-change-visible-columns' não está muito clara sobre o momento em que o evento será disparado.
Ajustada a documentação para melhor entendimento da funcionalidade
**Simulação**
Verificar no portal.
> docs: ajusta documentação da propriedade 'p-change-visible-columns' do 'po-table'

- projects/ui/src/lib/components/po-field/po-number/po-number.component.html
- projects/ui/src/lib/components/po-field/po-number/samples/sample-po-number-labs/sample-po-number-labs.component.html
- projects/ui/src/lib/components/po-field/po-number/samples/sample-po-number-labs/sample-po-number-labs.component.ts
**po-number**
**Fixes #437, DTHFUI-3572**
O componente `po-number` atualmente não tem a possibilidade de adicionar um ícone, todavia a propriedade `p-icon` aparece em sua documentação.
Adiciona a propriedade icon para o componente ter um ícone da biblioteca de ícones.
**Simulação**
Testar com o sample labs utilizando o select de ícone ou adicionar a propriedade `p-icon` no componente `po-number`:
`<po-number name="number" p-label="PO Number" p-icon="po-icon-star"> </po-number>`
> feat(number): adiciona a propriedade p-icon

- projects/templates/src/lib/components/po-page-dynamic-search/po-advanced-filter/po-advanced-filter-base.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-advanced-filter/po-advanced-filter-base.component.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-advanced-filter/po-advanced-filter.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-advanced-filter/po-advanced-filter.component.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
**page-dynamic-search**
**DTHFUI-2726**
Quando um dos filters usa o combo, o mesmo exibe os valores selecionados e não a descrição que o usuário usou para fazer o filtro.
- Criada nova propriedade `p-emit-object-value` em  **po-combo** para que o usuário opte por receber o objeto selecionado ao invés do model no evento `p-change`;
- Quando o usuário usar um combo para fazer um filtro, o disclaimer deve exibir a descrição do item selecionado e não o valor "interno". 
**Simulação**
No sample `SamplePoPageDynamicSearchHiringProcessesComponent`, substitua por favor na linha 41 por esse objeto: 
`{ property: 'city', optionsService: …
> fix(page-dynamic-search): corrige filtro para tipo combo

- projects/ui/src/lib/services/po-dialog/interfaces/po-dialog.interface.ts
- projects/ui/src/lib/services/po-dialog/po-dialog.component.spec.ts
- projects/ui/src/lib/services/po-dialog/po-dialog.component.ts
- projects/ui/src/lib/services/po-dialog/samples/sample-po-dialog-labs/sample-po-dialog-labs.component.ts
**po-dialog**
**651**
O po-dialog não permite a utilização de um callback para o botão fechar (x), impossibilitando que saibamos quando o dialog é fechado por ele.
Foi adicionado o parâmetro `close`, que é o callback para o botão fechar.
**Simulação**
Pode ser simulado nos samples do portal.
> feat(dialog): adiciona o evento close

- projects/ui/src/lib/components/po-field/po-input-generic/po-input-generic.ts
- projects/ui/src/lib/components/po-field/po-input/po-input-base.component.ts
- projects/ui/src/lib/components/po-field/po-password/po-password.component.spec.ts
- projects/ui/src/lib/components/po-field/po-password/po-password.component.ts
**PO-PASSWORD**
**#633**
O campo é preenchido automaticamente com a senha salva mesmo com o autocomplete desabilitado.
O campo não é mais completado automaticamente devido à utilização da propriedade `autocomplete="new-password"`.
**Simulação**
Utilizar o componente `po-password` em um formulário qualquer com a propriedade `p-no-autocomplete` ativada, digitar uma senha, fazer o submit do formulário e aceitar quando o navegador oferecer para salvar a senha. Ao voltar para o formulário, o `po-password` não será mais preenchido automaticamente.
> fix(password): sobrescreve a propriedade autocomplete

- projects/ui/src/lib/components/po-breadcrumb/po-breadcrumb-favorite/po-breadcrumb-favorite.component.html
- projects/ui/src/lib/components/po-breadcrumb/po-breadcrumb-favorite/po-breadcrumb-favorite.component.spec.ts
- projects/ui/src/lib/components/po-breadcrumb/po-breadcrumb-favorite/po-breadcrumb-favorite.component.ts
**BreadCrumb**
**MDO-35**
- [ X ] Código
Favoritar/Desfavoritar não suporta literais
Favoritar/Desfavoritar definir para literais suportados
**Simulação**
> feat(page-breadcrumb): define literais para idiomas suportados

- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-labs/sample-po-lookup-labs.component.html
O evento p-change será disparado ao alterar o ngModel. É uma função que será disparada quando houver alterações.
Fixes TIS-1
**po-lookup**
**TIS-1**
Não havia o evento change no componente
Criação do evento p-change, que deverá ser disparado toda vez que o model for alterado.
**Simulação**
Esta correção pode ser validada utilizando o sample labs no portal.
> feat(lookup): adicionar evento p-change

- projects/ui/src/lib/components/po-field/po-decimal/po-decimal.component.html
- projects/ui/src/lib/components/po-field/po-decimal/po-decimal.component.spec.ts
- projects/ui/src/lib/components/po-field/po-decimal/po-decimal.component.ts
- projects/ui/src/lib/components/po-field/po-decimal/samples/sample-po-decimal-labs/sample-po-decimal-labs.component.html
- projects/ui/src/lib/components/po-field/po-decimal/samples/sample-po-decimal-labs/sample-po-decimal-labs.component.ts
**PO-DECIMAL**
**#325** 
As mensagens de erros não são exibidas
As mensagens de erros são exibidas abaixo do input, seguindo o padrões dos demais componentes com essa característica
**Simulação**
Utilizar o componente po-decimal com validação de um valor mínimo para a propriedade p-min ou um valor máximo através da propriedade p-max, inserir uma mensagem de erro para a propriedade p-error-pattern, ao inserir um valor inválido com a validação a mensagem de erro com o texto inserido será exibida.
> feat(po-decimal): inclui as propriedades `p-error-pattern`, `p-min` e `p-max`

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/samples/sample-po-dynamic-form-register/sample-po-dynamic-form-register.component.ts
**TIS-4**
Atualmente não possui as propriedades currency, decimals-length, thousand-maxlength e icon
Adiciona propriedades as currency, decimals-length, thousand-maxlength e icon
**Simulação**
<po-dynamic-form [p-fields]="fields"></po-dynamic-form>
...
fields: Array<PoDynamicFormField> = [
...
{
property: 'wage',
label: 'Salario',
currency: true,
decimalsLength: 3,
thousandMaxlength: 7,
icon: 'po-icon-finance'
},
...
];
> feat(dynamic-form):  adiciona propriedades as decimals-length, thousand-maxlength e icon

- projects/ui/src/lib/components/po-menu/po-menu.component.spec.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.ts
**MENU**
Ao utilizar a propriedade p-collapsed não deve exibir a linha e o
elemento anchor caso os itens de menus não estejam corretamente
definidos.
**Simulação**
``` 
<po-menu p-collapsed [p-menus]="[ { label: 'Item 1', shortLabel: 'Item', icon: 'po-icon-user', link: '/' } ]"></po-menu>
```
> fix(menu): corrige exibição do rodape caso collasped for verdadeiro

- projects/ui/src/lib/components/po-field/po-field-container/po-field-container-literals.ts
- projects/ui/src/lib/components/po-field/po-field-container/po-field-container.component.html
- projects/ui/src/lib/components/po-field/po-field-container/po-field-container.component.spec.ts
- projects/ui/src/lib/components/po-field/po-field-container/po-field-container.component.ts
**po-field-container**
**MDO-39**
- [ X ] Código
A literal "Opcional" utilizado no po-field-container não traduz para os idiomas suportados.
A literal "Opcional" deverá utilizar no po-field-container as literais para os idiomas suportados.
**Simulação**
> field-container: traduz literais para os idiomas suportados

- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range-base.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range.literals.ts
**po-datepicker-range**
**MDO-40**
**traduzir literais no po-datepicker-range para os idiomas suportados**
- [ X ] Código
- [ X ] Documentação
serviço utiliza tradução do Browser
Utilizar o serviço de tradução (PoLanguageService) para traduzir as literais do componente PoDatepickerRange.
**Simulação**
> feat(datepicker-range): traduz as literais para os idiomas suportados

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
**po-dynamic-form**
**DTHFUI-4475**
A função p-validate do dynamic-form não esta disparando ao alterar o po-lookup.
Isto ocorre porque o po-lookup esta utilizando o p-selected para disparar a funcão changeField.
Toda alteração no model, será disparado o change do po-lookup
**Simulação**
<po-lookup *ngIf
...
(p-change)=changeField(..)>
</po-lookup>
> fix(dynamic-form): corrige disparo do evento p-validate

- projects/ui/src/lib/components/po-chart/po-chart-legend/po-chart-legend.component.html
- projects/ui/src/lib/components/po-chart/po-chart-legend/po-chart-legend.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-types/po-chart-circular/po-chart-circular-series.interface.ts
- projects/ui/src/lib/components/po-chart/po-chart-types/po-chart-circular/po-chart-circular.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-types/po-chart-circular/po-chart-circular.ts
- projects/ui/src/lib/components/po-chart/po-chart-types/po-chart-dynamic-type.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-types/po-chart-dynamic-type.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-types/po-chart-gauge/po-chart-gauge-series.interface.ts
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-basic/sample-po-chart-basic.component.html
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-coffee-ranking/sample-po-chart-coffee-ranking.component.ts
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-labs/sample-po-chart-labs.component.html
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-labs/sample-po-chart-labs.component.ts
Adiciona as propriedades label e data e deprecia as propriedades value e description.
Fixes DTHFUI-4444
**PO-CHART**
**DTHFUI-4444**
Atualmente há nomenclaturas diferentes para o valor da série e o texto que será exibido.
Nos gráficos do tipo Line e Column a nomenclatura atual é `label` para o texto que representa uma série e `data` para o valor da série. Porém nos outros gráficos as nomenclaturas são diferentes.
Foram crias novas propriedades `label` e `data` nas interfaces `PoCircularChartSeries` e `PoChartGaugeSerie` e foram depreciadas as propriedades:
- PoCircularChartSeries.category;
- PoCircularChartSeries.value;
- …
> feat(chart): adiciona propriedades label e data e deprecia value e description

- projects/ui/src/lib/components/po-field/po-number/po-number.component.spec.ts
- projects/ui/src/lib/components/po-field/po-number/po-number.component.ts
Permitir informar valores decimais nas propriedades p-min e p-max.
Fixes DTHFUI-3795
**po-number **
**DTHFUI-3795**
Atualmente não é possível passar casas decimais para as propriedades p-min e -max, com isso não consigo validar os valores minimo:1.99 e máximo: 9.99
O componente aceita números decimais como mínimo e máximo
**Simulação**
<po-number 
...
[p-min]="1.99"
[p-max]="9.99"
[p-step]="0.01">
</po-number>
> feat(number): permite usar números decimais nas propriedades min e max

- projects/ui/src/lib/components/po-modal/po-modal-base.component.spec.ts
- projects/ui/src/lib/components/po-modal/po-modal-base.component.ts
- projects/ui/src/lib/components/po-modal/po-modal.component.ts
- projects/ui/src/lib/components/po-modal/po-modal.literals.ts
**po-modal**
**MDO-42**
- [ X ] Código
A literal "Ok", que é utilizada quando não é informada uma primaryAction não utiliza literais.
Alterar a literal "Ok", que é utilizada quando não é informada uma primaryAction, para "Fechar" e traduzir para os idiomas suportados (pt, en, es, ru) através do PoLanguageService.
**Simulação**
> feat(modal): traduzir literais para os idiomas suportados

- projects/templates/src/lib/components/po-page-login/interfaces/po-page-login-literals.interface.ts
- projects/templates/src/lib/components/po-page-login/po-page-login.component.html
- projects/templates/src/lib/components/po-page-login/po-page-login.component.spec.ts
- projects/templates/src/lib/components/po-page-login/samples/sample-po-page-login-labs/sample-po-page-login-labs.component.html
- projects/ui/src/lib/components/po-page/po-page-filter.interface.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.html
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.ts
- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor-base.service.ts
- projects/ui/src/lib/interceptors/po-http-interceptor/samples/sample-po-http-interceptor-labs.component.html
- projects/ui/src/lib/interceptors/po-http-interceptor/samples/sample-po-http-interceptor-labs.component.ts
**PO-PAGE-LOGIN PO-PAGE-LIST PO-HTTP-INTERCEPTOR**
**DTHFUI-4482**
Os componentes po-page-login e o po-page-list possuem propriedades depreciadas que devem ser excluídas na versão 4.
O componente po-http-interceptor possui um parâmetro depreciado e que deverá ser mantido.
- po-page-login
removida propriedade `PoPageLoginLiterals.Title`
- po-page-list
Alteradas propriedades `PoPageFilter.action` e `PoPageFilter.advancedAction` que passam a não aceitar mais o tipo string e mantêm aceitando somente o tipo Function.
Removida propriedade `PoPageFilter.ngModel`
- po-http-interceptor
Removida a depreciação(@deprecated) do parâmetro …
> refactor(components): remove itens depreciados

- projects/ui/src/lib/components/po-popup/samples/sample-po-popup-email/sample-po-popup-email.component.html
**PO-POPUP**
**DTHFUI-4561**
A imagem do Po UI não está aparecendo.
Foi corrigido o caminho e a extensão do arquivo e agora a imagem abre corretamente.
**Simulação**
Sample Email do portal.
> docs(popup): corrige caminho da imagem no sample Email

- projects/ui/src/lib/components/po-field/po-clean/po-clean-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-clean/po-clean-base.component.ts
- projects/ui/src/lib/components/po-field/po-clean/po-clean.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.html
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.html
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.spec.ts
- projects/ui/src/lib/components/po-field/po-decimal/po-decimal.component.html
- projects/ui/src/lib/components/po-field/po-decimal/po-decimal.component.spec.ts
- projects/ui/src/lib/components/po-field/po-input/po-input.component.html
- projects/ui/src/lib/components/po-field/po-input/po-input.component.spec.ts
- projects/ui/src/lib/components/po-field/po-login/po-login.component.html
- projects/ui/src/lib/components/po-field/po-login/po-login.component.spec.ts
- projects/ui/src/lib/components/po-field/po-number/po-number.component.html
- projects/ui/src/lib/components/po-field/po-number/po-number.component.spec.ts
- projects/ui/src/lib/components/po-field/po-password/po-password.component.html
- projects/ui/src/lib/components/po-field/po-password/po-password.component.spec.ts
- projects/ui/src/lib/components/po-menu/po-menu-filter/po-menu-filter.component.spec.ts
- projects/ui/src/lib/components/po-menu/po-menu-filter/po-menu-filter.component.ts
- projects/ui/src/lib/utils/util.spec.ts
- projects/ui/src/lib/utils/util.ts
**COMPONENTS**
**DTHFUI-4456**
- [x ] Código
- [ x] Testes unitários
A partir da versão 11.0.X, a propriedade do ViewContainerRef
mudou de _hostView para _hostLView,
quebrando o componente <po_clean>
que era utilizado em nos seguintes campos:
- INPUT
- COMBO
- DECIMAL
- NUMBER
- PASSWORD
- LOGIN
- DATEPICKER
- DATEPICKER RANGE
- MENU-FILTER
Com isso não era possivel utilizar uma aplicação que usasse o PO UI.
No item de update para v4-rc.1, atualizamos a propriedade para [_hostLView],
porém para não utilizar propriedades privadas que possam quebrar novamente no futuro
será removido este tratamento.
A partir deste commit, os componentes serão
responsáveis por exibir …
> refactor(clean): remove a necessidade do ViewContainerRef[_hostLView]

- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
A ação de "Excluir" é ser a ultima ação a ser apresentada nas ações da tabela.
Fixes DTHFUI-4413
**po-page-dynamic-table**
**DTHFUI-4413**
A ação de "Excluir" 'não é a última ação a ser apresentada nas ações da tabela.
A ação de "Excluir" passa a ser a ultima ação a ser apresentada nas ações da tabela.
**Simulação**
// HTML
<po-page-dynamic-table
p-title="TITULO"
p-service-api="https://po-sample-api.herokuapp.com/v1/people"
[p-actions]="actions"
[p-table-custom-actions]="tableCustomActions">
</po-page-dynamic-table>
// TS
readonly actions = {
new: '/documentation/po-page-dynamic-edit',
remove: true,
};
readonly …
> feat(page-dynamic-table): ordena a ação de excluir por ultimo na tabela

- docs/guides/migration-poui-v4.md
- projects/ui/schematics/ng-update/v4/changes.ts
- projects/ui/schematics/ng-update/v4/index.ts
- projects/ui/src/lib/components/po-chart/helpers/po-chart-default-values.constant.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-axis-options.interface.ts
- projects/ui/src/lib/components/po-chart/po-chart-base.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-axis/po-chart-axis.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-axis/po-chart-axis.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-bar-base.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-line/po-chart-line.component.spec.ts
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-coffee-ranking/sample-po-chart-coffee-ranking.component.ts
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-labs/sample-po-chart-labs.component.html
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-labs/sample-po-chart-labs.component.ts
- projects/ui/src/lib/components/po-chart/services/po-chart-maths.service.spec.ts
- projects/ui/src/lib/components/po-chart/services/po-chart-maths.service.ts
**chart**
**DTHFUI-4576**
Atualmente a propriedade designada para quantidade de linhas do grid se chama `axisXGridLines`. É preciso definir um nome mais genérico já que, no caso de gráficos do tipo barra, as linhas modificadas são relacionadas com o eixo Y.
- Modificada a propriedade axisGridLines para gridLines.
- Incluída modificação na migração do ng-update.
**Simulação**
- Samples do Portal para teste da propriedade;
- Buildar os pacotes com a versão 4.0.0-rc.1 e publica-los localmente com verdaccio. (não esqueça de publicar style e tslint na mesma versão para não dar erro na hora de migrar o projeto).
Utilizar o Po Conference …
> feat(chart): altera propriedade `axisXGridLines` para `gridLines`

- projects/portal/src/styles.css
- projects/ui/src/lib/components/po-menu-panel/po-menu-panel-base.component.spec.ts
- projects/ui/src/lib/components/po-menu-panel/po-menu-panel-base.component.ts
- projects/ui/src/lib/components/po-menu-panel/po-menu-panel.component.html
- projects/ui/src/lib/components/po-menu-panel/samples/sample-po-menu-panel-customer/sample-po-menu-panel-customer.component.html
- projects/ui/src/lib/components/po-menu-panel/samples/sample-po-menu-panel-labs/sample-po-menu-panel-labs.component.html
- projects/ui/src/lib/components/po-menu-panel/samples/sample-po-menu-panel-labs/sample-po-menu-panel-labs.component.ts
**PO-MENU-PANEL**
**DTHFUI-4565**
Não é possível customizar a imagem do logo exibida no topo do menu.
Inclui propriedade p-logo que permite customizar a imagem destinada à logomarca exibida no topo do menu e também foi substituída a imagem default pela logo do PO UI.
**Simulação**
Através dos samples do Portal, possui um sample com a logo customizada.
> feat(menu-panel): inclui propriedade p-logo

- projects/ui/src/lib/services/po-dialog/interfaces/po-dialog.interface.ts
- projects/ui/src/lib/services/po-dialog/po-dialog.component.html
- projects/ui/src/lib/services/po-dialog/samples/sample-po-dialog-cancel-credit-card/sample-po-dialog-cancel-credit-card.component.ts
Permite informar mensagem com conteúdo HTML para que seja possível trabalhar com quebras de linhas, espaçamentos, ícones e etc.
Fixes DTHFUI-4423, #656
**po-dialog**
**DTHFUI-4423, #656**
Não permite informar conteúdo HTML na mensagem.
Permite informar mensagem com conteúdo HTML para que seja possível trabalhar com quebras de linhas, espaçamentos, ícones e etc.
**Simulação**
``` 
<button (click)="open()">Abrir</button>
...
constructor(private dialog: PoDialogService) {}
show() {
const message = 'Olá <b>Fulano</b> <p> Seu e-mail é: <i class="po-icon po-icon-mail"></i> fulano@gmail.com ?</p>';
this.dialog.confirm({
title: …
```
> feat(dialog): permite informar conteúdo HTML na mensagem

- projects/ui/src/lib/components/po-grid/po-grid-cell-action/po-grid-cell-action.component.ts
- projects/ui/src/lib/components/po-grid/po-grid-cell/po-grid-cell.component.html
- projects/ui/src/lib/components/po-grid/po-grid-cell/po-grid-cell.component.ts
- projects/ui/src/lib/components/po-grid/po-grid-head/po-grid-head.component.ts
- projects/ui/src/lib/components/po-grid/po-grid.component.html
- projects/ui/src/lib/components/po-grid/po-grid.component.ts
- projects/ui/src/lib/components/po-grid/samples/sample-po-grid-basic/sample-po-grid-basic.component.ts
**GRID**
**DTHFUI-2343**
**Descrição?**
Ao entrar modo de edição em uma celula, estava disparando um erro.
Isso ocorria pois estava sendo utilizado { static: true },
Mas no caso o correto é não informa-lo, deixa-lo como false (padrão).
Avaliado que em aplicações mais simples, o ngIf =false dispara o blur do campo, portanto ao chegar no blur,
o editValue ja estava undefined, limpando o campo.
A partir deste commit ao pressionar ENTER é invocado o blur do campo, para centralizar nele o tratamento e não disparar 2x
Remove comentarios de console.log, HTML e importações não utilizadas.
**Simulação**
Rodar no portal
> fix(grid): corrige erro disparado ao editar uma celula

- projects/ui/src/lib/components/po-field/po-checkbox-group/po-checkbox-group-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-checkbox-group/po-checkbox-group-base.component.ts
- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox-base.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range-base.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.ts
- projects/ui/src/lib/components/po-field/po-input/po-input-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-input/po-input-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
- projects/ui/src/lib/components/po-field/po-radio-group/po-radio-group-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-radio-group/po-radio-group-base.component.ts
- projects/ui/src/lib/components/po-field/po-select/po-select-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-select/po-select-base.component.ts
- projects/ui/src/lib/components/po-field/po-switch/po-switch-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-switch/po-switch-base.component.ts
- projects/ui/src/lib/components/po-field/po-textarea/po-textarea-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-textarea/po-textarea-base.component.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.component.ts
Implementa a função setDisabledStates nos seguintes componentes de entrada:
- Checkbox group
- Checkbox
- Combo
- Datepicker range
- Datepicker
- Decimal
- Email
- Input
- Login
- Lookup
- Number
- Multiselect
- Password
- Radio-Group
- Select
- Switch
- Textarea
- Upload
- Url
Fixes DTHFUI-2733, #238
**fields**
**DTHFUI-2733, #238**
Ao desabilitar um FormGroup ou até mesmo um FormControl através do formControl.disabled || .enable, os campos não estavam sendo desabilitado.
Ao desabilitar um FormGroup ou até mesmo um FormControl através do formControl.disabled || .enable, estão funcionando
**Simulação** …
> feat(fields): implementa a função setDisabledState

- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-hero-reactive-form/sample-po-lookup-hero-reactive-form.component.html
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-labs/sample-po-lookup-labs.component.html
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-labs/sample-po-lookup-labs.component.ts
**po-lookup**
**DTHFUI-4540**
Apenas realizava formatação dos campos através de função
Aceita também, array de strings para formatação do campo.
**Simulação**
{ email: jhony@gmail.com, name: undefined }
['email', 'name']
Apresentação do campo: "jhony@gmail.com"
> feat(lookup): permite informar propriedade p/ exibir descrição formatada 

- projects/ui/src/lib/components/po-page/po-page-action.interface.ts
- projects/ui/src/lib/components/po-page/po-page-default/po-page-default-base.component.ts
- projects/ui/src/lib/components/po-page/po-page-default/po-page-default.component.html
- projects/ui/src/lib/components/po-page/po-page-default/po-page-default.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-default/po-page-default.component.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list-base.component.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.html
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.ts
Permite realizar a exibição do campos caso o visible esteja como true lembrando que este campo pode ser utilizado como opcional. Caso não utilize este campo visible para determinar se ele será exibido ou não, ele será exibido.
Fixes DTHFUI-2145, #117
**po-page-default | list**
**DTHFUI-2145, #117**
atualmente permite apenas utilizar PoPageAction.visible acima de 4 ações.
Permite realizar a exibição do campos caso o visible esteja como true lembrando que este campo pode ser utilizado como opcional. Caso não utilize este campo visible para determinar se ele será exibido ou não, ele será exibido.
**Simulação** …
> feat(page-default|list): permite utilizar a propriedade visible

- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.component.html
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.component.ts
O componente estava disparando a requisição duas vezes quando possui filtros (initValue).
O comportamento correto é disparar a requisição dos recursos apenas quando retornar o metadata.
Fixes DTHFUI-4303
**po-page-dynamic-table**
**DTHFUI-4303**
O componente esta disparando a requisição duas vezes quando possui filtros (initValue).
Corrigido, agora dispara apenas uma vez.
**Simulação**
Verificar via network do navegador.
> fix(page-dynamic-table:):  corrige disparo duplicado dos recursos

- projects/ui/src/lib/components/po-breadcrumb/samples/sample-po-breadcrumb-labs/sample-po-breadcrumb-labs.component.html
- projects/ui/src/lib/components/po-page/po-page-default/samples/sample-po-page-default-labs/sample-po-page-default-labs.component.html
- projects/ui/src/lib/components/po-page/po-page-detail/samples/sample-po-page-detail-labs/sample-po-page-detail-labs.component.html
- projects/ui/src/lib/components/po-page/po-page-edit/samples/sample-po-page-edit-labs/sample-po-page-edit-labs.component.html
- projects/ui/src/lib/components/po-page/po-page-list/samples/sample-po-page-list-labs/sample-po-page-list-labs.component.html
Altera a URL do endpoint favorite utilizado nos samples dos componentes:
- Breadcrumb
- PageList
- PageDefault
- PageEdit
- PageDetail
Fixes DTHFUI-2669
**breadcrumb|page**
**DTHFUI-2669**
Link antigo das APIs
Inclusão dos links novos da API
**Simulação**
> docs(breadcrumb|page): altera endpoint utilizado nos samples

- docs/guides/sync-fundamentals.md
- projects/sync/src/lib/services/po-event-sourcing/po-event-sourcing.service.spec.ts
- projects/sync/src/lib/services/po-event-sourcing/po-event-sourcing.service.ts
- projects/sync/src/lib/services/po-http-client/interfaces/po-http-request-data.interface.ts
- projects/sync/src/lib/utils/utils.spec.ts
- projects/sync/src/lib/utils/utils.ts
**PO-SYNC**
**DTHFUI-4575**
Não é possível realizar o envio e sincronismo de arquivos (File).
Permite o sincronismo e envio de arquivos (File) ao servidor com o content-type: multipart/form-data.
**Simulação**
Simular através do aplicativo anexado na issue. Baixar o zip, descompactar, substituir o caminho do tgz no package.json e rodar o npm i. Para subir a aplicação utilize o ng serve.
**Importante baixar o arquivo `atualizado`**
Para testar também pode ser usada a API criada no 'po-sample-api-conference', basta utilizar a [PR](https://github.com/po-ui/po-sample-conference/pull/14) criada para subir a API e susbtituir a url da …
> feat(sync): permite o sincronismo e o envio de arquivos (File) ao servidor 

- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
Ao alterar o valor do model do campo, que contenha serviço, e o mesmo estiver selecionado,  é efetuada a busca novamente pelo "id" via getObjectByValue.
Fixes  DTHFUI-4312
**po-combo**
**DTHFUI-4312**
- [x ] Código
- [x ] Testes unitários
Ao alterar o valor do model do campo, que contenha serviço, e o mesmo estiver selecionado, não é efetuada a busca novamente pelo "id" via getObjectByValue.
A busca via getObjectByValue  acontecer quando o seu model for alterado, mesmo estando já selecionado.
**Simulação**
https://stackblitz.com/edit/po-ui-3sm5jy
- Selecionar a opção "São Paulo" no combo "Estado"
- O combo "Pessoa" não realiza a …
> fix(combo): efetua disparo do getObjectByValue caso alterar valor

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/samples/sample-po-dynamic-form-register/sample-po-dynamic-form-register.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view.service.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic.util.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic.util.ts
Permite passar através da propriedade PoDynamicFormField.format, uma lista de propriedades
para formatação do campo.
Fixes DTHFUI-3797
**po-dynamic-form**
**DTHFUI-3797**
Não é possível alterar a formatação do campo lookup no através do dynamic-form.
Permite informar uma lista de propriedades para formatação do campo  lookup através do  dynamic-form.
**Simulação**
<po-dynamic-form
#dynamicForm
p-auto-focus="name"
[p-value]="person"
>
</po-dynamic-form>
-- TS
person = {};
fields: Array<PoDynamicFormField> = [
{
property: 'favoriteHero',
gridColumns: 6,
gridSmColumns: 12,
label: 'Favorite hero',
optional: true, …
> feat(dynamic-form): permite formatar descrição do campo no lookup

- projects/ui/src/lib/components/po-field/po-decimal/po-decimal.component.html
Adiciona inputmode=decimal para utilizar o keyboard numérico no mobile
closes #751
**po-decimal**
**#751**
No mobile o keyboard apresentado é de texto, deixando ruim o seu manuseio.
No mobile utiliza o keyboard numérico.
**Simulação**
< po-decimal name="decimal" p-label="PO Decimal" > < /po-decimal >
Para testar pode usar a aplicação da seguinte forma:
ng serve app --host 0.0.0.0
E no celular, estando na mesma rede, acessar via IP da maquina.
> feat(decimal): utiliza keyboard numérico ao usar no mobile

- projects/ui/src/lib/components/po-chart/interfaces/po-chart-container-size.interface.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-axis/po-chart-axis-label/po-chart-axis-label.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-axis/po-chart-axis-label/po-chart-axis-label.component.svg
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-axis/po-chart-axis.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-axis/po-chart-axis.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-bar-path/po-chart-bar-path.component.svg
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-bar-path/po-chart-bar-path.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-bar.component.svg
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-bar.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-column/po-chart-column.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-line/po-chart-line.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-line/po-chart-line.component.ts
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-labs/sample-po-chart-labs.component.html
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-labs/sample-po-chart-labs.component.ts
- projects/ui/src/lib/components/po-chart/services/po-chart-maths.service.spec.ts
- projects/ui/src/lib/components/po-chart/services/po-chart-maths.service.ts
- projects/ui/src/lib/components/po-chart/services/po-chart-svg-container.service.spec.ts
- projects/ui/src/lib/components/po-chart/services/po-chart-svg-container.service.ts
**po-chart**
**DTHFUI-2805**
- O tooltip em gráficos do tipo coluna surgem do lado direito das barras;
- O sample labs permite usar a depreciação do Gauge.
- O gráfico do tipo linha possui um espaçamento entre as categorias e os cantos.
- O tooltip para gráficos do tipo coluna devem surgir prioritariamente no topo das barras.
- Removido o gauge do sample labs.
- Removida área lateral em gráficos do tipo Linha
**Simulação**
Os samples contemplam todas as alterações acima. Há PR também para o [style](https://github.com/po-ui/po-style/pull/184)
> fix(chart): correções no tooltip e espaço lateral

- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.component.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.service.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.service.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.ts
- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-labs/sample-po-upload-labs.component.html
- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-labs/sample-po-upload-labs.component.ts
Adiciona a propriedade headers no componente, para permitir envia-los para a requisição do envio do arquivo.
Fixes #593
**upload**
**#593**
Não existe propriedade headers no componente não podendo enviar um header para a requisição
Adiciona a propriedade headers permitindo envia-los para a requisição do envio do arquivo.
**Simulação**
< po-upload
name="upload"
p-label="PO Upload"
p-url="https://thf.totvs.com.br/sample/api/uploads/addFile"
[p-headers]="{ 'XPTO': ['API-123131-31321', '33']}">
< /po-upload>
< po-upload
name="upload"
p-label="PO Upload"
p-url="https://thf.totvs.com.br/sample/api/uploads/addFile"
[p-headers]="{ …
> feat(upload): adiciona a propriedade p-headers

- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
**PAGE DYNAMIC TABLE**
**#732**
Caso utilizasse p-table-custom-actions sem p-actions ocorria erro no po-table, pois adiciona "undefined" na lista de ações.
Não adiciona "undefined" na lista de ações da tabela, fazendo com que o funcione corretamente.
**Simulação**
https://stackblitz.com/edit/po-ui-ued1sn?file=src%2Fapp%2Fapp.component.html
> page-dynamic-table: corrige uso p-table-custom-actions sem p-actions

- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
**po-lookup**
**DTHFUI-4638**
- [ x] Código
Atualmente caso o valor informado no campo lookup fosse iniciado com um espaço, o mesmo era removido, fazendo com que o valor informado pelo usuário não fosse o mesmo a ser enviado para o servidor.
Foi realizada uma validação para que caso o valor informado seja apenas espaços em branco, a pesquisa não seja disparada, e caso o valor informado possua espaços os mesmos sejam preservados para serem enviados ao servidor.
**Simulação**
Executar a simulação relatada na ISSUE DTHFUI-4638
> fix(po-lookup): não remove espaços quando realizada busca pelo código

- projects/ui/src/lib/components/po-table/po-table.component.html
**TABLE**
**DTHFUI-4145**
Ao manipular uma tabela com dados e ordenação, com o google translate para portugues habilitado, 
a tabela não é atualizada corretamente e a ordenação não funciona.
Encontrado problema semelhante 
https://github.com/angular/angular.js/issues/11265
Desabilitado a tradução dos dados da tabela (notranslate), dessa forma a tabela funciona corretamente.
**Simulação**
Problema atual:
PO Page List - Hiring Processes
https://po-ui.io/documentation/po-page-list?view=web
Com a solução:
Entrar na branch, subir o portal e testar o mesmo sample
https://user-images.githubusercontent.com/6907801/107089155-e78a5200-67dc-11eb …
> fix(table): corrige tradução pelo google translate

- projects/code-editor/src/lib/components/po-code-editor/interfaces/po-code-editor-registerable-options.interface.ts
- projects/code-editor/src/lib/components/po-code-editor/samples/sample-po-code-editor-terraform/sample-po-code-editor-terraform.constant.ts
Durante o registro de uma nova sintaxe não era possível defini-la como case-insensitive.
Adiciona o atributo ignoreCase à interface PoCodeEditorRegisterableOptions, permitindo o registro de uma sintaxe case-insensitive.
**po-code-editor**
**778**
Não era possivel registrar uma sintaxe case-insensitive
É possível definir uma sintaxe case-insensitive, através do atributo ignoreCase
**Simulação**
1-Registrar uma nova sintaxe com ignoreCase=true
2-Definir uma keyword como return
3-Incluir no po-code-editor RETURN, por exemplo
> feat(code-editor): adiciona o atributo ignoreCase à interface options

- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-circular/po-chart-circular.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-circular/po-chart-circular.component.ts
**po-chart**
**DTHFUI-4719**
Os gráficos dos tipos 'pie' e 'donut' com apenas uma única série desaparecem no resize.
Permanecem na tela no resize
**Simulação**
Sample labs do portal
> fix(chart): corrige resize em gráficos circulares

- projects/ui/src/lib/components/po-chart/helpers/po-chart-default-values.constant.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-container-size.interface.ts
- projects/ui/src/lib/components/po-chart/po-chart-base.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-base.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-axis/po-chart-axis.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-axis/po-chart-axis.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-bar-base.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-bar.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-bar.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-column/po-chart-column.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-column/po-chart-column.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-circular/po-chart-circular.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-container.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-line/po-chart-line.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-line/po-chart-line.component.ts
- projects/ui/src/lib/components/po-chart/po-chart.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart.component.ts
- projects/ui/src/lib/components/po-chart/services/po-chart-maths.service.spec.ts
- projects/ui/src/lib/components/po-chart/services/po-chart-maths.service.ts
- projects/ui/src/lib/components/po-chart/services/po-chart-svg-container.service.spec.ts
- projects/ui/src/lib/components/po-chart/services/po-chart-svg-container.service.ts
**chart**
**DTHFUI-4552**
A área relativa aos textos dos eixos X era fixa. Categorias ou valores de série com uma grandes larguras quebravam o gráfico. 
Agora a área dos textos de eixo X é calculada de acordo com a largura do texto maior. Para gráficos do tipo `bar`, as categorias que são lançadas como label do eixo X. Já para os tipos `column` e `line`, são os valores das séries.
**Simulação**
Sample labs aceita toda manipulação necessária para testes.
> feat(chart): calcula a área de texto no grid

- projects/ui/src/lib/components/po-modal/index.ts
- projects/ui/src/lib/components/po-modal/po-modal.component.spec.ts
- projects/ui/src/lib/components/po-modal/po-modal.component.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide.component.ts
- projects/ui/src/lib/services/index.ts
- projects/ui/src/lib/services/po-active-overlay/index.ts
- projects/ui/src/lib/services/po-active-overlay/po-active-overlay.module.ts
- projects/ui/src/lib/services/po-active-overlay/po-active-overlay.service.ts
- projects/ui/src/lib/services/services.module.ts
**po-page-slide**
**DTHFUI-4666**
Ao usar modal ou um componente que chame a modal dentro do page-slide dá erro 'Maximum call stack size exceeded'.
Modificado serviço `PoModalService` para `PoActiveOverlayService` para controle de camada ativa (activeOverlay) através de repasse de id. Desta forma, o evento de focus do page-slide não será disparado caso o id seja diferente do declarado no serviço.
**Simulação**
Testar no exemplo anexado na issue (`po-lookup` inserido dentro do `po-page-slide`).
Testar também situação semelhante na modal (`po-lookup` dentro do `po-modal`).
> fix(page-slide): corrige focus ao usar modal dentro do page-slide

- projects/ui/src/lib/components/po-modal/po-modal.component.spec.ts
- projects/ui/src/lib/components/po-modal/po-modal.component.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide.component.ts
- projects/ui/src/lib/services/po-active-overlay/po-active-overlay.service.ts
**po-modal**
**DTHFUI-4749**
O controle de modal ativa para implementação do foco se perdia quando se tratava de múltiplas camadas de modal. 
Foi alterado o tipo em `PoActiveOverlayService.activeOverlay` para `Array<string>` e, desta forma, manter armazenada a lista de ids para a validação da modal ativa.
**Simulação**
Favor testar com o código abaixo que exemplifica múltiplas camadas de modal. Pode também modificar a primeira referência de `po-modal` para `po-page-slide` para uma simulação com modal inserida dentro de page-slide.
````
<po-page-default p-title="PO UI">
<po-modal #inclusaoPrevisaoEntrega p-title="Erro com Po-Page …
```
> fix(modal): corrige controle de foco em modais

- projects/ui/src/lib/components/po-chart/interfaces/po-chart-options.interface.ts
- projects/ui/src/lib/components/po-chart/po-chart-base.component.ts
- projects/ui/src/lib/components/po-chart/po-chart.component.html
- projects/ui/src/lib/components/po-chart/po-chart.component.spec.ts
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-labs/sample-po-chart-labs.component.html
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-labs/sample-po-chart-labs.component.ts
- projects/ui/src/lib/services/po-color/po-color.service.spec.ts
- projects/ui/src/lib/services/po-color/po-color.service.ts
**po-chart**
**DTHFUI-4732**
Não há opção para desabilitar a exibição de legendas
Adicionada `PoChartOptions.legend` para que seja possível ocultar as legendas do chart e seu valor default é `true`;
ps.: reparada e sanada situação em que, se passado `PoChartOptions.color` com undefined, estourava erro no console.
**Simulação**
Sample Labs
> feat(chart): nova propriedade `PoChartOptions.legend`

- projects/ui/src/lib/components/po-field/po-input/po-input-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-input/po-input-base.component.ts
**PO-INPUT**
**DTHFUI-4663**
setErros não funciona quando p-mask é dinâmico
Corrige validação do model indevida ao alterar a propriedade p-mask.
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/6038034/app.zip)
> fix(input): corrige validação do model quando p-mask é dinâmico

- docs/guides/api.md
- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor-base.service.spec.ts
- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor-base.service.ts
- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor-detail/po-http-interceptor-detail-literals.interface.ts
Permite informar o tipo da notificação que será exibida quando ocorrer algum erro de negócio.
Fixes DTHFUI-4750
**PO-HTTP-INTERCEPTOR**
**DTHFUI-4750**
Sempre que o interceptor recebe um erro, é sempre exibido como erro. Ignorando o tipo enviado.
O componente valida o tipo do erro, e exibe entre os tipos possíveis ('error', 'warning' ou 'information'), caso não esteja dentro dos tipos possíveis ou não seja enviado, o componente exibe como 'error'.
**Simulação**
Para testar é preciso usar o  `SamplePoHttpInterceptorLabsComponent` passandos os seguintes itens abaixo de acordo com o tipo informado.
`Warning`
```
{
"code": "401", …
```
> feat(interceptor): permite informar type no retorno do erro

- projects/ui/src/lib/components/po-chart/interfaces/po-chart-axis-options.interface.ts
- projects/ui/src/lib/components/po-chart/po-chart-base.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-axis/po-chart-axis.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-axis/po-chart-axis.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-column/po-chart-column.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-column/po-chart-column.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-container.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-container.component.ts
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-coffee-ranking/sample-po-chart-coffee-ranking.component.ts
- projects/ui/src/lib/components/po-chart/services/po-chart-maths.service.spec.ts
- projects/ui/src/lib/components/po-chart/services/po-chart-maths.service.ts
**po-chart**
**DTHFUI-4737**
Não era possível declarar séries com valores negativos em gráficos do tipo `column`.
- É possível utilizar séries contendo tanto valores positivos quanto negativos em gráficos dos tipos `column` e também em combinações entre `line` e `column`.
- Efetuado tratamento específico para o caso de somente houverem valores negativos nas séries. Nesse caso, o valor máximo será o zero.
- Se na média de labels referentes ao eixo X não houver um valor 0(zero), então é gerada uma linha adicional referente a ela. No entanto, o label zero não é exibido. Há uma imagem de referência na issue da tarefa.
**Simulação** …
> feat(chart): permite valores negativos em gráficos do tipo `column`

- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-search/po-multiselect-search.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.html
**DTHFUI-4662, #399**
O multiselect não possuía estilo ao posicionar o mouse sobre o mesmo.
O multiselect estava com diferenças no hover comparado ao select,
são componentes que devem possuir uma consistência de UI semelhante.
**Simulação**
- Buildar o style com a branch da PR https://github.com/po-ui/po-style/pull/199/
- Atualizar o estilo no projeto po-angular
- npm run build
- npm run build:portal
- ng serve portal
> feat(multiselect): adiciona estilo ao posicionar mouse sobre o campo

- projects/ui/src/lib/components/po-menu/po-menu-base.component.spec.ts
- projects/ui/src/lib/components/po-menu/po-menu-base.component.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.spec.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.ts
**po-menu**
**DTHFUI-1426**
Os itens de menu relativos às rotas carregadas via browser não eram marcados como ativos.
Agora o o item do menu é ativado no carregamento da página não importando o sub-nível.
**Simulação**
Pode testar no portal acessando qualquer item do menu e dar refresh e também [no app](https://github.com/po-ui/po-angular/files/6090411/app.zip)
> fix(menu): corrige "rota" ativa não destacada

- projects/ui/src/lib/components/po-dynamic/po-dynamic-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic.util.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic.util.ts
Foi adicionado novos css e propriedades ao dynamic-form e dynamic-view
Fixes #585
Foram adicionados as propriedades gridXXOffset.
Esta propriedade permite incluir espaço em branco após o campo.
Com esta propriedade é possível deixar apenas um campo na linha do form.
**PO-DYNAMIC**
**585**
No componente atual não é permitido inserir espaços em branco após um campo.
Com as novas propriedade é possível inserir um espaçamento entre um campo e outro podendo até mesmo quebrar a linha antes do aparecimento do próximo campo.
**Simulação**
Adicionar um po-dynamic-form ou po-dynamic-view e nas propriedades inserir a propriedade grid<tamanho …
> feat(po-dynamic): adiciona espaço após os campos

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
**<DYNAMIC-FORM>**
**DTHFUI-4688**
- Ao informar type time, não estava formatando o model corretamente
- Adiciona a propriedade PoDynamicFormField.maskFormatModel
Possibilitando formatar o model conforme a mascara
- Adiciona a propriedade PoDynamicFormField.maskFormatModel, possibilitando formatar o model conforme a mascara;
- fix(dynamic-form): corrige valor do model quando informar tipo `time` 
**Simulação**
Portal:
- npm run build:ui
- npm run build:portal
- ng serve portal
APP:
``` 
<po-dynamic-form [p-value]="value" [p-fields]="fields"></po-dynamic-form>
<hr>
{{ value | json }}
```
``` 
fields = [
{ property: 'sem …
```
> feat(dynamic-form): adiciona a prop `PoDynamicFormField.maskFormatModel`

- projects/ui/src/lib/components/po-field/po-email/po-email.component.spec.ts
- projects/ui/src/lib/components/po-field/po-email/po-email.component.ts
**EMAIL**
**DTHFUI-4814**
Informava error no componente quando utilizava o final do email com letra maiuscula, ex: john@gmail.COM
Permite informar letra maiuscula
**Simulação**
npm run build
Inserir os seguintes conteúdos no EMAIL:
"JOHN@GMAIL.COM"
"JOHN@GMAIL.com"
"JOHN@gmail.com
> fix(email): corrige expressão regular para permitir letras maiusculas

- projects/ui/src/lib/components/po-slide/po-slide-base.component.ts
- projects/ui/src/lib/components/po-slide/po-slide.component.html
- projects/ui/src/lib/components/po-slide/po-slide.component.spec.ts
- projects/ui/src/lib/components/po-slide/po-slide.component.ts
- projects/ui/src/lib/components/po-slide/samples/sample-po-slide-external-controls/sample-po-slide-external-controls.component.html
- projects/ui/src/lib/components/po-slide/samples/sample-po-slide-external-controls/sample-po-slide-external-controls.component.ts
**PO-SLIDE**
**DTHFUI-4753**
Não existe a possibilidade de controlar os passos do slide externamente, bem como de esconder as setas de navegação.
- Criada a propriedade `p-hide-arrows`: esconde as setas de navegação do po-slide.
- Publicados os métodos getCurrentSlideIndex, next e previous para controle externo dos passos do slide.
**Simulação**
Pode ser utilizado o sample `SamplePoSlideExternalControlsComponent` no app, ou utilizando o código abaixo:
```html
<po-slide #slide p-height="450" [p-slides]="items" p-interval="0" p-hide-arrows></po-slide>
<po-button
p-label="Previous"
(p-click)="previousAction()" …
```
> slide: permite esconder setas de navegação e controle de passos externo

- projects/ui/src/lib/components/po-chart/helpers/po-chart-default-values.constant.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-options.interface.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-bar.component.svg
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-circular/po-chart-circular.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-circular/po-chart-circular.component.svg
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-circular/po-chart-circular.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-circular/po-chart-donut/po-chart-donut.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-circular/po-chart-donut/po-chart-donut.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-container.component.html
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-labs/sample-po-chart-labs.component.html
**po-chart**
**DTHFUI-2109**
O gráfico do tipo donut possui uma espessura padrão.
- Criada propriedade `PoChartOptions.innerRadius`: Define o tamanho do diâmetro do gráfico tipo donut em porcentagem.
Se passado um percentual que torne a espessura do gráfico menor do que `40px`, os textos internos do gráficos serão ocultados para que não haja quebra de layout.
- Corrigido erro quando passado `[null]` em gráficos do tipo `bar` e `column`.
**Simulação**
Sample labs do portal.
> chart: permite definir expessura do donut

- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.ts
**PO-DATEPICKER**
**DTHFUI-4564**
A atualização de model está sendo disparada desnecessariamente, fazendo o form ficar com status de PENDING.
Corrigido disparo desnecessário da atualização do model.
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/6152104/app.zip)
> fix(datepicker): corrige disparo desnecessário da atualização do model

- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range.component.html
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range.component.ts
- projects/ui/src/lib/components/po-field/po-input/po-mask.ts
**DATEPICKER-RANGE**
**DTHFUI-2412**
Ao selecionar um trecho ou todo o conteúdo do campo e digitar um novo valor, o cursor se perdia alterava fora da seleção.
Corrige o posicionamento do cursor quando selecionado um trecho ou todo o conteúdo do campo e digitado um novo valor.
**Simulação**
npm run build
Seleção com o Mouse
- Inserir uma data válida
- Selecionar um trecho do código
- Alterar o trecho
Seleção com comandos do teclado (`ctrl + a`, `shift + tab`, `tab`)
- Inserir uma data válida
- Selecionar o campo com qualquer um dos comandos acima
- Alterar o trecho
> fix(datepicker-range): corrige posicionamento ao digitar o valor

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.ts
**DTHFUI-4127**
As propriedades `optionsService` e `searchService` aceitam uma URL como método de entrada de dados.
As propriedades `optionsService` e `searchService` continuam aceitando uma URL como serviço, mas poderá também receber instancias de serviços baseados em `PoComboFilter` e `PoLookupFilter` como métodos de entrada de dados.
**Simulação**
Baixar os arquivos [app.zip](https://github.com/po-ui/po-angular/files/6207716/app.zip) e realizar os testes.
> feat(dynamic-form): adiciona possibilidade de usar instancia de serviço

- projects/ui/src/lib/components/po-field/po-upload/po-upload-drag-drop/po-upload-drag-drop.directive.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-drag-drop/po-upload-drag-drop.directive.ts
- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-labs/sample-po-upload-labs.component.ts
**UPLOAD**
**DTHFUI-4792**
Ao utilizar o po-upload em drag drop, arquivos especificos, que não possuiam type (.prn, .zpl), estavam sendo ignorados.
Permite informar arquivos em formatos específicos, a validação da permissão foi alterada, para verificar se de fato é um arquivo e não olhar o type que poderia vir em "" (branco) e ser invalidado.
**Simulação**
- Buildar o projeto com a branch upload/DTHFUI-4792
- Rodar o portal e utilizar o Sample Po Upload Labs
- Atualizando o allowedExtensions nos formatos ".zpl, .prn, .xml"
> fix(upload): corrige validação para arquivos especificos

- projects/ui/src/lib/components/po-table/interfaces/po-table-filter.interface.ts
- projects/ui/src/lib/components/po-table/interfaces/po-table-filtered-items-params.interface.ts
- projects/ui/src/lib/components/po-table/interfaces/po-table-response-api.interface.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-with-api/sample-po-table-with-api.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-with-api/sample-po-table-with-api.component.ts
- projects/ui/src/lib/components/po-table/services/po-table.service.spec.ts
- projects/ui/src/lib/components/po-table/services/po-table.service.ts
Permite utilização de uma fonte de dados externo através de uma API.
Fixes DTHFUI-1885
**PO-TABLE**
**DTHFUI-1885**
Não é possível utilizar um serviço de dados externos.
Ao informar a URL na propriedade `p-service-api` será utilizado o serviço para criação dos dados do `po-table`
**Simulação**
Utilizar o sample do Portal [portal.zip](https://github.com/po-ui/po-angular/files/6287730/portal.zip), ou simular no `App` com o código abaixo:
```html
<po-table p-service-api="https://po-sample-api.herokuapp.com/v1/people"></po-table>
```
> feat(table): adiciona possibilidade de uso de serviço de dados

- projects/portal/src/index.html
- projects/ui/src/lib/components/components.module.ts
- projects/ui/src/lib/components/index.ts
- projects/ui/src/lib/components/po-button/po-button-base.component.ts
- projects/ui/src/lib/components/po-button/po-button.component.html
- projects/ui/src/lib/components/po-button/po-button.component.spec.ts
- projects/ui/src/lib/components/po-button/po-button.component.ts
- projects/ui/src/lib/components/po-button/po-button.module.ts
- projects/ui/src/lib/components/po-button/samples/sample-po-button-labs/sample-po-button-labs.component.ts
- projects/ui/src/lib/components/po-button/samples/sample-po-button-social-network/sample-po-button-social-network.component.html
- projects/ui/src/lib/components/po-button/samples/sample-po-button-social-network/sample-po-button-social-network.component.ts
- projects/ui/src/lib/components/po-icon/index.ts
- projects/ui/src/lib/components/po-icon/po-icon.component.html
- projects/ui/src/lib/components/po-icon/po-icon.component.spec.ts
- projects/ui/src/lib/components/po-icon/po-icon.component.ts
- projects/ui/src/lib/components/po-icon/po-icon.module.ts
- projects/ui/src/lib/components/po-page/po-page-detail/po-page-detail.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-edit/po-page-edit.component.spec.ts
**PO-BUTTON, PO-ICON, PO-PAGE-DETAIL, PO-PAGE-EDIT**
**DTHFUI-1795**
Não é possível utilizar outras fontes de ícones no componente `po-button`.
Criado e inserido no `po-button` o novo componente interno `po-icon` que permite a utilização e compatibilidade de outras fontes de ícones e customização via TemplateRef. 
**Simulação**
É possivel simular no sample labs e no sample de caso de uso do `po-button` no portal. Testar também com TemplateRef em app.
[my-po-project.zip](https://github.com/po-ui/po-angular/files/6229166/my-po-project.zip).
Obs: Ver [PR no po-style](https://github.com/po-ui/po-style/pull/203).
> feat(button): adiciona compatibilidade com outras fontes de ícones 

- projects/ui/src/lib/components/po-avatar/po-avatar-base.component.ts
- projects/ui/src/lib/components/po-page/po-page-detail/po-page-detail-base.component.ts
- projects/ui/src/lib/components/po-page/po-page-edit/po-page-edit-base.component.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
**PoPageEdit/Detail PoAvatar PoTable**
**#810**
#810 
Correções para permitir usar com strictTemplates habilitado
Alterado os componentes:
PoPageEdit
PoPageDetail
PoAvatar
PoTable
**Simulação**
- ng new aplicacaoteste --strict
- instalar o pacote po-ui/ng-componentes
- usar os componentes PoPageEdit e PoTable com os atributos afetados;
```
<po-page-edit (p-save)="save()">
<po-table
[p-items]="[{name: 'JOHN', age: 25}]"
[p-show-more-disabled]="false">
</po-table>
</po-page-edit>
```
- ng serve
É para ocorrer o erro.
Agora instalar o ng-components gerado localmente com a correção
subir novamente o ng serve, não é para acontecer o erro.
> fix(ui): correções para permitir usar com strictTemplates habilitado

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form.component.spec.ts
**< DYNAMIC-FORM >**
**< DTHFUI-4626>**
Esta disparando os validates ao carregar a tela.
Não deve disparar o validate ao carregar a tela (Tela de edição, por exemplo, pois os dados ja vem validados)
**Simulação**
Utilizar o fonte abaixo e avaliar se ao carregar a tela esta disparando o validate. (verificar console)
```
<po-dynamic-form
[p-validate]="onChangeFields.bind(this)"
[p-value]="person">
</po-dynamic-form>
```
```
person = {
name: 'John',
favoriteHero: 'kakaroto'
}
fields: Array<any> = [
{
property: 'name',
divider: 'PERSONAL DATA',
required: true,
minLength: 4,
maxLength: 50,
gridColumns: 6, …
```
> fix(dynamic-form): corrige disparo do validate ao carregar a pagina

- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.ts
- projects/ui/src/lib/components/po-page/po-page-list/samples/sample-po-page-list-hiring-processes/sample-po-page-list-hiring-processes.component.html
- projects/ui/src/lib/components/po-page/po-page-list/samples/sample-po-page-list-hiring-processes/sample-po-page-list-hiring-processes.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
**PAGE LIST**
**DTHFUI-4916**
Ao realizar uma busca na pagina de listagem não é possível apagar o conteúdo do campo de busca. O mesmo esta sendo mantido mesmo após remover o disclaimer atribuído a ele.
Quando é removido um disclaimer que foi digitado pelo campo de busca, o campo é limpo.
**Simulação**
Rodar o Portal (ou utilizar [portal.zip](https://github.com/po-ui/po-angular/files/6418075/portal.zip)) e testar utilizando o `Sample Hiring Process`.
> feat(page-list): adiciona `clearInputSearch`

- projects/ui/src/lib/components/po-tag/po-tag-base.component.ts
- projects/ui/src/lib/components/po-tag/po-tag.component.html
- projects/ui/src/lib/components/po-tag/po-tag.component.spec.ts
- projects/ui/src/lib/components/po-tag/po-tag.component.ts
- projects/ui/src/lib/components/po-tag/po-tag.module.ts
- projects/ui/src/lib/components/po-tag/samples/sample-po-tag-labs/sample-po-tag-labs.component.ts
**< TAG >**
**< DTHFUI-4892 >**
Atualmente era possível utilizar ícones da Bibliotecas de ícones apenas do PO UI
Permite utilizar outras fontes de ícones, como Font Awesome e Material Icons
PR STYLE
https://github.com/po-ui/po-style/pull/210
**Simulação**
Recuperar o CSS novo, através da PR https://github.com/po-ui/po-style/pull/210;
Rodar o portal e testar no Sample labs.
e
``` 
<po-tag p-icon="po-icon-copy" p-label="TAG" p-value="TAG"></po-tag>
<po-tag p-icon="fa fa-address-card" p-label="TAG" p-value="TAG"></po-tag>
<po-tag p-value="TEMPLATE FA-ICON" [p-icon]="icontemplate">
</po-tag>
<po-tag p-type="success" p-label="TAG " …
```
> feat(tag): adiciona possibilidade de informar outras fontes de ícones

- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.html
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
Corrige discrepância entre as colunas visíveis e as informações apresentadas no gerenciador de colunas.
Fixes DTHFUI-4861
**PO-TABLE**
**DTHFUI-4861**
Ao repassar novas colunas com definições de visibilidade diferente da atual, não atualiza corretamente o gerenciador de colunas.
Corrigida discrepância entre as colunas visíveis e as informações apresentadas no gerenciador de colunas.
**Simulação**
[app-table.zip](https://github.com/po-ui/po-angular/files/6361231/app-table.zip)
> fix(table): corrige apresentação do gerenciador de colunas

- projects/ui/src/lib/components/po-menu/index.ts
- projects/ui/src/lib/components/po-menu/po-menu-base.component.spec.ts
- projects/ui/src/lib/components/po-menu/po-menu-base.component.ts
- projects/ui/src/lib/components/po-menu/po-menu-item.interface.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.spec.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.ts
- projects/ui/src/lib/components/po-menu/services/po-menu-global.service.spec.ts
- projects/ui/src/lib/components/po-menu/services/po-menu-global.service.ts
- projects/ui/src/lib/components/po-navbar/po-navbar-base.component.spec.ts
- projects/ui/src/lib/components/po-navbar/po-navbar-base.component.ts
- projects/ui/src/lib/components/po-navbar/po-navbar.component.html
- projects/ui/src/lib/components/po-navbar/po-navbar.component.spec.ts
- projects/ui/src/lib/components/po-navbar/po-navbar.component.ts
**< NAVBAR >**
**< DTHFUI-1425 >**
Quando utilizado o PoNavbar em resolução menor, o mesmo não incluía os itens no Menu da aplicação.
Para isto era preciso informar a propriedade p-menu, porém ao utilizar uma aplicação mais dinâmica, não era possível
passar para o navbar a referencia do menu.
- PoNavbar passa a utilizar o menu da aplicação para injetar os itens quando usado em resolução menor, sem a necessidade de informar a propriedade p-menu;
- Deprecia a propriedade p-menu;
**Simulação**
- Rodar o Portal e utiliza-lo em resolução menor que 768px (na master os itens do navbar não são incluídos no menu) 
- Utilizar o …
> feat(navbar): deprecia a propriedade `p-menu`

- projects/templates/src/lib/components/po-page-dynamic-detail/po-page-dynamic-detail.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/templates/src/lib/services/po-page-dynamic/po-page-dynamic.service.spec.ts
- projects/templates/src/lib/services/po-page-dynamic/po-page-dynamic.service.ts
Corrige concatenação indevida da key com a propriedade newUrl da action beforeRemove.
Fixes 
**PO-PAGE-DYNAMIC-TABLE**
**DTHFUI-4664**
Concatenação indevida da key no remove quando é utilizado o beforeRemove e uma newUrl é retornada.
Quando é retornada uma newUrl no beforeRemove a key não é concatenada na requisição, já que o desenvolvedor poderá customizar a url inclusive passando os parâmetros que ele quiser.
**Simulação**
[app-dynamic-table.zip](https://github.com/po-ui/po-angular/files/6468409/app-dynamic-table.zip)
Validar também o funcionamento do componente `po-dynamic-detail` que é afetado pelo serviço alterado.
> fix(page-dynamic-table): corrige key no final da url no beforeRemove

- projects/ui/src/lib/components/po-button-group/po-button-group-item.interface.ts
- projects/ui/src/lib/components/po-button-group/samples/sample-po-button-group-labs/sample-po-button-group-labs.component.ts
**PO-BUTTON-GROUP**
**DTHFUI-4940**
Permite a utilização de outras fontes de ícones no componente `po-button-group`.
**Simulação**
Através do sample labs do portal e também é possível testar no app com o código abaixo:
```
<div class="po-m-3">
<po-divider p-label="BUTTON GROUP"></po-divider>
<po-button-group class="po-md-12" [p-buttons]="buttons"> </po-button-group>
</div>
</div>
<ng-template #icon>
<span class="material-icons" style="font-size: inherit;">dashboard</span>
</ng-template>
```
- app.component.ts:
```
@ViewChild('icon', { …
```
> feat(button-group): adiciona compatibilidade com outras fontes de ícones

- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.html
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-labs/sample-po-combo-labs.component.ts
- projects/ui/src/lib/components/po-field/po-decimal/po-decimal.component.html
- projects/ui/src/lib/components/po-field/po-decimal/po-decimal.component.spec.ts
- projects/ui/src/lib/components/po-field/po-decimal/samples/sample-po-decimal-labs/sample-po-decimal-labs.component.ts
- projects/ui/src/lib/components/po-field/po-email/po-email.component.spec.ts
- projects/ui/src/lib/components/po-field/po-field.module.ts
- projects/ui/src/lib/components/po-field/po-input/po-input-base.component.ts
- projects/ui/src/lib/components/po-field/po-input/po-input.component.html
- projects/ui/src/lib/components/po-field/po-input/po-input.component.spec.ts
- projects/ui/src/lib/components/po-field/po-input/samples/sample-po-input-labs/sample-po-input-labs.component.ts
- projects/ui/src/lib/components/po-field/po-number/po-number.component.html
- projects/ui/src/lib/components/po-field/po-number/samples/sample-po-number-labs/sample-po-number-labs.component.ts
- projects/ui/src/lib/components/po-field/po-url/po-url.component.spec.ts
**FIELDS: PO-COMBO, PO-INPUT, PO-NUMBER E PO-DECIMAL**
**DTHFUI-4388**
Atualmente não é possível utilizar outras fontes de ícones nos componentes de fields.
Adicionada nova funcionalidade para permitir a utilização de outras fontes de ícones.
**Simulação**
Possui PR no [po-style](https://github.com/po-ui/po-style/pull/214).
Samples do Portal, ou utilizar o código abaixo no app:
- app.html:
```
<div class="po-m-3">
<po-divider p-label="COMBO"></po-divider>
<po-combo p-icon="po-icon-server" p-label="PO COMBO"></po-combo>
<po-combo p-icon="fa fa-calculator" p-label="FA COMBO"></po-combo>
<po-combo [p-icon]="icon" …
```
> feat(fields): adiciona compatibilidade com outras fontes de ícones

- projects/ui/src/lib/components/po-calendar/index.ts
- projects/ui/src/lib/components/po-calendar/po-calendar-base.component.spec.ts
- projects/ui/src/lib/components/po-calendar/po-calendar-base.component.ts
- projects/ui/src/lib/components/po-calendar/po-calendar-header/po-calendar-header.component.html
- projects/ui/src/lib/components/po-calendar/po-calendar-header/po-calendar-header.component.spec.ts
- projects/ui/src/lib/components/po-calendar/po-calendar-header/po-calendar-header.component.ts
- projects/ui/src/lib/components/po-calendar/po-calendar-mode.enum.ts
- projects/ui/src/lib/components/po-calendar/po-calendar-wrapper/po-calendar-wrapper.component.html
- projects/ui/src/lib/components/po-calendar/po-calendar-wrapper/po-calendar-wrapper.component.spec.ts
- projects/ui/src/lib/components/po-calendar/po-calendar-wrapper/po-calendar-wrapper.component.ts
- projects/ui/src/lib/components/po-calendar/po-calendar.component.html
- projects/ui/src/lib/components/po-calendar/po-calendar.component.spec.ts
- projects/ui/src/lib/components/po-calendar/po-calendar.component.ts
- projects/ui/src/lib/components/po-calendar/po-calendar.module.ts
- projects/ui/src/lib/components/po-calendar/samples/sample-po-calendar-labs/sample-po-calendar-labs.component.html
- projects/ui/src/lib/components/po-calendar/samples/sample-po-calendar-labs/sample-po-calendar-labs.component.ts
- projects/ui/src/lib/components/po-calendar/services/po-calendar.lang.service.spec.ts
- projects/ui/src/lib/components/po-calendar/services/po-calendar.lang.service.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-calendar/po-calendar.component.html
- projects/ui/src/lib/components/po-field/po-datepicker/po-calendar/po-calendar.component.spec.ts
**CALENDAR**
**DTHFUI-4917**
Atualmente não há o modo "Range", que permita escolher uma faixa de datas.
Adiciona a propriedade p-mode, onde é possível informar "Range", possibilitando selecionar uma faixa de datas.
Obs: Hover e Estilo das datas entre o start e end não serão contemplados agora.
**Simulação**
1. Gerar build da PR no po-style https://github.com/po-ui/po-style/pull/215
2.
Teste local:
```
<po-calendar [p-mode]="mode" name="cal" [(ngModel)]="cal" (p-change)="onchange($event)"></po-calendar>
<hr>
{{ cal | json }}
<hr>
<po-select name="mode" [(ngModel)]="mode" [p-options]="[{ label: …
```
> feat(calendar): adiciona a propriedade `p-mode`

- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-container.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-container.component.ts
**PoChart**
**DTHFUI-4993, #874**
Ao utilizar o componente no Firefox, iniciando-o escondido (dentro de um PoTab,PoAccordion) estava ocasionando erro ao executar o metodo .inverse no momento de capturar o svgDomMatrix.
Erro acontece também no Portal rodando no Firefox
Verifica se o método getScreenCTM retorna valor para executar o método .inverse()
**Simulação**
Rodar o portal e avaliar o sample do gráfico no Firefox.
```
```
> fix(chart): corrige erro no firefox ao inicia-lo escondido

- projects/ui/src/lib/components/po-field/po-textarea/po-textarea-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-textarea/po-textarea-base.component.ts
**Textarea**
No componente textarea, caso informar um valor
inválido (falsy) no placeholder era exibido,
neste caso foi preciso realizar um tratamento
para caso dev informar invalido, utilizar valor em branco.
**Simulação**
```
<po-dynamic-form
[p-value]="value"
></po-dynamic-form>
```
```
fields = [
{ property: 'name', placeholder: 'Type your name' },
{ property: 'age' },
{ property: 'email', rows: 5 }
];
value = {};
```
> fix(textarea): realiza tratamento no placeholder caso informar undefined

- projects/ui/src/lib/components/po-table/interfaces/po-table-filtered-items-params.interface.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-with-api/sample-po-table-with-api.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-with-api/sample-po-table-with-api.component.ts
Adiciona método para filtrar dados quando utiliza a `po-table` com uma service.
Fixes DTHFUI-4949
**TABLE**
**DTHFUI-4949**
Não é possível utilizar filtros quando está usando a `po-table` utilizando uma service.
Ao se passar um objeto do formado `{ [ key: string ]: value: string | number }` deve ser adicionado nos parâmetros do GET da service.
**Simulação**
Utilizar o sample `Sample PO Table with API` do Portal.
> feat(table): cria método applyFilters

- projects/ui/src/lib/components/po-calendar/po-calendar-header/po-calendar-header.component.html
- projects/ui/src/lib/components/po-calendar/po-calendar-wrapper/po-calendar-wrapper.component.html
- projects/ui/src/lib/components/po-calendar/po-calendar-wrapper/po-calendar-wrapper.component.ts
- projects/ui/src/lib/components/po-calendar/po-calendar.component.html
- projects/ui/src/lib/components/po-calendar/po-calendar.component.spec.ts
- projects/ui/src/lib/components/po-calendar/po-calendar.component.ts
- projects/ui/src/lib/components/po-field/index.ts
- projects/ui/src/lib/components/po-field/po-clean/po-clean.module.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range-base.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range.component.html
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.module.ts
- projects/ui/src/lib/components/po-field/po-field.module.ts
**< DATEPICKER RANGE >**
**<DTHFUI-1855>**
Não tinha calendario para auxiliar a seleção de datas
Adiciona o calendario para auxiliar na seleção de datas
[**PR STYLE**](https://github.com/po-ui/po-style/pull/221)
**Simulação**
```
range;
<po-datepicker-range p-label="Range Picker" class="po-md-12" name="range" [(ngModel)]="range">
</po-datepicker-range> 
```
> feat(datepicker-range): adiciona calendário para selecionar a data

- projects/ui/src/lib/components/po-menu/po-menu.component.spec.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.ts
**MENU**
**DTHFUI-5058, #852**
Em rotas com menu dinâmico o componente estava ativando o menu item corretamente, porém em redirecionamentos e estrutura mais simples não estava ativando corretamente
Ativa o menu item conforme a rota da aplicação.
**Simulação**
1. Estrutura dinâmica:
- npm run build:portal && ng serve portal
2. Projeto com menu estatico:
3. Redirecionamentos (Mesmo projeto porem as rotas estão comentadas)
[app.zip](https://github.com/po-ui/po-angular/files/6717898/app.zip)
> fix(menu): corrige item de menu que não estava ativando

- projects/ui/src/lib/components/po-list-view/interfaces/po-list-view-action.interface.ts
- projects/ui/src/lib/components/po-list-view/samples/sample-po-list-view-labs/sample-po-list-view-labs.component.ts
**PO-LIST-VIEW**
**DTHFUI-5055**
Hoje a documentação da interface PoListViewAction sobrescreve a interface PoPopupAction e isso está impedindo que o list-view utilize a funcionalidade de permitir outras fontes de ícones por não estender a interface.
Estende a interface PoPopupAction, possibilitando a utilização de outras fontes de ícones.
**Simulação**
Verificar documentação no portal e utilizar o sample labs com os ícones do Font Awesome.
> feat(list-view): adiciona compatibilidade com outras fontes de ícones

- projects/ui/src/lib/components/po-toolbar/po-toolbar-actions/po-toolbar-actions.component.html
- projects/ui/src/lib/components/po-toolbar/po-toolbar-actions/po-toolbar-actions.component.ts
- projects/ui/src/lib/components/po-toolbar/po-toolbar-base.component.ts
- projects/ui/src/lib/components/po-toolbar/po-toolbar.module.ts
- projects/ui/src/lib/components/po-toolbar/samples/sample-po-toolbar-labs/sample-po-toolbar-labs.component.ts
**TOOLBAR**
**DTHFUI-5057**
Permite icones de outras fontes na proprieade p-actions-icon.
[**PR STYLE**](https://github.com/po-ui/po-style/pull/224)
**Simulação**
npm run build:portal && ng serve portal
```
<link
rel="stylesheet"
href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
crossorigin="anonymous"
/>
<link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">
<script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>
```
```
<po-toolbar p-title="PO ICON" [p-actions]="actions" …
```
> feat(toolbar): permite uso outras fontes de icones na prop actionsIcon

- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.html
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-labs/sample-po-lookup-labs.component.html
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-labs/sample-po-lookup-labs.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-sw-films/sample-po-lookup-sw-films.component.html
- projects/ui/src/lib/components/po-field/po-lookup/services/po-lookup-modal.service.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/services/po-lookup-modal.service.ts
Adicionado a funcionalidade de Infinite Scroll na tabela apresentada no componente Lookup
**Lookup**
**#653**
A opção de paginação do componente Lookup não possui a funcionalidade de infinite scroll já existente no PO-Table
Ao usar a diretiva p-infinite-scroll como "true", a tabela apresentada irá possuir o comportamento do infinite scroll já existente no PO-Table.
**Simulação**
Utilizar o sample Labs ou Star Wars films
> feat(lookup): adiciona p-infinite-scroll ao componente lookup

- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-airfare/sample-po-table-airfare.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-airfare/sample-po-table-airfare.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-airfare/sample-po-table-airfare.service.ts
**PO-TABLE**
**DTHFUI-5056**
Não existem métodos públicos que permitam a remoção ou a atualização de um item na tabela.
Método `removeItem()` e `updateItem()` foram inseridos no componente `po-table`.
**Simulação**
Simular através do sample `PO Table - Airfare` no portal.
> feat(table): adiciona métodos `removeItem` e `updateItem`

- .github/workflows/ci.yml
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/samples/sample-po-multiselect-labs/sample-po-multiselect-labs.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/samples/sample-po-multiselect-labs/sample-po-multiselect-labs.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/samples/sample-po-multiselect-vacation-reactive-form/sample-po-multiselect-vacation-reactive-form.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/samples/sample-po-multiselect-vacation-reactive-form/sample-po-multiselect-vacation-reactive-form.component.ts
**< MULTISELECT >**
**< DTHFUI-5063 >**
-
Permite ao componente ter uma altura auto ajustavel,
conforme a largura, quantidade de itens selecionados e a
extensão dos mesmos, sempre mantendo visível os itens selecionados.
**Simulação**
PR STYLE https://github.com/po-ui/po-style/pull/229
npm run build:portal && ng serve portal
> feat(multiselect): adiciona propriedade `p-auto-height`

- projects/ui/src/lib/components/po-menu/po-menu-item.interface.ts
- projects/ui/src/lib/components/po-menu/po-menu-item/po-menu-item.component.html
- projects/ui/src/lib/components/po-menu/po-menu-item/po-menu-item.component.spec.ts
- projects/ui/src/lib/components/po-menu/po-menu-item/po-menu-item.component.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.html
- projects/ui/src/lib/components/po-menu/po-menu.component.spec.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.ts
- projects/ui/src/lib/components/po-menu/po-menu.module.ts
- projects/ui/src/lib/components/po-menu/samples/sample-po-menu-labs/sample-po-menu-labs.component.html
- projects/ui/src/lib/components/po-menu/samples/sample-po-menu-labs/sample-po-menu-labs.component.ts
**PO-MENU**
**DTHFUI-5097**
Permite a utilização de outras fontes de ícones no componente `po-menu`
**Simulação**
Testar no `sample labs` do Portal ou utilizando o `app` com as informações abaixo:
`index.html`
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>App</title>
<base href="/" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="icon" type="image/x-icon" href="favicon.ico" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" …
```
> feat(menu): adiciona compatibilidade com outras fontes de ícones

- projects/ui/src/lib/services/po-notification/po-notification-base.service.ts
- projects/ui/src/lib/services/po-notification/po-notification.interface.ts
- projects/ui/src/lib/services/po-notification/po-notification.service.ts
- projects/ui/src/lib/services/po-notification/po-toaster/po-toaster.component.html
- projects/ui/src/lib/services/po-notification/po-toaster/po-toaster.component.spec.ts
- projects/ui/src/lib/services/po-notification/po-toaster/po-toaster.component.ts
**Notification**
**DTHFUI-5150**
Atualmente não possui botão de fechar na notificação, fazendo necessário adicionar uma ação para o usuário identificar que pode fechar, porem com isso, acaba deixando a notificação fixa pela regra que existe nela.
Adiciona botão de "Fechar" por padrão, fazendo com que torne desnecessário informar uma ação de fechar e tornar mais visual a possibilidade de fechamento.
**Simulação**
[PR STYLE](https://github.com/po-ui/po-style/pull/231)
- Portal (npm run build:portal && ng serve portal)
- App:
```
constructor(notification: PoNotificationService) {
setTimeout(() => {
notification.success({
message: …
```
> feat(notification): adiciona botão de fechar por padrão

- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.ts
- projects/ui/src/lib/services/po-control-position/po-control-position.service.spec.ts
- projects/ui/src/lib/services/po-control-position/po-control-position.service.ts
**PO-DATEPICKER**
**DTHFUI-4943**
Ao abrir o calendário do `PoDatepicker` na extremidade do lado direito da tela, parte do calendário fica oculto.
O componente agora se posiciona de maneira mais assertiva de acordo com o espaço disponível em tela, assim permitindo manipula-lo.
**Simulação**
Simular através dos samples disponíveis para o componente ou também conforme abaixo:
`index.html`
```
<po-page-default p-title="PO UI">
<po-datepicker class="po-md-6"></po-datepicker>        
<po-datepicker class="po-md-6"></po-datepicker>
</div>
```
> fix(datepicker): corrige o posicionamento do componente

- projects/ui/src/lib/components/po-navbar/interfaces/po-navbar-icon-action.interface.ts
- projects/ui/src/lib/components/po-navbar/po-navbar-actions/po-navbar-action/po-navbar-action.component.html
- projects/ui/src/lib/components/po-navbar/po-navbar-actions/po-navbar-action/po-navbar-action.component.ts
- projects/ui/src/lib/components/po-navbar/po-navbar-actions/po-navbar-actions.module.ts
- projects/ui/src/lib/components/po-navbar/po-navbar.module.ts
PO-NAVBAR
DTHFUI-5137
Permite a utilização de outras fontes de ícones no componente `po-navbar`
**Simulação**
Style: https://github.com/po-ui/po-style/pull/232
Importar `BrowserAnimationsModule` no `app.module.ts`
`index.html`
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>App</title>
<base href="/" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="icon" type="image/x-icon" href="favicon.ico" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" …
```
> feat(navbar): adiciona compatibilidade com outras fontes de ícones

- projects/templates/src/lib/components/po-page-change-password/samples/sample-po-page-change-password-request/sample-po-page-change-password-request.component.html
- projects/templates/src/lib/components/po-page-login/samples/sample-po-page-login-automatic-service/sample-po-page-login-automatic-service.component.html
- projects/templates/src/lib/components/po-page-login/samples/sample-po-page-login-human-resources/sample-po-page-login-human-resources.component.ts
Altera url da Api de autenticação e recuperação de senha no sample de page-login
DTHFUI-2668
Simulação:
alterar em `sample-po-page-login-automatic-service.component.html ` :
de: `https://po-sample-api.herokuapp.com/v1/users/authentication`
para: `https://localhost:3000/v1/users/authentication`
`npm run build:portal`
`ng serve portal`
Para rodar localmente o po-sample-api : 
https://github.com/po-ui/po-sample-api/pull/21
`npm run start:dev`
Samples alterados:
PO Page Login - Automatic Service : Recuperação de senha
PO Page Login - Human Resources : Autenticação do usuário
> docs(page-login): altera url de recuperacao e autenticacao

- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range.component.spec.ts
**po-datepicker-range**
Teste apresenta instabilidade durante a execução.
Teste foi ajustado para um resultado mais assertivo conforme o esperado pelo descrito no teste.
> test(datepicker-range): ajusta teste unitário

- projects/ui/src/lib/components/po-field/po-email/po-email.component.spec.ts
- projects/ui/src/lib/components/po-field/po-email/po-email.component.ts
**PO-EMAIL**
**DTHFUI-5088**
O componente ```po-email``` limita a quantidade de caracteres após o último ponto.
Limite de 6 caracteres.
O componente teve o limite alterado e agora permite até 66 caracteres após o último ponto.
**Simulação**
```app.component.html```
```
<po-page-default p-title="PO UI - Email">
<po-email
class="po-lg-12"
name="email"
[(ngModel)]="email"
p-clean
p-error-pattern="Invalid e-mail"
p-label="Email"
p-placeholder="Enter your e-mail"
p-required
>
</po-email>
<po-info
class="po-lg-12"
p-label='Quantidade de caracteres'
p-label-size=11
p-orientation=horizontal
p-value={{email.length}}
> …
```
> fix(email): corrige o limite de caracteres

- projects/ui/src/lib/services/po-notification/po-notification-base.service.spec.ts
- projects/ui/src/lib/services/po-notification/po-notification-base.service.ts
- projects/ui/src/lib/services/po-notification/po-notification.service.spec.ts
- projects/ui/src/lib/services/po-notification/po-notification.service.ts
- projects/ui/src/lib/services/po-notification/po-toaster/po-toaster.component.html
- projects/ui/src/lib/services/po-notification/po-toaster/po-toaster.component.spec.ts
- projects/ui/src/lib/services/po-notification/po-toaster/po-toaster.component.ts
**PO-NOTIFICATION**
**DTHFUI-5060**
O componente de notificação pode ser empilhado de forma ilimitada.
O componente de notificação tem um limite de até 5 notificações por vez. Caso seja enviada uma sexta notificação, a primeira notificação será apagada dando lugar a nova.
**Simulação**
https://github.com/po-ui/po-style/pull/236
app.component:
```
import { PoNotificationService, PoToasterOrientation } from '../../../ui/src/lib';
@Component({
})
constructor(private notification: PoNotificationService) {} …
```
> feat(notification): limita em até 5 notificações na tela

- projects/ui/src/lib/components/po-field/index.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-filter.interface.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/samples/sample-po-multiselect-heroes/sample-po-multiselect-heroes.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/samples/sample-po-multiselect-heroes/sample-po-multiselect-heroes.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/samples/sample-po-multiselect-heroes/sample-po-multiselect-heroes.service.ts
**PO MULTISELECT**
**DTHFUI-1104**
Não permite a utilização com serviço.
Possível utilizar serviço no componente para recuperar os dados do servidor.
**Simulação**
1. Baixar o projeto e subir a aplicação **po-sample-api** localmente através do [PR](https://github.com/po-ui/po-sample-api/pull/22).
2. Buildar o [PR](https://github.com/po-ui/po-style/pull/238) do **po-style** e colocar a dist style dentro da pasta _@po-ui_ na _node_modules_ dentro do projeto po-angular.
3. Alterar as URLs da API no serviço `sample-po-multiselect-heroes.service.ts` no projeto **po-angular**, substituir nas linhas 21 e 31 as URLs:
- …
> feat(multiselect): permite utilizar com serviço

- projects/ui/src/lib/components/po-chart/services/po-chart-maths.service.spec.ts
- projects/ui/src/lib/components/po-chart/services/po-chart-maths.service.ts
Fixes DTHFUI-4931
**Chart**
**DTHFUI-4931**
O gráfico de tabelas não respeita a ordem das categorias enviadas. Sempre mantém a categoria com maior caractere em primeiro.
O gráfico mantém a ordem da lista de categorias enviadas
**Simulação**
`app.component.html` :
```
<po-chart
class="po-md-12 po-mt-2"
p-title="Ranking of the most purchased and consumed beverages in Germany between 2018 and 2020 - in %"
[p-height]="816"
[p-categories]="consumptionPerCapitaItems"
[p-series]="consumptionPerCapita"
[p-type]="consumptionPerCapitaType"
[p-options]="consumptionPerCapitaOptions"
>
</po-chart>
```
`app.component`:
```
import { Component } …
```
> fix(chart): corrige ordenação indevida das categorias

- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-labs/sample-po-combo-labs.component.html
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-labs/sample-po-combo-labs.component.ts
**Combo**
**DTHFUI-4405**
Não permite desabilitar a busca por TAB quando houver serviço, podendo realizar uma chamada para uma API com valor inválido.
Permiti desabilitar a busca por TAB quando houver serviço.
**Simulação**
Visualizar a aba de network e verificar se faz chamada via TAB para algum valor digitado.
`app.component.html:`
```
<po-combo
name="heroName"
[(ngModel)]="heroName"
p-field-label="name"
p-field-value="name"
p-label="Search a Hero"
[p-disabled-tab-filter]="true">
</po-combo>
{{heroName }}
```
`app.component:`
```
import { Component } from …
```
> feat(combo): adiciona propriedade para desabilitar busca por tab

- projects/ui/src/lib/interceptors/po-http-request/po-http-request-interceptor.service.ts
Remove a tela de carregando e diminui o número de requisições pendentes quando a requisição é cancelada.
Fixes DTHFUI-5080
**HTTP REQUEST INTERCEPTOR**
**DTHFUI-5080**
Quando se cancela uma requisição, via unsubscribe ou até mesmo redirecionamento de rota que possui resolver, a tela de carregamento não é removida, nem o número de requests é diminuído.
Quando se cancela uma requisição é removida a tela de carregamento e o número de requisições pendentes é diminuído.
**Simulação**
Utilizando o APP
**Obs:** validar branch `master` para verificar o problema e depois na branch `interceptor/DTHFUI-5080` para ver a solução.
1. Código fonte …
> fix(interceptor): corrige interceptor quando a requisição é cancelada

- projects/templates/src/lib/components/po-page-login/po-page-login.component.html
- projects/templates/src/lib/components/po-page-login/po-page-login.component.spec.ts
**page-login**
**DTHFUI-5136**
Ao atribuir valor vazio para as propriedades `loginHint` e `rememberUserHint` o ícone continua aparecendo mesmo sem dica.
Ao atribuir valor vazio para as propriedades `loginHint` e `rememberUserHint` o ícone não é exibido.
**Obs:** Em telas menores que 540px os campos vão manter 100% de largura caso não contenha nenhum ícone.
Caso tenha apenas o primeiro ícone, o  campo para entrar automaticamente fica com 100% de largura.
Caso tenha apenas o segundo ícone, os campos de login e senha mantém a largura (menor que 100%) .
**Simulação**
Style : https://github.com/po-ui/po-style/pull/243 …
> feat(page-login): retira exibição de icone caso a dica seja vazia

- projects/ui/src/lib/components/po-table/interfaces/po-table-column.interface.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-components/sample-po-table-components.component.ts
PO-TABLE
Ajudaria em muito quando temos varias colunas e algumas delas são
colunas "calculadas" que não são ordenáveis. Isso evitaria de chamar
o evento "p-sort-by" para colunas que não tem ordenação.
O usuário não teria a falsa impressão que pode ordenar a coluna, mesmo
ela não sendo ordenável. Também é útil para remover das colunas que
possuem botões de ação.
#960
Todas as colunas podem ser ordenadas.
Podemos remover a ordenação de colunas que não são ordenáveis através do parâmetro "sortable=false"
**Simulação**
Esta nova propriedade pode ser vista nos exemplos table (PO Table - Po Field Components)
> feat(table): adicionada propriedade `PoTableColumn.sortable`

- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor-base.service.ts
- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor-detail/po-http-interceptor-detail.component.html
- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor-detail/po-http-interceptor-detail.component.spec.ts
- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor-detail/po-http-interceptor-detail.component.ts
- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor-detail/po-http-interceptor-detail.interface.ts
- projects/ui/src/lib/interceptors/po-http-interceptor/samples/sample-po-http-interceptor-labs.component.ts
**HTTP-INTERCEPTOR**
**DTHFUI-4330**
Não é possível passar um título detalhado.
É possível passar um título detalhado, e ele será exibido como título da modal da notificação caso tenha apenas 1 resposta, ou como título do accordion caso hajam mais itens. 
**Simulação**
Pode ser testado no `PO Http Interceptor Labs` do `HTTP Interceptor` do Portal ou no APP conforme informações abaixo:
`app.module.ts`
```typescript
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from …
```
> feat(interceptor): adiciona a propriedade `detailTitle`

- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-filter.service.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-filter.service.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/samples/sample-po-multiselect-heroes/sample-po-multiselect-heroes.service.ts
- projects/ui/src/lib/components/po-field/po-multiselect/samples/sample-po-multiselect-labs/sample-po-multiselect-labs.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/samples/sample-po-multiselect-labs/sample-po-multiselect-labs.component.ts
**MultiSelect**
**DTHFUI-5250**
Não permite passar uma `string` como parâmetro para utilizar um serviço.
Permite informar url como `string` para utilizar um serviço no `multiselect`.
**Simulação**
`app.component.html`:
```
<po-multiselect
class="po-md-6"
name="multiselect"
p-label="Search a Hero"
[(ngModel)]="heroes"
[p-debounce-time]="debounce"
>
</po-multiselect>
```
`app.component.ts`:
```
import { PoMultiselectFilter, PoTableColumn } from '../../../ui/src/lib';
@Component({
templateUrl: …
```
> feat(multiselect): permite informar url no filterService

- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-custom-action.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.component.ts
**PoPageDynamicTable**
**#987**
A interface `PoPageDynamicTableCustomAction` não permite informar o ícone dos botões de ação.
É possível adicionar ícones as ações do `page-dynamic-table` via as custom actions da página, conforme ilustrado abaixo:
**Simulação**
Basta informar a chave `icon` no objeto de configuração:
.ts
```
readonly customActions: PoPageDynamicTableCustomAction[] = [
{
label: 'Home',
action: () => console.log('Você clicou na home'),
icon: 'po-icon-home',
}
];
```
.html
```
<po-page-dynamic-table
[p-page-custom-actions]="customActions"
></po-page-dynamic-table>
```
> feat(po-page-dynamic-table): adiciona a propriedade icon a interface PoPageDynamicTableCustomAction 

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.ts
**DTHFUI-5285**
O componente não dispara o "validate" para os campos do tipo booleano
O componente passa a disparar o "validate" para os campos do tipo booleano
**Simulação**
`component.html`
```
<po-dynamic-form [p-fields]="fields" [p-validate]="onChangeFields.bind(this)" [p-value]="value"></po-dynamic-form>
```
`component.ts`
```
@Component({
})
value = {};
fields: Array<any> = [
{
booleanTrue: 'Ativado',
property: 'convertEntityQty',
booleanFalse: 'Desativado',
label: 'Converter qtd …
```
> fix(dynamic-form): corrige o "validate" ao clicar em um campo do tipo booleano

- projects/ui/src/lib/components/po-calendar/po-calendar-base.component.spec.ts
- projects/ui/src/lib/components/po-calendar/po-calendar-base.component.ts
- projects/ui/src/lib/services/po-date/po-date.service.ts
**DTHFUI-5296**
Quando seleciona o dia 01 de uma mês, o mês selecionado some e aparece o mês anterior.
Exemplo: Quando selecionar o dia 01 de setembro, o calendário passará a apresentar o mês de agosto.
Quando seleciona o dia 01 de uma mês, o mês selecionado se mantém sendo apresentado.
**Simulação**
Incluir o componente PoDatepickerRangeComponent no app e selecionar o primeiro dia de qualquer mês do ano.
> fix(datepicker-range): corrige calendario ao selecionar 01/mm/yyyy

- HOW_TO_DOCUMENT.md
- projects/portal/docs/configuration.js
- projects/portal/docs/processors/helpers/functions.js
- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-field.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-filters.interface.ts
- projects/ui/src/lib/components/po-page/po-page-action.interface.ts
**DTHFUI-4296**
Documentação não estende propriedades.
Documentação estende propriedades.
**Simulação**
- subir o portal e ver documentação
Exemplo : 
- Ver documentação do componente : `po-page-dynamic-table` (http://localhost:4200/documentation/po-page-dynamic-table)
- Interface `PoPageDynamicTableFilters` estende propriedades da interface `PoPageDynamicTableField` e `PoDynamicFormField`
> docs(portal): estende propriedades/metodos/docs

- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-custom-table-action.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.component.ts
**Po Page Dynamic Table**
**#1014**
Não existe forma de incluir ícones as ações customizadas da tabela.
Permite incluir ícones as ações customizadas da tabela através da interface PoPageDynamicTableCustomTableAction.
**Simulação**
Atualizar o portal localmente e ver o exemplo PO Page Dynamic Table - Users.
> feat(po-page-dynamic-table): inclui icon e disabled a interface custom table action

- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/samples/sample-po-dynamic-form-register/sample-po-dynamic-form-register.component.ts
Atualmente não permite utilizar intervalos de datas com o componente datepicker range.
Através da propriedade range da interface PoDynamicFormField é possível transformar o componente datepicker em datepicker range.
Para o componente Page Dynamic Search, já foi feito um tratamento para os disclaimers aparecerem corretamente.
**Simulação**
Utilizar o sample do Dynamic Form. Também é possível usar essa propriedade com Page Dynamic Search, Page Dynamic Table e Page Dynamic Edit.
> feat(dynamic-form): add range to interface dynamic form

- projects/templates/src/lib/components/po-page-dynamic-detail/interfaces/po-page-dynamic-detail-field.interface.ts
**PO-PAGE-DYNAMIC-DETAIL**
**#1042**
Algumas propriedades da interface `PoPageDynamicDetailField` não estavam sendo exibidas.
Todas as propriedades  da interface são exibidas
**Simulação**
A correção pode ser validada na documentação, onde todas as propriedades disponível da interface são exibidas.
> docs(page-dynamic-detail): exibe propriedades extendidas na documentação

- CONTRIBUTING.md
**CONTRIBUTING**
O guia de contribuição conta com tags de link `<a>` para ligar o item na tabela de conteúdo ao seu texto dentro do guia
Passa a ser utilizado o id gerado pelo próprio heading no texto, fazendo com que os links deixem de ter utilidade.
**Simulação**
Simular através do arquivo `CONTRIBUTING.md` e clicando em um item da tabela de conteúdo.
> docs(contributing): remove tags de links do arquivo

- projects/ui/src/lib/components/po-field/po-datepicker-range/interfaces/po-datepicker-range-literals.interface.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range-base.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range.literals.ts
fix(datepicker-range): corrige para permitir apenas datas válidas
O componente estava permitindo inserir valores inválidos via digitação,
como exemplo 31/02/2021, sendo que Fevereiro é até dia 28.
Fixes DTHFUI-5127
**< DatepickerRange>**
**< DTHFUI-5127 >**
Componente está permitindo inserir uma data inválida via digitação, como exemplo 31/02/2021 sendo que fevereiro é até o dia 28.
Componente apresenta mensagem "Data inválida" quando insere no campo uma data inválida, como exemplo 31/02/2021.
**Simulação**
- component.html
```
<po-datepicker-range
name="datepickerRange"
p-auto-focus="boolean"
p-clean="true" …
```
> fix(datepicker-range): corrige para permitir apenas datas válidas

- projects/ui/src/lib/components/po-stepper/po-stepper-circle/po-stepper-circle.component.html
- projects/ui/src/lib/components/po-stepper/po-stepper-circle/po-stepper-circle.component.spec.ts
- projects/ui/src/lib/components/po-stepper/po-stepper-step/po-stepper-step.component.html
- projects/ui/src/lib/components/po-stepper/po-stepper-step/po-stepper-step.component.spec.ts
- projects/ui/src/lib/components/po-stepper/po-stepper-step/po-stepper-step.component.ts
- projects/ui/src/lib/components/po-stepper/po-stepper.component.html
- projects/ui/src/lib/components/po-stepper/po-stepper.component.spec.ts
**Stepper**
**DTHFUI-5061**
Alteração do visual do componente stepper conforme zeplin que contem na issue.
**Simulação**
build style : https://github.com/po-ui/po-style/pull/253
https://github.com/totvs/po-theme-totvs/pull/116
`app.ts `: 
```
@Component({
})
canActive() {
//return false;
return true;
}
}
```
`app.html`  :
```
<po-stepper [p-step-icons]="false" p-orientation="vertical" p-step-size="44">
<po-step p-label="Step 1"></po-step>
<po-step p-label="Step 2"></po-step>
<po-step p-label="Step 3" [p-can-active-next-step]="canActive.bind(this)"></po-step> …
```
> feat(stepper): melhora identificação visual dos passos

- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-field.interface.ts
- projects/ui/src/lib/components/po-table/po-table-column-label/po-table-column-label.interface.ts
Implementa propriedade labels na interface PoPageDynamicTableField
**PO-PAGE-DYNAMIC-TABLE**
**#1038**
A interface não exibe a propriedade `PoPageDynamicTableField` na documentação.
A propriedade é exibida na documentação com exemplo de utilização.
**Simulação**
Simular através do **portal**
> docs(page-dynamic-table): adiciona propriedade faltante em interface

- projects/ui/src/lib/components/po-field/po-decimal/po-decimal.component.spec.ts
- projects/ui/src/lib/components/po-field/po-decimal/po-decimal.component.ts
- projects/ui/src/lib/components/po-field/po-number/po-number-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-number/po-number-base.component.ts
- projects/ui/src/lib/components/po-field/po-number/po-number.component.spec.ts
- projects/ui/src/lib/components/po-field/po-number/po-number.component.ts
- projects/ui/src/lib/components/po-field/po-textarea/po-textarea-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-textarea/po-textarea-base.component.ts
- projects/ui/src/lib/components/po-field/po-textarea/po-textarea.component.spec.ts
- projects/ui/src/lib/components/po-field/po-textarea/po-textarea.component.ts
**Number, Decimal e TextArea**
**DTHFUI-5460**
Os componentes utilizam o ChangeDetectionStrategy.Default
Os componentes utilizam o ChangeDetectionStrategy.OnPush
**Simulação**
teste dos componentes no portal e app  : 
app.html: 
```
<po-decimal name="decimal" [(ngModel)]="decimal" p-label="PO Decimal"> </po-decimal>
<po-textarea name="textarea" [(ngModel)]="textarea" p-label="PO Textarea"> </po-textarea>
<po-number name="number" [(ngModel)]="number" p-label="PO Number"> </po-number>
```
app.ts: 
```
@Component({
})
export …
```
> perf(fields): implementa ChangeDetectionStrategy OnPush

- projects/ui/src/lib/components/po-calendar/po-calendar-wrapper/po-calendar-wrapper.component.html
- projects/ui/src/lib/components/po-calendar/po-calendar-wrapper/po-calendar-wrapper.component.spec.ts
- projects/ui/src/lib/components/po-calendar/po-calendar-wrapper/po-calendar-wrapper.component.ts
- projects/ui/src/lib/components/po-calendar/po-calendar.component.ts
- projects/ui/src/lib/components/po-calendar/services/po-calendar.lang.service.ts
**CALENDAR**
**DTHFUI-5464**
Componente `calendar` não tem um botão para selecionar o dia referente a data atual.
Adicionado botão no rodapé do `calendar` para que seja possível selecionar o dia referente a data atual mesmo durante a navegação entre meses e anos.
**Simulação**
```
<div class="po-p-2">
<po-calendar [(ngModel)]="calendar" [p-locale]="locale"></po-calendar>
<po-info p-value={{calendar}}></po-info>
</div>
<div class="po-p-2">
<po-calendar [(ngModel)]="calendarRange" [p-locale]="locale" [p-mode]="mode"></po-calendar>
</div>
<div class="po-p-2">
<po-datepicker [(ngModel)]="datepicker" …
```
> feat(calendar): adiciona botão `hoje`

- projects/ui/src/lib/components/po-modal/index.ts
- projects/ui/src/lib/components/po-modal/po-modal-base.component.ts
- projects/ui/src/lib/components/po-modal/po-modal-footer/po-modal-footer.component.html
- projects/ui/src/lib/components/po-modal/po-modal-footer/po-modal-footer.component.spec.ts
- projects/ui/src/lib/components/po-modal/po-modal-footer/po-modal-footer.component.ts
- projects/ui/src/lib/components/po-modal/po-modal.component.html
- projects/ui/src/lib/components/po-modal/po-modal.component.spec.ts
- projects/ui/src/lib/components/po-modal/po-modal.component.ts
- projects/ui/src/lib/components/po-modal/po-modal.module.ts
- projects/ui/src/lib/components/po-modal/samples/sample-po-modal-fruits-salad/sample-po-modal-fruits-salad.component.html
- projects/ui/src/lib/components/po-modal/samples/sample-po-modal-fruits-salad/sample-po-modal-fruits-salad.component.ts
MODAL-FOOTER
DTHFUI-4864
Rodapé do modal possui um alinhamento padrão a direita, para os botões de ações.
Da liberdade ao desenvolvedor personalizar o alinhamento e a quantidade de botões de ações. 
**Simulação**
```
<div class="po-p-2">
<po-modal #modal p-title="PO Modal">
We are TOTVERS!!!
<po-modal-footer [p-disabled-align]="true">
<po-button p-label="Tertiary Action"> </po-button>
<po-button p-label="Secondary Action"> </po-button>
<po-button p-label="Primary Action"> </po-button>
</po-modal-footer>
</po-modal>
<po-button p-label="Open modal" (p-click)="modal.open()"> </po-button>
</div>
```
Build …
> feat(modal-footer): cria componente `modal-footer`

- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-sw-films/sample-po-lookup-sw-films.component.ts
**LOOKUP**
**DTHFUI-5512**
O componente `lookup` não atualiza o campo de disclaimers ao realizar a limpeza do model.
O método `setDisclaimers` foi adicionado ao método `cleanViewValue` para executar a limpeza do campo de disclaimers.
**Simulação**
`app.compenent.html`
```
<div class="po-p-2">
<po-lookup
name="lookup"
[(ngModel)]="lookup"
[p-multiple]="true"
></po-lookup>
{{ lookup }}
<button (click)="onclick()">LIMPA</button>
</div>
```
`app.component.ts`
```
import { Component } from …
```
> fix(lookup): campo não atualizado ao alterar o model

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
**DTHFUI-5494**
O componente `dynamic-form` não aceita o uso de serviço no campo do tipo `multiselect`.
Ajuste na condição de uso para o uso de serviço com o campo de `multiselect`.
**Simulação**
```
<po-dynamic-form [p-fields]="fields" [p-value]="value"></po-dynamic-form>
```
`app.component.ts`
```
options = ['A', 'B', 'C', 'D', 'E'];
service = 'https://po-sample-api.herokuapp.com/v1/heroes';
fields = [
{ property: 'heroes options', options: this.options }, // isSelect
{ property: 'heroes options multi', options: this.options, optionsMulti: true }, // isMultiselect
{ property: 'heroes …
```
> feat(dynamic-form): permite multiselect com serviço

- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range-base.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.ts
**Datepicker** e **Datepicker-range**
**DTHFUI-5461**
Os componentes utilizam o ChangeDetectionStrategy.Default
Os componentes utilizam o ChangeDetectionStrategy.OnPush
**Simulação**
Simular no Portal e no app :
app.ts: 
```
@Component({
})
date = new Date(2021, 9, 15);
dateRange;
limpa() {
this.date = null;
}
limpaRange() {
this.dateRange = undefined;
}
}
```
app.html: 
```
<po-datepicker p-label="PO Date" name="date" [(ngModel)]="date" > </po-datepicker>
{{date}}
<button …
```
> implementa ChangeDetectionStrategy OnPush no datepicker e datepicker-range

- projects/templates/src/lib/components/po-page-job-scheduler/interfaces/po-job-scheduler-internal.interface.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-base.component.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-base.component.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-execution/po-page-job-scheduler-execution.component.html
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-execution/po-page-job-scheduler-execution.component.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-execution/po-page-job-scheduler-execution.component.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-internal.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-literals.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-summary/po-page-job-scheduler-summary.component.html
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-summary/po-page-job-scheduler-summary.component.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-summary/po-page-job-scheduler-summary.component.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.service.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.service.ts
**PAGE JOB SCHEDULER**
**DTHFUI-5526**
Não é possível configurar a frequência
Permite configurar a frequência
**Simulação**
Simular através do sample do portal.
[app 2.zip](https://github.com/po-ui/po-angular/files/7570798/app.2.zip)
[PR no po-sample-api - WIP](https://github.com/po-ui/po-sample-api/pull/26)
> feat(page-job-scheduler): permite configuração de frequência

- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
**DTHFUI-5503**
O componente não dispara evento de `change` caso a quantidade de seleções atuais seja igual à anterior após a limpeza do campo.
Incluída condicional que valida a quantidade de seleções e corrige o valor do `model` anterior.
**Simulação**
```
<po-multiselect
class="po-md-12"
name="multiselect"
[(ngModel)]="multiselect"
p-label="Multiselect service"
[p-options]="options"
(p-change)="changeEvent('p-change')"
></po-multiselect>
</div>
<po-info class="po-md-6" …
```
> fix(multiselect): componente não dispara evento de `change`

- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.ts
**Table**
**DTHFUI-5488**
As ações ficam do lado direito da tabela como padrão
As ações ficam do lado esquerdo da tabela como padrão, porém mantém a possibilidade de manter a coluna de ações na direita utilizando a propriedade `p-actions-right`
**Simulação**
Testar o componente table, portal e samples.
app.html:
```
<sample-po-table-airfare></sample-po-table-airfare>
```
> feat(table): move coluna de ações para esquerda

- projects/ui/src/lib/components/po-navbar/po-navbar-base.component.ts
**NAVBAR**
**DTHFUI-5487**
Componente Navbar possui propriedade ```p-menu```  desnecessária.
Componente Navbar deixou de possuiu propriedade ```p-menu```.
**Simulação**
Rodar do portal
> refactor(navbar): remove a propriedade p-menu

- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search-base.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search-base.component.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.ts
fixes DTHFUI-5621
**Dynamic-Table**
**DTHFUI-5621**
Erro no console ao tentar filtrar coluna searchService
Aplica verificação para não filtrar searchService
**Simulação**
- Alterar filtro no gerenciador da tabela
- Abrir busca avançada, selecionar para pesquisar e alterar novamente o gerenciador de filtro.
- Alterar novamente o filtro no gerenciador da tabela.
- Verificar se ocorre erro no console.
Utilizar app: 
[app.zip](https://github.com/po-ui/po-angular/files/7729194/app.zip)
> fix(dynamic-table): ocorre erro ao tentar filtrar `searchService`

- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-field.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.component.ts
**DTHFUI-4849**
**Simulação**
Portal e app : 
app.html:
```
<po-page-dynamic-table p-service-api="https://po-sample-api.herokuapp.com/v1/people" [p-fields]="fields">
</po-page-dynamic-table>
```
app.ts:
```
readonly fields: Array<any> = [
{ property: 'id', key: true },
{ property: 'name', label: 'Name' },
{ property: 'city', label: 'City', sortable: false }
];
```
> feat(page-dynamic-table): adiciona propriedade `sortable` na interface

- projects/ui/src/lib/components/po-field/po-radio-group/po-radio-group.component.spec.ts
- projects/ui/src/lib/components/po-field/po-radio-group/po-radio-group.component.ts
**radio-group**
**fixes DTHFUI-5519**
**Simulação**
Simular portal e app:
[app.zip](https://github.com/po-ui/po-angular/files/7771151/app.zip)
> perf(radio-group): implementa ChangeDetectionStrategy.OnPush

- projects/ui/src/lib/components/po-menu/po-menu.component.spec.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.ts
**MENU**
**DTHFUI-5543**
Quando temos um menu com subitens com o mesmo nome, por exemplo `edit`, e clicamos no último `edit` listado, o menu item selecionado era sempre o primeiro `edit` exibido no menu, sendo exibido de forma equivocada no menu.
Quando temos um menu com subitens com o mesmo nome, por exemplo `edit`, e clicamos no ultimo `edit` listado, este aparece selecionado no menu.
**Simulação**
Criar um menu com subitens de mesmo label, ou u tilizar este  [app.zip](https://github.com/po-ui/po-angular/files/7916423/app.zip) para testes.
> feat(menu): ajusta sinalização de item ativo

- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.html
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.component.html
adiciona propriedade p-actions-right que permite manter as ações na direita da tabela.
Feat#1160
**1160**
Houve uma mudança no componente table, onde o lado padrão das ações foi movido para a esquerda e no componente page-dynamic-table não existe a possibilidade de colocar no lado direito como no table.  
Foi adiciona propriedade p-actions-right que permite manter as ações na direita da tabela.
**Simulação**
npm run build:portal && ng serve portal
No exemplo "PO Page Dynamic Table - Users" foi adicionado a propriedade [p-actions-right]="true" que posiciona as acções do lado direito.
> feat(page-dynamic-table): adiciona a propriedade p-actions-right

- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-custom-table-action.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
**PAGE-DYNAMIC-TABLE**
**DTHFUI-5648**
Atualmente não é permitido a utilização de URL Externa, nem concatenar o ID do item da tabela com a URL digitada.
Agora é possível utilizar URL Externa, bem como concatenar o ID à URL adicionada, através da propriedade `concatKey`
**Simulação**
Utilizar este [APP](https://github.com/po-ui/po-angular/files/7953859/app.zip)
> feat(page-dynamic-table): permite url externa e implementa `concatKey`

- docs/guides/releases.md
- projects/portal/src/app/app.component.ts
**Releases**
Conforme agenda de publicação de novas versões estáveis do Angular, nós atualizaremos nossas versões como de costume e aproveitaremos para fazer uma mudança na nomenclatura das nossas versões. A próxima v7.x.x será lançada como v14.x.x, assim a versão 14.x.x do PO UI terá compatibilidade com a v14 do Angular e assim por diante. Mais informações: https://github.com/po-ui/po-angular/issues/1184.
Verificar notification na página inicial do portal e alteração na documentação de releases.
> docs(releases): documenta mudança de nomenclatura das versões

- docs/guides/getting-started.md
- package.json
- projects/app/.browserslistrc
- projects/portal/browserslist
**SCHEMATICS**
**DTHFUI-5697**
Não era possível executar o comando `ng add @po-ui/ng-components`, por que ocorria um erro durante a execução.
Foi corrigido este erro de ngAdd
**Simulação**
Existem duas formas:
1. Remover o `xdescribe` do arquivo `projects/ui/schematics/ng-add/index.spec.ts` e executar `npm run test:schematics`.
2. Seguir o passo a passo do arquivo `projects/ui/schematics/README.md` e seguir o [Primeiros Passos](https://po-ui.io/guides/getting-started) do portal do PO UI.
> fix(schematics): corrige erro no ng add @po-ui/ng-components

- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-custom-table-action.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.component.html
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.component.ts
- projects/ui/src/lib/components/po-popup/po-popup-action.interface.ts
- projects/ui/src/lib/components/po-popup/po-popup.component.html
Adiciona o atributo visible.
Opções para tornar a ação visível ou não:
- Função que retorna um booleano
- Informar diretamente um valor booleano.
Fixes #1156
** Page Dynamic Table **
** 1156 **
A propriedade p-table-custom-actions não tem o atributo visible.
Foi adicionado o atributo visible na propriedade p-table-custom-actions para tornar a ação visível ou não. O valor do atributo pode ser atribuído por função que retorna um booleano ou informar diretamente o valor booleano. 
**Simulação**
Pode ser realizada no portal.
> feat(page-dynamic-table): p-table-custom-actions

- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-custom-action.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.component.html
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.component.ts
Adiciona o atributo `visible` na propriedade `p-page-custom-actions`.
Opções para tornar a ação visível ou não:
- Função que retorna um booleano
- Informar diretamente um valor booleano.
Fixes #1158
**1158**
A propriedade `p-page-custom-actions` não tem o atributo `visible`.
Foi adicionado o atributo `visible` na propriedade `p-page-custom-actions` para tornar a ação visível ou não. O valor do atributo pode ser atribuído por função que retorna um booleano ou informar diretamente o valor booleano.
**Simulação**
Pode ser realizada no portal.
> feat(page-dynamic-table): p-page-custom-actions

- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-sw-films/sample-po-lookup-sw-films.component.ts
**Lookup**
**DTHFUI-5695**
Quando o componente não é multiplo o `p-selected` retorna apenas o id do item selecionado
Quando o componente não é multiplo o `p-selected` retorna o objeto completo
**Simulação**
html:
```
<po-lookup
[(ngModel)]="lookup"
name="lookup"
(p-selected)="teste($event)"
>
</po-lookup>
```
app.ts:
```
teste(value) {
console.log(value)
}
```
> fix(lookup): `p-selected`  não retorna objeto completo

- projects/ui/src/lib/directives/po-tooltip/po-tooltip-base.directive.spec.ts
- projects/ui/src/lib/directives/po-tooltip/po-tooltip-base.directive.ts
- projects/ui/src/lib/directives/po-tooltip/samples/sample-po-tooltip-labs/sample-po-tooltip-labs.component.html
**tooltip**
**DTHFUI-2201**
componente tem limite de caracteres
componente não tem limite de caracteres
**Simulação**
testar portal com o tooltip e componentes que utilizam e app:
html:
```
<po-page-login [p-literals]="customLiterals"></po-page-login>
```
ts:
```
customLiterals: PoPageLoginLiterals = {
loginHint: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quisua.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quisua.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quisua.`,
};
```
> feat(tooltip): remove restrição de caracteres

- projects/ui/src/lib/components/po-menu/po-menu.component.html
**MENU**
**DTHFUI-5760**
Ao utilizar a extensão AxeDevTools, aparece este aviso sobre o menu: (All page content should be contained by landmarks).
Ao utilizar a extensão AxeDevTools não deve mais aparecer este aviso.
**Simulação**
Instalar a extensão [axe DevTools](https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd) e rodar este [app](https://github.com/po-ui/po-angular/files/8092437/src.zip).
PR no Style https://github.com/po-ui/po-style/pull/284 para verificação da CDN do projeto.
> feat(menu): melhora acessibilidade ao menu

- projects/ui/src/lib/components/po-calendar/po-calendar-wrapper/po-calendar-wrapper.component.html
**Calendar**
**DTHFUI-5688**
Ao selecionar um input e apertar ENTER o componente datepicker é preenchido e recebe foco
Ao selecionar um input e apertar ENTER o componente datepicker não é preenchido e não recebe foco
**Simulação**
Selecionar Input e apertar enter
html:
```
<form>
<po-input class="po-md-6" name="label" [(ngModel)]="label" p-clean p-label="Label"> </po-input>
<po-input class="po-md-6" name="label2" [(ngModel)]="label2" p-clean p-label="Label2"> </po-input>
<po-datepicker
class="po-sm-12"
name="datepicker"
[(ngModel)]="datepicker"
>
</po-datepicker>
</form>
```
app.ts:
```
datepicker;
label;
label2;
```
> fix(calendar): corrige focus quando pressionada a tecla ENTER

- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
Quando o `value` é do tipo `number` e igual a zero o retorno do `value` do `p-filter-service` é `undefined`
Fixes #1183
**Combo**
**1183**
Quando o `value` é do tipo `number` e igual a zero o retorno do `value` do `p-filter-service` é `undefined`
Na situação relatada acima, agora o retorno é zero como esperado.
**Simulação**
A simulação pode ser feita neste [App](https://github.com/po-ui/po-angular/files/8069114/app.zip).
> fix(combo): corrige retorno `undefined` do `p-filter-service`

- projects/ui/src/lib/components/po-field/po-radio-group/po-radio-group-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-radio-group/po-radio-group-base.component.ts
- projects/ui/src/lib/components/po-field/po-radio-group/po-radio-group.component.spec.ts
- projects/ui/src/lib/components/po-field/po-radio-group/po-radio-group.component.ts
A ativação do `onTouched` no componente permite que o evento `validate` seja disparado no componente `page-dynamic-edit` quando o `radio-group` é o primeiro componente a ser tocado.
Fixes #1202
**Radio Group**
**1202**
O evento `validate` não é disparado no componente `page-dynamic-edit` quando o `radio-group` é o primeiro componente a ser tocado.
A ativação do `onTouched` no componente permite que o evento `validate` seja disparado no componente `page-dynamic-edit`
quando o `radio-group` é o primeiro componente a ser tocado.
**Simulação**
Usar o [App](https://github.com/po-ui/po-angular/files/8100859/app.zip) para realizar …
> feat(radio-group): ativado o estado `onTouched` no componente

- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.component.html
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.component.spec.ts
RICH-TEXT
DTHFUI-5847
Não possui atributo aria-label no input do color picker, impossibilitando o (NVDA) de fazer a leitura.
Ao utilizar leitor de tela (NVDA) no input do color picker o mesmo passa ler corretamente o atributo aria-label definido.
**Simulação**
```
<!DOCTYPE html>
<html lang="pt">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Document</title>
</head>
<body>
<po-rich-text></po-rich-text>
</body>
</html>
```
Utiliza o leito de tela (NVDA) no color picker.
> feat(rich-text): adiciona atributo aria-label

- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
**PO-TABLE**
**DTHFUI-5752**
O scroll vertical fica visível apenas no final da tabela.
O scroll vertical fica sempre visível.
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/8421425/app.zip)
**PO-STYLE**
https://github.com/po-ui/po-style/pull/295
> feat(table): fixa scroll vertical

- projects/sync/src/lib/services/po-event-sourcing/po-event-sourcing.service.ts
**Event Sourcing (PO Sync)**
**Sem issue**
Está exibindo lint de códigos depreciados na esteira do build.
Remover os lints de códigos depreciados.
**Simulação**
Rodar projeto sample usando a lib sync.
> refactor(event-sourcing): utiliza StatusCodes

- projects/ui/src/lib/components/po-progress/samples/sample-po-progress-basic/sample-po-progress-basic.component.html
A propriedade `strictTemplates` já vem configurado como `true` na versão atual do Angular e desta forma o exemplo apresenta erro de compilação.
Fixes #1243
**Progress**
**1243**
O exemplo atual declara o `p-value` da seguinte forma `<po-progress p-value="25"></po-progress>` e apresenta erro caso o `angularCompilerOptions` estiver da seguinte forma `strictTemplates: true` .
Foi alterado a declaração do `p-value` para `<po-progress [p-value]="25"></po-progress>` e não apresenta erro caso o `angularCompilerOptions` estiver da seguinte forma `strictTemplates: true` .
**Simulação**
Pode ser feita no próprio portal.
> docs(progress): ajusta a propriedade `p-value` com a opção `strict`

- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-airfare/sample-po-table-airfare.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-airfare/sample-po-table-airfare.component.ts
**table**
**DTHFUI-4787**
Cria evento `p-restore-column-manager` para restaurar as colunas configuradas inicialmente no botão de gerenciamento.
**Simulação**
Testar app ou pelo portal:
[app.zip](https://github.com/po-ui/po-angular/files/8475078/app.zip)
> feat(table): cria evento para restaurar padrão

- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
**Combo**
**DTHFUI-5962**
Não permite itens com a mesma label
Permite itens com a mesma label
**Simulação**
portal 
[app.zip](https://github.com/po-ui/po-angular/files/8557861/app.zip)
> fix(combo): permite labels com o mesmo valor

- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.html
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-people/sample-po-page-dynamic-table-people.component.html
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-people/sample-po-page-dynamic-table-people.component.ts
Adiciona as propriedades p-infinite-scroll e p-height
que serão repassadas para o componente po-table,
onde já são suportadas.
Fixes #1092
** Page Dynamic Table **
** 1192 **
O componente não tem as propriedades p-infinite-scroll e p-heigh.
Foram adicionadas as propriedades p-infinite-scroll e p-height, que serão repassadas para o componente po-table, onde já são suportadas pelo mesmo.
**Simulação**
Foi criado no portal um exemplo com a funcionalidade ativada.
> feat(page-dynamic-table): adiciona p-infinite-scroll e p-height

- projects/ui/src/lib/components/po-field/po-decimal/po-decimal.component.spec.ts
- projects/ui/src/lib/components/po-field/po-decimal/po-decimal.component.ts
**DECIMAL**
**DTHFUI-5920**
Quando copiamos e colamos um valor com mais de 16 caracteres o campo não apresenta uma formatação correta e não invalida o campo.
Ao copiar e colar um valor com mais de 16 caracteres o campo será invalidado.
**Simulação**
```
<po-page-default p-title="PO page default">
<po-decimal
class="po-md-12"
name="decimal"
[(ngModel)]="decimal"
[p-decimals-length]="decimalsLength"
p-label="PO decimal"
p-clean="true"
[p-thousand-maxlength]="thousandMaxlength"
[p-max]="max"
[p-min]="min"
(p-blur)="changeEvent('p-blur')"
(p-change)="changeEvent('p-change')" …
```
> fix(decimal): atualiza as validações do campo 

- projects/ui/src/lib/components/po-button/po-button-base.component.spec.ts
- projects/ui/src/lib/components/po-button/po-button-base.component.ts
- projects/ui/src/lib/components/po-button/po-button-type.enum.ts
- projects/ui/src/lib/components/po-button/po-button.component.html
- projects/ui/src/lib/components/po-button/samples/sample-po-button-labs/sample-po-button-labs.component.ts
- projects/ui/src/lib/components/po-modal/po-modal.component.spec.ts
- projects/ui/src/lib/components/po-modal/po-modal.component.ts
- projects/ui/src/lib/components/po-page/po-page-detail/po-page-detail.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-detail/po-page-detail.component.ts
- projects/ui/src/lib/components/po-page/po-page-edit/po-page-edit.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-edit/po-page-edit.component.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.html
**Button**
**DTHFUI-6000**
Deprecia `link` e `default` e adiciona `secondary` e `tertiary`
**Simulação**
Testar no portal e app:
```
<po-button  p-label="PO Button" > </po-button>
<po-button p-type="secondary" p-label="PO Button" > </po-button>
<po-button p-type="default" p-label="PO Button" > </po-button>
<br>
<po-button p-type="link" p-label="PO Button" > </po-button>
<po-button p-type="tertiary" p-label="PO Button" > </po-button>
<br>
<po-button p-type="primary" p-label="PO Button" > </po-button>
<po-button p-type="danger" p-label="PO Button" > </po-button>
```
> Button - deprecia link e default

- projects/ui/src/lib/components/po-field/index.ts
- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox.module.ts
- projects/ui/src/lib/components/po-field/po-field.module.ts
- projects/ui/src/lib/components/po-table/po-table-detail/po-table-detail.component.html
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.module.ts
**TABLE**
**DTHFUI-6066**
Atualmente a PoTable utiliza um checkbox estilizado para selecionar linhas.
Agora a PoTable começa a utilizar o PoCheckbox no lugar do checkbox antigo.
**Simulação**
Utilizar este [app.zip](https://github.com/po-ui/po-angular/files/8764026/app.zip) e utilizar os Samples do Portal.
**PO-STYLE**: https://github.com/po-ui/po-style/pull/308
> feat(table): adiciona po-checkbox na po-table

- projects/ui/src/lib/components/po-menu/po-menu-base.component.spec.ts
- projects/ui/src/lib/components/po-menu/po-menu-base.component.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.html
**MENU**
**DTHFUI-6004**
Atualmente o logo do menu não possuí a propriedade `alt`.
Adicionado a propriedade `p-logo-alt` para inclusão de texto alternativo e realizado os tratamentos necessários para controle de caracteres.
**Simulação**
```
<po-menu
p-logo="https://po-ui.io/assets/po-logos/po_color.svg"
p-logo-alt="Po-UI Logo"
[p-menus]="[{ label: 'PO UI - Angular Framework', link: '/' }]"
>
</po-menu>
```
> feat(menu): inclui propriedade p-logo-alt

- projects/ui/src/lib/components/po-button/po-button-base.component.spec.ts
- projects/ui/src/lib/components/po-button/po-button-base.component.ts
- projects/ui/src/lib/components/po-button/po-button.component.html
- projects/ui/src/lib/components/po-button/samples/sample-po-button-labs/sample-po-button-labs.component.html
- projects/ui/src/lib/components/po-button/samples/sample-po-button-labs/sample-po-button-labs.component.ts
**BUTTON**
**DTHFUI-6005**
Atualmente o `PoButton` tem a propriedade `p-kind/p-type` que pode receber o valor `danger` e aplicar um estilo ao botão.
A partir de agora será utilizada a propriedade `p-danger` para definir esse estilo e a propriedade `p-kind/p-type` terá o valor `danger` depreciado de sua enumeração.
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/8720907/app.zip)
> feat(button): deprecia type danger e adiciona propriedade p-danger

- package.json
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-table/po-table.module.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-basic/sample-po-table-basic.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.ts
**TABLE**
**DTHFUI-5921**
O componente table não possui cdk-virtual-scroll 
Componente table passa a ter cdk-virtual-scroll para melhor desempenho
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/8594506/app.zip),  portal e coloca os samples do portal em um app, dynamic table por exemplo.
po-style: https://github.com/po-ui/po-style/pull/300
> feat(table): implementa virtual scroll

- docs/guides/getting-started.md
- docs/guides/sync-get-started.md
- package.json
- projects/sync/ng-package.json
- projects/sync/package.json
- projects/sync/schematics/ng-add/index.spec.ts
- projects/sync/schematics/ng-add/index.ts
- projects/sync/src/lib/po-sync.module.ts
- projects/sync/src/lib/services/po-network/po-network.service.spec.ts
- projects/sync/src/lib/services/po-network/po-network.service.ts
**BUILD**
**DTHFUI-6020**
Ao utilizar uma versão do npm maior do que a v6 (v7+) ocorre um erro de conflito de dependências do rxjs entre o root e uma peer-dependency do @ionic-native/core e @ionic-native/network
Ao realizar o npm i no monorepo com uma versão do npm superior à v6, deve concluir a instalação sem erros.
**Simulação**
1. `npm run build`
2. Usar o [Verdaccio](https://verdaccio.org/docs/installation)
3. publicar os pacotes usando `npm run publish:local`
4. Seguir um dos passos abaixo:
3.1 Seguir o guia [Primeiros Passos](https://po-ui.io/guides/getting-started)
3.2 Apagar `package-lock.json` e `node_modules` no …
> fix(build): corrige erro do npm v7+

- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.component.html
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.service.ts
A propriedade `stric` e `strictTemplates` já vem configurado como `true` na versão atual do Angular e desta forma o exemplo apresenta erro de compilação.
Fixes #1260
**1260**
O exemplo atual apresenta erro caso o `compilerOptions` estiver com `strict: true` e o `angularCompilerOptions` estiver com `strictTemplates: true` .
O código foi alterado e não apresenta mais os erros de compilação.
**Simulação**
Pode ser feita no portal.
> docs(page-dynamic-table): ajusta código do componente com opção strict

- projects/templates/src/lib/components/po-page-dynamic-detail/samples/sample-po-page-dynamic-detail-user/sample-po-page-dynamic-detail-user.component.html
A propriedade `strictTemplates` já vem configurado como `true` na versão atual do Angular e desta forma o exemplo apresenta erro de compilação.
Fixes #1257
**Page Dynamic Detail**
**1257**
O exemplo está informando desta forma:
```
<po-page-dynamic-detail
p-auto-router
p-title="Detail"
[p-actions]="actions"
[p-breadcrumb]="breadcrumb"
[p-service-api]="serviceApi"
>
</po-page-dynamic-detail>
```
Deve ser informado desta forma:
```
<po-page-dynamic-detail
[p-auto-router]="true"
p-title="Detail"
[p-actions]="actions"
[p-breadcrumb]="breadcrumb"
[p-service-api]="serviceApi"
> …
```
> docs(page-dynamic-detail): ajusta propriedade p-auto-router com strict

- projects/ui/src/lib/components/po-gauge/samples/sample-po-gauge-basic/sample-po-gauge-basic.component.html
A propriedade `strictTemplates` já vem configurado
como `true` na versão atual do Angular e desta forma
o exemplo apresenta erro de compilação.
Fixes #1255
**Gauge**
**1255**
O exemplo atual declara o `p-value` da seguinte forma `<po-gauge p-value="50"></po-gauge>` e apresenta erro caso o `angularCompilerOptions` estiver da seguinte forma `strictTemplates: true` .
Foi alterado a declaração do p-value para <po-gauge [p-value]="50"></po-gauge> e não apresenta erro caso o angularCompilerOptions estiver da seguinte forma strictTemplates: true .
**Simulação**
Pode ser feita no próprio portal.
> docs(gauge): ajusta a propriedade `p-value` com a opção strict

- projects/ui/ng-package.json
- projects/ui/package.json
**BUILD**
**DTHFUI-6180**
Ao iniciar um novo projeto em angular e adicionar a biblioteca de componentes do Po-UI, é apresentado um erro na execução por falta da dependência @angular/cdk/scrolling.
Dependência foi incluída no projeto do UI.
**Simulação**
Criar um novo projeto angular seguindo os primeiros passos no portal.
Primeiros passos: https://po-ui.io/guides/getting-started
> fix(build): adiciona a dependencia do cdk

- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.ts
- projects/ui/src/lib/utils/util.spec.ts
- projects/ui/src/lib/utils/util.ts
**Datepicker**
**DTHFUI-5990**
Ao selecionar uma data através do componente po-datepicker, a data que é aplicada é a do dia anterior ao selecionado.
A data selecionada deve ser a mesma data aplicada no model do componente, independente da localização, do fuzo e horário de inverno e verão.
**Simulação**
Alterar Data e Hora do computador local para o fuso de Lisboa.
Importante testar com datas do fuso de inverno da europa, que é o fuso diferente do atual que é o de verão. Exemplo de mês é o fevereiro. Na issue tem a descrição completa dos períodos de inverno e verão. …
> fix(datepicker): corrige data independente do fuso

- projects/ui/src/lib/components/po-table/po-table.component.html
**TABLE**
**DTHFUI-6088**
O botão do gerenciador de colunas não está acessível para leitores de tela pois não possuí texto, apenas o ícone de uma engrenagem.
O botão está acessível pois foi inserido o atributo `aria-label` para que os leitores de tela possam identificar a coluna.
**Simulação**
Executar no app ou no portal.
[app.zip](https://github.com/po-ui/po-angular/files/8863744/app.zip)
> feat(table): inclui acessibilidade no gerenciador

- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
Alinha colunas do header quando a tabela possui `p-height`
**Table**
**DTHFUI-6095**
colunas da tabela estão ficando desalinhada quando possui p-height
colunas da tabela estão ficando alinhadas quando possui p-height
**Simulação**
utilizar app e testar samples do portal:
[app.zip](https://github.com/po-ui/po-angular/files/8846442/app.zip)
> fix(table): alinha colunas do header

- projects/ui/src/lib/components/po-field/index.ts
- projects/ui/src/lib/components/po-field/po-field.module.ts
- projects/ui/src/lib/components/po-field/po-radio/po-radio-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-radio/po-radio-base.component.ts
- projects/ui/src/lib/components/po-field/po-radio/po-radio-size.enum.ts
- projects/ui/src/lib/components/po-field/po-radio/po-radio.component.html
- projects/ui/src/lib/components/po-field/po-radio/po-radio.component.spec.ts
- projects/ui/src/lib/components/po-field/po-radio/po-radio.component.ts
**RADIO**
**DTHFUI-6067**
Não existe componente interno de input Radio.
Cria componente interno input Radio baseado nas definições do AnimaliaDS.
**Simulação**
```html
<po-radio p-label="Po Radio" p-disabled="true" [p-checked]="true"></po-radio>
<po-radio p-label="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin et semper diam. Sed porta nisi id pellentesque lacinia. Pellentesque bibendum tellus quis tortor elementum, id pellentesque erat tincidunt. Morbi ut accumsan libero, sed pellentesque orci. Vivamus sollicitudin pellentesque turpis, id vehicula nisl ornare et. Ut …
```
> feat(radio): cria novo componente po-radio

- projects/ui/src/lib/components/po-field/po-radio/po-radio-base.component.ts
- projects/ui/src/lib/components/po-field/po-radio/po-radio.component.ts
**RADIO**
**DTHFUI-6233**
Método `changeModelValue` do componente base está com a tipagem do parâmetro diferente do componente. 
`po-radio-base.component.ts`
> protected abstract changeModelValue(value: boolean | null);
`po-radio.component.ts`
> protected changeModelValue(value: boolean | string) { ... }
Ajustada a tipagem do método.
`po-radio-base.component.ts`
> protected abstract changeModelValue(value: boolean | string);
`po-radio.component.ts`
> protected changeModelValue(value: boolean | string) { ... }
**Simulação**
Portal e novo projeto em angular utilizando o PO-UI.
> fix(radio): ajuste no `po-radio`

- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
po-combo.component.ts, po-combo-base.component.ts
#1292 
O valor do input digitado só acessível ao escopo do po-combo
O valor do input digitado é emitido através do output "p-input-change"
**Simulação**
Ao ser digitado alguma tecla o valor é emito para o output "p-input-change", somente quando nenhum "p-filter-service" for definido
> feat(combo): adicionado um output para o input search do combo

- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
**TABLE**
**DTHFUI-6170**
O botão "Carregar mais resultados" está sendo cortado utilizando o PoLookup.
O botão "Carregar mais resultados" está sendo exibido corretamente.
**Simulação**
Testar o App abaixo e no Portal.
```html
<po-lookup
name="lookup"
[p-multiple]="true"
>
</po-lookup>
<po-table p-service-api="https://po-sample-api.herokuapp.com/v1/heroes" p-height="300"> </po-table>
<po-lookup
name="lookup" …
```
> fix(table): ajusta o calculo de altura da tabela

- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-list-base.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.html
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
**DYNAMIC-TABLE**
**DTHFUI-6173**
Não era possível utilizar os eventos `p-restore-column-manager`, `p-change-visible-columns` e `p-sort-by` da PoTable através do PoDynamicTable.
Agora é possível utilizar os eventos `p-restore-column-manager`, `p-change-visible-columns` e `p-sort-by` da PoTable através do PoDynamicTable.
**Simulação**
Utilizar este [app.zip](https://github.com/po-ui/po-angular/files/9004008/app.zip) e testar no Portal.
> feat(dynamic-table): permite disparar evento de restaurar padrão

- projects/ui/src/lib/services/po-notification/po-toaster/po-toaster.component.html
- projects/ui/src/lib/services/po-notification/po-toaster/po-toaster.component.spec.ts
- projects/ui/src/lib/services/po-notification/po-toaster/po-toaster.component.ts
**Toaster**
**DTHFUI-6203**
O toaster não se ajusta corretamente em pequenas resoluções.
O toaster se ajusta conforme definição de UX para pequenas resoluções.
**Simulação**
Testar app no navegador em resolução mobile.
[app.zip](https://github.com/po-ui/po-angular/files/9014787/app.zip)
PR STYLE > https://github.com/po-ui/po-style/pull/320
> feat(toaster): implementa para pequenas resoluções

- projects/templates/src/lib/components/po-page-dynamic-edit/samples/sample-po-page-dynamic-edit-user/sample-po-page-dynamic-edit-user.component.html
A propriedade `strictTemplates` já vem configurado como `true`  na versão atual do Angular e desta forma o exemplo apresenta erro de compilação.
Fixes #1262
**1262**
O exemplo está informando desta forma:
```
<po-page-dynamic-edit
p-auto-router
p-title="User edit"
[p-actions]="actions"
[p-breadcrumb]="breadcrumb"
[p-service-api]="serviceApi"
>
</po-page-dynamic-edit>
```
Deve ser informado desta forma:
```
<po-page-dynamic-edit
[p-auto-router]="true"
p-title="User edit"
[p-actions]="actions"
[p-breadcrumb]="breadcrumb"
[p-service-api]="serviceApi"
> …
```
> docs(page-dynamic-edit): ajusta propriedade p-auto-router com strict

- projects/ui/src/lib/components/po-dynamic/po-dynamic-field-force-component.enum.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.ts
**DTHFUI-6251**
O dynamic-form caso tenha mais de 4 options será um multiselect e se tiver menos será um radio-group
Podemos forçar se será um select ou radio-group utilizando a propriedade `forceOptionsComponentType`
**Simulação**
app: [app.zip](https://github.com/po-ui/po-angular/files/9063843/app.zip)
> feat(dynamic-form): permite escolher componente a ser renderizado

- .eslintrc.json
**LINT**
**DTHFUI-6274**
Com a atualização dos pacotes do projeto, acabou quebrando as regras de lint, por mudança no comportamento dos mesmos.
Foi ajustada a configuração para que o lint continue funcionando como funcionava antes da atualização.
**Simulação**
Executar `npm run lint`
> build(lint): ajusta regras após atualização de pacote

- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
**TABLE**
**DTHFUI-6154**
Ao utilizar a PoTable dentro de uma PoTab.
Caso o navegador seja redimensionado a tabela que está na guia inativa perderá o tamanho do conteúdo no head da coluna.
Ao utilizar a PoTable dentro de uma PoTab.
Caso o navegador seja redimensionado a tabela que está na guia inativa não perderá o tamanho do conteúdo no head da coluna.
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/9074641/app.zip)
**STYLE**
https://github.com/po-ui/po-style/pull/324
> fix(table): corrige quebra de colunas

- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-base.component.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.component.html
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.component.spec.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.component.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text.component.html
- projects/ui/src/lib/components/po-field/po-rich-text/samples/sample-po-rich-text-labs/sample-po-rich-text-labs.component.html
- projects/ui/src/lib/components/po-field/po-rich-text/samples/sample-po-rich-text-labs/sample-po-rich-text-labs.component.ts
- projects/ui/src/lib/services/po-notification/po-notification-base.service.spec.ts
**RICH-TEXT**
**DTHFUI-5598**
Componente não permite desativar os botões de alinhamento de texto.
Componente permite desativar os botões de alinhamento de texto.
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/9145088/app.zip)
**Styles**
https://github.com/po-ui/po-style/pull/327
> feat(rich-text): adiciona `p-disabled-text-align`

- projects/ui/src/lib/components/po-dynamic/index.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-field-force-component.enum.ts
Ocorre um erro ao importar o enum ForceOptionComponentEnum
o Enum foi exportado e o erro não ocorre mais
**Simulação**
Simular em um aplicação apartada.
> fix(dynamic-form): exporta ForceOptionComponentEnum

- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.ts
- projects/ui/src/lib/utils/util.spec.ts
- projects/ui/src/lib/utils/util.ts
**DATEPICKER**
**DTHFUI-6215**
Atualmente o componente apresenta uma falha ao ser utilizado em países com horário de verão e fuso diferente.
Ao selecionar uma data fora do horário de verão, a data era convertida para o dia anterior a data selecionada.
Ex:
Data selecionada: 22/02/2022
Data registrada: 21/02/2022
O componente passou a verificar se a data selecionada esta dentro do horário de verão, convertendo corretamente.
**Simulação**
app e portal
[app.zip](https://github.com/po-ui/po-angular/files/9170288/app.zip)
> fix(datepicker): corrige funcionamento com fuso

- docs/guides/migration-poui.md
Inclui trecho de documentação que orienta em caso de erro no console ao executar o ng update do @po-ui/ng-components
> docs(migration): orienta em caso de erro

- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-filters.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-list-base.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-list-base.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.component.html
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.component.ts
**po-page-dynamic-table**
**Fixes #1287**
No template Page Dynamic Table não é possível ocultar filtros no filtro avançado como é possível com o Page Dynamic Search através da propriedade visible. No Page Dynamic Table a propriedade visible é utilizada apenas na table e todos os fields com propriedade filter:true são repassadas para o Page Dynamic Search como visible:true.
Foi criada a propriedade fixed na interface PoPageDynamicTableFilters que será usada em conjunto com as propriedades
filter e initValue, com o objetivo de ocultar o filtro na tela de filtro avançado, porém, mantendo o filtro na consulta das informações. …
> feat(page-dynamic-table): adiciona propriedade para fixar filtros

- projects/templates/src/lib/components/po-page-login/po-page-login-base.component.ts
Quando a propriedade `p-authentication-url` está ativada, não existe `loading` automático durante a autenticação pela API do backend.
Fixes #1350
**Page Login**
**1350**
Quando a propriedade `p-authentication-url` está ativada, não existe `loading` automático durante a autenticação pela API do backend e se houver um pequena demora o usuário fica sem saber se a autenticação está sendo realizada ou não.
Quando a propriedade `p-authentication-url` está ativada, existe `loading` automático durante a autenticação pela API do backend e se houver um pequena demora o usuário fica sabendo que e a autenticação está sendo realizada. …
> feat(page-login): adiciona `loading` automático com `p-authentication-url`

- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
**TABLE**
**DTHFUI-6153**
Ao utilizar a tabela com uma altura dinamica o gerenciador de colunas para de funcionar após alterar a altura da tabela.
Ao utilizar a tabela com uma altura dinamica o gerenciador de colunas permanece funcionando mesmo após alterar a altura da tabela.
**Simulação**
Portal
> fix(table): corrige o gerenciador de colunas

- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.ts
**multiselect**
**DTHFUI-6085**
multiselect faz requisição desnecessária quando utilizado em um dynamic-form
multiselect não faz requisição desnecessária quando utilizado em um dynamic-form
**Simulação**
app:
[app.zip](https://github.com/po-ui/po-angular/files/9242566/app.zip)
> fix(multiselect): corrige chamada de api

- projects/ui/src/lib/components/po-breadcrumb/po-breadcrumb-dropdown/po-breadcrumb-dropdown.component.html
**BREADCRUMB**
**DTHFUI-6341, #1325**
A função de Action/link não é executada quando a label é muito longa e a tela é pequena transformando a label em um ícone de '...'
A função de Action/link é executada quando a label é muito longa e a tela é pequena transformando a label em um ícone de '...'
**Simulação**
Utilizar o sample do Portal ou este [app.zip](https://github.com/po-ui/po-angular/files/9245795/app.zip).
> fix(breadcrumb): ajusta execução de action

- projects/ui/src/lib/components/po-field/po-select/po-select.component.html
- projects/ui/src/lib/components/po-field/po-select/po-select.component.spec.ts
- projects/ui/src/lib/components/po-field/po-select/po-select.component.ts
- projects/ui/src/lib/components/po-field/po-select/samples/sample-po-select-companies/sample-po-select-companies.component.html
- projects/ui/src/lib/components/po-field/po-select/samples/sample-po-select-companies/sample-po-select-companies.component.ts
- projects/ui/src/lib/utils/util.spec.ts
- projects/ui/src/lib/utils/util.ts
**SELECT**
**DTHFUI-6091**
Componente não possui as propriedades ` p-field-value` e `p-field-label` 
Componente passa a ter novas propriedades ` p-field-value` e `p-field-label`
**Simulação**
Rodar build do portal e testar sample `PO Select Companies`
> feat(select): adiciona ` p-field-value` e `p-field-label`

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.html
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/services/po-lookup-modal.service.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/services/po-lookup-modal.service.ts
**LOOKUP**
**DTHFUI-6214**
Não era possível utilizar os eventos `p-restore-column-manager` e `p-change-visible-columns` dentro do Lookup.
É possível utilizar os eventos `p-restore-column-manager` e `p-change-visible-columns` dentro do Lookup.
**Simulação**
Utilizar o APP abaixo e testar nos samples do Portal.
```html
<po-lookup
name="lookup"
(p-restore-column-manager)="restoreColumnManager($event)"
(p-change-visible-columns)="changeVisibleColumns($event)"
> …
```
> feat(lookup): repassa eventos do po-table

- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
**TABLE**
**DTHFUI-5959**
Ao clicar em qualquer lugar da linha da table, ela é selecionada.
Agora é possível habilitar e desabilitar a seleção quando houver clique na linha utilizando a propriedade ` p-selectable-entire-line`.
**Simulação**
Simular no portal e utilizar este [app.zip](https://github.com/po-ui/po-angular/files/9282931/app.zip).
> feat(table): adiciona ` p-selectable-entire-line`

- projects/portal/src/app/home/home.component.html
- projects/portal/src/app/tools/tools-dynamic-form/tools-dynamic-form.component.html
- projects/portal/src/app/tools/tools-dynamic-view/tools-dynamic-view.component.html
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.html
- projects/ui/src/lib/components/po-button-group/po-button-group-base.component.ts
- projects/ui/src/lib/components/po-button-group/samples/sample-po-button-group-labs/sample-po-button-group-labs.component.html
- projects/ui/src/lib/components/po-button-group/samples/sample-po-button-group-labs/sample-po-button-group-labs.component.ts
- projects/ui/src/lib/components/po-button-group/samples/sample-po-button-group-post/sample-po-button-group-post.component.html
- projects/ui/src/lib/components/po-button/po-button-base.component.spec.ts
- projects/ui/src/lib/components/po-button/po-button-base.component.ts
- projects/ui/src/lib/components/po-button/po-button-size.enum.ts
- projects/ui/src/lib/components/po-button/po-button.component.html
- projects/ui/src/lib/components/po-button/samples/sample-po-button-labs/sample-po-button-labs.component.html
- projects/ui/src/lib/components/po-button/samples/sample-po-button-labs/sample-po-button-labs.component.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.component.html
- projects/ui/src/lib/components/po-list-view/po-list-view.component.html
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.html
**BUTTON**
**DTHFUI-6022**
**DTHFUI-6353**
O componente `po-button` não possuí uma propriedade para aumentar o tamanho do botão.
O componente possuí a propriedade `p-small` para diminuir o tamanho do botão.
Adicionada a propriedade `p-size` para definir o tamanho do botão, permitindo alternar entre os valores `medium` ou `large`.
Deprecia a propriedade `p-small` para seguir com as definições do AnimaliaDS e as regras de acessibilidade.
**Simulação**
app e portal.
[app.zip](https://github.com/po-ui/po-angular/files/9268614/app.zip)
**Style**
https://github.com/po-ui/po-style/pull/331
**Theme Totvs** …
> feat(button): adiciona a propriedade `p-size` e deprecia a propriedade `p-small`

- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.html
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-scheduling/sample-po-combo-scheduling.component.html
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-scheduling/sample-po-combo-scheduling.component.ts
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-scheduling/sample-po-combo-scheduling.service.ts
**Combo**
**DTHFUI-6127**
não permite usar o `p-options` com `any` com `p-field-value` e `p-field-label`
permite usar o `p-options` com `any` com `p-field-value` e `p-field-label`
**Simulação**
app:
[app.zip](https://github.com/po-ui/po-angular/files/9309160/app.zip)
e samples do portal
> feat(combo): permite usar o `p-options` com `any`

- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range-base.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range.component.html
- projects/ui/src/lib/components/po-field/po-datepicker-range/samples/sample-po-datepicker-range-labs/sample-po-datepicker-range-labs.component.html
- projects/ui/src/lib/components/po-field/po-datepicker-range/samples/sample-po-datepicker-range-labs/sample-po-datepicker-range-labs.component.ts
Adiciona propriedade `locale` para definir o idioma a ser exibido pelo componente `po-datepicker-range`.
Fixes #1041
**Datepicker**
**1041**
O componente não recebe a propriedade `locale`, referente ao idioma exibido.
É possível definir o idioma do componente através da propriedade `locale`
**Simulação**
Simular através do portal ou pelo [App](https://github.com/po-ui/po-angular/files/9244390/app.zip).
> feat(datepicker-range): adiciona a propriedade `locale`

- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.ts
A mudança de estado já ocorre no evento `eventOnBlur` e foi incluído também no evento `dateSelected` devido a ordem dos disparos dos eventos no programa `po-dynamic-form-fields.component.ts`:
1. Quando a data é informada manualmente e depois teclado "TAB" o evento `eventOnBlur` ocorre antes do evento `onChangeField`.
2. Quando a data é escolhida através do ícone/calendário e depois teclado "TAB", o evento `eventOnBlur` ocorre depois do
evento `onChangeField`.
Na segunda situação o evento `validate` do componente `page-dynamic-edit` não é disparado, porque a mudança de estado só ocorrerá no evento `eventOnBlur`.
Fixes #1207
**Datepicker**
**1207**
O …
> feat(datepicker): ativa mudança de estado também no evento `dateSelected`

- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.ts
**Table**
** DTHFUI-6380**
Ao interagir com o gerenciador de colunas o icone fica com a aparencia de desabilitado mesmo se estiver com ordenador selecionado
Ao interagir com o gerenciador de colunas o icone não fica com a aparencia de desabilitado
**Simulação**
Samples do portal
> fix(table): corrige ícone de ordenação

- projects/ui/src/lib/components/po-accordion/po-accordion-item/po-accordion-item.component.spec.ts
- projects/ui/src/lib/components/po-accordion/po-accordion-item/po-accordion-item.component.ts
- projects/ui/src/lib/components/po-accordion/po-accordion.component.ts
- projects/ui/src/lib/components/po-accordion/services/po-accordion.service.spec.ts
- projects/ui/src/lib/components/po-accordion/services/po-accordion.service.ts
Closes #DTHFUI-6432.
**PoAccordionItem**
**DTHFUI-6432**
PoAccordionItem não possui eventos de alteração de estado expand/collapse.
Possível adicionar listeners aos eventos de expand e collapse.
**Simulação**
```html
<po-accordion>
<po-accordion-item
p-label="xyz"
(p-expand)="handleXyzExpand()"
(p-collapse)="handleXyzCollapse()"
>
po-accordion works
</po-accordion-item>
<po-accordion-item
p-label="abc"
(p-expand)="handleAbcExpand()"
(p-collapse)="handleAbcCollapse()"
>
po-accordion works
</po-accordion-item>
</po-accordion>
```
```ts
@Component({
templateUrl: …
```
> feat(accordion-item): adding outputs to expand and collapse events

- projects/ui/src/lib/components/po-button-group/po-button-group.component.html
Foi realizado um ajuste para que o valor da propriedade `selected` seja atribuído antes da chamada da propriedade `action`.
Fixes #1234
**Button Group**
**1234**
A ação atribuída ao botão está sendo executada antes das alterações na propriedade `selected`, fazendo com que o valor esteja sempre um passo atrás do que será exibido na tela.
A ação atribuída ao botão é executada após as alterações na propriedade `selected`, para que, ao acessar esta propriedade, os valores estejam condizentes com o que aparecerá na tela.
**Simulação**
Segue o [App](https://github.com/po-ui/po-angular/files/8587124/app.zip) para a simulação.
> fix(button-group): ajusta `selected` para ocorrer antes de `action`

- projects/ui/src/lib/components/po-tree-view/po-tree-view-base.component.spec.ts
- projects/ui/src/lib/components/po-tree-view/po-tree-view-base.component.ts
**Tree-view**
**DTHFUI-6307**
ao selecionar um item de uma arvore, outra arvore pai é expandida caso contenha filhos expandidos
ao selecionar um item de uma arvore, outra arvore pai não é expandida caso contenha filhos expandidos
**Simulação**
Testar no labs do portal e app:
[app.zip](https://github.com/po-ui/po-angular/files/9536553/app.zip)
> fix(tree-view): corrige funcionamento inadequado

- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-filter.interface.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-filter.service.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-search/po-multiselect-search.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/samples/sample-po-multiselect-any-array/sample-po-multiselect-any-array.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/samples/sample-po-multiselect-any-array/sample-po-multiselect-any-array.component.ts
**DTHFUI-6128**
Não permite usar o `p-options` com `any` com `p-field-value` e `p-field-label`
Permite usar o `p-options` com `any` com `p-field-value` e `p-field-label`
**Simulação**
Utilizar este  [app.zip](https://github.com/po-ui/po-angular/files/9492109/app.zip)  e o Sample no Portal.
> feat(multiselect): permite usar o `p-options` com `any`

- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
**DTHFUI-6424**
O componente não emite o change quando removemos a ultima seleção ativa dos itens na lista, impactando a emissão do validate no DynamicFormField.
Foi ajustado a emissão do change sempre que removermos qualquer seleção ativa dos itens na lista, ajustando o problema de emitir o validate usando o DynamicFormField
**Simulação**
Utilizar o seguinte [App.zip](https://github.com/po-ui/po-angular/files/9560713/app.zip) e os Samples do Portal
> fix(multiselect): corrige emissão de evento pela listagem

- docs/guides/migration-poui.md
no Guia Migração do PO UI o pacote @po-ui/ng-components está escrito
com grafia errada, possuindo a letra "e" a mais gerando erro na instalação.
**Guia Migração do PO UI**
No Guia Migração do PO UI o pacote @po-ui/ng-components está escrito com grafia errada, possuindo a letra "e" o que gera erro na instalação.
Corrigida a grafia no nome do pacote.
**Simulação**
> docs(guia de migração do PO-UI): corrige o nome da dependência

- projects/ui/src/lib/components/po-field/po-textarea/po-textarea-base.component.ts
- projects/ui/src/lib/components/po-field/po-textarea/po-textarea.component.html
**TEXTAREA**
**DTHFUI-6442**
O componente não apresenta o estilo definido pelo design system e não segue as regras de acessibilidade.
O componente apresenta novo estilo definido pelo design system e segue as regras de acessibilidade.
**Simulação**
Simular no [app.zip](https://github.com/po-ui/po-angular/files/9538860/app.zip) e no portal.
https://github.com/po-ui/po-style/pull/340
https://github.com/totvs/po-theme-totvs/pull/176
Varíaveis customizadas
```css
po-textarea {
--font-family: "Comic Sans MS", "Comic Sans", cursive;
--font-size: .5 rem;
--text-color-placeholder: red;
--color:navy;
--background: green; …
```
> feat(textarea): aplica estilo e acessibilidade definidos pelo DS

- projects/ui/src/lib/components/po-button-group/po-button-group-base.component.ts
**BUTTON-GROUP**
**N/A**
Na documentação do button-group estava informando que deveria ser utilizado os valores do enum `PoMultiselectFilterMode`, porém o componente espera que sejam utilizados os valores do enum `PoButtonGroupToggle`
Foi ajustada a documentação informando utilizar os valores do enum `PoButtonGroupToggle`.
**Simulação**
Verificar documentação no Portal
> docs(button-group): corrige enum na documentação

- projects/ui/src/lib/components/po-table/po-table-detail/po-table-detail.component.html
- projects/ui/src/lib/components/po-table/po-table-detail/po-table-detail.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-detail/po-table-detail.component.ts
Quando a propriedade `detail` tem uma coluna do tipo `array`, o conteúdo não é exibido, por exemplo `product.productName`.
Fixes #1328
**Table**
**1328**
Quando a propriedade `detail` tem uma coluna do tipo `array`, o conteúdo não é exibido, por exemplo `product.productName`.
Quando a propriedade `detail` tem uma coluna do tipo `array`, o conteúdo é exibido, por exemplo `product.productName`.
**Simulação**
Pode usar este [App](https://github.com/po-ui/po-angular/files/9192264/app.zip).
> feat(table): exibe coluna tipo `array` em linha tipo `detail`

- projects/ui/src/lib/components/po-table/po-table.component.html
**TABLE**
**DTHFUI-6545**
Os eventos `p-selected` e `p-unselected` estavam sendo chamados simultaneamente.
Foi ajustado e agora os eventos `p-selected` e `p-unselected` estão sendo chamados no momento certo.
**Simulação**
Testar o seguinte [App.zip](https://github.com/po-ui/po-angular/files/9657015/app.zip)
> fix(table): ajusta eventos sendo executados simultaneamente

- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.component.spec.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.component.ts
**RICH-TEXT**
**DTHFUI-6454**
O componente `po-rich-text` não está aplicando o efeito de botão pressionado nos botões de alinhamento.
O componente `po-rich-text` está aplicando o efeito de botão pressionado nos botões de alinhamento.
**Simulação**
[app_rich-text_DTHFUI-6454.zip](https://github.com/po-ui/po-angular/files/9658549/app_rich-text_DTHFUI-6454.zip)
**Style**
[PO-STYLE](https://github.com/po-ui/po-style/pull/346)
> fix(rich-text): ajustes na toolbar

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/samples/sample-po-dynamic-form-register/sample-po-dynamic-form-register.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/samples/sample-po-dynamic-form-register/sample-po-dynamic-form-register.service.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/samples/sample-po-dynamic-view-employee/sample-po-dynamic-view-employee.component.ts
**DYNAMIC-FORM**, **DYNAMIC-VIEW**
**DTHFUI-6453**
Dynamic-view: não é possível personalizar as cores do componente `po-tag`.
Dynamic-form: não é possível que componentes `po-combo`, `po-select` e `po-multiselect` utilizem um Array<any> como opções para serem exibidas, bem como utilizar as propriedades fieldLabel e fieldValue.
Dynamic-view: agora é permitido personalizar as cores do componente `po-tag`.
Dynamic-form: agora os componentes `po-combo`, `po-select` e `po-multiselect` podem utilizar um Array<any> como opções para serem exibidas, bem como utilizar as propriedades fieldLabel e fieldValue.
**Simulação**
Testar nos …
> feat(dynamic): repasse de propriedades, permite uso de Array<any> no options e personalização de cores do `po-tag`

- projects/ui/src/lib/components/po-field/index.ts
- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox-base.component.ts
- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox-size.enum.ts
- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox.component.html
- projects/ui/src/lib/components/po-field/po-checkbox/samples/sample-po-checkbox-labs/sample-po-checkbox-labs.component.html
- projects/ui/src/lib/components/po-field/po-checkbox/samples/sample-po-checkbox-labs/sample-po-checkbox-labs.component.ts
**CHECKBOX**
**DTHFUI-6452**
Componente não possuía propriedade para alterar o size do checkbox.
Agora é possível escolher o `p-size` entre os tamanhos `medium` e `large`.
**Simulação**
Testar no Labs do Portal e pelo [App.zip](https://github.com/po-ui/po-angular/files/9599381/app.zip)
https://github.com/po-ui/po-style/pull/343
> feat(checkbox): adiciona propriedade `p-size`

- projects/ui/src/lib/services/po-language/po-language.service.ts
Foi adicionado a limpeza das variáveis do `localStorage`:
- `PO_DEFAULT_LANGUAGE`
- `PO_USER_LOCALE`
Estas variáveis são populadas pelas funções:
- `languageDefault`.
- `setLanguage`.
A limpeza é necessária quando se deixa de usar as funções acima, evitando uso de valores indevidos.
Fixes #1331
**Language**
**1331**
O serviço não está carregando o idioma correto, quando se usa as funções `languageDefault` e ou `setLanguage` e depois deixa  de usar, assim os valores ficam gravados indevidamente na `localStorage`, impedindo a verificação do idioma do navegador
O serviço esta carregando o idioma do navegados, quando as funções …
> fix(language): adiciona limpeza das variáveis do `localStorage`

- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-base.component.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-base.component.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.html
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.ts
O componente po-page-job-scheduler tem internamente um po-stepper o qual a orientação é definida pela largura da tela. Adiciona a propriedade orientation para que o componente possa receber uma orientação definida e assim aproveitar melhor o espaço em tela para casos específicos.
**po-page-job-scheduler**
**#1418**
O componente po-page-job-scheduler tem internamente um po-stepper o qual a orientação é definida pela largura da tela. 
Com a propriedade p-orientation o componente podereceber uma orientação definida ('horizontal' ou 'vertical') e assim aproveitar melhor o espaço em tela para casos específicos.
> feat(page-job-scheduler): adiciona a propriedade p-orientation

- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-field.interface.ts
- projects/ui/src/lib/components/po-field/po-lookup/interfaces/po-lookup-column.interface.ts
- projects/ui/src/lib/components/po-table/interfaces/po-table-column.interface.ts
- projects/ui/src/lib/components/po-table/po-table-detail/po-table-detail-column.interface.ts
**Table / Lookup / Dynamic View**
**#1355**
Documentação incorretamente indicava o uso de `mm` para a formatação de mês.
A documentação recomenda apenas o uso de `MM` para o formato de mês.
**Simulação**
Verificar se todas as referencias de `mm` para formato de mês foram removidas da documentação
> docs(table): corrige documentação das colunas para o formato MM

- projects/ui/src/lib/components/po-field/po-select/po-select.component.spec.ts
- projects/ui/src/lib/components/po-field/po-select/po-select.component.ts
Foi ajustado o `OnTouched` para que o evento `change` seja disparado corretamente, pois o mesmo só é disparado após o campo ser tocado.
Fixes #1378, DTHFUI-6477
**1378**
O evento `change` não dispara quando o combo é o primeiro campo a ser tocado e alterado
O evento `change` dispara quando o combo for tocado e alterado independente da ordem de alteração dos campos.
**Simulação**
Pode ser feita pelo portal ou pelo [APP](https://github.com/po-ui/po-angular/files/9427473/app.zip).
> fix(select): ajusta o `OnTouched` do campo

- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search-literals.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.html
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
**PAGE-DYNAMIC_TABLE**
**PAGE-DYNAMIC-SEARCH**
**DTHFUI-5714**
Atualmente ao realizar uma pesquisa, a requisição é feita com o parâmetro 'search'.
Ao realizar uma pesquisa, a requisição é feita com o parâmetro 'search' mas pode ser customizada através da propriedade `p-quick-search-param`.
Adicionada a propriedade `p-literals` que permite a customização de textos.
**Simulação**
[app_page-dynamic-table_DTHFUI-5714.zip](https://github.com/po-ui/po-angular/files/9686159/app_page-dynamic-table_DTHFUI-5714.zip)
> feat(dynamic-table): altera filtro de pesquisa

- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/services/po-lookup-modal.service.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/services/po-lookup-modal.service.ts
**< LOOKUP >**
**< DTFUI-6537 >**
Não é possível restaurar o padrão das colunas no gerenciador de colunas dentro do po-lookup.
É possível restaurar o padrão das colunas do gerenciador dentro do po-lookup mantendo a visibilidade das alterações.
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/9779154/app.zip)
> fix(lookup):  corrige comportamento do gerenciador de colunas no po-lookup

- projects/ui/src/lib/components/po-breadcrumb/samples/sample-po-breadcrumb-labs/sample-po-breadcrumb-labs.component.html
Troca a url base das API's do po-breadcrumb devido a 
mudança de servidor do projeto po-sample-api
Fixes #1436
**po-breadcrumb**
**#1436**
A url base das API's do componente estão apontando para o servidor do heroku.
A url base das API's do componente passam a apontar agora para o servidor do fly.io.
> docs(breadcrumb): atualiza url base da API

- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-heroes-reactive-form/sample-po-combo-heroes-reactive-form.component.html
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-heroes-reactive-form/sample-po-combo-heroes-reactive-form.component.ts
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-heroes/sample-po-combo-heroes.component.html
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-heroes/sample-po-combo-heroes.component.ts
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-hotels/sample-po-combo-hotels.component.html
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-infinity-scroll/sample-po-combo-infinity-scroll.component.html
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-infinity-scroll/sample-po-combo-infinity-scroll.component.ts
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-labs/sample-po-combo-labs.component.html
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-transfer/sample-po-combo-transfer.component.html
Troca a url base das API's do po-combo devido a
mudança de servidor do projeto po-sample-api
Fixes #1439
**po-combo**
**#1439**
A url base das API's do componente estão apontando para o servidor do heroku.
A url base das API's do componente passam a apontar agora para o servidor do fly.io.
> docs(combo): atualiza url base da API

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/samples/sample-po-dynamic-form-register/sample-po-dynamic-form-register.component.ts
Troca a url base das API's do po-dynamic-form devido a
mudança de servidor do projeto po-sample-api
Fixes #1437
**po-dynamic-form**
**#1437**
A url base das API's do componente estão apontando para o servidor do heroku.
A url base das API's do componente passam a apontar agora para o servidor do fly.io.
> docs(dynamic-form): atualiza url base da API

- projects/templates/src/lib/components/po-page-dynamic-edit/index.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/interfaces/po-page-dynamic-edit-literals.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/samples/sample-po-page-dynamic-edit-user/sample-po-page-dynamic-edit-user.component.html
- projects/templates/src/lib/components/po-page-dynamic-edit/samples/sample-po-page-dynamic-edit-user/sample-po-page-dynamic-edit-user.component.ts
Foi adicionado o parâmetro `p-literals` para customizar o rótulo dos botões de ação e o texto das mensagens.
Fixes #1321
**1321**
Não é possível renomear os botões de ação do componente.
É possível renomear os botões de ação do componente.
**Simulação**
Pode ser feita através do portal ou pelo [App](https://github.com/po-ui/po-angular/files/9660128/app.zip).
> feat(page-dynamic-edit): adiciona parâmetro `p-literals`

- projects/templates/src/lib/components/po-modal-password-recovery/samples/sample-po-modal-password-recovery-request/sample-po-modal-password-recovery-request.component.ts
Altera `urlRecovery` em `sample-po-modal-password-recovery-request.components.ts` 
de: 'https://po-sample-api.herokuapp.com/v1/user' para: 'https://po-sample-api.fly.dev/v1/users'.
Devido a mudança de servidor, do heroku para o fly.io.
Fixes #1429
**modal-password-recovery**
**#1429**
**Simulação**
> docs(modal-password-recovery): altera url base da API

- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.ts
Foi adicionado a lista completa de literais onde é possível customizar.
Foi também corrigido o nome do componente na documentação
Fixes #1470
**1470**
Os exemplos de customização dos literais não trazem a lista completa.
Foi adicionado na documentação a lista completa dos literais que podem ser customizados.
**Simulação**
Pode ser verificada no portal
> docs(page-dynamic-edit): ajusta a documentação do componente

- projects/ui/src/lib/components/po-field/po-multiselect/samples/sample-po-multiselect-heroes/sample-po-multiselect-heroes.service.ts
- projects/ui/src/lib/components/po-field/po-multiselect/samples/sample-po-multiselect-labs/sample-po-multiselect-labs.component.html
Foi alterado o servidor do projeto po-sample-api do heroku para o fly.io Este commit altera a url do antigo servidor para o atual fly.io
Fixes #1453
multiselect
#1453 
O exemplo se encontra utilizando o servidor antigo no Heroku
Alterado para o novo servidor Fly.io
**Simulação**
ng serve app e npm run build:portal && ng serve portal
> docs(multiselect): atualiza url base da API

- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-basic/sample-po-page-dynamic-table-basic.component.html
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-hotels/sample-po-page-dynamic-table-hotels.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-people/sample-po-page-dynamic-table-people.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-users/sample-po-page-dynamic-table-users.component.ts
Alteramos o servidor do projeto po-sample-api do heroku para o fly.io, portanto se faz necessário a troca da url base das API's.
Fixes #1433
**1433**
O projeto usa a API do po-sample-api do heroku.
O projeto passa a usar a API po-sample-api do fly.io.
**Simulação**
Pode ser feita no portal
> docs(page-dynamic-table): atualiza url base da API

- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-basic/sample-po-lookup-basic.component.html
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-labs/sample-po-lookup-labs.component.html
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-multiple/sample-po-lookup-multiple.component.html
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-multiple/sample-po-lookup-multiple.service.ts
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup.service.ts
Alteramos o servidor do projeto po-sample-api do heroku para o fly.io, portanto se faz necessário a troca da url base das API's.
Fixes #1452
**Lookup**
**1452**
O projeto usa a API po-sample-api do heroku,
O projeto vai usar a API po-sample-api do fly.io,
**Simulação**
Pode ser feita no portal
> docs(lookup): atualiza url base da API

- projects/ui/src/lib/components/po-field/po-select/samples/sample-po-select-customer-registration/sample-po-select-customer-registration.component.html
- projects/ui/src/lib/components/po-field/po-select/samples/sample-po-select-customer-registration/sample-po-select-customer-registration.service.ts
Altera o  `p-src` do `po-avatar` no componente `sample-po-select-customer-registration.component.html`
de: https://po-sample-api.herokuapp.com/v1/sampleSelect/{{ option.value }}.png
para: https://po-sample-api.fly.dev/v1/sampleSelect/{{ option.value }}.png
Altera a `url` do serviço `sample-po-select-customer-registration.service.ts` 
de: https://po-sample-api.herokuapp.com/v1/sampleSelect
para: https://po-sample-api.fly.dev/v1/sampleSelect
Devido a mudança de servidor do heroku para o fly.io.
Fixes https://github.com/po-ui/po-angular/issues/1454
po-select
https://github.com/po-ui/po-angular/issues/1454
**Simulação**
> docs(select): atualiza url base da API

- projects/templates/src/lib/components/po-page-dynamic-detail/samples/sample-po-page-dynamic-detail-user/sample-po-page-dynamic-detail-user.component.ts
Muda `serviceApi` para 'https://po-sample-api.fly.dev/v1/people'. Devido a mundaça de servidor para o fly.io.
Fixes #1431
**page-dynamic-edit**
**#1431**
**Simulação**
> docs(page-dynamic-detail): altera url base da API

- projects/templates/src/lib/components/po-page-login/samples/sample-po-page-login-automatic-service/sample-po-page-login-automatic-service.component.html
- projects/templates/src/lib/components/po-page-login/samples/sample-po-page-login-human-resources/sample-po-page-login-human-resources.component.ts
- projects/templates/src/lib/components/po-page-login/samples/sample-po-page-login-labs/sample-po-page-login-labs.component.html
Altera o `p-authentication-url` do componente `sample-po-page-login-automatic-service.component.html` 
de: https://po-sample-api.herokuapp.com/v1/users/authentication
para: https://po-sample-api.fly.dev/v1/users/authentication
Altera a propriedade `passwordRecovery.url` do componente  `sample-po-page-login-human-resources.component.ts`
de: https://po-sample-api.herokuapp.com/v1/users
para: https://po-sample-api.fly.dev/v1/users
Altera o `p-help` do `po-input` no componente  `sample-po-page-login-labs.component.html`
de: https://po-sample-api.herokuapp.com/v1/heroes
para: https://po-sample-api.fly.dev/v1/heroes
Devido a mudança de servidor do heroku para o fly.io.
Fixes https://github.com/po-ui/po-angular/issues/1435
po-page-login
https://github.com/po-ui/po-angular/issues/1435 …
> docs(page-login): atualiza url base da API

- projects/templates/src/lib/components/po-page-job-scheduler/samples/sample-po-page-job-scheduler-background-process/sample-po-page-job-scheduler-background-process.component.html
Alteração da `url` no componente `sample-po-page-job-scheduler-background-process.component.html `
de: https://po-sample-api.herokuapp.com/v1/scheduler
para: https://po-sample-api.fly.dev/v1/scheduler
Devido a mudança de servidor do heroku para o fly.io.
Fixes https://github.com/po-ui/po-angular/issues/1434
po-page-job-scheduler
https://github.com/po-ui/po-angular/issues/1434
**Simulação**
> docs(page-job-scheduler): atualiza url base da API

- projects/ui/src/lib/components/po-field/po-multiselect/samples/sample-po-multiselect-heroes/sample-po-multiselect-heroes.service.ts
- projects/ui/src/lib/components/po-field/po-multiselect/samples/sample-po-multiselect-labs/sample-po-multiselect-labs.component.html
Altera o `p-help` do `po-input` no componente `sample-po-multiselect-labs.component.html`
de: https://po-sample-api.herokuapp.com/v1/heroes
para: https://po-sample-api.fly.dev/v1/heroes
Altera API consumida no serviço `sample-po-multiselect-heroes.service.ts`
de: https://po-sample-api.herokuapp.com/v1/heroes
para: https://po-sample-api.fly.dev/v1/heroes
Devido a mudança de servidor do heroku para fly.io.
sample-po-multiselect
**Simulação**
> docs(sample-po-multiselect): atualiza URL base da API

- projects/portal/src/app/tools/tools-dynamic-form/tools-dynamic-form.component.ts
Altera o `serviceFields.help` no componente `tools-dynamic-form.component.ts`
de: https://po-sample-api.herokuapp.com/v1/heroes
para: https://po-sample-api.fly.dev/v1/heroes
Devido a mudança de servidor do heroku para fly.io.
po-tools-dynamic-form
**Simulação**
> docs(tools-dynamic-form): atualiza URL base da API

- projects/ui/src/lib/components/po-page/po-page-default/samples/sample-po-page-default-labs/sample-po-page-default-labs.component.html
Devido a alteração de servidor do po-sample-api do heroku para o fly.dev, é necessário mudar a url base da API
**sample-po-page-default-labs**
O valor da URL API Service é do antigo serviço de apis heroku.
O valor da URL API Service é do novo serviço de api: fly.dev
**Simulação**
Navegar até o exemplo do sample-po-page-default-labs
> docs(sample-po-page-default-labs): atualiza URL base da API

- projects/ui/src/lib/interceptors/po-http-request/samples/sample-po-http-request-interceptor-labs.component.html
Devido a alteração de servidor do po-sample-api do heroku para o fly.dev,  é necessário mudar a url base da API
**sample-po-http-request-interceptor-labs**
O valor da URL API Service é do antigo serviço de apis heroku.
O valor da URL API Service é do novo serviço de api: fly.dev
**Simulação**
Navegar até o exemplo do sample-po-http-request-interceptor-labs
> docs(sample-po-http-request-interceptor-labs): atualiza URL base da API

- projects/portal/src/app/app.component.ts
remove notification do hacktoberfest no fim do mês de outubro
**app-component**
Ao abrir a home do portal  PO-UI o componente exibe a notificação sobre o evento "PO UI + Hacktoberfest 2022".
A notificação não é exibida ao abrir o portal PO-UI
**Simulação**
Abrir o portal PO-UI
> refactor(portal): remove notification do Hacktoberfest

- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.ts
**< Po-upload >**
**< DTHFUI-6347 >**
o método clear (Método responsável por limpar os arquivos selecionados) não está limpando os arquivos do po-upload
Limpa os arquivos selecionados conforme o esperado quando utiliza o método clear()
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/9878916/app.zip)
> fix(upload): ajusta funcionamento do método clear

- projects/ui/src/lib/components/components.module.ts
- projects/ui/src/lib/components/index.ts
- projects/ui/src/lib/components/po-image/index.ts
- projects/ui/src/lib/components/po-image/po-image-base.component.spec.ts
- projects/ui/src/lib/components/po-image/po-image-base.component.ts
- projects/ui/src/lib/components/po-image/po-image.component.html
- projects/ui/src/lib/components/po-image/po-image.component.spec.ts
- projects/ui/src/lib/components/po-image/po-image.component.ts
- projects/ui/src/lib/components/po-image/po-image.module.ts
- projects/ui/src/lib/components/po-image/samples/sample-po-image-basic/sample-po-image-basic.component.html
- projects/ui/src/lib/components/po-image/samples/sample-po-image-basic/sample-po-image-basic.component.ts
- projects/ui/src/lib/components/po-image/samples/sample-po-image-labs/sample-po-image-labs.component.html
- projects/ui/src/lib/components/po-image/samples/sample-po-image-labs/sample-po-image-labs.component.ts
- projects/ui/src/lib/components/po-image/samples/sample-po-image-travel/sample-po-image-travel.component.html
- projects/ui/src/lib/components/po-image/samples/sample-po-image-travel/sample-po-image-travel.component.ts
**PO-IMAGE**
**DTHFUI-6612**
Não possui componente de image.
Criado componente de image seguindo as definições do AnimaliaDS.
**Simulação**
`html`
```
<po-image 
p-alt="teste de imagem" 
p-height="300"
[p-src]='srcImage' 
>
</po-image>
<po-image 
p-alt="teste de imagem" 
p-height="300"
[p-src]='srcImage' 
>
</po-image>
```
`TS`
```
@Component({
})
srcImage = 'https://images.unsplash.com/photo-1633409361618-c73427e4e206?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit …
```
> feat(image): novo componente po-image

- projects/ui/src/lib/components/po-dynamic/po-dynamic-field-type.enum.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/samples/sample-po-dynamic-form-register/sample-po-dynamic-form-register.component.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.component.ts
**DTHFUI-3223**
Não era possível utilizar o componente `po-upload` dentro do `po-dynamic-form`.
Agora é possível utilizar o componente `po-upload` dentro do `po-dynamic-form` junto com todas as suas propriedades.
**Simulação**
Verificar no Portal e utilizar o seguinte [App.zip](https://github.com/po-ui/po-angular/files/9873602/app.zip)
> feat(dynamic-form): adiciona po-upload

- projects/ui/src/lib/components/po-divider/index.ts
- projects/ui/src/lib/components/po-divider/po-divider-base.component.spec.ts
- projects/ui/src/lib/components/po-divider/po-divider-base.component.ts
- projects/ui/src/lib/components/po-divider/po-divider-size.enum.ts
- projects/ui/src/lib/components/po-divider/po-divider.component.html
- projects/ui/src/lib/components/po-divider/samples/sample-po-divider-labs/sample-po-divider-labs.component.html
- projects/ui/src/lib/components/po-divider/samples/sample-po-divider-labs/sample-po-divider-labs.component.ts
**divider**
**DTHFUI-6663**
**Simulação**
style: https://github.com/po-ui/po-style/pull/358
totvs: https://github.com/totvs/po-theme-totvs/pull/189
testar portal e app:
```
<po-divider></po-divider>
<po-divider p-border-width="small"></po-divider>
<po-divider p-border-width="medium"></po-divider>
<po-divider p-border-width="large"></po-divider>
<po-divider p-label="default"></po-divider>
<po-divider p-label="small" p-border-width="small"></po-divider>
<po-divider p-label="medium" p-border-width="medium"></po-divider>
<po-divider p-label="large" p-border-width="large"></po-divider>
```
custom: 
```
po-divider {
--color: red;
--stroke-linecap: square; …
```
> feat(divider): aplica estilo definido pelo DS

- docs/guides/sync-fundamentals.md
- docs/guides/sync-get-started.md
**SYNC**
**DTHFUI-6640**
Documentação aponta para heroku
Ajusta novo endereço do po-sample-conference após migração do heroku para fly.io
**Simulação**
Getting started do Portal
> docs(sync): ajusta novo endereço po-sample-conference

- projects/ui/src/lib/components/po-field/po-multiselect/samples/sample-po-multiselect-heroes/sample-po-multiselect-heroes.component.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-heroes/sample-po-table-heroes.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-heroes/sample-po-table-heroes.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-heroes/sample-po-table-heroes.service.ts
**TABLE**
**DTHFUI-6695**
Atualmente o PoTable não está atualizando os itens sem refresh.
Agora o PoTable atualiza os itens sem refresh.
**Simulação**
Simular nos Samples do Portal e utilizar este [App.zip](https://github.com/po-ui/po-angular/files/9974306/App.zip).
> fix(table): ajusta exibição de itens sem refresh

- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
fixes DTHFUI-6736
**dynamic-table**
**DTHFUI-6736**
Coloca valor `undefined` na requisicao quando nao passa valor no `p-quick-search-param`
Coloca valor padrão na requisicao quando nao passa valor no `p-quick-search-param`
**Simulação**
testar app, passando p-quick-search-param e sem passar o p-quick-search-param
[app.zip](https://github.com/po-ui/po-angular/files/9963943/app.zip)
> fix(dynamic-table): corrige valor `undefined` na requisicao

- projects/templates/src/lib/components/po-page-job-scheduler/index.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-execution/po-page-job-scheduler-execution.component.html
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-execution/po-page-job-scheduler-execution.component.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-parameters/index.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-parameters/po-job-scheduler-parameters-template/index.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-parameters/po-job-scheduler-parameters-template/po-job-scheduler-parameters-template.directive.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-parameters/po-job-scheduler-parameters-template/po-job-scheduler-parameters-template.directive.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-parameters/po-page-job-scheduler-parameters.component.html
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-parameters/po-page-job-scheduler-parameters.component.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.html
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.module.ts
Permite definir um componente para ser renderizado na etapa de parametrização através de template. As alterações são repassadas através da propriedade p-execution-parameter.
Fixes #1491
**po-page-job-scheduler**
**#1491**
Não é possível definir um componente personalizado na etapa de parametrização, somente renderizado o `po-dynamic-form` com as informações de fields ou com a url de parâmetros.
É possível passar um componente através de template, utilizando-se a diretiva `p-job-scheduler-parameters-template`. 
Para que o model do JobScheduler contenha os valores alterados no componente de template, deve ser repassado …
> feat(page-job-scheduler): adiciona funcionalidade de template na parametrização

- projects/templates/src/lib/components/po-page-dynamic-edit/samples/sample-po-page-dynamic-edit-basic/sample-po-page-dynamic-edit-basic.component.html
- projects/templates/src/lib/components/po-page-dynamic-edit/samples/sample-po-page-dynamic-edit-user/sample-po-page-dynamic-edit-user.component.ts
Muda `serviceApi` e propriedade `p-service-api` para 'https://po-sample-api.fly.dev/v1/people'.
Devido a mundaça de servidor para o fly.io.
Fixes #1432
**page-dynamic-edit**
**#1432**
**Simulação**
> docs(page-dynamic-edit): altera url base da API

- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.ts
- projects/ui/src/lib/services/po-language/po-language.constant.ts
- projects/ui/src/lib/services/po-language/po-language.interface.ts
- projects/ui/src/lib/services/po-language/po-language.service.spec.ts
- projects/ui/src/lib/services/po-language/po-language.service.ts
**poDatePicker**
**1506**
O separador do picture do locale russo para datas nao eh suportado
exemplo: mostra a data como 12/01/2022
O separador do picture do locale russo para datas  eh suportado
exemplo: mostra a data como 12.01.2022
**Simulação**
> fix(datepicker): suporte locale russo

- projects/ui/src/lib/components/po-widget/po-widget.component.spec.ts
- projects/ui/src/lib/components/po-widget/po-widget.component.ts
**widget**
**DTHFUI-6727**
Componente emite click se o wiget é clicável ou não. Componente quando utilizado com campos de input não consegue dar espaço quando o widget não é clicavel
Componente não emite click se o wiget é clicável ou não. Componente quando utilizado com campos de input consegue dar espaço quando o widget não é clicavel
**Simulação**
app: 
[app.zip](https://github.com/po-ui/po-angular/files/10067425/app.zip)
> fix(widget): corrige comportamento indevido no componente

- projects/ui/src/lib/interceptors/po-http-request/po-http-request-interceptor.service.spec.ts
- projects/ui/src/lib/interceptors/po-http-request/po-http-request-interceptor.service.ts
**HTTP-REQUEST-INTERCEPTOR**
**DTHFUI-6485**
Atualmente o HttpInterceptor acaba deixando passar os headers customizados 'X-PO-No-Count-Pending-Requests' e 'X-PO-Screen-Lock' que 
são utilizados apenas pelo frontend.
Agora os headers customizados 'X-PO-No-Count-Pending-Requests' e 'X-PO-Screen-Lock' são removidos antes do envio para o backend
**Simulação**
Testar no sample do Portal ou pelo [app.zip](https://github.com/po-ui/po-angular/files/10070921/app.zip)
> fix(http-request): remove headers customizados

- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/templates/src/lib/utils/util.spec.ts
- projects/templates/src/lib/utils/util.ts
Corrige paginação do componente quando usado mais de uma chave, sendo uma delas com o mesmo valor
fixes DTHFUI-6749
**dynamic-table**
**DTHFUI-6749**
Quando utilizada mais de uma key, sendo uma delas com o mesmo valor, a paginação não está sendo feita de forma correta
Quando utilizada mais de uma key, sendo uma delas com o mesmo valor, a paginação está sendo feita de forma correta
**Simulação**
entrar na branch "dynamic-table/teste-task6749" do po-sample-api e rodar  ```npm run start:dev```
App: 
[app.zip](https://github.com/po-ui/po-angular/files/10078948/app.zip)
> fix(dynamic-table): corrige a paginação do componente

- projects/templates/src/lib/components/po-page-job-scheduler/interfaces/po-job-scheduler-internal.interface.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-base.component.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.ts
Permite adicionar parâmetros no json de envio ao endpoint no componente po-page-job-scheduler ao concluir os passos do job scheduler através da propriedade p-before-send.
Fixes #1468
**po-page-job-scheduler**
**#1468**
Não é possível adicionar parâmetros customizados pois ao utilizar o 'p-value' apenas é possível manter valores de fora da propriedade 'executionParameter', pois essa propriedade é usada como model do componente da etapa de parametrização perdendo os valores definidos de início.
Alguns parâmetros não precisam ser mostrados nem preenchidos pelo usuário, porém precisam ser enviados ao endpoint chamado ao concluir os passos do job scheduler. …
> feat(page-job-scheduler): adiciona a propriedade p-before-send

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/samples/sample-po-dynamic-form-register/sample-po-dynamic-form-register.component.ts
- projects/ui/src/lib/components/po-field/po-switch/po-switch.component.spec.ts
- projects/ui/src/lib/components/po-field/po-switch/po-switch.component.ts
- projects/ui/src/lib/components/po-field/po-switch/samples/sample-po-switch-labs/sample-po-switch-labs.component.html
- projects/ui/src/lib/components/po-field/po-switch/samples/sample-po-switch-labs/sample-po-switch-labs.component.ts
Indica se o `model` receberá o valor formatado pelas propriedades `p-label-on` e `p-label-off` ou apenas o valor puro (sem formatação).
Fixes #1423, DTHFUI-1887
**Switch**
**1423**
O componente não permitir customizar os valores do model (true/false)
O componente permitir customizar os valores do model (true/false)
**Simulação**
Para simulação pelo portal ou pode ser usado o [App.zip](https://github.com/po-ui/po-angular/files/9981695/app.zip).
> feat(switch): adiciona propriedade `p-format-model`

- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox.component.html
- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox.component.spec.ts
- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox.module.ts
- projects/ui/src/lib/components/po-field/po-field.module.ts
- projects/ui/src/lib/components/po-field/po-radio/po-radio.component.html
- projects/ui/src/lib/components/po-field/po-radio/po-radio.component.spec.ts
- projects/ui/src/lib/components/po-field/po-switch/po-switch.component.html
- projects/ui/src/lib/components/po-field/po-switch/po-switch.component.spec.ts
**CHECKBOX
SWITCH
RADIO**
**DTHFUI-6764**
Componentes `po-checkbox`, `po-radio`  e  `po-switch`  não reutilizam componente `po-label` nas opcões dos fields.
Componentes `po-checkbox`, `po-radio`  e  `po-switch` passam a reutilizar componente `po-label` nas opcões dos fields.
**PRs Adicionais:**
- https://github.com/po-ui/po-style/pull/372
- https://github.com/totvs/po-theme-totvs/pull/201
**Simulação**
portal nos samples dos componentes.
> feat(checkbox): reutiliza componente `po-label`

- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view.component.spec.ts
**DYNAMIC-VIEW**
**DTHFUI-6841**
Componente não tinha teste unitário para o `po-image`
Componente passa a ter teste unitário para o `po-image`
**Simulação**
Rodar `npm run test:ui` e conferir no coverage
> test(dynamic-view): inclui teste para o `po-image`

- projects/ui/src/lib/directives/po-tooltip/po-tooltip.directive.spec.ts
- projects/ui/src/lib/directives/po-tooltip/po-tooltip.directive.ts
**TOOLTIP**
**DTHFUI-6771**
Atualmente quando se clica num link com tooltip e redireciona a página, o mesmo não remove o tooltip.
Agora ao clicar em um link com tooltip e redireciona a página o mesmo é removido.
**Simulação**
Utilizar este [APP.zip](https://github.com/po-ui/po-angular/files/10167057/APP.zip) e testar no sample `PO Table - Po Field Components`.
> fix(tooltip): corrige remoção de tooltip

- projects/ui/src/lib/components/po-button/po-button-base.component.spec.ts
- projects/ui/src/lib/components/po-button/po-button-base.component.ts
**PO-BUTTON**
**DTHFUI-6884**
Componente possui propriedade `p-type` depreciada da v15.x.x.
Componente deixa de ter propriedade `p-type` depreciada da v15.x.x. Utilizando propriedade `p-kind` no lugar.
**PR Adicional:**
- https://github.com/po-ui/po-style/pull/377
> refactor(button): remove a propriedade `p-type`

- README.md
- docs/guides/getting-started.md
- package.json
- projects/ui/README.md
- projects/ui/schematics/ng-add/index.spec.ts
- projects/ui/schematics/ng-add/setup-project.ts
**SCHEMATICS**
**DTHFUI-6447**
Ao utilizar os schematics de add do PO UI o HttpClientModule não era importado no módulo root da aplicação.
Ao utilizar os schematics de add do PO UI o HttpClientModule passa a ser importado no módulo root da aplicação.
**Simulação**
Portal e Testar com o Verdaccio , ao utilizar ng add.
**Doc de auxílio:**
- https://docs.google.com/document/d/13CGDAYNLUT69eYsIJrOCNtt2BMByhoEmKr2x8S4g18k/edit?usp=sharing
> feat(schematics): adiciona módulo `HttpClientModule`

- projects/ui/src/lib/components/po-tag/po-tag.component.spec.ts
- projects/ui/src/lib/components/po-tag/po-tag.component.ts
**TAG**
**DTHFUI-6842**
Ao customizar a cor do background (sem utilizar um tipo pré-estabelecido) a cor do texto está ficando preto.
Ao customizar a cor do background (sem utilizar um tipo pré-estabelecido) a cor do texto é branca, quando não definida uma cor de texto diferente.
**Simulação**
Portal sample po-tag
> fix(tag): altera cor do texto

- projects/ui/src/lib/components/po-modal/po-modal-base.component.ts
Adiciona evento `p-close` que é disparado quando o modal é fechado:
- Pelo botão `Fechar`;
- Pelo `X` da interface do modal;
- Pela tecla `ESC`;
Fixes #1217
**Modal**
**1217**
Quando o modal é fechado pela tecla "ESC", não é disparado nenhum evento para que o usuário possa executar alguma ação.
Quando o modal é fechado pela tecla "ESC" ou de qualquer outra forma, será disparado um evento para que o usuário possa executar alguma ação.
**Simulação**
Pode ser simulado pelo [App](https://github.com/po-ui/po-angular/files/10368814/app.zip).
> feat(modal): adiciona evento `p-close`

- projects/ui/src/lib/components/po-disclaimer/po-disclaimer-base.component.spec.ts
- projects/ui/src/lib/components/po-disclaimer/po-disclaimer-base.component.ts
- projects/ui/src/lib/components/po-disclaimer/po-disclaimer.component.html
- projects/ui/src/lib/components/po-disclaimer/po-disclaimer.literals.ts
**DISCLAIMER**
**DTHFUI-6894**
Componente não tem literais para o botão de remover
Componente passa a ter literais para o botão de remover
**Simulação**
[Portal](https://po-ui.io/documentation/po-disclaimer-group)  testando com `NVDA`
> feat(disclaimer): adiciona `literals` para o botão de remover

- projects/ui/src/lib/components/po-widget/po-widget.component.html
- projects/ui/src/lib/components/po-widget/po-widget.component.spec.ts
- projects/ui/src/lib/components/po-widget/samples/sample-po-widget-labs/sample-po-widget-labs.component.html
- projects/ui/src/lib/components/po-widget/samples/sample-po-widget-labs/sample-po-widget-labs.component.ts
**widget**
**fixes-DTHFUI-7003**
p-no-shadow está apagando a borda de um widget não clicavel
p-no-shadow não está apagando a borda de um widget não clicavel
**Simulação**
PR STYLE: https://github.com/po-ui/po-style/pull/384
testar portal e app:
html :
```
<po-widget p-title="title" (p-click)="teste($event)" [p-no-shadow]="true"></po-widget>
<br>
<br>
<br>
<po-widget p-title="title"  [p-no-shadow]="true"></po-widget>
```
ts: 
```
teste(event) {
console.log('click')
}
```
> fix(widget): corrige borda sendo apagada com `p-no-shadow`

- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
**combo**
**DTHFUI-6818**
Lista só é carregada no segundo clique após limpar o campo e a lista esteja com hasNext=false
Lista é carregada normalmente após limpar o campo e a lista esteja com hasNext=false
**Simulação**
Testar todos os exemplos do portal e app: 
[app.zip](https://github.com/po-ui/po-angular/files/10490969/app.zip)
> fix(combo): corrige carregamento da lista após limpar campo

- projects/ui/src/lib/directives/po-tooltip/po-tooltip.directive.spec.ts
- projects/ui/src/lib/directives/po-tooltip/po-tooltip.directive.ts
**TOOLTIP>**
**DTHFUI-6956**
Tooltip se mantém após redirecionamento utilizando coluna do tipo link
Tooltip deixa de se manter após redirecionamento utilizando coluna do tipo link
**Simulação**
Utilizar esse [app.zip](https://github.com/po-ui/po-angular/files/10492985/app.zip)
> fix(tooltip): corrige remoção de tooltip em coluna do tipo link

- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range-base.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.ts
- projects/ui/src/lib/utils/util.spec.ts
- projects/ui/src/lib/utils/util.ts
**datepicker-range**
**DTHFUI-6949**
datepicker com locale russo estava com o formato dd/mm/yyyy
datepicker com locale russo está com o formato dd.mm.yyyy
**Simulação**
Testar labs do DATEPICKER-RANGE e do DATEPICKER
> feat(datepicker-range): suporte locale russo

- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-table/po-table.module.ts
Altera o conteúdo do `po-table-column-label` para utilizar o componente `po-tag`.
Fixes #1421, DTHFUI-2583
**Table**
**1421**
O componente usa `po-table-column-label`.
O componente passa a usar o `po-tag` no lugar do `po-table-column-label`.
**Simulação**
Pode ser feita no Portal ou pelo [App.zip](https://github.com/po-ui/po-angular/files/10079962/app.zip).
> feat(table): utiliza po-tag para exibir o label

- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.html
**DATEPICKER**
**DTHFUI-7042**
Componente possui classe não sendo mais utilizada.
Componente deixa de possuir classe não utilizada.
**Simulação**
Portal sample Datepicker Labs com `clean`
> refactor(datepicker): remove classe não sendo mais utilizada

- projects/ui/src/lib/components/po-field/po-select/po-select.component.html
Ajusta a exibição da opção selecionada, quando o `value` for `number` e igual a zero.
Fixes #1473
**Select**
**1473**
A opção selecionada não é exibida quando o `value` for igual a zero, a opção anterior for diferente da selecionada e diferente de branco.
A opção selecionada é exibida quando o `value` for igual a zero, a opção anterior for diferente da selecionada e diferente de branco.
**Simulação**
Não é possível simular no portal, pois no exemplo que lá existe o `value` é `string`. 
Use este [App](https://github.com/po-ui/po-angular/files/10035725/app.zip) para a simulação, seguindo as instruções abaixo:
1. Primeiro …
> fix(select): ajusta a exibição da opção quando o `value` igual a zero

- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
**DTHFUI-7058**
Não mantém a ordenação após paginação da tabela
Mantém a ordenação após paginação da tabela
**Simulação**
testar todos os samples do portal da TABLE e do DYNAMIC-TABLE
> fix(page-dynamic-table): corrige ordenação após paginação

- projects/ui/src/lib/components/components.module.ts
- projects/ui/src/lib/components/index.ts
- projects/ui/src/lib/components/po-dropdown/po-dropdown.component.spec.ts
- projects/ui/src/lib/components/po-dropdown/po-dropdown.component.ts
- projects/ui/src/lib/components/po-field/po-field.module.ts
- projects/ui/src/lib/components/po-listbox/enums/po-item-list-type.enum.ts
- projects/ui/src/lib/components/po-listbox/index.ts
- projects/ui/src/lib/components/po-listbox/interfaces/po-listbox-literals.interface.ts
- projects/ui/src/lib/components/po-listbox/po-item-list/interfaces/po-item-list-action.interface.ts
- projects/ui/src/lib/components/po-listbox/po-item-list/interfaces/po-item-list-option-group.interface.ts
- projects/ui/src/lib/components/po-listbox/po-item-list/interfaces/po-item-list-option.interface.ts
- projects/ui/src/lib/components/po-listbox/po-item-list/po-item-list-base.component.spec.ts
- projects/ui/src/lib/components/po-listbox/po-item-list/po-item-list-base.component.ts
- projects/ui/src/lib/components/po-listbox/po-item-list/po-item-list.component.html
- projects/ui/src/lib/components/po-listbox/po-item-list/po-item-list.component.spec.ts
- projects/ui/src/lib/components/po-listbox/po-item-list/po-item-list.component.ts
- projects/ui/src/lib/components/po-listbox/po-listbox-base.component.spec.ts
- projects/ui/src/lib/components/po-listbox/po-listbox-base.component.ts
- projects/ui/src/lib/components/po-listbox/po-listbox.component.html
- projects/ui/src/lib/components/po-listbox/po-listbox.component.spec.ts
- projects/ui/src/lib/components/po-listbox/po-listbox.component.ts
- projects/ui/src/lib/components/po-listbox/po-listbox.module.ts
- projects/ui/src/lib/components/po-popup/po-popup.component.html
- projects/ui/src/lib/components/po-popup/po-popup.component.spec.ts
- projects/ui/src/lib/components/po-popup/po-popup.component.ts
- projects/ui/src/lib/components/po-popup/po-popup.module.ts
- projects/ui/src/lib/components/po-popup/samples/sample-po-popup-email/sample-po-popup-email.component.ts
**LISTBOX**
**DTHFUI-6733**
Não existe um componente interno de listbox.
Cria componente interno listbox para ser reutilizado.
**Simulação**
Testar labs do portal
**PR's Relacionadas**
- https://github.com/po-ui/po-style/pull/378
- https://github.com/totvs/po-theme-totvs/pull/205
> feat(listbox): novo componente

- projects/ui/src/lib/components/po-field/po-input-generic/po-input-generic.spec.ts
- projects/ui/src/lib/components/po-field/po-input-generic/po-input-generic.ts
- projects/ui/src/lib/components/po-field/po-input/po-input-base.component.ts
- projects/ui/src/lib/components/po-field/po-input/samples/sample-po-input-labs/sample-po-input-labs.component.html
- projects/ui/src/lib/components/po-field/po-input/samples/sample-po-input-labs/sample-po-input-labs.component.ts
**INPUT**
**#1520**
Não existe uma propriedade para transformar o model em caixa alta. 
Com a propriedade p-uppercase, todo o conteúdo do model é transformado em caixa alta.
**Simulação**
[1520-p-uppercase.zip](https://github.com/po-ui/po-angular/files/10025725/1520-p-uppercase.zip)
- https://github.com/po-ui/po-angular/issues/1520
> feat(input): adiciona a propriedade p-uppercase

- projects/ui/src/lib/components/po-tabs/po-tabs.component.html
- projects/ui/src/lib/components/po-tabs/po-tabs.component.ts
Adicionada a tradução para a palavra "Mais" quando as abas forem apresentadas de forma agrupada e em idioma diferente de português.
Fixes #1577
**Tabs**
**1577**
Quando as abas são apresentadas de forma agrupada e em idioma diferente de português, a palavra "Mais" não tem tradução para o idioma do navegador.
Quando as abas são apresentadas de forma agrupada e em idioma diferente de português, a palavra "Mais" foi adicionada a tradução para o idioma do navegador.
**Simulação**
Pode ser feita a simulação com o [App](https://github.com/po-ui/po-angular/files/10551956/app.zip)
> fix(tabs): adiciona tradução para a palavra "Mais"

- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/samples/sample-po-dynamic-view-employee/sample-po-dynamic-view-employee.component.ts
**DYNAMIC-VIEW**
**DTHFUI-7097**
Componente não possuia propriedade `options` para exibir a label da opção selecionada.
Componente passa a ter propriedade `options` para exibir a label da opção selecionada.
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/10875282/app.zip) e Portal sample `Dynamic View - Employee`
> feat(dynamic-view): permitir passar `options` e atribuir `label`

- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/templates/src/lib/utils/util.spec.ts
- projects/templates/src/lib/utils/util.ts
**dynamic-table**
**DTHFUI-7087**
não está removendo de forma correta os itens duplicados
Está removendo de forma correta os itens duplicados
**Simulação**
testar sample do portal e testar o seguinte app com 3 exemplos:
[app.zip](https://github.com/po-ui/po-angular/files/10854093/app.zip)
Para testar o primeiro exemplo, deve rodar localmente (npm run start) o po-sample-api na branch : 'dynamic-table/teste-task6749'
> fix(dynamic-table): corrige paginação dos itens

- projects/ui/src/lib/components/po-calendar/po-calendar-base.component.spec.ts
- projects/ui/src/lib/components/po-calendar/po-calendar-base.component.ts
- projects/ui/src/lib/components/po-calendar/po-calendar.component.spec.ts
- projects/ui/src/lib/components/po-calendar/po-calendar.component.ts
**CALENDAR**
**DTHFUI-7053**
Ao selecionar dia 31 no calendário o mesmo pulava 1 mês a frente no modo range.
Ao selecionar dia 31 no calendário o mesmo apresenta seguencia de meses corretamente no modo range.
**Simulação**
Portal sample `PO Calendar Labs`
> fix(calendar): corrige seguencia de meses no modo range

- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/templates/src/lib/utils/util.spec.ts
- projects/templates/src/lib/utils/util.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/utils/util.spec.ts
- projects/ui/src/lib/utils/util.ts
**dthf UI 7091**
dynamic table e lookup está acumulando pesquisa ao realizar filtro
dynamic table e lookup não estão acumulando pesquisa ao realizar filtro
**Simulação**
realizar o build antes de testar app e portal
testar app e samples do portal do dynamic table, table e lookup
app:
```
<po-lookup
name="lookup"
p-filter-service="https://po-sample-api.fly.dev/v1/heroes"
>
</po-lookup>
<po-page-dynamic-table p-title="Po Page Dynamic Table" p-service-api="https://po-sample-api.fly.dev/v1/people">
</po-page-dynamic-table>
<po-page-dynamic-table p-height="700" …
```
> fix(dynamic-table/lookup): arruma acúmulo de registros do filtro

- projects/ui/src/lib/components/po-table/po-table-column-label/po-table-column-label.component.html
- projects/ui/src/lib/components/po-table/po-table-column-label/po-table-column-label.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-column-label/po-table-column-label.component.ts
- projects/ui/src/lib/components/po-table/po-table-column-label/po-table-column-label.interface.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-transport/sample-po-table-transport.service.ts
**TABLE**
**fixes DTHFUI-7094**
Componente não possuia propriedades do `po-tag`
Componente passa a possuir propriedades do `po-tag`
**Simulação**
Samples do portal e [app.zip](https://github.com/po-ui/po-angular/files/10983427/app.zip).
Obs: O texto da `tag` deixa de ser preto quando não é passado nenhuma cor do `PoColorPaletteEnum` por exemplo: red, rgb(201, 53, 125), #753399 ficando texto em branco.
> feat(table): repassa propriedades do po-tag

- projects/ui/src/lib/components/po-list-view/po-list-view-base.component.ts
- projects/ui/src/lib/components/po-list-view/po-list-view.component.html
- projects/ui/src/lib/components/po-list-view/po-list-view.component.spec.ts
- projects/ui/src/lib/components/po-list-view/po-list-view.component.ts
**LIST-VIEW**
**fixes DTHFUI-7062**
Componente não possuia evento no botão de "Exibir detalhes"
Componente passa a ter evento no botão de "Exibir detalhes" 
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/10995025/app.zip)
> feat(list-view): adiciona evento no botão de mostrar detalhes

- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.ts
Permite alterar o model do componente po-page-dynamic-edit após feita a busca dos dados através da propriedade p-load-data.
Fixes #1633
**po-page-dynamic-edit**
**#1633**
Hoje o componente po-page-dynamic-edit busca os dados pela api informada e não há uma maneira de alterar antes de repassar ao model do componente.
Agora é possível passar uma função ao novo parâmetro **"p-load-data"** que recebe o model e pode fazer as alterações necessárias, para adicionar ou modificar valores antes destes serem repassados a variável de model do componente.
**Simulação**
https://gist.github.com/guilnorth/1f88de824abdf0754ec7145572f4c703
> feat(page-dynamic-edit): adiciona p-load-data

- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.html
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
Possibilita desabilitar que o combo guarde o ultimo valor e não gere nova requisição com a nova propriedade `p-cache`
**Combo**
**fixes DTHFUI-7179**
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/11141790/app.zip)
> feat(combo): adiciona opção que desativa o armazenamento do último valor

- projects/ui/src/lib/components/po-field/po-number/po-number.component.spec.ts
- projects/ui/src/lib/components/po-field/po-number/po-number.component.ts
**NUMBER**
**DTHFUI-7129**
Componente em navegador Firefox ao rolar scroll do mouse em cima do contador acontece ação de incremento e decremento.
Componente em navegador Firefox ao rolar scroll do mouse em cima do contador não acontece ação de incremento e decremento.
**Simulação**
[Portal](https://po-ui.io/)
> fix(number): desativa ação de incremento e decremento

- .eslintrc.json
- projects/portal/src/app/theme-builder/theme-builder.component.html
- projects/portal/src/app/theme-builder/theme-builder.component.ts
- projects/ui/src/lib/components/po-link/po-link-base.component.spec.ts
- projects/ui/src/lib/components/po-link/po-link-base.component.ts
- projects/ui/src/lib/components/po-link/po-link.component.html
- projects/ui/src/lib/components/po-link/po-link.component.ts
- projects/ui/src/lib/components/po-link/po-link.module.ts
- projects/ui/src/lib/components/po-table/po-table-column-link/po-table-column-link.component.html
- projects/ui/src/lib/components/po-table/po-table-column-link/po-table-column-link.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-column-link/po-table-column-link.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.module.ts
**TABLE**
**DTHFUI-7204**
O componente po-table-column-link não utiliza o componente po-link.
O componente po-table-column-link passa a utiliza o componente po-link.
**Style**
- https://github.com/po-ui/po-style/pull/408
**Simulação**
Portal
> feat(table): reutiliza componente

- projects/ui/src/lib/services/po-notification/po-toaster/po-toaster.component.spec.ts
- projects/ui/src/lib/services/po-notification/po-toaster/po-toaster.component.ts
**NOTIFICATION**
**DTHFUI-7212**
Atualmente o componente `po-notification` não apresenta um empilhamento correto das notificações.
As notificações agora serão empilhadas corretamente
**Simulação**
Portal
> fix(toaster): ajusta empilhamento das notificações

- projects/ui/src/lib/services/po-i18n/po-i18n-base.service.spec.ts
- projects/ui/src/lib/services/po-i18n/po-i18n.module.ts
**po-i18n**
O serviço PoI18nService está retornando o idioma nulo.
O serviço PoI18nService está retornando uma string, contendo o idioma correto.
**Simulação**
Importar o serviço PoI18nService e utilizar o método getShortLanguage.
> fix(i18n): Métodos do PoI18nService retornam nulo

- projects/ui/karma.conf.js
- projects/ui/src/lib/services/po-i18n/po-i18n-base.service.spec.ts
- projects/ui/src/lib/services/po-i18n/po-i18n-base.service.ts
Corrige serviço de tradução no i18n
Fixes DTHFUI-7282
*po-i18n*
*DTHFUI-7282*
___________________________
*PR Checklist [Revisor]*
*Qual o comportamento atual?*
A técnica de Tradução parou de funcionar
*Qual o novo comportamento?*
Tradução e Testes agora funcionam
*Simulação*
Pelo portal através do `po-page-login`
> test(i18n): ajusta os testes do i18n

- projects/ui/src/lib/components/po-table/po-table-column-label/po-table-column-label.component.html
- projects/ui/src/lib/components/po-table/po-table-column-label/po-table-column-label.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-column-label/po-table-column-label.component.ts
PO-TABLE
DTHFUI-7227
Colunas do tipo label da tabela estão sendo exibidas mesmo sem nenhum valor
Colunas do tipo label da tabela devem ser exibidas apenas quando houver valor
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/11509215/app.zip)
> fix(table): corrige exibição de colunas do tipo label

- projects/ui/src/lib/components/po-table/po-table-detail/po-table-detail.component.html
- projects/ui/src/lib/components/po-table/po-table-detail/po-table-detail.component.spec.ts
TABLE
DTHFUI-6317
Colunas de detalhe do tipo 'number' e 'currency' da tabela estão com os valores e títulos centralizados
Colunas de detalhe do tipo 'number' e 'currency' da tabela estão com os valores e títulos alinhados à direita
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/11531000/app.zip)
> fix(table): alinha colunas do tipo number e currency à direita

- projects/ui/src/lib/components/po-disclaimer-group/po-disclaimer-group.component.spec.ts
- projects/ui/src/lib/components/po-tag/po-tag-base.component.ts
- projects/ui/src/lib/components/po-tag/po-tag.component.html
- projects/ui/src/lib/components/po-tag/po-tag.component.spec.ts
- projects/ui/src/lib/components/po-tag/po-tag.component.ts
- projects/ui/src/lib/components/po-tag/po-tag.literals.ts
- projects/ui/src/lib/components/po-tag/samples/sample-po-tag-labs/sample-po-tag-labs.component.html
- projects/ui/src/lib/components/po-tag/samples/sample-po-tag-labs/sample-po-tag-labs.component.ts
**tag**
**DTHFUI-6870**
O componente PoTag foi reescrito seguindo as definições do Animalia DS, porém sua variação de remoção não foi implementada.
O componente PoTag agora tem a variação de remoção e pode ser utilizado no PoDisclaimer
**Simulação**
[app.zip](https://github.com/po-ui/po-style/files/11452888/app.zip)
**Style**
[style.zip](https://github.com/po-ui/po-angular/files/11531528/style.zip)
**Themes**
[theme.zip](https://github.com/po-ui/po-angular/files/11531547/theme.zip)
> feat(tag): implementa novas propriedades

- projects/ui/src/lib/components/po-field/po-decimal/po-decimal.component.spec.ts
- projects/ui/src/lib/components/po-field/po-decimal/po-decimal.component.ts
DECIMAL
DTHFUI-6099
Espaços em brancos são permitidos e caracteres como somente hífen ou diversos pontos e números com locale russo retorna o input como 'NaN'
Espaços são bloqueados e caracteres que resultam o retorno do input como 'NaN' são limpos.
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/11626468/app.zip)
> fix(decimal): corrige o uso de hífens, pontos e espaços

- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
**Combo**
**DTHFUI-7339**
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/11665530/app.zip)
> feat(combo): cria nova propriedade `p-remove-initial-filter`

- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.spec.ts
DATEPICKER
#1725, DTHFUI-7389
Horário da data é exibido como T00:00:01-00:00
Horário da data é exibido como T00:00:00-00:00
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/11747771/app.zip)
> fix(datepicker): corrige exibição de horário em formatação extendida

- projects/ui/src/lib/components/po-field/po-radio-group/po-radio-group.component.spec.ts
- projects/ui/src/lib/components/po-field/po-radio-group/po-radio-group.component.ts
- projects/ui/src/lib/components/po-field/po-radio/po-radio.component.html
- projects/ui/src/lib/components/po-field/po-radio/po-radio.component.spec.ts
- projects/ui/src/lib/components/po-field/po-radio/po-radio.component.ts
RADIO-GROUP
https://github.com/po-ui/po-angular/issues/1717, DTHFUI-7357
não é atríbuido foco utilizando a propriedade p-auto-focus ao radio group e método focus() gera erro no console
foco com a propriedade p-auto-focus ao radio group executa normalmente e método focus() não gera erro no console
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/11739419/app.zip)
> fix(radio-group): corrige método focus

- projects/ui/src/lib/components/po-field/po-number/po-number-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-number/po-number-base.component.ts
NUMBER
fixes DTHFUI-7431
Tecla enter não disparava evento de keyup ao usuário
Tecla enter dispara evento de keyup ao usuário
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/11909832/app.zip)
> feat(number): adiciona evento para tecla enter

- projects/templates/src/lib/components/po-page-login/po-page-login.component.html
PAGE-LOGIN
#1743, DTHFUI-7429
Propriedades p-product-name e p-environment estão alinhado à esquerda.
Propriedades p-product-name e p-environment estão alinhado ao centro.
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/11909151/app.zip)
> fix(page-login): centraliza propriedades p-environment e p-product-name

- projects/ui/src/lib/components/po-menu/po-menu-base.component.spec.ts
- projects/ui/src/lib/components/po-menu/po-menu-item/po-menu-item-filtered.interface.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.spec.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.ts
- projects/ui/src/lib/components/po-menu/services/po-menu.service.spec.ts
**MENU**
**DTHFUI-6636**
`po-menu` em sua interface `po-menu-item-filtered.interface` não possui propriedade `action`.
`po-menu` em sua interface `po-menu-item-filtered.interface` passa possuir propriedade `action`.
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/11952015/app.zip)
> feat(menu): adiciona propriedade `action`

- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.html
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.html
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-multiple/sample-po-lookup-multiple.component.html
- projects/ui/src/lib/components/po-table/interfaces/po-table-literals.interface.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-airfare/sample-po-table-airfare.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-airfare/sample-po-table-airfare.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-heroes/sample-po-table-heroes.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-heroes/sample-po-table-heroes.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.ts
- projects/ui/src/lib/components/po-table/services/po-table.service.spec.ts
- projects/ui/src/lib/components/po-table/services/po-table.service.ts
TABLE
fixes DTHFUI-7317
N/A
Quando a tabela possui a propriedade selectable = true, é permitido ao usuário a opção de realizar ações (exclusão) em lote. Utilizando serviço, é possível apenas 1 item por vez
**Simulação**
Necessário rodar o comando npm run build:portal para executar os samples
[app.zip](https://github.com/po-ui/po-angular/files/12006101/app.zip)
Pasta styles para substituir na node_modules:
[style.zip](https://github.com/po-ui/po-angular/files/11984505/style.zip)
> feat(table): implementa funcionalidade de ações em lote

- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.spec.ts
DATEPICKER
fixes DTHFUI-7436
Quando o usuário seleciona uma data no datepicker, por padrão o timezone é -00:00
Quando o usuário seleciona uma data no datepicker, por padrão o timezone é baseado no fuso horário da máquina do mesmo. Exemplo, meu fuso horário é brasília, então meu timezone é -03:00
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/12098254/app.zip)
> feat(datepicker): implementa timezone na data extendida

- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.html
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-drag-and-drop/sample-po-page-dynamic-table-drag-and-drop.component.html
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-drag-and-drop/sample-po-page-dynamic-table-drag-and-drop.component.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-table/po-table.module.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-draggable/sample-po-table-draggable.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-draggable/sample-po-table-draggable.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.e2e-spec.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.po.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.ts
**TABLE**
**DTHFUI-7315**
Componente não possui recurso de drag and drop nas colunas.
Implementado recurso de drag and drop no componente com parâmetro p-draggable opcional tendo valor padrão falso. Caso seja passado como verdadeiro, o recurso de drag and drop estará disponível.
**Simulação**
Samples: [/portal (po-table e po-page-dynamic-table)](Portal)
App: [app.zip](https://github.com/po-ui/po-angular/files/12018446/app.zip)
> feat(table): implementa recurso `drag and drop` nas colunas da tabela

- projects/ui/src/lib/components/po-field/po-checkbox-group/interfaces/po-checkbox-group-option.interface.ts
- projects/ui/src/lib/components/po-field/po-checkbox-group/po-checkbox-group-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.html
- projects/ui/src/lib/components/po-table/index.ts
- projects/ui/src/lib/components/po-table/interfaces/po-table-column.interface.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table-column-frozen/po-table-column-frozen.directive.spec.ts
- projects/ui/src/lib/components/po-table/po-table-column-frozen/po-table-column-frozen.directive.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.html
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.ts
- projects/ui/src/lib/components/po-table/po-table-list-manager/po-table-list-manager.component.html
- projects/ui/src/lib/components/po-table/po-table-list-manager/po-table-list-manager.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-list-manager/po-table-list-manager.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-table/po-table.module.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-heroes/sample-po-table-heroes.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.ts
**Table**
** DTHFUI-7314**
Consigo fixar até 5 colunas da tabela
**Simulação**
Testar todos os samples do portal, testar o fixador (para testar o fixador de forma efetiva o ideal é testar em tabelas que tenham scroll horizontal) e todas as funcionalidades já existente da tabela.
Testar theme totvs se mantém o padrão do tema.
style: https://github.com/po-ui/po-style/pull/437
> feat(table): implementa fixador de colunas

- projects/ui/src/lib/components/po-table/enums/po-table-spacing.enum.ts
- projects/ui/src/lib/components/po-table/index.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-transport/sample-po-table-transport.component.html
Cria nova propriedade para customizar o tamanho da row da tabela
fixes DTHFUI-7432
O espaçamento das colunas não são customizáveis
O espaçamento das colunas possuem 3 tamanhos diferentes, sendo alteranado através da nova propriedade p-spacing
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/12216693/app.zip)
style:
https://github.com/po-ui/po-style/pull/436
> feat(table): cria propriedade p-spacing para a tabela

- projects/ui/src/lib/components/po-dynamic/po-dynamic-field-type.enum.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.ts
**Dynamic-form**
**DTHFUI-7516*
caso seja passado currency com mask renderiza input
caso seja passado decimal com mask renderiza decimal
**Simulação**
```
//app.html
<po-dynamic-form [p-fields]="fields" [p-validate-on-input]="true"> </po-dynamic-form>
//app.ts
fields: Array<PoDynamicFormField> = [
{
property: 'exemple1',
label: 'renderia decimal',
placeholder: 'teste1',
type: 'currency',
decimalsLength: 0
},
{
property: 'exemple2',
label: 'renderiza input',
placeholder: 'teste2 ',
type: 'currency',
decimalsLength: 0,
mask: '999.999.999-99'
},
{
property: 'exemple3',
label: 'renderiza decimal',
placeholder: 'teste3',
type: …
```
> feat(dynamicform): adiciona tipo `decimal`

- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.ts
PO-LOOKUP-MODAL
fixes DTHFUI-7511
Após realizar algum filtro na busca avançada do lookup, o resultado no disclaimer é apenas o valor e se for do tipo booleano aparece o valor true ou false ao invés das propriedades 'booleanTrue' ou 'booleanFalse'. Exemplo: O campo do tipo booleano com o nome de 'Tem carro' com os valores do switch sendo 'Sim' para true e 'Não' para false aparece no disclaimer quando filtrado somente 'true'
Após realizar algum filtro na busca avançada do lookup, o resultado no disclaimer é a label concatenada com o valor e se for do tipo booleano aparece o valor das propriedades 'booleanTrue' ou …
> fix(lookup): resolve disclaimer do lookup para o filtro booleano

- angular.json
- projects/portal/src/app/theme-builder/theme-builder.component.css
- projects/portal/src/app/theme-builder/theme-builder.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/samples/sample-po-multiselect-template/sample-po-multiselect-template.component.ts
THEME-BUILDER
fixes #DTHFUI-7601
Construtor de temas está com a estilização incorreta quando executamos os comandos npm run build:portal e npm run build:portal:prod e rodamos live-server na pasta dist/portal na versão do Angular 16
Construtor de temas está com a estilização correta quando executamos os comandos npm run build:portal e npm run build:portal:prod e rodamos live-server na pasta dist/portal na versão do Angular 16
**Simulação**
Executar os comandos npm run build:portal e npm run build:portal:prod -> entrar pelo terminal na pasta dist/portal e rodar live-server e verificar se o construtor de temas está correto
> fix(theme-builder): ajusta estilização para o angular 16

- projects/ui/src/lib/components/po-tree-view/po-tree-view-base.component.spec.ts
- projects/ui/src/lib/components/po-tree-view/po-tree-view-base.component.ts
- projects/ui/src/lib/components/po-tree-view/po-tree-view.component.spec.ts
- projects/ui/src/lib/components/po-tree-view/po-tree-view.component.ts
- projects/ui/src/lib/components/po-tree-view/samples/sample-po-tree-view-labs/sample-po-tree-view-labs.component.html
- projects/ui/src/lib/components/po-tree-view/samples/sample-po-tree-view-labs/sample-po-tree-view-labs.component.ts
O componente de tree-view não permitia mais do que 4 subníveis.
Adiciona a propriedade p-max-level para permitir configurar o número máximo de subníveis.
Fixes DTHFUI-7556
**po-tree-view**
**DTHFUI-7556**
O componente de tree-view não permite mais do que 4 subníveis.
Com a propriedade p-max-level agora é possível configurar o número máximo de subníveis.
**Simulação**
Acessar o labs do componente po-tree-view
> feat(tree-view): adiciona propriedade p-max-level

- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.ts
- projects/ui/src/lib/components/po-field/po-checkbox-group/po-checkbox-group.component.spec.ts
- projects/ui/src/lib/components/po-field/po-checkbox-group/po-checkbox-group.component.ts
- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox.component.html
Page-Dynamic-Edit e Checkbox
[DTHFUI-7478]
Não existe nenhum comportamento visual além de um alert quando submete o formulário com campos obrigatórios faltantes, além de não funcionar a propriedade p-auto-focus no checkbox e checkbox-group
É colocado uma borda vermelha em todos os campos vazios obrigatórios ao clicar no botão de submeter o formulário do Po-Page-Dynamic-Edit, além de realizar o foco no primeiro campo inválido. Propriedade p-auto-focus corrigida no checkbox e checkbox-group
**Simulação**
Rodar npm run build ; npm run build:portal para funcionamento do PoTemplatesModule …
> fix(page-edit): valida campos obrigatórios

- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
Corrige ordenação após realizar filtragem na tabela com ou sem altura
**table**
**Simulação**
Realizar testes no sample
> fix(table): corrige ordenação após filtragem de itens

- .github/workflows/publish_po_angular_ci.yml
> build(cd): realiza publish npm com checkout@v4

- projects/ui/src/lib/components/po-list-view/po-list-view.component.html
**list-view**
**7641**
Botao de ação não obedece interface danger
Botao de ação agora pode ser utilizar `p-danger`
**Simulação**
Samples do portal
> fix(listview): propriedade p-danger no botão de ação

- .github/workflows/publish_po_angular_ci.yml
Adiciona o caminho do diretorio de trabalho {{working_dir}} no endereco do publish npm. Adiciona action de setup-node@v3 para cada deploy de acordo com as boas práticas do githubactions
**< publish_po_angular >**
**< DTHFUI-7679 >**
O pipeline de deploy apresenta erro ao realizar o NPM Publish de cada pacote. 
O pipeline de deploy deve encontrar os arquivos de cada pacote buildado e realizar o npm publish com sucesso.
**Simulação**
Disparar o workflow publish_po_angular
> build(cd): adiciona caminho do diretório de trabalho

- projects/ui/src/lib/components/po-accordion/index.ts
- projects/ui/src/lib/components/po-accordion/interfaces/po-accordion-literals.interface.ts
- projects/ui/src/lib/components/po-accordion/po-accordion-base.component.spec.ts
- projects/ui/src/lib/components/po-accordion/po-accordion-base.component.ts
- projects/ui/src/lib/components/po-accordion/po-accordion-item-header/po-accordion-item-header.component.html
- projects/ui/src/lib/components/po-accordion/po-accordion-item-header/po-accordion-item-header.component.spec.ts
- projects/ui/src/lib/components/po-accordion/po-accordion-item-header/po-accordion-item-header.component.ts
- projects/ui/src/lib/components/po-accordion/po-accordion-item/po-accordion-item.component.spec.ts
- projects/ui/src/lib/components/po-accordion/po-accordion-item/po-accordion-item.component.ts
- projects/ui/src/lib/components/po-accordion/po-accordion-manager/po-accordion-manager.component.html
- projects/ui/src/lib/components/po-accordion/po-accordion-manager/po-accordion-manager.component.spec.ts
- projects/ui/src/lib/components/po-accordion/po-accordion-manager/po-accordion-manager.component.ts
- projects/ui/src/lib/components/po-accordion/po-accordion.component.html
- projects/ui/src/lib/components/po-accordion/po-accordion.component.spec.ts
- projects/ui/src/lib/components/po-accordion/po-accordion.component.ts
- projects/ui/src/lib/components/po-accordion/po-accordion.module.ts
- projects/ui/src/lib/components/po-accordion/samples/sample-po-accordion-faq/sample-po-accordion-faq.component.html
- projects/ui/src/lib/components/po-accordion/samples/sample-po-accordion-labs/sample-po-accordion-labs.component.html
- projects/ui/src/lib/components/po-accordion/samples/sample-po-accordion-labs/sample-po-accordion-labs.component.ts
ACCORDION
DTHFUI-7691
implementa definições do AnimaliaDS
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/12753067/app.zip)
Styles para testar tokens no App: 
[styles.zip](https://github.com/po-ui/po-angular/files/12739763/styles.zip)
Testar samples, documentação e customização
Style: https://github.com/po-ui/po-style/pull/451
Theme-totvs: https://github.com/totvs/po-theme-totvs/pull/257
> feat(accordion): implementa definições do AnimaliaDS

- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.service.ts
Esta melhoria permite a alteração da `url` no evento `upload`, assim  o componente fica compativel com a API de upload do Fluig.
Fixes #1825
**Upload**
**1825**
O componente `po-upload` não é compativel com a API de upload do Fluig, pois o nome do arquivo em upload precisa ser informado na `url` para realizar o upload pela API do Fluig. 
Com a melhoria o componente permite a alteração da `url` no evento `upload` do componete e isso possibilita a inclusão do nome do arquivo na `url`.
**Simulação**
Para realizar a simulação pode ser usado este [App.zip](https://github.com/po-ui/po-angular/files/12778054/app.zip).
> feat(upload): inclui a propriedade `url` no evento `upload`

- projects/ui/src/lib/components/po-field/po-input-generic/po-input-generic.spec.ts
- projects/ui/src/lib/components/po-field/po-input-generic/po-input-generic.ts
- projects/ui/src/lib/components/po-field/po-input/po-input-base.component.ts
- projects/ui/src/lib/components/po-field/po-input/po-mask.ts
**input**
**DTHFUI-7479**
Em campos onde carregamos um model com um valor inserido que seja incompatível com a máscara do campo, ocorre um comportamento indesejado. O campo fica vazio
Em campos onde carregamos um model com um valor inserido que seja incompatível com a máscara do campo, o campo sinaliza que a mascara esta invalida
**Simulação**
app: [app.zip](https://github.com/po-ui/po-angular/files/12834289/app.zip)
testar tambem portal
[Style](https://github.com/po-ui/po-style/pull/457)
> fix(input): adiciona indicação visual de campo inválido

- projects/ui/src/lib/components/po-menu/po-menu-item/po-menu-item.component.html
**MENU**
**DTHFUI-7743**
Componente apresenta diferenças visuais entre os navegadores suportados,
- Safari apresenta os marcadores de itens na lista.
- Firefox apresenta espaçamento maior entre os itens na lista.
Componente apresenta o mesmo visual entre os navegadores suportados.
Corrige classe de item do menu:
| DE | PARA |
| - | - |
| po-menu-subm-items-list-item | po-menu-sub-items-list-item |
Fixes DTHFUI-7743
**Simulação**
Portal
** PR Complementar **
- https://github.com/po-ui/po-style/pull/459
> fix(menu): corrige item seletor

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
Esta melhoria estende a propriedade `p-form-field` do componente `upload`, assim o componente fica compatível com a API de upload do Fluig permitindo a passagem do literal `file`, através da  propriedade `formField` que foi criada.
Fixes #1847
**1847**
O componente `Dynamic Form` suporta o campo do tipo `upload`, porém não tem como passa a propriedade `p-form-field` existente no componente Upload.
O padão da propriedade `p-form-field` é `files`, porém para produto Fluig é necessário passar o literal `file` e isso é possivel no componente `Upload`, mas não é possivel no componente `Dynamic Form` para o campo do tipo `upload`.
**Qual o …
> feat(dynamic-form): adiciona a propriedade `formField` para o  `upload`

- projects/ui/src/lib/components/po-tag/enums/po-tag-type.enum.ts
- projects/ui/src/lib/components/po-tag/po-tag-base.component.ts
- projects/ui/src/lib/components/po-tag/po-tag.component.spec.ts
- projects/ui/src/lib/components/po-tag/samples/sample-po-tag-labs/sample-po-tag-labs.component.ts
**TAG**
**DTHFUI-7639**
Implementa variação de status neutral de acordo com definições do AnimaliaDS.
**Simulação**
A variável --color-neutral, que estava definida para fazer uso da variável --color-neutral-dark-70, passa a utilizar --color-neutral-light-10. Por esse motivo as classes .po-color-neutral e .po-modal-title receberam ajuste, sendo necessário o respectivo teste nos componentes.
- Testar Labs da Tag no portal;
- Testar o Modal para verificar que po-modal-title está com o novo color-neutral;
> feat(tag): implementa variação de status neutral

- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
Corrige ordenação após pesquisa de um item na tabela mantendo a ordenação atual
**table**
**fixes DTHFUI-7716**
Não mantém a ordenação dos itens após realizar uma pesquisa
Mantém a ordenação dos itens após realizar uma pesquisa
**Simulação**
testar app com a tabela utilizando altura e sem altura:
app: 
[app.zip](https://github.com/po-ui/po-angular/files/12861188/app.zip)
> fix(table): mantém ordenação dos itens após uma pesquisa

- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.ts
Corrige posicionamento do multiselect quando colocado em uma tabela com altura
fixes DTHFUI-7742
**multiselect**
**DTHFUI-7742**
**Simulação**
testar app e samples do portal
[app.zip](https://github.com/po-ui/po-angular/files/12957128/app.zip)
> fix(listbox): corrige posicionamento

- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.component.html
**rich-text**
**DTHFUI-7755**
O formulário está sendo enviado ao escolher uma cor imediatamente.
O formulário não envia de imediato ao escolher uma cor.
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/13057863/app.zip)
Obs: Clicar bem na borda do botão para escolher cor, pois somente assim para simular a ação.
> feat(rich-text): impede envio de dados ao escolher cor

- projects/ui/src/lib/components/po-field/po-combo/interfaces/po-combo-literals-default.interface.ts
- projects/ui/src/lib/components/po-field/po-combo/interfaces/po-combo-literals.interface.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.html
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
- projects/ui/src/lib/components/po-listbox/po-listbox.component.html
- projects/ui/src/lib/components/po-listbox/po-listbox.component.spec.ts
**combo**
**DTHFUI-7500**
**Simulação**
style: https://github.com/po-ui/po-style/pull/465/files
theme: https://github.com/totvs/po-theme-totvs/pull/267
tester app e portal
app: 
[app.zip](https://github.com/po-ui/po-angular/files/13217037/app.zip)
customização:
```
/* @import url('https://fonts.googleapis.com/css2?family=Lumanosimo&family=Playfair+Display+SC&display=swap');
po-combo {
--border-radius: 20px;
--font-family: 'Lumanosimo', cursive;
--text-color-placeholder: red;
--color: green;
--text-color: blue;
--color-hover: pink;
--background-hover: yellow;
--color-focused: rgb(168, 37, 37);
--outline-color-focused: gold;
--color-disabled: rgb(198, 231, 229);
--background-disabled: …
```
> feat(combo): implementa definições do animaliaDS

- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.ts
- projects/ui/src/lib/components/po-listbox/po-item-list/po-item-list.component.html
LISTBOX, MULTISELECT E COMBO
DTHFUI-7931
Não funciona clique no checkbox do listbox.
Caso o listbox esteja aberto e o foco esteja na caixa de texto do multiselect ou combo e seja pressoniado shift + tab, o listbox permanece aberto
Funciona clique no checkbox do listbox.
Caso o listbox esteja aberto e o foco esteja na caixa de texto do multiselect ou combo e seja pressoniado shift + tab, o listbox é fechado
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/13288645/app.zip)
> fix(listbox): ajusta checkbox e fechamento via navegação por teclado

- projects/ui/src/lib/components/components.module.ts
- projects/ui/src/lib/components/index.ts
- projects/ui/src/lib/components/po-loading/po-loading-overlay/po-loading-overlay.component.html
- projects/ui/src/lib/components/po-loading/po-loading-overlay/po-loading-overlay.component.spec.ts
- projects/ui/src/lib/components/po-loading/po-loading.component.html
- projects/ui/src/lib/components/po-loading/po-loading.component.spec.ts
- projects/ui/src/lib/components/po-loading/po-loading.module.ts
- projects/ui/src/lib/components/po-overlay/index.ts
- projects/ui/src/lib/components/po-overlay/po-overlay-base.component.spec.ts
- projects/ui/src/lib/components/po-overlay/po-overlay-base.component.ts
- projects/ui/src/lib/components/po-overlay/po-overlay.component.html
- projects/ui/src/lib/components/po-overlay/po-overlay.component.spec.ts
- projects/ui/src/lib/components/po-overlay/po-overlay.component.ts
- projects/ui/src/lib/components/po-overlay/po-overlay.module.ts
**overlay**
**loading overlay**
**DTHFUI-7502**
Componente Loading Overlay traz na sua composição, uma camada pai fazendo o papel de overlay com fundo composto por rgb e alpha, e uma camada filho que carrega o po-loading, que é a caixa mais clara exibindo conteúdo. Por conta das definições do AnimaliaDS, a forma como está estruturado não atende as especificações de tokens. 
Desmembrado a camada pai que era uma div, transformando-a em um componente po-overlay. 
Com essa forma é possível atender às especificações do AnimaliaDS e reaproveitá-lo em outros componentes que atualmente se utilizam do efeito de overlay como é o caso …
> feat(loading-overlay): novo componente interno e implementações do AnimaliaDS

- projects/portal/src/app/theme-builder/theme-builder.component.css
- projects/portal/src/app/theme-builder/theme-builder.component.html
- projects/portal/src/app/theme-builder/theme-builder.component.ts
- projects/ui/src/lib/components/po-accordion/po-accordion-item-header/po-accordion-item-header.component.html
- projects/ui/src/lib/components/po-accordion/po-accordion-item-header/po-accordion-item-header.component.ts
- projects/ui/src/lib/components/po-accordion/po-accordion.component.html
- projects/ui/src/lib/components/po-accordion/po-accordion.component.ts
Construtor de temas e Accordion
DTHFUI-7944
Accordion não customiza o icone da seta nos estados de hover e pressed e não existe os componentes de multiselect, combo, accordion, breadcrumb e tag no construtor de temas.
Accordion customiza o icone da seta nos estados de hover e pressed e é implementado os componentes de multiselect, combo, accordion, breadcrumb e tag no construtor de temas.
PR Style: https://github.com/po-ui/po-style/pull/473
**Simulação**
Validar os novos componentes no construtor de temas e verificar sample do accordion
> feat(theme-builder): implementa novos componentes animalizados

- projects/ui/src/lib/components/po-dynamic/po-dynamic-field-force-component.enum.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/samples/sample-po-dynamic-form-register/sample-po-dynamic-form-register.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/samples/sample-po-dynamic-form-register/sample-po-dynamic-form-register.component.ts
O usuário poderá escolher entre um `po-checkbox` ou um `po-switch` para exibição dentro de um `po-dynamic-form`.
Fixes #1420, DTHFUI-5286
**1420**
O tipo `boolean` renderiza somente o `po-switch`.
O usuário poderá escolher entre um `po-checkbox` ou um `po-switch` para exibição dentro de um `po-dynamic-form`.
**Simulação**
Pode ser feito no portal ou pelo [App](https://github.com/po-ui/po-angular/files/9883275/app.zip).
> feat(dynamic-form): adiciona escolha entre `po-switch` ou `po-checkbox`

- projects/ui/src/lib/components/po-listbox/po-listbox.component.html
- projects/ui/src/lib/components/po-loading/po-loading-base.component.ts
- projects/ui/src/lib/components/po-loading/po-loading-overlay/po-loading-overlay-base.component.spec.ts
- projects/ui/src/lib/components/po-loading/po-loading-overlay/po-loading-overlay-base.component.ts
- projects/ui/src/lib/components/po-loading/po-loading-overlay/po-loading-overlay.component.html
- projects/ui/src/lib/components/po-loading/po-loading.component.html
- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
**loading-overlay**
**DTHFUI-8010**
Componentes listbox e table apresentam o loading desposicionado.
Adicionado propriedade p-size e ajustado posicionamento do loading
**Simulação**
Uso dos samples do po-combo e po-table no App em anexo
[app.zip](https://github.com/po-ui/po-angular/files/13530195/app.zip)
[po-style](https://github.com/po-ui/po-style/pull/476)
> feat(loading): ajusta redimensionamento do loading

- projects/ui/src/lib/components/components.module.ts
- projects/ui/src/lib/components/index.ts
- projects/ui/src/lib/components/po-badge/interfaces/po-badge-literals-default.ts
- projects/ui/src/lib/components/po-badge/interfaces/po-badge-literals.interface.ts
- projects/ui/src/lib/components/po-badge/po-badge-base.component.spec.ts
- projects/ui/src/lib/components/po-badge/po-badge-base.component.ts
- projects/ui/src/lib/components/po-badge/po-badge.component.html
- projects/ui/src/lib/components/po-badge/po-badge.component.spec.ts
- projects/ui/src/lib/components/po-badge/po-badge.component.ts
- projects/ui/src/lib/components/po-badge/po-badge.module.ts
- projects/ui/src/lib/components/po-badge/samples/sample-po-badge-basic/sample-po-badge-basic.component.html
- projects/ui/src/lib/components/po-badge/samples/sample-po-badge-basic/sample-po-badge-basic.component.ts
- projects/ui/src/lib/components/po-badge/samples/sample-po-badge-labs/sample-po-badge-labs.component.html
- projects/ui/src/lib/components/po-badge/samples/sample-po-badge-labs/sample-po-badge-labs.component.ts
- projects/ui/src/lib/components/po-badge/samples/sample-po-badge-message/sample-po-badge-message.component.css
- projects/ui/src/lib/components/po-badge/samples/sample-po-badge-message/sample-po-badge-message.component.html
- projects/ui/src/lib/components/po-badge/samples/sample-po-badge-message/sample-po-badge-message.component.ts
- projects/ui/src/lib/components/po-menu/po-menu-item/po-menu-item-badge.interface.ts
implementa definições do AnimaliaDS no componente `po-badge`
**badge**
**DTHFUI-7933**
implementa definições do AnimaliaDS no componente `po-badge`
**Simulação**
Portal
[style](https://github.com/po-ui/po-style/pull/480)
[app.zip](https://github.com/po-ui/po-angular/files/13640700/app.zip)
[themes](https://github.com/totvs/po-theme-totvs/pull/283)
> feat(badge): implementa definições do AnimaliaDS

- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view.component.ts
Implementa exibição personalizada para campos booleanos no PoDynamicView, respeitando as propriedades booleanTrue e booleanFalse
**< PoDynamicView>**
**< #1913 >**
Atualmente, o PoDynamicView trata campos booleanos exibindo os valores padrão de true ou false. Isso pode não ser ideal para a experiência do usuário, pois esses valores são técnicos e podem não transmitir claramente o significado pretendido no contexto de negócios da aplicação.
Com a nova implementação, o PoDynamicView passará a exibir valores personalizados para campos booleanos, baseando-se nas propriedades booleanTrue e booleanFalse do campo. Isso permite que …
> feat(PoDynamicView): Melhoria no PoDynamicView para Exibição Personalizada de Valores Booleanos.

- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.html
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.ts
**dynamic-page**
**DTHFUI-6660**
Não apaga input de busca rapida após realizar busca avançada
Apaga input de busca rapida após realizar busca avançada
**Simulação**
buildar antes de testar o app
[app.zip](https://github.com/po-ui/po-angular/files/13715709/app.zip)
> fix(dynamic-search): limpa campo de busca rápida

- projects/ui/src/lib/components/po-menu/po-menu-base.component.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.spec.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.ts
- projects/ui/src/lib/components/po-menu/samples/sample-po-menu-human-resources/sample-po-menu-human-resources.component.html
- projects/ui/src/lib/components/po-menu/samples/sample-po-menu-labs/sample-po-menu-labs.component.ts
Permite habilitar o automatic toggle no componente `po-menu`
**menu**
**DTHFUI-8037**
Menu colapsa e expande a partir de um evento de hover no menu
Propriedade que permite colapsar e expandir partir de um evento de hover no menu
**Simulação**
portal ou sample labs
> feat(menu): permite habilitar o automatic toggle

- projects/ui/src/lib/components/po-listbox/po-listbox.component.html
- projects/ui/src/lib/components/po-listbox/po-listbox.component.spec.ts
- projects/ui/src/lib/components/po-listbox/po-listbox.component.ts
**DTHFUI-7981**
Ao pressionar a tecla tab no checkbox de selecionar todos do multiselect o listbox se mantém aberto
Ao pressionar a tecla tab no checkbox de selecionar todos do multiselect o listbox fecha normalmente
**Simulação**
Portal
> fix(multiselect): corrige comportamento ao utilizar a tecla Tab

- projects/ui/src/lib/components/po-disclaimer-group/po-disclaimer-group-base.component.spec.ts
- projects/ui/src/lib/components/po-disclaimer-group/po-disclaimer-group-base.component.ts
- projects/ui/src/lib/components/po-disclaimer-group/po-disclaimer-group.component.html
- projects/ui/src/lib/components/po-disclaimer-group/po-disclaimer-group.component.spec.ts
- projects/ui/src/lib/components/po-disclaimer-group/po-disclaimer-group.component.ts
Reutiliza `po-tag` no componente `disclaimer-group` com nova definição de acessibilidade
fixes DTHFUI-7945
Reutiliza o po-tag dentro do disclaimer-group
**Simulação**
testar portal e app
app: 
[app.zip](https://github.com/po-ui/po-angular/files/13904516/app.zip)
> feat(disclaimer-group): reutiliza `po-tag` no componente

- projects/ui/src/lib/components/po-tag/po-tag-base.component.ts
- projects/ui/src/lib/components/po-tag/po-tag.component.html
- projects/ui/src/lib/components/po-tag/po-tag.component.spec.ts
- projects/ui/src/lib/components/po-tag/po-tag.component.ts
**TAG**
**DTHFUI-7938**
`tag` não possuia área de click mínima de 44px
`tag` passa a ter área de click mínima de 44px
**Simulação**
HTML 
```
<po-tag p-value="PO Tag" (p-click)="changeEvent('p-click')"> </po-tag>
``` 
TS
```
@Component({
})
event: string;
changeEvent(event: string) {
this.event = event;
}
}
```
- Pr adicional
https://github.com/po-ui/po-style/pull/484/checks
> feat(tag): ajusta area de click minima

- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-field.interface.ts
Adiciona método formatFields e refatora transformArrayValue
- Criado método formatFields para concatenar propriedades do objeto.
- Refatorado transformArrayValue para usar formatFields.
Fixes: #1928
**< po-dynamic-view >**
**< #1928 >**
No PoDynamicView, há uma limitação na forma como os campos que possuem um formato específico definido em suas propriedades são exibidos. Atualmente, apenas o label é apresentado, ignorando outros elementos formativos especificados. Por exemplo, em um campo configurado com o formato ["id", "nome"], somente o componente "nome" é visível na exibição, como "Carlos Diego", sem incorporar o "id" correspondente. Isso resulta em …
> feat(po-dynamic-view): adiciona format aos valores

- .github/workflows/ci.yml
- .github/workflows/publish_po_angular_ci-beta.yml
- .github/workflows/publish_po_angular_ci-latest.yml
- .github/workflows/publish_po_angular_ci-next.yml
Permite publicar no NPM com as tag's: next, latest e beta
Fixes DTHFUI-8079
Hoje existe apenas um action que envia a versão para o npm com as tag next e latest
Os actions serão separado pela tag que se deseja enviar para ao npm 
**Simulação**
Dentro do GitHub na aba "Action" executar conforme a necessidade da publicação
> ci: permite publicar no npm com tag especifica

- projects/ui/src/lib/components/po-table/interfaces/po-table-column.interface.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
Ajusta propriedade width das colunas
**table**
**DTHFUI-7754**
A definição de largura das colunas na tabela não estão funcionando conforme o esperado
A definição de largura das colunas na tabela estão funcionando conforme o esperado
**Simulação**
portal
[app.zip](https://github.com/po-ui/po-angular/files/13968183/app.zip)
[style](https://github.com/po-ui/po-style/pull/487)
> fix(table): ajusta propriedade width

- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-field.interface.ts
**< po-dynamic-view>**
**< #1933 >**
Atualmente, o po-dynamic-view não suporta a passagem de parâmetros adicionais para as requisições de serviços, limitando a contextualização dos dados apresentados.
Com a proposta de melhoria, o po-dynamic-view incluiria a nova propriedade params, permitindo a adição de parâmetros extras nas requisições de serviços de maneira dinâmica, similar aos componentes lookup e combo usados no po-dynamic-edit. Isso expandiria a funcionalidade para casos de uso que requerem contexto adicional, como filtrar dados baseados em parâmetros específicos do usuário ou da sessão.
**Simulação**
Considere um …
> feat(po-dynamic-view): adicionado a propriedade params

- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide-base.component.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide.component.html
Ajusta largura do `po-page-slide` concedendo mais flexibilidade
**page-slide**
**DTHFUI-8038**
Ao utilizar componentes grandes dentro do `po-page-slide` sua largura não era flexível e não calculava automaticamente
Ao utilizar componentes grandes dentro do `po-page-slide` sua largura e flexível é calcula automaticamente
**Simulação**
[Style](https://github.com/po-ui/po-style/pull/488)
[app.zip](https://github.com/po-ui/po-angular/files/14088214/app.zip)
> fix(page-slide): ajusta largura do `po-page-slide`

- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic.module.ts
**< po-dynamic-view >**
**< #1939 >**
Atualmente, o componente po-dynamic-view do PO UI suporta apenas a propriedade searchService para carregar dados dinamicamente. Isso limita sua funcionalidade a casos de uso onde a busca de dados é realizada através de um serviço de pesquisa, sem suportar outras formas de carregamento de dados como seleções de múltiplas opções ou combo, que são comuns no uso do po-dynamic-edit.
Com a implementação da melhoria proposta, o po-dynamic-view passará a suportar as propriedades **optionsService** e **optionsMulti**. Isso permitirá que o componente carregue automaticamente opções de dados para …
> feat(dynamic-view): adicionado optionsService e optionsMulti

- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.ts
**< po-dynammic-edit>**
**< #1950 >**
Ao clicar no botão gravar no PoPageDynamicEdit, o componente valida seus campos obrigatórios. No entanto, se houver campos do tipo lookup já preenchidos (obrigatórios ou não), ao gravar, uma alteração no model é feita. Isso dispara o método writeValue do componente lookup, que executa um GET no serviço para recarregar as informações, mesmo que desnecessariamente. Esse comportamento resulta em um custo adicional para o servidor, especialmente em telas com vários componentes lookup, onde múltiplas requisições GET são enviadas desnecessariamente apenas para validar o formulário.
Com a …
> feat(po-dynamic-edit): otimiza validacao

- projects/ui/src/lib/components/po-listbox/po-listbox.component.html
- projects/ui/src/lib/components/po-listbox/po-listbox.component.spec.ts
- projects/ui/src/lib/components/po-listbox/po-listbox.component.ts
Corrige listbox para permitir o uso de TemplateRef sem quebrar a aplicação
fixes DTHFUI-8417
**LISTBOX**
**DTHFUI-8417**
Ocorrem diversos erros no console ao utilizar templateRef no item icon da interface PoPopupAction e o componente não é renderizado da maneira correta.
O componente e o ícone devem ser apresetados corretamente. 
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/14440694/app.zip)
> fix(listbox): corrige erros ao usar TemplateRef

- projects/ui/src/lib/components/po-field/po-input/po-input-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-input/po-input-base.component.ts
feat(input): permite output através do (p-change-model)
**input**
**DTHFUI-7232**
Chamadas à formGroup.reset(), parecem não resetar o valor do model
Chamadas à formGroup.reset(), reseta e emite o valor do model
**Simulação**
portal
[app.zip](https://github.com/po-ui/po-angular/files/14364568/app.zip)
> feat(input): permite output através do `(p-change-model)`

- .github/workflows/ci.yml
- .github/workflows/publish_po_angular_ci-beta.yml
- docs/guides/migration-poui.md
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-list-base.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-list-base.component.ts
- scripts/update-version.js
**< PoPageDynamicTable >**
**< 1998 >**
O componente PoPageDynamicTable não estava aplicando corretamente a ordem das colunas quando algumas possuíam a propriedade **order** definida ou não. Isso causava inconsistência na visualização dos dados, afetando a experiência do usuário.
Agora, o PoPageDynamicTable assegura a correta ordenação de todas as colunas, independente de possuírem ou não a propriedade **order** definida. Colunas sem order são agora consistentemente posicionadas após as colunas com order definido, preservando a ordem relativa entre elas conforme especificado.
**Simulação**
Para simular o comportamento, é …
> fix(po-page-dynamic-table): aplica ordem correta as colunas

- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide.component.ts
**< PAGE-SLIDE >**
**< DTHFUI-8413 >**
**Qual é o comportamento atual?**
Mesmo tendo o botão de fechar visível, o primeiro foco acaba sendo no elemento seguinte. No exemplo da issue, era um accordion localizado em uma posição mais abaixo de outras informções, resultando em uma experiência ruim para o usuário pois nesse caso ocorria a rolagem da tela por conta do foco no respectivo campo.
**Qual é o novo comportamento?**
Ao abrir o page-slide o primeiro foco estará no botão de fechar. 
Somente se [p-hide-close]="true"  [p-click-out]="true" é que não será exibido o ícone de fechar e consequentemente o foco estará no primeiro elemento que for encontrado.
**Simulação**
No app em anexo, …
> fix(page-slide): ajusta regra do foco no elemento

- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.ts
**po-dynamic-view**
** 8512**
Ocorre uma duplicação de alguns campos mostrados no dynamicview, quando esses campos não possue valor ou eles estão com visibilidade falsa
correção feita, não ocorre mais a duplicata dos campos
**Simulação**
- Abrir na documentação [PO-UI > dynamic view](https://po-ui.io/documentation/po-dynamic-view). O Ultimo exemplo tem campos com visible false, que estava duplicando o campo 'city'
> fix(dynamic-view): Correção campos duplicados no dynamicview

- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide.component.ts
**PAGE-SLIDE**
**DTHFUI-8546**
Não havia cobertura para pageContent.nativeElement
Implementado cobertura.
**Simulação**
Rodar npm run test:ui para constatar a cobertura do teste.
> fix(page-slide): cobre teste para pageContent

- projects/templates/src/lib/components/po-page-dynamic-edit/interfaces/po-page-dynamic-edit-literals.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.ts
**PAGE-DYNAMIC-EDIT**
*DTHFUI-8576**
Atualmente não é possível definir o tipo de alerta na validação.
Adicionado propriedade p-notification-type onde é possível especificar se o tipo da notificação será 'warning' ou 'error'.
**Simulação**
No app em anexo, acessar no navegador o end-point /aluno e clicar no botão Gravar;
Por padrão aparecerá a notificação tipo 'warning'.
Ao selecionar a opção "Notification type Error" e clicar novamente no botão Gravar, deverá aparecer a notificação do tipo 'error'
[app.zip](https://github.com/po-ui/po-angular/files/14795674/app.zip)
> feat(page-dynamic-edit): inclui p-notification-type para definir o tipo de notificação na validação

- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
Altera para `null` 'selectedValue' e 'selectedOption' usando `setInputValue`
**combo**
**DTHFUI-8405**
Não tem ação no 'p-change' após usar o método do combo: 'setInputValue(null)';
Ao limpar o combo utilizando o método, 'setInputValue(null)', altera para `null` 'selectedValue' e 'selectedOption'
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/14499065/app.zip)
> fix(combo): Altera para `null` 'selectedValue' e 'selectedOption'

- projects/ui/src/lib/components/po-search/interfaces/po-search-option.interface.ts
- projects/ui/src/lib/components/po-search/po-search-base.component.ts
- projects/ui/src/lib/components/po-search/po-search.component.html
- projects/ui/src/lib/components/po-search/po-search.component.spec.ts
- projects/ui/src/lib/components/po-search/po-search.component.ts
- projects/ui/src/lib/components/po-search/po-search.module.ts
- projects/ui/src/lib/components/po-search/samples/sample-po-search-labs/sample-po-search-labs.component.html
- projects/ui/src/lib/components/po-search/samples/sample-po-search-labs/sample-po-search-labs.component.ts
- projects/ui/src/lib/components/po-search/samples/sample-po-search-listbox/sample-po-search-listbox.component.html
- projects/ui/src/lib/components/po-search/samples/sample-po-search-listbox/sample-po-search-listbox.component.ts
- projects/ui/src/lib/components/po-search/samples/sample-po-search-listbox/sample-po-search-listbox.service.ts
**po-search**
**DTHFUI-7812**
Não tem a opção de ter um listbox ao fazer uma pesquisa 
Implementação da propriedade 't-show-listbox'.
Com essa propriedade ativa, sempre ira mostrar uma listbox das opções informadas, quando houver mudança no input. ela também obedece a regra do filterKeys
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/14727927/app.zip)
> feat(search): inclusão do listbox ao fazer o search

- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-heroes/sample-po-table-heroes.component.html
**TABLE**
**DTHFUI-8743**
Quebra de linha nos textos das colunas não é possivel 
Quebra de linha nos textos das colunas é possivel 
**Simulação**
[app-wrap.zip](https://github.com/po-ui/po-angular/files/15168700/app-wrap.zip)
PR adicional
- https://github.com/po-ui/po-style/pull/535
> feat(table): adiciona propriedade `textWrap`

- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.html
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-hotels/sample-po-page-dynamic-table-hotels.component.html
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-hotels/sample-po-page-dynamic-table-hotels.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/samples/sample-po-page-dynamic-table-people/sample-po-page-dynamic-table-people.component.html
**DYNAMIC-TABLE**
**DTHFUI-8744**
Componente `dynamic-table` não possui propriedades `textWrap` e `spacing` 
Componente `dynamic-table` compartilha propriedades `textWrap` e `spacing`  de `po-table`
**Simulação**
Portal e app 
-  [app-8747.zip](https://github.com/po-ui/po-angular/files/15308015/app-8747.zip)
> feat(dynamic-table): repassa propriedade p-spacing e p-text-wrap

- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.html
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-labs/sample-po-lookup-labs.component.html
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-labs/sample-po-lookup-labs.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/services/po-lookup-modal.service.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/services/po-lookup-modal.service.ts
**PoLookup**
**DTHFUI-8745>**
Atualmente o PoLookup exibe a tabela sem considerar o tamanho de espaçamento e quebra de texto, características já presentes na PoTable.
Realizado repasse das propriedades p-spacing e p-text-wrap já presentes na PoTable
**Simulação**
Nesta branch é possível subir o portal e testar o PoLookup Labs, as propriedades p-spacing e p-text-wrap estão disponíveis em tela para teste.
> feat(lookup): inclui p-spacing e p-text-wrap

- projects/ui/src/lib/components/po-table/enums/po-table-spacing.enum.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.ts
**PoTable**
**DTHFUI-8742**
Mesmo atribuindo p-sizing="small" a tabela ainda apresentava um espaçamento não tão pequeno entre os itens e colunas, dificultando a visualização dos dados em casos em que uma tabela venha conter um grande número de colunas e itens a serem exibidos.
A tabela passa assumir dimenssões menores nos ícones de "sort" e "draggable", o espaçamento dentro da célula foi reduzido e o p-sizing="small" passa a ser aplicável mesmo que a tabela passe a ser interativa. Entende-se interativa, tabela com p-selectable='true' ou que contenha colunas do tipo detail ou link, ou que possua ações por linha. …
> feat(table): Permite maior visibilidade de itens e colunas

- projects/ui/src/lib/components/po-menu/po-menu-item.interface.ts
- projects/ui/src/lib/components/po-menu/po-menu-item/po-menu-item.component.html
- projects/ui/src/lib/components/po-menu/po-menu.module.ts
Adiciona tooltip para exibir shortLabel no menu colapsado
fixes DTHFUI-8903
A propriedade shortLabel é obrigatória para colapsar o menu porém não é exibida em nenhum momento
A propriedade shortLabel segue sendo obrigatória para colapsar o menu, porém agora o valor da mesma será exibido através de um tooltip
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/15335904/app.zip)
Testar samples do portal
> feat(menu): adiciona tooltip para exibição do shortLabel

- projects/ui/src/lib/components/po-disclaimer/po-disclaimer-base.component.ts
- projects/ui/src/lib/components/po-disclaimer/po-disclaimer.component.html
- projects/ui/src/lib/components/po-disclaimer/po-disclaimer.component.spec.ts
- projects/ui/src/lib/components/po-disclaimer/po-disclaimer.component.ts
Adiciona propriedades internas afim de adequar ao lookup.
fixes DTHFUI-8646
N/A
Adiciona propriedades internas no disclaimer para o último disclaimer do lookup ser clicável.
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/15042652/app.zip)
> feat(disclaimer): adiciona propriedades internas

- projects/ui/src/lib/components/po-menu/po-menu-item/po-menu-item.component.html
**MENU**
** DTHFUI-8947**
Tootip com shortLabel não sobrepõe elementos da página.
Tootip com shortLabel sobrepõe elementos da página.
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/15393996/app.zip)
> fix(menu): corrige sobreposicao

- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
**COMBO**
**DTHFUI-8744**
Ao abrir um po-combo com valor inicial atribuído o scroll é acionado para dar foco no componente.
Ao abrir um po-combo com valor inicial atribuído o mesmo não interferi na jornada do usuário.
**Simulação**
[app-new-8774.zip](https://github.com/po-ui/po-angular/files/15421973/app-new-8774.zip)
style.css global
```
.spacing-lg {
margin-top: 450px; 
}
```
> fix(combo): corrige inicialização do focus

- projects/ui/src/lib/components/po-dropdown/po-dropdown.component.html
- projects/ui/src/lib/components/po-dropdown/po-dropdown.component.spec.ts
- projects/ui/src/lib/components/po-dropdown/po-dropdown.component.ts
- projects/ui/src/lib/components/po-search/index.ts
- projects/ui/src/lib/components/po-search/interfaces/po-search-filter-select.interface.ts
- projects/ui/src/lib/components/po-search/literals/po-search-literals-default.ts
- projects/ui/src/lib/components/po-search/literals/po-search-literals.ts
- projects/ui/src/lib/components/po-search/po-search-base.component.ts
- projects/ui/src/lib/components/po-search/po-search.component.html
- projects/ui/src/lib/components/po-search/po-search.component.spec.ts
- projects/ui/src/lib/components/po-search/po-search.component.ts
- projects/ui/src/lib/components/po-search/po-search.module.ts
- projects/ui/src/lib/components/po-search/samples/sample-po-search-filter-select/sample-po-search-filter-select.component.html
- projects/ui/src/lib/components/po-search/samples/sample-po-search-filter-select/sample-po-search-filter-select.component.ts
- projects/ui/src/lib/components/po-search/samples/sample-po-search-labs/sample-po-search-labs.component.html
- projects/ui/src/lib/components/po-search/samples/sample-po-search-labs/sample-po-search-labs.component.ts
**po-search**
**8644**
Adição da propriedade `p-filter-select`, a propriedade define os tipos de filtros (p-filter-keys) a serem aplicados na busca ou lista do componente (p-items).
Hoje o Componente search não possui uma seletor para qual tipo de buscar fazer.
Com a nova propriedade é possui enviar mais de um tipo de filtro de busca, alterando o `p-filter-keys`
**Simulação**
[dthfui8644_simulação.zip](https://github.com/po-ui/po-angular/files/15236867/dthfui8644_simulacao.zip)
> feat(search): inclusão da propriedade se filterSelect

- projects/ui/src/lib/services/po-theme/po-theme.service.ts
**Serviço de Tema**
**DTHFUI-9022**
Na troca de Tema, não esta mostrando o icone do po-select
Agora quando troca o tema, esta mostrando o icone com a cor definida no po-select
cénario com erro:
https://stackblitz.com/edit/pouitheme-1pezca 
Simulação
[app.zip](https://github.com/user-attachments/files/15514852/app.zip)
> fix(tema): correção do icone no po-select

- projects/ui/src/lib/components/po-field/po-clean/po-clean.component.html
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.html
- projects/ui/src/lib/components/po-menu/po-menu-filter/po-menu-filter.component.spec.ts
- projects/ui/src/lib/components/po-search/po-search.component.html
**CLEAN | COMBO**
**DTHDUI-8875**
Ícone do `po-clean` não é consistente em todos os componentes apresentando o ícone indicado pelo AnimaliaDS.
Ícone do `po-clean` é consistente em todos os componentes apresentando o ícone indicado pelo AnimaliaDS.
**Simulação**
[app-8875.zip](https://github.com/po-ui/po-angular/files/15476190/app-8875.zip)
PR Adicional
- https://github.com/po-ui/po-style/pull/552
> feat(clean): atualiza icone definido pelo animalia

- projects/ui/src/lib/components/po-tabs/po-tab/po-tab-base.component.ts
- projects/ui/src/lib/components/po-tabs/po-tab/po-tab.component.spec.ts
- projects/ui/src/lib/components/po-tabs/po-tab/po-tab.component.ts
- projects/ui/src/lib/components/po-tabs/po-tabs.component.html
- projects/ui/src/lib/components/po-tabs/po-tabs.component.spec.ts
- projects/ui/src/lib/components/po-tabs/po-tabs.component.ts
- projects/ui/src/lib/components/po-tabs/po-tabs.service.ts
Permite a reordenação das abas visíveis quando uma aba do dropdown é selecionada. Ao selecionar uma aba do dropdown, ela se torna visível, e a última aba visível anteriormente é movida para o dropdown.
Isso proporciona uma melhor experiência de usuário ao gerenciar um grande número de abas.
Fixes DTHFUI-8578
**< po-tabs >**
**< DTHFUI-8578 >**
Ao selecionar uma aba do dropdown não há nenhum comportamento visual, fazendo com que o usuário fique com a dúvida se selecionou a aba ou não.
Ao selecionar uma aba do dropdown, ela se torna visível, e a última aba visível anteriormente é movida para o dropdown.
Isso proporciona uma …
> feat(tabs): adiciona reordenação visual das abas

- projects/ui/src/lib/components/po-disclaimer/po-disclaimer-base.component.ts
- projects/ui/src/lib/components/po-disclaimer/po-disclaimer.component.ts
PO-DISCLAIMER
fixes DTHFUI-9088
Disclaimer só exibe tooltip caso seja maior que 201px
Disclaimer exibe tooltip caso seja maior que o valor da nova propriedade criada. Seu valor default continua sendo 201.
**Simulação**
[app.zip](https://github.com/user-attachments/files/15686397/app.zip)
> feat(disclaimer): adiciona propriedade para validar exibição do tooltip

- projects/ui/src/lib/components/po-tabs/po-tabs.component.spec.ts
- projects/ui/src/lib/components/po-tabs/po-tabs.component.ts
Corrige a emissão do Output p-click para disparar
corretamente.
fixes DTHFUI-9176
**Simulação**
[app.zip](https://github.com/user-attachments/files/15890379/app.zip)
> fix(tabs): corrige emissão de evento p-click

- projects/ui/src/lib/services/po-theme/helpers/po-theme-dark-defaults.constant.ts
**po-toaster**
**DTHFUI-9230**
po-toaster está sobrepondo outros componentes e no tema dark, a cor do ícone warning não está da cor esperada.
Foi corrigido o z-index do po-toaster para não ficar sobreposto a outros componentes e a cor do ícone do tipo `warning` para cor escura no tema dark
**Simulação**
[simulacao.zip](https://github.com/user-attachments/files/16054896/simulacao.zip)
> fix(toaster): corrige z-index e cor ícone warning no tema dark

- projects/ui/src/lib/components/po-stepper/po-stepper-base.component.spec.ts
- projects/ui/src/lib/components/po-stepper/po-stepper-base.component.ts
po-stepper
DTHFUI-8956
O componente po-stepper não está obedecendo o status `disabled`.
Corrigido o comportamento do po-stepper para desabilitar quando status for `disabled`.
**Simulação**
[simulacao.zip](https://github.com/user-attachments/files/16074830/simulacao.zip)
> fix(stepper): corrige status disabled do stepper

- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
po-table
DTHFUI-9159
O componente po-table quando carregado dentro de uma po-modal, está apresentando erro no `console`.
Corrigido a inicialização do po-table que causava o erro no `console`.
**Simulação**
[simulacao.zip](https://github.com/user-attachments/files/16089206/simulacao.zip)
> fix(table): corrige erro no console

- projects/ui/src/lib/components/po-tabs/po-tab-dropdown/po-tab-dropdown.component.spec.ts
- projects/ui/src/lib/components/po-tabs/po-tab-dropdown/po-tab-dropdown.component.ts
Foi realizado uma correção no posicionamento do dropdown. (Ao utilizar o po-tabs com tabs agrupadas pelo dropdown o listbox não abre na posição correta estando dentro de um po-page-default)
fixes DTHFUI-9361
**PO-TABS**
**DTHFUI-9361**
Ao utilizar o po-tabs com tabs agrupadas pelo dropdown o listbox não abre na posição correta.
o po-tabs esta abrindo corretamente
**Simulação**
simular no portal
> fix(tabs): corrige posicionamento do dropdown

- projects/templates/src/lib/components/po-page-login/po-page-login-base.component.ts
- projects/templates/src/lib/components/po-page-login/po-page-login.component.html
Permite desabilitar ou habilitar o autocomplete no campo de login e senha individualmente e também permite habilitar ou desabilitar a funcionalidade de espiar a senha.
**Simulação**
> feat(page-login): permite desabilitar o autocomplete

- projects/ui/src/lib/components/po-menu/po-menu-base.component.spec.ts
- projects/ui/src/lib/components/po-menu/po-menu-base.component.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.spec.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.ts
- projects/ui/src/lib/components/po-menu/samples/sample-po-menu-labs/sample-po-menu-labs.component.html
- projects/ui/src/lib/components/po-menu/samples/sample-po-menu-labs/sample-po-menu-labs.component.ts
**PO-MENU**
**DTHFUI-8971**
O componente po-menu não possui uma propriedade de busca que retorne por itens agrupadores do menu.
Adiciona propriedade p-search-tree-items para que o filtro do componente retorne resultados de itens agrupadores do menu.
**Simulação**
Labs do po-menu no portal.
> feat(menu): adiciona propriedade p-search-tree-items

- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.component.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.service.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.service.ts
Adiciona a propriedade `extraFormData` no evento `p-upload` e  nesta propriedade pode ser informado algum dado solicitado pela API que não possa estar no objeto `data`, assim o conteúdo será extraído do objeto e enviado como parâmetro.
Fixes #1395
**Upload**
**1395**
Não é possível enviar um parâmetro para a API fora do objeto `data`, ou seja, o atributo precisa estar diretamente no `body`.
Agora é possível inserir alguns dados no objeto `extraFormData`, que serão extraídos e enviados como parâmetro para API diretamente no `body`.
**Simulação**
Pode ser feito pelo portal ou pelo …
> feat(upload): adiciona o parâmetro `extraFormData` no evento `p-upload`

- projects/ui/src/lib/components/po-tree-view/po-tree-view-item/po-tree-view-item.component.html
- projects/ui/src/lib/components/po-tree-view/po-tree-view-item/po-tree-view-item.component.ts
**Treeview**
**8465**
o tree view expande dentro do page-slide após o fechamento
o tree view não expande dentro do page-slide após o fechamento
**Simulação**
app e portal
[app.zip](https://github.com/user-attachments/files/16442730/app.zip)
> Treeview/dthf UI 8465

- projects/templates/src/lib/components/po-page-job-scheduler/index.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-summary/index.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-summary/po-job-scheduler-summary-template/index.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-summary/po-job-scheduler-summary-template/po-job-scheduler-summary-template.directive.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-summary/po-job-scheduler-summary-template/po-job-scheduler-summary-template.directive.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-summary/po-page-job-scheduler-summary.component.html
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-summary/po-page-job-scheduler-summary.component.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.html
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.module.ts
- projects/templates/src/lib/components/po-page-job-scheduler/samples/sample-po-page-job-scheduler-directives/sample-po-page-job-scheduler-directives.component.html
- projects/templates/src/lib/components/po-page-job-scheduler/samples/sample-po-page-job-scheduler-directives/sample-po-page-job-scheduler-directives.component.ts
Cria diretiva para poder customizar as informações no sumário.
fixes DTHFUI-9306
N/A
Permite customizar a exibição de resumo na etapa de sumário do job-scheduler através de uma nova diretiva, utilizando ng-template.
**
[app (31).zip](https://github.com/user-attachments/files/16553035/app.31.zip)
Simulação**
> feat(job-scheduler): cria diretiva p-job-scheduler-summary-template

- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.html
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.ts
- projects/ui/src/lib/components/po-listbox/po-listbox-base.component.ts
- projects/ui/src/lib/components/po-listbox/po-listbox.component.html
- projects/ui/src/lib/components/po-listbox/po-listbox.component.spec.ts
- projects/ui/src/lib/components/po-listbox/po-listbox.component.ts
- projects/ui/src/lib/components/po-loading/po-loading-overlay/po-loading-overlay-base.component.ts
- projects/ui/src/lib/components/po-loading/po-loading-overlay/samples/sample-po-loading-overlay-labs/sample-po-loading-overlay-labs.component.html
- projects/ui/src/lib/components/po-loading/po-loading-overlay/samples/sample-po-loading-overlay-labs/sample-po-loading-overlay-labs.component.ts
**po-listbox**
**DTHFUI-8490**
Componente loading-overlay não está respeitando as dimensões do po-listbox. 
Ajusta dimensões do loading-overlay no componente po-listbox.
**Simulação**
[DTHFUI-8490_simulacao.zip](https://github.com/user-attachments/files/16630078/DTHFUI-8490_simulacao.zip)
> fix(listbox): ajusta dimensões do loading-overlay no po-listbox

- projects/ui/src/lib/components/po-tabs/po-tabs.component.ts
As tabs eram adicionadas na lista dropdown antes da rotina que define a criação do dropdown com tabs ativas.
Fixes DTHFUI-9602
**< TABS >**
**< DTHFUI-9602 >**
Ao iniciar o componente po-tabs com uma tab ativa, mesmo esta sendo a primeira visível em tela, ela é apresentada por último na lista.
Ao iniciar uma tab como ativa, se ela não estiver sendo exibida no dropdown ela deve manter o posicionamento inicial dela;
Tabs que iniciaram no dropdown e estão ativas devem continuar sendo exibidas por último na listagem visível (fora do dropdown);
**Simulação**
Samples do portal e/ou app po-angular em anexo …
> fix(tabs): corrige renderização das tabs no estado inicial do componente

- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/samples/sample-po-dynamic-view-employee/sample-po-dynamic-view-employee.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/samples/sample-po-dynamic-view-employee/sample-po-dynamic-view-employee.component.ts
**PO-DYNAMIC-VIEW**
**DTHFUI-9446**
O componente po-dynamic-view não preserva as quebras de linha dos dados recebidos da API.
Adiciona a propriedade p-text-wrap para garantir que as quebras de linha (\n) sejam respeitadas na visualização dos dados.
**Simulação**
> feat(dynamic-view): adiciona propriedade p-text-wrap

- projects/ui/src/lib/components/po-popup/samples/sample-po-popup-basic/sample-po-popup-basic.component.html
- projects/ui/src/lib/components/po-popup/samples/sample-po-popup-basic/sample-po-popup-basic.component.ts
- projects/ui/src/lib/components/po-toolbar/po-toolbar-notification/po-toolbar-notification.component.html
- projects/ui/src/lib/components/po-toolbar/po-toolbar-notification/po-toolbar-notification.component.spec.ts
- projects/ui/src/lib/components/po-toolbar/po-toolbar-notification/po-toolbar-notification.component.ts
**PO-TOOLBAR**
**DTHFUI-9586**
Closes #2172 
o popup da notificação da toolbar, esta aparecendo em local incorreto na tela.
corrigido o posicionamento ao abrir a popup da notificação no toolbar, tanto em tamanhos de tela pequena, quanto grande.
**Simulação**
[simulacao_dthfui-9586.zip](https://github.com/user-attachments/files/16853380/simulacao_dthfui-9586.zip)
> fix(toolbar): corrige posicionamento do popup ao abrir notificação

- projects/ui/src/lib/components/po-logo/po-logo.component.html
- projects/ui/src/lib/components/po-logo/po-logo.component.spec.ts
- projects/ui/src/lib/components/po-logo/po-logo.component.ts
- projects/ui/src/lib/components/po-menu/po-menu-base.component.spec.ts
- projects/ui/src/lib/components/po-menu/po-menu-base.component.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.html
- projects/ui/src/lib/components/po-menu/samples/sample-po-menu-labs/sample-po-menu-labs.component.html
- projects/ui/src/lib/components/po-menu/samples/sample-po-menu-labs/sample-po-menu-labs.component.ts
**Menu**
**DTHFUI-9495**
Hoje o logo do menu possue apenas um link para a pagina inicial `./`
Adicionado customização ao link do logo, através da propriedade `[p-logo-link]`. 
Aceitando:
- caso true, rota padrão `./`; 
- caso false, não terá link associado; 
- caso string, define a rota para o link informado.
**Simulação**
[simulação_9495.zip](https://github.com/user-attachments/files/16935786/simulacao_9495.zip)
> feat(menu): customiza link do logo

- projects/ui/src/lib/components/po-stepper/po-step/po-step.component.ts
- projects/ui/src/lib/components/po-stepper/po-stepper-base.component.spec.ts
- projects/ui/src/lib/components/po-stepper/po-stepper-base.component.ts
- projects/ui/src/lib/components/po-stepper/po-stepper-circle/po-stepper-circle.component.html
- projects/ui/src/lib/components/po-stepper/po-stepper-circle/po-stepper-circle.component.spec.ts
- projects/ui/src/lib/components/po-stepper/po-stepper-circle/po-stepper-circle.component.ts
- projects/ui/src/lib/components/po-stepper/po-stepper-item.interface.ts
- projects/ui/src/lib/components/po-stepper/po-stepper-label/po-stepper-label.component.html
- projects/ui/src/lib/components/po-stepper/po-stepper-label/po-stepper-label.component.spec.ts
- projects/ui/src/lib/components/po-stepper/po-stepper-label/po-stepper-label.component.ts
- projects/ui/src/lib/components/po-stepper/po-stepper-step/po-stepper-step.component.html
- projects/ui/src/lib/components/po-stepper/po-stepper-step/po-stepper-step.component.spec.ts
- projects/ui/src/lib/components/po-stepper/po-stepper-step/po-stepper-step.component.ts
- projects/ui/src/lib/components/po-stepper/po-stepper.component.html
- projects/ui/src/lib/components/po-stepper/po-stepper.component.spec.ts
- projects/ui/src/lib/components/po-stepper/po-stepper.component.ts
- projects/ui/src/lib/components/po-stepper/po-stepper.module.ts
- projects/ui/src/lib/components/po-stepper/samples/sample-po-stepper-active/sample-po-stepper-active.component.html
- projects/ui/src/lib/components/po-stepper/samples/sample-po-stepper-basic/sample-po-stepper-basic.component.html
- projects/ui/src/lib/components/po-stepper/samples/sample-po-stepper-labs/sample-po-stepper-labs.component.html
- projects/ui/src/lib/components/po-stepper/samples/sample-po-stepper-labs/sample-po-stepper-labs.component.ts
- projects/ui/src/lib/components/po-stepper/samples/sample-po-stepper-sales/sample-po-stepper-sales.component.html
- projects/ui/src/lib/components/po-stepper/samples/sample-po-stepper-steps/sample-po-stepper-steps.component.html
- projects/ui/src/lib/components/po-stepper/samples/sample-po-stepper-steps/sample-po-stepper-steps.component.ts
**PO-STEPPER**
**DTHFUI-9714**
Após as implementações do animalia, os steps passaram a ser alinhados à esquerda no modo horizontal e ao topo no modo vertical.
Adiciona propriedade p-align-center que permite o alinhamento centralizado dos steps em ambas as orientações.
**Simulação**
[DTHFUI-9714_simulacao.zip](https://github.com/user-attachments/files/16999961/DTHFUI-9714_simulacao.zip)
> feat(stepper): adiciona propriedade p-align-center

- projects/ui/src/lib/services/index.ts
- projects/ui/src/lib/services/po-media-query/index.ts
- projects/ui/src/lib/services/po-media-query/po-media-query.interface.ts
- projects/ui/src/lib/services/po-media-query/po-media-query.module.ts
- projects/ui/src/lib/services/po-media-query/po-media-query.service.spec.ts
- projects/ui/src/lib/services/po-media-query/po-media-query.service.ts
- projects/ui/src/lib/services/services.module.ts
**PoMediaQueryService**
**DTHFUI-9851**
Atualmente, os navegadores não interpretam a leitura de variáveis em regras de breakpoint como por exemplo:
@media (min-width: var(--variavel-customizavel))
Disponibilizamos os tokens de breakpoint no formato var(--nome-da-variavel) junto as regras de media query permitindo ao desenvolvedor realizar a customização dos breakpoints em tempo de execução através do serviço PoMediaQueryService.
Para mais informações:
http://localhost:4200/guides/grid-system (necessário build do po-style para o correto funcionamento pos é dependência) https://github.com/po-ui/po-style/pull/629/files …
> feat(media-query): implementa serviço para media query customizável

- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
Corrige direcionamento de rota interna e externa quando utilizado `PageCustomAction`
fixes: DTHFUI-9660
**Simulação**
https://github.com/po-ui/po-angular/pull/2238
> fix(dynamic-table): corrige rota no PageCustomAction

- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
Corrige direcionamento de rota interna e externa quando utilizado `PageCustomAction`
fixes: DTHFUI-9660
**Simulação**
[app.zip](https://github.com/user-attachments/files/17282615/app.zip)
> fix(dynamic-table): corrige rota no `PageCustomAction`

- projects/ui/src/lib/components/po-page/po-page-slide/index.ts
- projects/ui/src/lib/components/po-page/po-page-slide/interfaces/po-page-slide-literals.interface.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide-base.component.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide-footer/po-page-slide-footer.component.html
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide-footer/po-page-slide-footer.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide-footer/po-page-slide-footer.component.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide.component.html
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide.component.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide.module.ts
- projects/ui/src/lib/components/po-page/po-page-slide/samples/sample-po-page-slide-configuration/sample-po-page-slide-configuration.component.html
- projects/ui/src/lib/components/po-page/po-page-slide/samples/sample-po-page-slide-configuration/sample-po-page-slide-configuration.component.ts
- projects/ui/src/lib/services/po-media-query/po-media-query.service.ts
- projects/ui/src/lib/services/po-theme/helpers/po-theme-dark-defaults.constant.ts
Implementa definições do animaliaDS no page-slide
fixes DTHFUI-9873
**Simulação**
[app.zip](https://github.com/user-attachments/files/17365455/app.zip)
https://github.com/po-ui/po-style/pull/641
https://github.com/totvs/po-theme-totvs/pull/389
```
@import url('https://fonts.googleapis.com/css2?family=Londrina+Sketch&family=Sixtyfour+Convergence&display=swap');
/* TOKENS ATUAIS DO FIGMA e NOVOS */
/* :root {
--transition-duration: 1000ms;
--transition-timing: 1000ms ease-in;
} */
/* po-page-slide {
--background-color: red;
--border-color: blue;
--color-overlay: green;
--font-family: 'Londrina Sketch', sans-serif;
--padding-footer: 100px;
} */ …
```
> feat(page-slide): implementa definições do animalia-DS

- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table-detail/po-table-detail.component.html
- projects/ui/src/lib/components/po-table/po-table-detail/po-table-detail.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-detail/po-table-detail.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
**PO-TABLE**
**DTHFUI-7346**
Ao selecionar um registro filho (master detail) do componente po-table, o elemento pai não fica indeterminate
Ao selecionar um registro filho (master detail) do componente po-table, o elemento pai fica indeterminate
**Simulação**
[app-7346.zip](https://github.com/user-attachments/files/17347132/app-7346.zip)
> fix(table): aplica regra indeterminate no checkbox

- projects/ui/src/lib/components/po-accordion/po-accordion-item-header/po-accordion-item-header.component.html
- projects/ui/src/lib/components/po-accordion/po-accordion-item-header/po-accordion-item-header.component.spec.ts
- projects/ui/src/lib/components/po-accordion/po-accordion-item-header/po-accordion-item-header.component.ts
- projects/ui/src/lib/components/po-accordion/po-accordion-manager/po-accordion-manager.component.html
- projects/ui/src/lib/components/po-accordion/po-accordion-manager/po-accordion-manager.component.spec.ts
- projects/ui/src/lib/components/po-accordion/po-accordion-manager/po-accordion-manager.component.ts
- projects/ui/src/lib/components/po-accordion/po-accordion.module.ts
Corrige texto estourando a tela no accordion
fixes DTHFUI-9636
**Simulação**
> fix(accordion): corrige texto grande no componente

- projects/ui/src/lib/components/po-accordion/po-accordion-item-header/po-accordion-item-header.component.html
- projects/ui/src/lib/components/po-accordion/po-accordion-item-header/po-accordion-item-header.component.spec.ts
- projects/ui/src/lib/components/po-accordion/po-accordion-item-header/po-accordion-item-header.component.ts
- projects/ui/src/lib/components/po-accordion/po-accordion-manager/po-accordion-manager.component.html
- projects/ui/src/lib/components/po-accordion/po-accordion-manager/po-accordion-manager.component.spec.ts
- projects/ui/src/lib/components/po-accordion/po-accordion-manager/po-accordion-manager.component.ts
- projects/ui/src/lib/components/po-accordion/po-accordion.module.ts
Corrige texto estourando a tela no accordion
fixes DTHFUI-9636
**Simulação**
> fix(accordion): corrige texto grande no componente (17)

- projects/ui/src/lib/components/po-page/po-page-default/po-page-default-base.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-default/po-page-default-base.component.ts
- projects/ui/src/lib/components/po-page/po-page-default/po-page-default.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-default/po-page-default.component.ts
A propriedade `visible` do `PoPageAction` não estava funcionando como função, apenas como `boolean`.
Foi feito um ajuste para que a mesma funcione como função de forma semelhante a propriedade `disabled`, conforme indica a documentação.
Fixes #1836
**Page Default**
**1836**
A propriedade `visible` do `PoPageAction` não estava funcionando como função, apenas como `boolean`.
Foi feito um ajuste para que a mesma funcione como função de forma semelhante a propriedade `disabled`, conforme indica a documentação.
**Simulação**
Para simulação pode ser usado o [APP](https://github.com/user-attachments/files/17451731/app.zip).
> fix(page-default): ajusta propriedade `visible` do `PoPageAction`

- projects/ui/src/lib/components/po-page/po-page-default/po-page-default-base.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-default/po-page-default-base.component.ts
- projects/ui/src/lib/components/po-page/po-page-default/po-page-default.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-default/po-page-default.component.ts
**PO-PAGE-DEFAULT**
**1836**
A propriedade `visible` do `PoPageAction` não estava funcionando como função, apenas como `boolean`.
Foi feito um ajuste para que a mesma funcione como função de forma semelhante a propriedade `disabled`, conforme indica a documentação
**Simulação**
[DTHFUI-10070_contribuição-1836_simulacao.zip](https://github.com/user-attachments/files/17512697/DTHFUI-10070_contribuicao-1836_simulacao.zip)
> fix(page-default): ajusta propriedade visible do PoPageAction

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.ts
Corrige requisição repetidade em campos de serviço ao atualizar dados
fixes DTHFUI-10114
**Simulação**
app: 
[app.zip](https://github.com/user-attachments/files/17542564/app.zip)
> fix(dynamic-form): corrige requisição repetida

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.ts
Corrige requisição repetidade em campos de serviço ao atualizar dados
fixes DTHFUI-10114
**Simulação**
> fix(dynamic-form): corrige requisição repetida (v17)

- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.service.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.service.ts
Ajustado a diferença entre a data selecionada e a data submitida para API
**<po-page-job-scheduler>**
**DTHFUI-10152**
Ao enviar a data selecionara para API existe uma diferenção de 1 dia a menos
Ao enviar a data selecionada para API a data se mantém a mesma informada pelo usuário
**Simulação**
Utilizar o portal para simular
> fix(page-job-scheduler): ajusta diferença na data selecionada

- projects/ui/src/lib/components/po-field/po-lookup/interfaces/po-lookup-literals.interface.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.html
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.html
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.ts
**PO-LOOKUP**
**DTHFUI-9693**
Atualmente o po-lookup não contempla uma navegação pelo ícone de pesquisa do input nem tão pouco pelo ícone de limpar o valor contido nele, deixando a navegação pelo teclado uma experiência limitada.
Implementa definições Animalia no po-lookup:
Recebe comportamento semelhante do modo trigger do po-search onde possibilita navegar pelo input, realizar consulta, apagar o(s) valor(es) e abrir a modal, pelo teclado.
Mantém o estilo e a customização animalia;
Traz a compatibilidade para leitor de tela;
**Simulação**
1 - No app em anexo é possível simular o uso do componente pela navegação pelo …
> feat(lookup): implementa definições animalia-DS

- projects/ui/src/lib/components/po-field/index.ts
- projects/ui/src/lib/components/po-field/po-rich-text/enum/po-rich-text-toolbar-actions.enum.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-base.component.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.component.html
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.component.spec.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.component.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text.component.html
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text.component.spec.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text.component.ts
- projects/ui/src/lib/components/po-field/po-rich-text/samples/sample-po-rich-text-labs/sample-po-rich-text-labs.component.html
- projects/ui/src/lib/components/po-field/po-rich-text/samples/sample-po-rich-text-labs/sample-po-rich-text-labs.component.ts
**PO-RICHTEXT**
**DTHFUI-9923**
Hoje existe somente a possibilidade de ocultar o alinhamento de texto.
Implementação da propriedade 'p-hide-toolbar-actions'. Com essa propriedade, será possível passar os botões do toolbar que serão ocultados do toolbar. Se for passado todas as opções existentes ('color', 'align', 'format', 'list', 'link', 'media'), a toolbar não será exibida.
**Simulação**
> buildar o po-style e adicionar no po-angular, via `.tgz`, `verdaccio` ou `copiando o dist`.
- Testar Portal po-ui / exemplo LABS do Richtext
```
npm run build:ui // build po-ui
npm run build:portal // build portal
npm run start portal …
```
> feat(richtext): inclusão propriedade para ocultar botões do toolbar

- projects/ui/src/lib/components/po-field/po-input/po-mask.spec.ts
- projects/ui/src/lib/components/po-field/po-input/po-mask.ts
Corrige erro ao focar no botão e pressionar teclas diferentes de `enter` e `space`
DTHFUI-9908
**Simulação**
> fix(date-picker): corrige erro no console (17)

- projects/ui/src/lib/services/po-theme/po-theme.service.ts
- Verificação da cor aplicada no ícone do po-select através do serviço de troca de tema.
Fixes #2154, chevron-down/DTHFUI-9679
**Simulação**
> fix(chevron-down): ajusta cores dos componentes conforme AnimaliaDS

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.spec.ts
Dynamic-Form
DTHFUI-10180
A propriedade optionsService nao aceita ser tipada com a interface PoMultiselectFilter
A propriedade optionsService aceita ser tipada com a interface PoMultiselectFilter
**Simulação**
[app.zip](https://github.com/user-attachments/files/17817090/app.zip)
> fix(dynamic-form): adiciona interface de multiselect em optionsService

- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.component.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.html
- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-labs/sample-po-upload-labs.component.html
- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-labs/sample-po-upload-labs.component.ts
- projects/ui/src/lib/components/po-progress/po-progress-base.component.spec.ts
- projects/ui/src/lib/components/po-progress/po-progress-base.component.ts
- projects/ui/src/lib/components/po-progress/po-progress.component.html
- projects/ui/src/lib/components/po-progress/samples/sample-po-progress-labs/sample-po-progress-labs.component.html
- projects/ui/src/lib/components/po-progress/samples/sample-po-progress-labs/sample-po-progress-labs.component.ts
Upload e Progress
N/A
Cria nova propriedade p-disabled-remove-file que permite desabilitar o botão de remover o arquivo no po-upload.
Cria nova propriedade p-disabled-cancel que permite desabilitar o botão no canto inferior direito do po-progresso que dispara o evento de p-cancel
**Simulação**
[app.zip](https://github.com/user-attachments/files/17806425/app.zip)
> feat(upload): cria propriedade p-disabled-remove-file

- projects/ui/src/lib/components/po-accordion/po-accordion.module.ts
- projects/ui/src/lib/components/po-list-view/po-list-view.module.ts
- projects/ui/src/lib/components/po-navbar/po-navbar.module.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide-base.component.ts
- projects/ui/src/lib/components/po-slide/po-slide.module.ts
- projects/ui/src/lib/components/po-tree-view/po-tree-view.module.ts
Atualiza a documentação do po-accordion, page-slide, list-view, tree-view e navBar para suportar aplicações standalone.
Para standalone:
- Usar CommonModule ao invés de BrowserModule.
- Adicionar configuração de bootstrap com BrowserAnimationsModule.
accordion/DTHFUI-9707
> docs(components): ajusta documentação para aplicações standalone

- projects/ui/src/lib/components/po-chart/po-chart.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart.component.ts
**PO-CHART**
**DTHFUI-10263**
Corrige espaço em branco gerado ao atribuir números quebrados nas séries dentro de um po-widget.
**Simulação**
[DTHFUI-10263.zip](https://github.com/user-attachments/files/17847631/DTHFUI-10263.zip)
> fix(chart): corrige espaço em branco

- projects/ui/src/lib/services/po-theme/po-theme.service.ts
- Verificação da cor aplicada no ícone do po-select através do serviço de troca de tema.
chevron-down/DTHFUI-9679
> fix(combo/select): ajusta cores do chevron-down conforme AnimaliaDS

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.ts
Corrige erro ao setar visibilidade nos campos quando dentro de um container
fixes DTHFUI-10270
**DTHFUI-10270**
Ao setar a visibilidade de um campo dentro de um container não era respeitado está configuração
Ao setar a visibilidade de um campo dentro de um container respeita está configuração
**Simulação**
[DTHFUI-10270.zip](https://github.com/user-attachments/files/17815426/DTHFUI-10270.zip)
> fix(dynamic-form): corrige erro de visibilidade campos no container

- projects/ui/src/lib/components/po-chart/index.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-path-coordinates.interface.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-points-coordinates.interface.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-serie-data-label.interface.ts
- projects/ui/src/lib/components/po-chart/po-chart-base.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-container.component.html
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-container.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-container.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-line/po-chart-line-base.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-line/po-chart-line-base.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-line/po-chart-line.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-line/po-chart-line.component.svg
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-line/po-chart-line.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-line/po-chart-series-point/po-chart-series-point.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-line/po-chart-series-point/po-chart-series-point.component.svg
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-line/po-chart-series-point/po-chart-series-point.component.ts
- projects/ui/src/lib/components/po-chart/po-chart.component.html
- projects/ui/src/lib/components/po-chart/po-chart.component.ts
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-labs/sample-po-chart-labs.component.html
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-labs/sample-po-chart-labs.component.ts
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-world-exports/sample-po-chart-world-exports.component.html
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-world-exports/sample-po-chart-world-exports.component.ts
**PO-CHART**
**DTHFUI-10134**
Hoje o gráfico do tipo line não tem a possibilidade do valor das series estarem sempre visiveis
Implementação da propriedade 'p-data-label', onde é possível passar a propriedade `fixed`. Com essa propriedade (fixed=tue), irar alterar o grafico do tipo line.
- O valor da series ficar sendo exibido fixado com uma background transparente.
- Não será mostrado o tooltip ao hover do bullet.
- Será adicionado uma opacidade a todas outras series quando selecionado uma delas.
- O hover da serie ficará ate selecionar outra ou sair do gráfico.
ex. funcionalidade
**Simulação** …
> feat(chart): inclusão propriedade `p-data-label` para chart tipo `line`

- projects/ui/src/lib/components/po-button/index.ts
- projects/ui/src/lib/components/po-button/po-button-base.component.ts
- projects/ui/src/lib/components/po-button/po-button-type.enum.ts
- projects/ui/src/lib/components/po-button/po-button.component.html
- projects/ui/src/lib/components/po-button/po-button.component.spec.ts
- projects/ui/src/lib/components/po-button/samples/sample-po-button-labs/sample-po-button-labs.component.html
- projects/ui/src/lib/components/po-button/samples/sample-po-button-labs/sample-po-button-labs.component.ts
po-button
DTHFUI-10009
Nao e possivel alterar o atributo type do button, ficando sempre fixo como type=button
Adiciona o Input `type` ao componente po-button.
**Simulação**
```
<po-button p-label="Type: button (default)"></po-button>
<po-button p-label="Type: submit" p-type="submit"></po-button>
```
> feat(button): adiciona input type

- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view.component.ts
Ajusta renderização de campo com multiplas opções.
Fixes #2308
**Dynamic-View**
**2308**
Componente não renderiza corretamente campo com múltiplas opções selecionadas. 
Componente renderiza corretamente campo com múltiplas opções selecionadas. 
**Simulação**
Pode ser realizada com o [APP](https://github.com/user-attachments/files/17853471/app.zip)
> fix(dynamic-view): ajusta renderização do multiselect

- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.service.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.service.ts
Corrigo erro quando 'firstExecution' é definido como undefined
fixes DTHFUI-10385
**page-job-scheduler**
**DTHFUI-10385**
Ao definir `firstExecution` como undefined um erro é apresentado no console
Ao definir `firstExecution` como undefined não deve ser apresentado no console
**Simulação**
[DTHFUI-10385.zip](https://github.com/user-attachments/files/18030031/DTHFUI-10385.zip)
> fix(page-job-scheduler): corrige erro quando 'firstExecution' undefined

- .gitignore
- projects/app/src/app/app.module.ts
- projects/portal/src/app/app.component.ts
- projects/portal/src/app/theme-builder/theme-builder.component.css
- projects/portal/src/app/theme-builder/theme-builder.component.html
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.html
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range.component.html
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.html
- projects/ui/src/lib/po.module.ts
- projects/ui/src/lib/services/po-theme/enum/po-theme-a11y.enum.ts
- projects/ui/src/lib/services/po-theme/enum/po-theme-type.enum.ts
- projects/ui/src/lib/services/po-theme/helpers/accessibilities/po-theme-default-aa.constant.ts
- projects/ui/src/lib/services/po-theme/helpers/accessibilities/po-theme-default-aaa.constant.ts
- projects/ui/src/lib/services/po-theme/helpers/po-theme-poui.constant.ts
- projects/ui/src/lib/services/po-theme/helpers/types/po-theme-dark-defaults.constant.ts
- projects/ui/src/lib/services/po-theme/helpers/types/po-theme-light-defaults.constant.ts
- projects/ui/src/lib/services/po-theme/index.ts
- projects/ui/src/lib/services/po-theme/interfaces/po-theme.interface.ts
- projects/ui/src/lib/services/po-theme/po-theme.service.spec.ts
- projects/ui/src/lib/services/po-theme/po-theme.service.ts
- projects/ui/src/lib/services/po-theme/samples/sample-po-theme-labs/sample-po-theme-labs.component.ts
Adicionado possibilidade de passar mais de uma opção de tema  de acessibilidade como exemplo: ‘AA’ e ‘AAA’.
**DTHFUI-9037**
Atuamente não é possivel passar diferentes tipos de acessibilidade do mesmo tema
COm nova implementação agora pode passar varios temas com diferentes tipos de acessibilidade
**Simulação**
segue um exemplo de uso:
```
theme = {
name: 'custom',
type: [
{
light: {},
dark: {},
accessibility: PoThemeAccessibilityEnum.AA
},
{
light: {},
dark: {},
accessibility: PoThemeAccessibilityEnum.AAA
}
],
active: {
type: PoThemeTypeEnum.light,
accessibility: PoThemeAccessibilityEnum.AAA
}
};
```
> feat(theme): Adicionado melhoria no tema para diferentes acessibilidades

- projects/ui/src/lib/components/po-stepper/po-stepper-base.component.ts
- projects/ui/src/lib/components/po-stepper/po-stepper-label/po-stepper-label.component.html
- projects/ui/src/lib/components/po-stepper/po-stepper-label/po-stepper-label.component.ts
- projects/ui/src/lib/components/po-stepper/po-stepper-step/po-stepper-step.component.html
- projects/ui/src/lib/components/po-stepper/po-stepper-step/po-stepper-step.component.spec.ts
- projects/ui/src/lib/components/po-stepper/po-stepper-step/po-stepper-step.component.ts
- projects/ui/src/lib/components/po-stepper/po-stepper.component.html
- projects/ui/src/lib/components/po-stepper/samples/sample-po-stepper-labs/sample-po-stepper-labs.component.html
- projects/ui/src/lib/components/po-stepper/samples/sample-po-stepper-labs/sample-po-stepper-labs.component.ts
Cria propriedade `p-disable-click` para desabilitar o clique no step
DTHFUI-9924
> feat(stepper): cria a propriedade `p-disable-click`

- projects/ui/src/lib/components/po-field/po-input/po-input-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-input/po-input-base.component.ts
- projects/ui/src/lib/components/po-field/po-input/samples/sample-po-input-labs/sample-po-input-labs.component.html
- projects/ui/src/lib/components/po-field/po-input/samples/sample-po-input-labs/sample-po-input-labs.component.ts
- projects/ui/src/lib/components/po-field/validators.spec.ts
- projects/ui/src/lib/components/po-field/validators.ts
**PO-INPUT**
**DTHFUI-10421**
Hoje ao passar uma mascara junto com comprimentos mínimos (minLength) ou máximos (maxLength), ele contabiliza os caracteres especiais ao valor do input incorretamente,
Adicionada a propriedade `p-mask-no-length-validation` ao componente `po-input` para permitir que caracteres especiais definidos na máscara sejam ignorados ao validar os comprimentos mínimos (minLength) e máximos (maxLength).
Essa funcionalidade garante maior flexibilidade ao lidar com máscaras, como no exemplo de números de telefone ou CEP, onde os caracteres especiais não devem interferir na validação do comprimento do valor. …
> feat(input): inclusão da propriedade `p-mask-no-length-validation`

- projects/ui/src/lib/components/po-accordion/po-accordion-item-header/po-accordion-item-header.component.html
- projects/ui/src/lib/components/po-accordion/po-accordion-manager/po-accordion-manager.component.html
- projects/ui/src/lib/components/po-accordion/samples/sample-po-accordion-labs/sample-po-accordion-labs.component.html
Adicionado o controle sobre o evento emitido pela tecla Enter no corpo de dados do accordion-item para o mesmo parmenecer aberto quando o usuário apertar a tecla Enter em outros campos dentro do accordion-item O evento de abrir/fechar o accordion permanece funcionando quando o foco está no cabeçalho Ajusta o posicionamento da tag em relação ao título fixes DTHFUI-10166
**Simulação**
> fix(accordion): corrige eventos de teclado e alinha tag ao título

- .github/workflows/ci.yml
A versão v3 do action upload-artifact foi depreciada, impedindo a esteira CI.
Essa alteração atualiza para a versão mais recente seguindo a documentação de migração fornecida pelo action upload-artifact
**< GitHub Actions CI>**
**< DTHFUI-10689 >**
A versão v3 do action upload-artifact foi depreciada, impedindo a esteira CI.
Essa alteração atualiza para a versão mais recente seguindo a documentação de migração fornecida pelo action upload-artifact
**Simulação**
Esteira CI após criação de pull request nas branches master e 17.x.x
> build(ci): atualiza versão do action upload-artifact

- projects/ui/src/lib/components/po-accordion/po-accordion-item-header/po-accordion-item-header.component.html
- projects/ui/src/lib/components/po-accordion/po-accordion-manager/po-accordion-manager.component.html
- projects/ui/src/lib/components/po-accordion/samples/sample-po-accordion-labs/sample-po-accordion-labs.component.html
Alterado o tipo do botão dentro do componente accordion-item-body de submit para button, evitando que o formulário seja enviado ao pressionar a tecla Enter.
Essa alteração impede que o Accordion feche inesperadamente quando a tecla Enter é pressionada em campos de entrada.
fixes DTHFUI-10166
Ao pressionar a tecla Enter em um input que está dentro do componente accordion-item-body o Componente Accordion realiza o evento de fechar todos os itens.
A tecla Enter não dispara o envio do formulário, pois o botão foi alterado para o tipo button, mantendo os itens do Accordion abertos.
**Simulação**
Samples no portal.
[app_dthfui10166.zip](https://github.com/user-attachments/files/18430027/app_dthfui10166.zip)
> fix(accordion): ajusta tipo do botão para evitar envio de formulário

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.ts
**PO-DYNAMIC-FORM**
**DTHFUI-10604**
Componentes po-lookup e po-datepicker-range não estão emitindo evento para p-validate quando a alteração de valor é feita através da interação com o botão.
Corrige a emissão do evento para p-validate em campos com alteração de valor através de interações com botões.
**Simulação**
[DTHFUI-10604_simulacao.zip](https://github.com/user-attachments/files/18440072/DTHFUI-10604_simulacao.zip)
> fix(dynamic-form): ajusta emissão de evento para p-validate

- projects/ui/src/lib/components/po-chart/enums/po-chart-label-format.enum.ts
- projects/ui/src/lib/components/po-chart/index.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-axis-options.interface.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-axis/po-chart-axis-label/po-chart-axis-label.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-axis/po-chart-axis-label/po-chart-axis-label.component.svg
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-axis/po-chart-axis-label/po-chart-axis-label.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-axis/po-chart-axis.component.svg
- projects/ui/src/lib/components/po-chart/po-chart.module.ts
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-coffee-ranking/sample-po-chart-coffee-ranking.component.ts
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-labs/sample-po-chart-labs.component.html
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-labs/sample-po-chart-labs.component.ts
**po-chart**
**#2358**
O po-chart não permite formatação numérica ou monetária do eixo de valor, dificultando a visualização de valores muito altos. 
Foram adicionadas novas propriedades nas opções do gráfico que possibilitam informar o tipo dos valores do eixo e outra propriedade para especificar a formatação dos valores.
Agora os valores do gráfico podem ser formatados de forma numérica ou monetária.
**Simulação**
Esta correção pode ser validada na seção Coffee Ranking da documentação do po-chart. Alguns gráficos foram alterados para ilustrar o uso desta propriedade, facilitando a compreensão do usuário.
Esta correção …
> feat(chart): adiciona possibilidade de formatação do eixo de valor

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
- projects/ui/src/lib/components/po-listbox/po-item-list/po-item-list.component.spec.ts
- projects/ui/src/lib/components/po-listbox/po-item-list/po-item-list.component.ts
**PO-COMBO**
**DTHFUI-10068**
Atualmente a propriedade p-remove-initial-filter aplica-se apenas ao p-options, sendo assim, quando montado uma lista de ítens pelo p-filter-service não é considerado a funcionalidade de p-remove-initial-filter.
Ajustado para que p-remove-initial-filter funcione tanto com p-options como para p-filter-service.
Também repassado para po-dynamic-form-field a propriedade removeInitialFilter para atuar com a funcionalidade p-remove-initial-filter.
**Simulação**
[app.zip](https://github.com/user-attachments/files/18233106/app.zip)
> feat(combo): considera p-remove-initial-filter junto ao p-filter-service

- projects/ui/src/lib/components/po-popover/po-popover-base.component.ts
- projects/ui/src/lib/components/po-popover/po-popover.component.html
- projects/ui/src/lib/components/po-popover/po-popover.component.ts
- projects/ui/src/lib/components/po-popover/po-popover.module.ts
**PO-POPOVER**
**DTHFUI-7133**
Ao incluir o po-popover via template no PO-table ou THF-Grid com virtual-scroll habilitado, o mesmo abre na posição incorreta.
Adiciona `p-append-in-body` para corrigir o posicionamento do `po-popover` quando usado dentro de um `po-table` com altura definida e virtual scroll habilitado.
**Simulação**
[DTHFUI-7133_app.zip](https://github.com/user-attachments/files/18671863/DTHFUI-7133_app.zip)
> fix(popover): corrige posicionamento no po-table com virtual scroll

- projects/ui/src/lib/services/po-i18n/index.ts
- projects/ui/src/lib/services/po-i18n/interfaces/po-i18n-config-context.interface.ts
- projects/ui/src/lib/services/po-i18n/interfaces/po-i18n-config.interface.ts
- projects/ui/src/lib/services/po-i18n/po-i18n-base.service.spec.ts
- projects/ui/src/lib/services/po-i18n/po-i18n-base.service.ts
- projects/ui/src/lib/services/po-i18n/po-i18n-config-injection-token.ts
- projects/ui/src/lib/services/po-i18n/po-i18n.module.ts
- projects/ui/src/lib/services/po-i18n/po-i18n.service.spec.ts
- projects/ui/src/lib/services/po-i18n/po-i18n.service.ts
Resolvido problema onde os literais da lib não eram carregados quando a lib era adicionada em um app que também utiliza i18n.
Habilitado o I18N_CONFIG com multi: true
Conforme previso na documentação, informava-se: "Caso existam literais comuns na aplicação, estas devem ser reimportadas".
A partir deste commit foi implementado o provider I18N_CONFIG com multi: true, permitindo que múltiplas configurações de internacionalização (i18n) sejam injetadas como um array de configurações, ao invés de sobrescrever uma única configuração.
Desta forma, se no app, determinado literal não for definido, será considerado o literal da lib.
Fixes DTHFUI-10440
> fix(i18n): corrigido conflito de literais entre app e lib no PO UI

- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
Corrige alinhamento do texto "nenhum dado encontrado" sem dados. Adiciona função auxiliar para unificar condições extras de coluna. Mantém compatibilidade com temas e design tokens.
Fixes DTHFUI-8450
> fix(table): ajusta contagem de colunas extras na po-table

- projects/ui/src/lib/components/po-table/po-table.component.html
**PO-TABLE**
**DTHFUI-9372**
Ao definir uma tabela que contenha uma coluna do tipo detalhe, embutida em um ngTemplate, há diferença de posicionamento do ícone arrow se comparado a uma tabela que possui a coluna de detalhes apenas definida no Array de objetos do (p-columns).
Não há evidencia no figma do PoTable que informe que deva ter esta diferença de posicionamento do ícone arrow. Lá está definido que deve estar a esquerda do ícone de ações da respectiva linha;
Ajustado a lógica no template do componente para que em ambos os casos o ícone arrow seja posicionado a esquerda do ícone de ações;
**Simulação**
No app em anexo …
> fix(table): corrige posição do ícone arrow para coluna detalhe

- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
Ocorriam diversos warnings no console do navegador ao utilizar o po-table com po-column-template, mesmo quando as propriedades estavam sendo alimentadas corretamente.
Agora, a exibição dos warnings ocorre apenas quando necessário, garantindo que o componente opere de forma correta e sem mensagens indesejadas no console.
Fixes DTHFUI-9561
Ocorriam diversos warnings no console do navegador ao utilizar o po-table com po-column-template, mesmo quando as propriedades estavam sendo alimentadas corretamente.
Agora, a exibição dos warnings ocorre apenas quando necessário, garantindo que o componente opere de forma correta e sem mensagens indesejadas no …
> fix(table): corrige warnings indesejados ao utilizar po-column-template

- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.ts
Corrige remoção de opção do po-multiselect para valor falsy.
Fixes DTHFUI-9922
**Simulação**
> fix(multiselect): corrige remoção da tag para value 0

- projects/ui/src/lib/components/po-stepper/po-stepper-base.component.ts
- projects/ui/src/lib/components/po-stepper/po-stepper-item.interface.ts
- projects/ui/src/lib/components/po-stepper/po-stepper.component.spec.ts
- projects/ui/src/lib/components/po-stepper/po-stepper.component.ts
**PO-STEPPER**
[DTHFUI-10914]
Para navegação entre os steps utilizando o seletor po-step:
Quando o step selecionado é o último da lista,  ao retornar para o step anterior  o serviço configura a propriedade canActiveNextStep para o valor false. Essa ação impede a navegação para o próximo step já que o serviço entende que não pode habilitar o próximo step.
Para navegação entre os steps utilizando a lista p-steps:
Não é possível avançar para o próximo.
Navegação livre de bloqueios caso os formulários e as ativações dos steps estiverem válidos.
Para navegação entre os steps utilizando a lista p-steps:
Foi adicionado um id interno para validação e …
> fix(stepper): corrige navegação entre os steps

- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-table/services/po-table.service.spec.ts
- projects/ui/src/lib/components/po-table/services/po-table.service.ts
Ao utilizar mais de uma po-table com serviço habilitado e endpoints diferentes, o botão de carregar mais de todas as tabelas estava requisitando no mesmo serviço.
Agora, cada po-table requisita corretamente ao endpoint configurado no componente, sem interferência nas demais.
Comportamento esperado:
- Cada po-table com serviço habilitado deve chamar corretamente o endpoint configurado ao clicar em 'Carregar mais'.
- O botão de carregar mais não interfere nas requisições das outras tabelas."
Fixes DTHFUI-10553
> fix(table): corrige requisição de múltiplas tabelas

- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
- projects/ui/src/lib/components/po-field/po-select/po-select.component.spec.ts
- projects/ui/src/lib/components/po-field/po-select/po-select.component.ts
Adiciona nova propriedade 'p-control-value-with-label' que permite o componente receber e devolver objeto do tipo {value: any, label: any}
**select, combo e multiselect**
**DTHFUI-10599**
Quando p-control-value-with-label for true deve retorna o model do componente como um objeto do tipo `{value: any, label: any}`
**Simulação**
[DTHFUI-10599_poui.zip](https://github.com/user-attachments/files/18972551/DTHFUI-10599_poui.zip)
> feat(components): adiciona nova propriedade 'p-control-value-with-label'

- projects/ui/src/lib/services/po-i18n/index.ts
- projects/ui/src/lib/services/po-i18n/interfaces/po-i18n-config-context.interface.ts
- projects/ui/src/lib/services/po-i18n/interfaces/po-i18n-config.interface.ts
- projects/ui/src/lib/services/po-i18n/po-i18n-base.service.spec.ts
- projects/ui/src/lib/services/po-i18n/po-i18n-base.service.ts
- projects/ui/src/lib/services/po-i18n/po-i18n-config-injection-token.ts
- projects/ui/src/lib/services/po-i18n/po-i18n.module.ts
- projects/ui/src/lib/services/po-i18n/po-i18n.service.spec.ts
- projects/ui/src/lib/services/po-i18n/po-i18n.service.ts
Ajustado `getLiterals()` para garantir que as literais sejam exibidas corretamente, independente da configuração utilizada. Agora, ao utilizar o PO UI e o THF-Components, o serviço i18n realiza o merge das literais da aplicação client e das bibliotecas de terceiros, evitando sobreposição indevida e garantindo a exibição esperada.
Fixes DTHFUI-10854
> feat(i18n): garantir merge correto de literais no PO UI e THF-Components

- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.ts
**PO Datepicker**
**DTHFUI-9953**
Ao atribuir um valor inválido no datepicker e pressionar a tecla TAB a mensagem de data inválida some tornando o campo válido novamente erroneamente.
Ao atribuir um valor inválido no datepicker e pressionar a tecla TAB a mensagem de data inválida é apresentada e o campo  permanece inválido.
**Simulação**
[app.component.zip](https://github.com/user-attachments/files/19008365/app.component.zip)
> fix(datapicker): corrige validação do campo

- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.ts
Corrige seleção de registros do lookup para o modo múltiplo.
Fixes DTHFUI-10695
**Simulação**
> fix(lookup): corrige seleção de registros no modo múltiplo

- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.ts
Corrige o comportamento da exibição do value ao
utilizar optionsService em campos com container.
Fixes DTHFUI-10548
**Simulação**
> fix(dynamic-view): corrige utilização de optionsService em container

- projects/ui/src/lib/components/po-tabs/po-tabs-base.component.ts
O componente po-tabs implementa apenas o token --background, que altera a cor de fundo do componente por inteiro. Adiciona o token --background-item-default para permitir a customização da cor de fundo do item padrão separadamente da cor de fundo de todo o po-tabs.
Fixes: DTHFUI-10947
**po-tabs**
**DTHFUI-10947**
Atualmente não é possível alterar a cor de fundo dos botões padrão de forma dinâmica e separada da cor de fundo do container do po-tabs, alterando por completo o fundo do componente.
Adiciona o token --background-item-default para customizar apenas a cor de fundo dos itens padrões renderizados no po-tabs. …
> feat(tabs): adiciona o token --background-item-default

- package.json
Os pacotes custom-idle-queue na versão 3.0.1 e @angular-devkit/build-angular na versão ~19.0.4 dependem de uma versão vulnerável do @babel/runtime. Adiciona o override em ambos os pacotes para utilizar o @babel/runtime ~7.26.10, primeira versão com a vulnerabilidade corrigida.
Fixes: DTHFUI-11004
**storage**
**DTHFUI-11004**
Dois pacotes do po-ui, "custom-idle-queue" e "@angular-devkit/build-angular" dependem da biblioteca @babel/runtime em uma [versão vulnerável](https://github.com/advisories/GHSA-968p-4wvh-cqc8), sendo acusado no comando "npm audit" e em processos de análise de código:
Com a definição de dois overrides no …
> fix(storage): sobrescreve dependência vulnerável @babel/runtime

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/interfaces/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/samples/sample-po-dynamic-form-container/sample-po-dynamic-form-container.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-hotels/sample-po-combo-hotels.component.html
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-labs/sample-po-combo-labs.component.html
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-labs/sample-po-combo-labs.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/samples/sample-po-multiselect-any-array/sample-po-multiselect-any-array.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/samples/sample-po-multiselect-labs/sample-po-multiselect-labs.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/samples/sample-po-multiselect-labs/sample-po-multiselect-labs.component.ts
- projects/ui/src/lib/components/po-listbox/po-listbox.component.spec.ts
- projects/ui/src/lib/services/po-control-position/po-control-position.service.ts
Adiciona a propriedade `p-listbox-control-position` aos componentes po-multiselect e po-combo, permitindo definir a posição preferencial do listbox (acima ou abaixo do campo). A funcionalidade também foi repassada para o po-dynamic-form.
fixes DTHFUI-10389
**Simulação**
> feat(listbox): adiciona propriedade para controle de posição

- projects/ui/src/lib/components/po-chart-new/po-chart-grid-utils.ts
- projects/ui/src/lib/components/po-chart-new/po-chart-grid.utils.spec.ts
- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.html
- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.spec.ts
- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.ts
> feat(charts): implementa chart do tipo pie

- projects/ui/src/lib/services/po-theme/po-theme.service.spec.ts
- projects/ui/src/lib/services/po-theme/po-theme.service.ts
- Garantir que baseStyle e theme sejam inseridos no início do <head>
- Estilos do usuário (styles.scss) são carregados após as definições do framework
- Documentação atualizada para orientar customizações corretamente
fixes DTHFUI-11244
**Simulação**
> fix(theme): ajusta ordem de inserção de estilos no DOM

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.spec.ts
**po-lookup**
**DTHFUI-10860 e #2430**
DTHFUI-10860: Ao utilizar o po-lookup single, de forma individual ou no dynamic-form, o valor não é preenchido corretamente quando o searchService retorna uma resposta no padrão de coleção utilizado pelo PO-UI, não exibindo o valor definido programaticamente.
#2430: Ao utilizar o po-lookup, caso seja inserido "." no campo de busca do componente e pressionado o botão "tab" do teclado (removido o foco), são adicionados todos os itens retornados pelo searchService.
DTHFUI-10860: Corrige o preenchimento do valor do componente, passando a aceitar as respostas no padrão de coleção e objeto …
> fix(lookup): corrige o preenchimento do valor do componente e corrige preenchimento múltiplo ao pesquisar "."

- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-labs/sample-po-lookup-labs.component.html
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-labs/sample-po-lookup-labs.component.ts
- projects/ui/src/lib/components/po-table/enums/po-table-spacing.enum.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table-icon/po-table-icon.component.html
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.ts
**PO-TABLE**
**DTHFUI-10661**
A propriedade p-spacing do po-table disponibiliza atualmente três opções de espaçamento: large, medium e small.
Adiciona a opção de espaçamento extraSmall, que é disponibilizada automaticamente quando o nível de acessibilidade AA estiver configurado por meio do serviço de tema. Essa nova opção também passa a ser aplicada nos componentes que consomem o po-table, como po-lookup e po-dynamic-table.
**Simulação**
> feat(table): adiciona tamanho extraSmall ao p-spacing

- README.md
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.ts
**PO-DYNAMIC-FORM**
**DTHFUI-10571**
Ao aplicar a propriedade visible dinamicamente em campos semelhantes (mesmo componente), sem o uso de um container, o primeiro campo afeta os valores dos campos seguintes.
Corrige o comportamento quando o visible é aplicado de forma dinâmica, garantindo que campos com ou sem divider sejam exibidos corretamente.
**Simulação**
> fix(dynamic-form): corrige visible dinâmico dos campos

- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.ts
- projects/ui/src/lib/components/po-field/po-input/po-input-base.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.ts
Adiciona chamadas ao markForCheck no método validate dos componentes po-datepicker, po-input e po-multiselect para garantir que as mensagens de erro sejam exibidas imediatamente ao sujar o campo (dirty/touched).
Resolve o problema onde a view só atualizava após foco ou blur, não refletindo o erro de forma imediata.
fixes DTHFUI-11419
**Simulação**
> feat(fields): atualiza renderização de mensagens ao manipular forms

- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.ts
- projects/ui/src/lib/components/po-field/po-input/po-input-base.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.ts
Adiciona chamadas ao markForCheck no método validate dos componentes po-datepicker, po-input e po-multiselect para garantir que as mensagens de erro sejam exibidas imediatamente ao sujar o campo (dirty/touched).
Resolve o problema onde a view só atualizava após foco ou blur, não refletindo o erro de forma imediata.
fixes DTHFUI-11419
**< po-datepicker, po-input e po-multiselect >**
**< DTHFUI-11419 >**
**Simulação**
> fix(fields): atualiza renderização de mensagens ao manipular forms

- projects/ui/src/lib/components/po-listbox/po-listbox.component.html
- projects/ui/src/lib/components/po-listbox/po-listbox.component.spec.ts
- projects/ui/src/lib/components/po-listbox/po-listbox.component.ts
- projects/ui/src/lib/components/po-popup/po-popup.component.html
**po-toolbar**
**DTHFUI-10678**
Ao incluir mais do que 6 actions no componente po-toolbar o mesmo deixa de apresentar a linha de profile.
Quando são incluídos mais de 6 ações no componente po-toolbar, a linha do profile é exibida no topo do po-toolbar:
**Simulação**
> fix(toolbar): corrige exibição do profile ao renderizar scroll

- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.html
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
**PO-COMBO**
**DTHFUI-10960**
Não possue suporte de navegação por teclado entre o input e o listbox quando usado o append-in-body
Adiciona navegação por teclado e suporte a leitores de tela no modo append-in-body, implementando fluxo de Tab e Arrow-down para abrir o listbox
**Simulação**
<po-combo 
name="combo2" 
p-label="PO Combo" 
[p-options]="[{ value: 'Option 1' }, { value: 'Option 2' }]"
[p-clean]="true"
p-append-in-body="true"
> </po-combo>
> feat(combo): implementar acessibilidade com append-in-body

- projects/ui/src/lib/components/po-chart/interfaces/po-chart-options.interface.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-serie-data-label.interface.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-serie.interface.ts
- projects/ui/src/lib/components/po-chart/po-chart-grid-utils.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-grid-utils.ts
- projects/ui/src/lib/components/po-chart/po-chart.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart.component.ts
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-labs/sample-po-chart-labs.component.html
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-labs/sample-po-chart-labs.component.ts
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-stacked/sample-po-chart-stacked.component.html
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-stacked/sample-po-chart-stacked.component.ts
PO-CHART
DTHFUI-11561
O chart do tipo donut ao possuir um texto centralizado e passar o mouse sobre ele, acaba exibindo a tooltip e aplicando foco à primeira serie.
Permite agrupar todas ou algumas series nos gráficos do tipo Bar e Column. Para o efeito de aplicar foco à primeira serie ao passar o mouse sobre o texto centralizado do donut.
**Simulação**
[app.zip](https://github.com/user-attachments/files/20927129/app.zip)
> feat(chart): implementa nova funcionalidade stacked

- projects/ui/src/lib/components/po-modal/po-modal.component.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide.component.ts
- projects/ui/src/lib/services/services.module.ts
Corrige o erro "Maximum call stack size exceeded", mantendo apenas o providedIn root do PoActiveOverlayService, e garante a remoção correta dos IDs de overlays fechadas.
Fixes DTHFUI-11114
**po-active-overlay**
**DTHFUI-11114**
Atualmente, é possível criar múltiplas instâncias do PoActiveOverlayService, mesmo que ele seja um serviço com `providedIn: 'root'`. Esse comportamento pode ocasionar o erro "Maximum call stack size exceeded" em cenários de renderização de um modal dentro de um page-slide com componente dinamicamente criados.
Remove a importação e exportação do PoActiveOverlayModule que estava presente no …
> fix(overlay): evita múltiplas instâncias do PoActiveOverlayService - v17

- projects/ui/src/lib/components/po-modal/po-modal.component.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide.component.ts
- projects/ui/src/lib/services/services.module.ts
Corrige o erro "Maximum call stack size exceeded", mantendo apenas o providedIn root do PoActiveOverlayService, e garante a remoção correta dos IDs de overlays fechadas.
Fixes DTHFUI-11114
**po-active-overlay**
**DTHFUI-11114**
Atualmente, é possível criar múltiplas instâncias do PoActiveOverlayService, mesmo que ele seja um serviço com `providedIn: 'root'`. Esse comportamento pode ocasionar o erro "Maximum call stack size exceeded" em cenários de renderização de um modal dentro de um page-slide com componente dinamicamente criados.
Remove a importação e exportação do PoActiveOverlayModule que estava presente no …
> fix(overlay): evita múltiplas instâncias do PoActiveOverlayService

- projects/ui/src/lib/components/po-table/po-table-column-frozen/po-table-column-frozen.directive.ts
Corrige alinhamento incorreto de colunas fixas quando há uma única ação posicionada à esquerda ao aplicar scroll horizontal.
fixes DTHFUI-10907
**Simulação**
> fix(table): ajusta alinhamento de coluna fixa com ação única à esquerda

- projects/ui/src/lib/components/po-calendar/po-calendar-wrapper/po-calendar-wrapper.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/interfaces/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.html
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.ts
- projects/ui/src/lib/components/po-modal/po-modal.component.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide.component.ts
**Datepicker**
**DTHFUI-11416**
Quando no modo 'append-in-body' a tabulação não funciona corretamente
Adiciona navegação por teclado e suporte a leitores de tela no modo append-in-body, implementando fluxo de Tab para abrir o listbox
**Simulação**
Testar tabulação quando o calendar estiver visivel.
Tab: Seguir fluxo INPUT → botão (ABRIR CALENDARIO) → CALENDARIO (botão hoje) → botão (ABRIR CALENDARIO)
`<po-datepicker name="datepicker" p-label="PO Datepicker" p-append-in-body="true" />`
> feat(datepicker): implementa acessibilidade com append-in-body

- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox-base.component.ts
**checkbox**
**DTHFUI-11408**
Não é exibido o evento "p-blur" do checkbox na documentação.
Adiciona o evento "p-blur" do checkbox na documentação.
**Simulação**
> docs(checkbox): adiciona descrição do evento p-blur

- .github/workflows/issue.yml
Sanitiza as variáveis TITLE, AUTHOR e URL removendo quebras de linha antes de montar o payload enviado ao Discord, prevenindo possíveis tentativas de injeção de conteúdo malicioso no JSON.
Fixes #2603
**ci**
**2603**
**Simulação**
> build(ci): sanitiza variáveis para evitar injeção no payload JSON

- projects/sync/src/lib/services/po-event-sourcing/po-event-sourcing.service.spec.ts
- projects/sync/src/lib/services/po-event-sourcing/po-event-sourcing.service.ts
Ajusta método createPoHttpRequestData para definir body como objeto vazio caso record seja null/undefined.
Fixes: DTHFUI-11347
**Simulação**
> fix(sync): adiciona fallback para body undefined ou null

- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.ts
Foi incluído o `$filter` para filtros complexos no GET Request quando o atributo `range` está com `true`
Fixes #1211
**1211**
Quando é usado o atributo `range` a URL da requisição está sendo gerada com um objeto e não funciona conforme esperado.
Quando é usado o atributo `range` a URL da requisição está sendo gerado o atributo `$filter` para filtro complexo conforme o  [Guia de APIs da Totvs - Filtros complexos](https://tdn.totvs.com/pages/viewpage.action?pageId=484701395#Guiadeimplementa%C3%A7%C3%A3odeAPIV2.0-Filtroscomplexos(opcional))
**Simulação**
A simulação pode ser feita no …
> fix(page-dynamic-search): ajusta o GET request com atributo `range`

- projects/ui/src/lib/components/po-context-tabs/po-context-tabs.component.spec.ts
- projects/ui/src/lib/components/po-context-tabs/po-context-tabs.component.ts
Ajusta adição de tabs dinamicamente para ser exibida fora do dropdown enquanto houver espaço em tela.
Fixes: DTHFUI-11863
**Simulação**
> fix(context-tabs): ajusta adição dinâmica de tabs

- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox-base.component.ts
- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range-base.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.spec.ts
- projects/ui/src/lib/components/po-field/po-field-validate.model.ts
- projects/ui/src/lib/components/po-field/po-field.model.spec.ts
- projects/ui/src/lib/components/po-field/po-field.model.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.component.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.ts
** `po-checkbox`, `po-combo`, `po-datepicker`, `po-select` e
`po-upload`**
**DTHFUI-11949**
Os componentes (mencionados) não regiam quando desabilitado via FormControl
Os componentes (mencionados) devem reger quando desabilitado via FormControl
**Simulação**
[Uploading app_po-ui.zip…]()
> fix(components): ajusta detecção do estado disable via FormControl
