po-ui/po-angular

- CHANGELOG.md
- commitlint.config.js
- package.json
**RELEASE**
**DTHFUI-1295**
N/A
N/A
**Simulação**
N/A
> build: relase v1.1.0

- projects/ui/karma.conf.js
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-base.component.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-body/po-rich-text-body.component.spec.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-body/po-rich-text-body.component.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.component.html
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.component.spec.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.component.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text.component.html
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text.component.spec.ts
- projects/ui/src/lib/components/po-field/po-rich-text/samples/sample-po-rich-text-labs/sample-po-rich-text-labs.component.html
- projects/ui/src/lib/components/po-field/po-rich-text/samples/sample-po-rich-text-labs/sample-po-rich-text-labs.component.ts
- projects/ui/src/lib/components/po-field/po-rich-text/samples/sample-po-rich-text-recipe/sample-po-rich-text-recipe.component.html
**PO-RICH-TEXT**
**DTHFUI-1174**
Componente não possuía testes unitários e estava com problema no sample labs que ao executar AOT no portal ocorria erro.
Criado os testes unitários do componente e resolvido problema no sample labs, passando a executar o AOT com sucesso.
**Simulação**
- npm run test: ui (verificar coverage e revisar os testes escritos)
- utilizar os samples no app interno do repositorio e executar o ng build app --prod
> test(rich-text): adiciona testes unitários no componente

- projects/ui/src/lib/utils/util.spec.ts
- projects/ui/src/lib/utils/util.ts
**PO LOOKUP**
**DTHFUI-854**
O table dentro do lookup e também fora não estava ordenando corretamente quando eram utilizados caracteres minúsculos e maiúsculos.
Foi adicionado um tratamento par ao método sortValues do utils para que o mesmo quando receber um valor string possa converter em caractere minúsculo antes de fazer a  ordenação.
**Simulação**
Acessar uma API que tenha retorno o value como 0.
• Para simulação, utilizei o pacote json-server para simular uma API (https://www.npmjs.com/package/json-server);
Arquivo json:
```
{
"lookup": {
"items": [{
"label": "aaaa",
"value": 0
}, {
"label": "Aaaaa",
"value": 1
}, {
"label": …
```
> fix(lookup): corrige ordenação das tabelas

- CHANGELOG.md
- package.json
**RELEASE**
**DTHFUI-1296**
N/A
N/A
**Simulação**
N/A
> build: release v1.1.1

- CHANGELOG.md
- package.json
**DTHFUI-1472**
N/A
N/A
**Simulação**
N/A
> build: release 1.2.0

- projects/ui/src/lib/components/po-field/po-field.module.ts
- projects/ui/src/lib/components/po-field/po-upload/interfaces/po-upload-literals.interface.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.component.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-drag-drop/po-upload-drag-drop-area-overlay/po-upload-drag-drop-area-overlay.component.html
- projects/ui/src/lib/components/po-field/po-upload/po-upload-drag-drop/po-upload-drag-drop-area-overlay/po-upload-drag-drop-area-overlay.component.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-drag-drop/po-upload-drag-drop-area-overlay/po-upload-drag-drop-area-overlay.component.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-drag-drop/po-upload-drag-drop-area/po-upload-drag-drop-area.component.html
- projects/ui/src/lib/components/po-field/po-upload/po-upload-drag-drop/po-upload-drag-drop-area/po-upload-drag-drop-area.component.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-drag-drop/po-upload-drag-drop-area/po-upload-drag-drop-area.component.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-drag-drop/po-upload-drag-drop.component.html
- projects/ui/src/lib/components/po-field/po-upload/po-upload-drag-drop/po-upload-drag-drop.component.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-drag-drop/po-upload-drag-drop.component.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-drag-drop/po-upload-drag-drop.directive.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-drag-drop/po-upload-drag-drop.directive.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.html
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.ts
- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-labs/sample-po-upload-labs.component.html
- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-labs/sample-po-upload-labs.component.ts
- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-resume-drag-drop/sample-po-upload-resume-drag-drop.component.html
- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-resume-drag-drop/sample-po-upload-resume-drag-drop.component.ts
**PO-UPLOAD**
**DTHFUI-653**
O componente não tinha a opção de drag-drop
Adicionada a funcionalidade necessária para a opção de drag-drop
**Simulação:**
Verificar o sample labs
> feat(upload): permite que o componente aceite drag and drop

- CHANGELOG.md
- package.json
**DTHFUI-1473**
N/A
N/A
**Simulação**
N/A
> build: release 1.3.0

- CHANGELOG.md
- package.json
**DTHFUI-1568**
N/A
N/A
**Simulação**
N/A
> build: release v1.3.1

- angular.json
- docs/guides/browser-support.md
- package.json
- projects/app/src/polyfills.ts
- projects/app/tsconfig-es5.app.json
**PORTINARI-APP**
**DTHFUI-1288**
O projeto não está rodando no Internet Explorer.
Agora é possível executar o projeto também no Internet Explorer.
**Simulação**
Subir um *sample* no servidor local e verificar se o mesmo funciona corretamente.
> Utilizando o *build* do projeto `portinari-angular` com esta *branch* no projeto do [portal temporário](https://totvstfs.visualstudio.com/THF/_git/thf-portal-portinari-temp) utilizando a *branch* de mesmo nome é também será possível executa-lo no IE.
> fix(portinari-app): corrige o funcionamento geral no IE

- projects/ui/src/lib/components/components.module.ts
- projects/ui/src/lib/components/index.ts
- projects/ui/src/lib/components/po-progress/enums/po-progress-status.enum.ts
- projects/ui/src/lib/components/po-progress/index.ts
- projects/ui/src/lib/components/po-progress/po-progress-bar/po-progress-bar.component.html
- projects/ui/src/lib/components/po-progress/po-progress-bar/po-progress-bar.component.spec.ts
- projects/ui/src/lib/components/po-progress/po-progress-bar/po-progress-bar.component.ts
- projects/ui/src/lib/components/po-progress/po-progress-base.component.spec.ts
- projects/ui/src/lib/components/po-progress/po-progress-base.component.ts
- projects/ui/src/lib/components/po-progress/po-progress.component.html
- projects/ui/src/lib/components/po-progress/po-progress.component.spec.ts
- projects/ui/src/lib/components/po-progress/po-progress.component.ts
- projects/ui/src/lib/components/po-progress/po-progress.module.ts
- projects/ui/src/lib/components/po-progress/samples/sample-po-progress-basic/sample-po-progress-basic.component.html
- projects/ui/src/lib/components/po-progress/samples/sample-po-progress-basic/sample-po-progress-basic.component.ts
- projects/ui/src/lib/components/po-progress/samples/sample-po-progress-labs/sample-po-progress-labs.component.html
- projects/ui/src/lib/components/po-progress/samples/sample-po-progress-labs/sample-po-progress-labs.component.ts
- projects/ui/src/lib/components/po-progress/samples/sample-po-progress-publication/sample-po-progress-publication.component.html
- projects/ui/src/lib/components/po-progress/samples/sample-po-progress-publication/sample-po-progress-publication.component.ts
**PO PROGRESS**
**DTHFUI-1435**
N/A
Criação do novo componente
**Simulação**
Utilizar a branch com o mesmo nome no portinari-style. Também pode ser testado no portal.
**OBS.:** Verificar o funcionamento do tema do portinari-theme no TFS.
> feat(progress): cria o componente po-progress

- CHANGELOG.md
- package.json
**BUILD**
**DTHFUI-1605**
N/A
N/A
**Simulação**
N/A
> build: release v1.4.0

- projects/ui/src/lib/components/po-tabs/po-tab-button/po-tab-button.component.html
- projects/ui/src/lib/components/po-tabs/po-tabs-base.component.ts
- projects/ui/src/lib/components/po-tabs/po-tabs.component.html
- projects/ui/src/lib/components/po-tabs/po-tabs.component.spec.ts
- projects/ui/src/lib/components/po-tabs/po-tabs.component.ts
**PO-TABS**
**Fixes DTHFUI-1416**
***
***
O componente são exibe corretamente as *labels* das *tabs* em telas pequenas.
Implementada verificação no tratamento de múltiplas abas para alternar o comportamento da exibição em telas pequenas (mobile), fazendo com que exiba as *labels* corretamente.
**Simulação**
Verificar *samples*.
**Style**
- https://github.com/portinariui/portinari-style/pull/16
> feat(tabs): possibilita scrollagem horizontal das tabs em telas pequenas

- CHANGELOG.md
- package.json
**RELEASE**
**DTHFUI-1660**
N/A
N/A
**Simulação**
N/A
> build: release v1.5.0

- CHANGELOG.md
**MENU**
**DTHFUI-1660**
N/A
N/A
**Simulação**
N/A
> fix(menu): adiciona no changelog a correçao do menu header template

- projects/templates/src/lib/components/po-page-login/po-page-login-base.component.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.spec.ts
- projects/ui/src/lib/components/po-navbar/po-navbar-items/po-navbar-item/po-navbar-item.component.spec.ts
**PORTINARI-ANGULAR**
**Fixes DTHFUI-1678**
***
***
Ocorre alguns erro no log após executar o comando `npm run lint`.
Após a execução do comando, todos os arquivos devem ser validados com sucesso.
**Simulação**
Executar o comando `npm run lint`.
> fix(portinari): corrige a falha no lint do projeto

- .travis.yml
- projects/ui/karma.conf.js
Adiciona o arquivo .travis.yml e com isso, a partir das novas PRs serão executado automaticamente:
- Lint
- Build e
- Testes
Para verificar os builds, acesse:
- https://travis-ci.com/
- e Clique na organização Portinari UI
> ci(travis): adiciona TravisCI

- CHANGELOG.md
- package.json
**Release**
**DTHFUI-1712**
N/A
N/A
**Simulação**
N/A
> build: release v1.6.0

- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-base.component.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-body/po-rich-text-body.component.html
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-body/po-rich-text-body.component.spec.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-body/po-rich-text-body.component.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text.component.html
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text.component.spec.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text.component.ts
- projects/ui/src/lib/components/po-field/po-rich-text/samples/sample-po-rich-text-labs/sample-po-rich-text-labs.component.html
- projects/ui/src/lib/components/po-field/po-rich-text/samples/sample-po-rich-text-labs/sample-po-rich-text-labs.component.ts
**PO RICH-TEXT**
**DTHFUI-1719**
Como desenvolvedor eu gostaria de saber quando o usuário está alterando os valores do componente para que eu possa fazer intervenções quando necessário.
Definidas propriedades relacionadas aos eventos change e changeModel.
**Simulação**
Pode-se conferir os disparos dos eventos no sample labs no Portal.
> feat(rich-text): adiciona eventos de mudança de valores

- CHANGELOG.md
- package.json
**RELEASE**
**DTHFUI-1808**
N/A
N/A
**Simulação**
N/A
> build: release v1.7.0

- projects/ui/src/lib/components/po-field/po-field.module.ts
- projects/ui/src/lib/components/po-field/po-upload/interfaces/po-upload-literals.interface.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.component.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-file.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-file.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.html
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.ts
**UPLOAD**
**DTHFUI-1587**
Atualmente o componente upload possui sua própria barra de progresso, que difere
do nosso guideline.
Passa a utilizar o componente po-progress, para seguir o guideline e também componentiza o upload.
**Simulação**
Rodar o Portal e utilizar o componente po-upload
> feat(upload): utiliza o componente progress como barra de progresso

- CHANGELOG.md
- package.json
**RELEASE**
**DTHFUI-1912**
- [x ] Documentação
N/A
N/A
**Simulação**
N/A
> build: release v1.8.0

- CHANGELOG.md
- package.json
**Release**
**DTHFUI-2004**
N/A
N/A
**Simulação**
N/A
> build: release v1.9.0

- CHANGELOG.md
- package.json
**Release**
**DTHFUI-2066**
N/A
N/A
**Simulação**
N/A
> build: release v1.10.0

- projects/ui/src/lib/components/components.module.ts
- projects/ui/src/lib/components/index.ts
- projects/ui/src/lib/components/po-accordion/index.ts
- projects/ui/src/lib/components/po-accordion/po-accordion-base.component.spec.ts
- projects/ui/src/lib/components/po-accordion/po-accordion-base.component.ts
- projects/ui/src/lib/components/po-accordion/po-accordion-item-body/po-accordion-item-body.component.html
- projects/ui/src/lib/components/po-accordion/po-accordion-item-body/po-accordion-item-body.component.spec.ts
- projects/ui/src/lib/components/po-accordion/po-accordion-item-body/po-accordion-item-body.component.ts
- projects/ui/src/lib/components/po-accordion/po-accordion-item-header/po-accordion-item-header.component.html
- projects/ui/src/lib/components/po-accordion/po-accordion-item-header/po-accordion-item-header.component.spec.ts
- projects/ui/src/lib/components/po-accordion/po-accordion-item-header/po-accordion-item-header.component.ts
- projects/ui/src/lib/components/po-accordion/po-accordion-item/po-accordion-item.component.html
- projects/ui/src/lib/components/po-accordion/po-accordion-item/po-accordion-item.component.spec.ts
- projects/ui/src/lib/components/po-accordion/po-accordion-item/po-accordion-item.component.ts
- projects/ui/src/lib/components/po-accordion/po-accordion.component.html
- projects/ui/src/lib/components/po-accordion/po-accordion.component.spec.ts
- projects/ui/src/lib/components/po-accordion/po-accordion.component.ts
- projects/ui/src/lib/components/po-accordion/po-accordion.module.ts
- projects/ui/src/lib/components/po-accordion/samples/sample-po-accordion-basic/sample-po-accordion-basic.component.html
- projects/ui/src/lib/components/po-accordion/samples/sample-po-accordion-basic/sample-po-accordion-basic.component.ts
- projects/ui/src/lib/components/po-accordion/samples/sample-po-accordion-faq/sample-po-accordion-faq.component.html
- projects/ui/src/lib/components/po-accordion/samples/sample-po-accordion-faq/sample-po-accordion-faq.component.ts
- projects/ui/src/lib/components/po-accordion/samples/sample-po-accordion-labs/sample-po-accordion-labs.component.html
- projects/ui/src/lib/components/po-accordion/samples/sample-po-accordion-labs/sample-po-accordion-labs.component.ts
- projects/ui/src/lib/components/po-accordion/services/po-accordion.service.spec.ts
- projects/ui/src/lib/components/po-accordion/services/po-accordion.service.ts
**PO ACCORDION**
**DTHFUI-798**
N/A
Novo componente
**Simulação**
Utilização do portal
> feat(accordion): cria o componente

- README.md
**readme**
- [X ] Documentação
A instalação recomendada do angular/cli obriga o desenvolvedor alterar manualmente o arquivo package.json gerado pelo cli.
Alterada a instalação recomendada para o usuário ter o package.json
gerado pelo cli já com as versões do angular corretas.
**Simulação**
> fix(readme): corrigida instalação do angularcli

- CHANGELOG.md
- package.json
**RELEASE**
**DTHFUI-2104**
- [ x] Documentação
N/A
N/A
**Simulação**
N/A
> build: release v1.11.0

- .github/ISSUE_TEMPLATE/bug_report.md
Adiciona bug report issue template para criação de issues,
para facilitar e encontrar os problemas relatados mais facilmente.
> docs(issue): adiciona bug report issue template

- CHANGELOG.md
- package.json
**Release**
**DTHFUI-2153**
N/A
N/A
**Simulação**
N/A
> build: release v1.12.0

- CHANGELOG.md
- package.json
**Release**
**DTHFUI-2222**
N/A
N/A
**Simulação**
N/A
> build: release v1.13.0

- CHANGELOG.md
- package.json
**Release**
**DTHFUI-2262**
N/A
N/A
**Simulação**
N/A
> build: release 1.13.1

- projects/ui/src/lib/components/po-field/po-checkbox-group/po-checkbox-group.module.ts
- projects/ui/src/lib/components/po-field/po-field-container/po-field-container.module.ts
- projects/ui/src/lib/components/po-field/po-field.module.ts
- projects/ui/src/lib/components/po-popover/po-popover.component.spec.ts
- projects/ui/src/lib/components/po-popover/po-popover.component.ts
- projects/ui/src/lib/components/po-table/interfaces/po-table-column.interface.ts
- projects/ui/src/lib/components/po-table/interfaces/po-table-literals.interface.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.html
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-table/po-table.module.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-airfare/sample-po-table-airfare.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-transport/sample-po-table-transport.service.ts
**Table**
**DTHFUI-1502**
Atualmente não consigo informar as colunas que quero deixar visíveis.
Permite gerenciar as colunas que serão exibidas no componente e
também permite informar quantidade máxima de colunas visíveis.
**Simulação**
Utilizar as tabelas do Portal
> feat(table): adiciona gerenciador de colunas

- CHANGELOG.md
- package.json
**Release**
**DTHFUI-2315**
N/A
N/A
**Simulação**
N/A
> build: release v1.14.0

- projects/ui/src/lib/components/po-button/po-button.component.spec.ts
- projects/ui/src/lib/components/po-button/po-button.component.ts
**Button**
O componente utiliza ChangeDetectionStrategy.Default, disparando a detecção de mudança
mesmo quando não há necessidade.
Adicionando OnPush faz com que o componente faça a detecção de mudança apenas quando necessário, aumentando a performance do componente.
**Simulação**
- Avaliar samples dos componentes que utilizem po-button;
- Utilizar Samples Labs do po-button;
> feat(button): implementa ChangeDetectionStrategy.OnPush no componente

- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.html
**page-job-scheduler**
** DTHFUI-2205**
O container não estava envolvendo o conteúdo exibido no step.
Definida div contendo a class `po-row` para que o container tenha referência de altura dos elementos.
**Simulação**
O sample basic deve conter o novo comportamento esperado.
> fix(page-job-scheduler): corrige altura do container

- CHANGELOG.md
- package.json
**Release**
**DTHFUI-2364**
N/A
N/A
**Simulação**
N/A
> build: release v1.15.0

- projects/ui/src/lib/components/components.module.ts
- projects/ui/src/lib/components/index.ts
- projects/ui/src/lib/components/po-tree-view/index.ts
- projects/ui/src/lib/components/po-tree-view/po-tree-view-base.component.spec.ts
- projects/ui/src/lib/components/po-tree-view/po-tree-view-base.component.ts
- projects/ui/src/lib/components/po-tree-view/po-tree-view-item-header/po-tree-view-item-header.component.html
- projects/ui/src/lib/components/po-tree-view/po-tree-view-item-header/po-tree-view-item-header.component.spec.ts
- projects/ui/src/lib/components/po-tree-view/po-tree-view-item-header/po-tree-view-item-header.component.ts
- projects/ui/src/lib/components/po-tree-view/po-tree-view-item/po-tree-view-item.component.html
- projects/ui/src/lib/components/po-tree-view/po-tree-view-item/po-tree-view-item.component.spec.ts
- projects/ui/src/lib/components/po-tree-view/po-tree-view-item/po-tree-view-item.component.ts
- projects/ui/src/lib/components/po-tree-view/po-tree-view-item/po-tree-view-item.interface.ts
- projects/ui/src/lib/components/po-tree-view/po-tree-view.component.html
- projects/ui/src/lib/components/po-tree-view/po-tree-view.component.spec.ts
- projects/ui/src/lib/components/po-tree-view/po-tree-view.component.ts
- projects/ui/src/lib/components/po-tree-view/po-tree-view.module.ts
- projects/ui/src/lib/components/po-tree-view/samples/sample-po-tree-view-basic/sample-po-tree-view-basic.component.html
- projects/ui/src/lib/components/po-tree-view/samples/sample-po-tree-view-basic/sample-po-tree-view-basic.component.ts
- projects/ui/src/lib/components/po-tree-view/samples/sample-po-tree-view-folder-structure/sample-po-tree-view-folder-structure.component.html
- projects/ui/src/lib/components/po-tree-view/samples/sample-po-tree-view-folder-structure/sample-po-tree-view-folder-structure.component.ts
- projects/ui/src/lib/components/po-tree-view/samples/sample-po-tree-view-labs/sample-po-tree-view-labs.component.html
- projects/ui/src/lib/components/po-tree-view/samples/sample-po-tree-view-labs/sample-po-tree-view-labs.component.ts
- projects/ui/src/lib/components/po-tree-view/services/po-tree-view.service.spec.ts
- projects/ui/src/lib/components/po-tree-view/services/po-tree-view.service.ts
- projects/ui/src/lib/utils/util.spec.ts
- projects/ui/src/lib/utils/util.ts
**Tree View**
**DTHFUI-1740**
N/A
Novo componente Tree View
**Simulação**
Utilizar Samples a partir do portal local.
> feat(tree-view): novo componente

- CHANGELOG.md
- package.json
**RELEASE**
**DTHFUI-2390**
N/A.
N/A.
**Simulação****
N/A.
> build: release v1.16.0

- CHANGELOG.md
- package.json
**Release**
**DTHFUI-2419**
N/A
N/A
**Simulação**
N/A
> build: release v1.17.0

- .github/ISSUE_TEMPLATE/feature.md
Adiciona template de feature para criação de issues.
> issue_template: adiciona template de feature para criação de issue

- projects/ui/src/lib/components/po-field/index.ts
- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox-base.component.ts
- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox.component.html
- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox.component.spec.ts
- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox.component.ts
- projects/ui/src/lib/components/po-field/po-checkbox/samples/sample-po-checkbox-acceptance-term/sample-po-checkbox-acceptance-term.component.html
- projects/ui/src/lib/components/po-field/po-checkbox/samples/sample-po-checkbox-acceptance-term/sample-po-checkbox-acceptance-term.component.ts
- projects/ui/src/lib/components/po-field/po-checkbox/samples/sample-po-checkbox-basic/sample-po-checkbox-basic.component.html
- projects/ui/src/lib/components/po-field/po-checkbox/samples/sample-po-checkbox-basic/sample-po-checkbox-basic.component.ts
- projects/ui/src/lib/components/po-field/po-checkbox/samples/sample-po-checkbox-labs/sample-po-checkbox-labs.component.html
- projects/ui/src/lib/components/po-field/po-checkbox/samples/sample-po-checkbox-labs/sample-po-checkbox-labs.component.ts
- projects/ui/src/lib/components/po-field/po-field.module.ts
**PO-CHECKBOX**
**Fixes DTHFUI-2397**
***
*** 
N/A
Novo componente *checkbox*.
**Simulação**
Utilizar *samples*.
***
Style: https://github.com/portinariui/portinari-style/pull/60
> feat(checkbox): novo componente

- CHANGELOG.md
- package.json
**Release**
**DTHFUI-2453**
N/A
N/A
**Simulação**
N/A
> build: release v1.18.0

- projects/ui/src/lib/components/po-info/po-info-base.component.ts
- projects/ui/src/lib/components/po-info/po-info.component.html
- projects/ui/src/lib/components/po-info/po-info.component.spec.ts
- projects/ui/src/lib/components/po-info/po-info.component.ts
- projects/ui/src/lib/components/po-info/po-info.module.ts
- projects/ui/src/lib/components/po-info/samples/sample-po-info-labs/sample-po-info-labs.component.html
- projects/ui/src/lib/components/po-info/samples/sample-po-info-labs/sample-po-info-labs.component.ts
**INFO**
**DTHFUI-2458**
Não era possível transformar o conteúdo em um LINK.
- Adiciona a propriedade p-url, que ao ser informar transforma o conteúdo em LINK.
- Também foi adicionado ChangeDetectionStrategy.onPush no componente.
**Simulação**
Utilizar sample do componente.
> feat(info): possibilita transformar o valor em um link

- CHANGELOG.md
- package.json
**Release**
**DTHFUI-2494**
N/A
N/A
**Simulação**
N/A
> build: release v1.19.0

- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view.service.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view.service.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/samples/sample-po-dynamic-view-employee-on-load/sample-po-dynamic-view-employee-on-load.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/samples/sample-po-dynamic-view-employee-on-load/sample-po-dynamic-view-employee-on-load.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic.module.ts
**DYNAMIC VIEW**
**DTHFUI-2417**
Atualmente não é possível executar uma função quando o componente é inicializado para permitir que eu configure a visualização das informações de acordo como perfil de usuário (por exemplo).
Permite executar uma função ou fazer uma requisição durante a inicialização do componente, possibilitando alterar a visualização das informações.
**Simulação**
Pode ser simulado nos samples do portal.
Incluído novo sample de caso de uso para exemplificar a utilização da funcionalidade.
> feat(dynamic-view): permite executar uma função durante a inicialização

- projects/ui/src/lib/components/po-field/index.ts
- projects/ui/src/lib/components/po-field/po-combo/interfaces/po-combo-group.interface.ts
- projects/ui/src/lib/components/po-field/po-combo/interfaces/po-combo-option-group.interface.ts
- projects/ui/src/lib/components/po-field/po-combo/interfaces/po-combo-option.interface.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-option-template/po-combo-option-template.directive.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.html
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-labs/sample-po-combo-labs.component.html
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-labs/sample-po-combo-labs.component.ts
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-scheduling/sample-po-combo-scheduling.component.html
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-scheduling/sample-po-combo-scheduling.component.ts
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-scheduling/sample-po-combo-scheduling.service.ts
**po-combo**
**DTHFUI-2192**
O componente permite uma listagem simple de opções.
É possível agora agrupar os itens exibidos pelo componente para uma facilitação de visualização.
**Simulação**
O sample labs tem os campos para manipulação de grupos e também o sample scheduling possui um field combo contendo uma customização de template. 
Favor validar em conjunto com a PR criada no styles.
> feat(combo): permite agrupamento dos itens

- CHANGELOG.md
- package.json
**RELEASE**
**DTHFUI-2519**
***
***
N/A.
N/A.
**Simulação**
N/A.
> build: release v1.20.0

- CHANGELOG.md
- package.json
**Release**
**DTHFUI-2560**
N/A
N/A
**Simulação**
N/A
> build: release v1.21.0

- CHANGELOG.md
- package.json
**Release**
**DTHFUI-2572**
N/A
N/A
**Simulação**
N/A
> build: release v1.22.0

- projects/ui/src/lib/components/po-divider/po-divider.component.spec.ts
- projects/ui/src/lib/components/po-divider/po-divider.component.ts
ChangeDetectionStrategy.Default
Adiciona a estrategia de detecção de mudança para OnPush.
**Simulação**
Utilizar Sample
> perf(divider): adiciona ChangeDetectionStrategy.OnPush

- projects/ui/src/lib/components/po-tag/po-tag.component.spec.ts
- projects/ui/src/lib/components/po-tag/po-tag.component.ts
ChangeDetectionStrategy.Default
Adiciona a estrategia de detecção de mudança para OnPush.
**Simulação**
- Utilizar Sample no Portal
> perf(tag): adiciona ChangeDetectionStrategy.OnPush

- CHANGELOG.md
- package.json
> build: release v1.22.1

- CHANGELOG.md
- package.json
**Release**
**DTHFUI-2640**
N/A
N/A
**Simulação**
N/A
> build: release v1.22.2

- projects/ui/src/lib/components/po-field/po-field.module.ts
**Fields**
**DTHFUI-2723**
N/A
Informa a necessidade dos imports do FormsModule e ReactiveFormsModule.
**Simulação**
N/A
> docs(fields): adiciona informações sobre imports do angular

- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor-base.service.ts
**http-interceptor**
**DTHFUI-2601**
N/A
Informa a necessidade do import do BrowserAnimationsModule.
**Simulação**
N/A
> docs(http-interceptor): adiciona informações sobre imports do angular

- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.ts
- projects/templates/src/lib/components/po-page-dynamic-search/samples/sample-po-page-dynamic-search-hiring-processes/sample-po-page-dynamic-search-hiring-processes.component.ts
- projects/templates/src/lib/components/po-page-dynamic-search/samples/sample-po-page-dynamic-search-hiring-processes/sample-po-page-dynamic-search-hiring-processes.service.ts
**Page Dynamic Search**
**DTHFUI-2540**
Quando aplicados filtros de campos relacionados à seleção de valor,
aplicava-se o value do campo ao invés do label nos campos:
- checkbox-group
- radio-group
- select
Correção para mostrar ao usuário o label e não o value.
**Simulação**
Pode ser utilizado o sample do portal.
> fix(page-dynamic-search): corrige disclaimers da busca avançada

- CONTRIBUTING.md
**CONTRIBUTING**
____________________________________________________________________________
Explicação para contibuições de pessoas externas ao time
Correção
**Simulação**
> Correção CONTRIBUTING.md

- CHANGELOG.md
- package.json
**Release**
**DTHFUI-2734**
N/A
N/A
**Simulação**
N/A
> build: release v1.23.0

- projects/ui/src/lib/components/po-accordion/po-accordion-base.component.ts
> docs(accordion): corrige palavra na documentação do accordion

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/samples/sample-po-dynamic-form-register/sample-po-dynamic-form-register.component.ts
**PO-DYNAMIC-FORM**
**DTHFUI-2599**
***
***
Como desenvolvedor eu gostaria de exibir uma mensagem quando o campo é opcional para o usuário saber que não é obrigado a preencher o campo.
Agora o componente também permite definir os campos como opcionais através da propriedade `p-optional`.
**Simulação**
Verificar a implementação nos campos do *sample Register*.
> feat(dynamic-form): implementa a propriedade p-optional

- CHANGELOG.md
- package.json
**Release**
**DTHFUI-2775**
**Simulação**
> build: release v1.24.0

- docs/guides/sync-get-started.md
**Po Sync**
**DTHFUI-2045**
Ao seguir o tutorial, o usuário não estava conseguindo utilizar o sync por incompatibilidade com as versões colocadas no tutorial. 
Agora o usuário deve conseguir seguir o tutorial de acordo com as versões e ajustes colocados no documento.
**Simulação**
**front-end:**
Seguir o tutorial Começando com o PO Sync
**backend:**
1- Será necessário baixar o repositorio: `git@github.com:totvs/thf-conference-sample.git`
2 - entrar no diretorio:` thf-conference-api`
3 - executar `npm i` e depois `node index.js`
4 - Substituir na sua aplicação ionic os trechos:
```
export const conferenceSchema: PoSyncSchema = { …
```
> docs(sync): atualização das versões do tutorial

- CHANGELOG.md
- package.json
**Release**
**DTHFUI-2839**
N/A
N/A
**Simulação**
N/A
> build: release v1.25.0

- README.md
> feat(readme): adiciona twitter badge

- projects/templates/src/lib/components/po-page-login/po-page-login-base.component.ts
**Page Login**
**DTHFUI-2830**
N/A
N/A
**Simulação**
N/A
> docs(page-login): atualiza exemplos da documentação

- CONTRIBUTING.md
- STYLEGUIDE.md
n/a
Adiciona novo STYLEGUIDE.MD
**Simulação**
> docs(styleguide): adiciona documento de boas práticas

- CODE_OF_CONDUCT.md
**CODE-OF-CONDUCT**
**DTHFUI-2868**
N/A
Inclusão do código de conduta.
**Simulação**
N/A
> docs(code-of-conduct): inclusão de código de conduta

- CHANGELOG.md
- package.json
> build: release v1.26.0

- CHANGELOG.md
- package.json
> build: release v1.27.0

- CHANGELOG.md
docs(changelog): atualiza o change log com as documentações
> docs(changelog): atualiza o change log com as documentações

- docs/guides/getting-started.md
**GETTING-STARTED**
**DTHFUI-3020**
Melhoria na documentação de "Primeiros passos" possibilitando um melhor entendimento para diversas necessidades.
**Simulação**
> feat(getting-started): melhoria na documentação dos primeiros passos

- README.md
- docs/guides/getting-started.md
**getting-started e readme**
**DTHFUI-3020**
Melhoria na documentação dos primeiros passos.
**Simulação**
> feat(primeiros-passos): melhoria na documentação

- CHANGELOG.md
- package.json
> build: release v1.27.1

- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor-detail/po-http-interceptor-detail.component.spec.ts
**http-interceptor-detail**
Ao rodar CI no travis este teste unitário estava quebrando porque no ambiente a linguagem era português porém o testado era inglês.
Definido antes de realizar o teste a linguagem inglês, para não se basear no browser.
**Simulação**
Avaliar se o teste não quebra no TRAVIS.
> test(http-interceptor-detail): utiliza literais de tradução em ingles 

- projects/ui/src/lib/components/po-stepper/po-step/po-step.component.ts
- projects/ui/src/lib/components/po-stepper/po-stepper.component.spec.ts
- projects/ui/src/lib/components/po-stepper/po-stepper.component.ts
- projects/ui/src/lib/components/po-stepper/samples/sample-po-stepper-sales/sample-po-stepper-sales.component.html
- projects/ui/src/lib/components/po-stepper/samples/sample-po-stepper-sales/sample-po-stepper-sales.component.ts
**STEPPER**
**DTHFUI-2970**
Não definia o step atual com status de erro, caso acontecesse algum erro no Observable.
Também não possuía um sample utilizando observable.
Implementa tratamento de erro ao canActiveNextStep, que caso ocorrer, definirá o step atual com status de Error e não prosseguirá para o próximo step.
Também foi refatorado alguns trechos do código, e 
Adicionado um examplo de observable no sample de caso de uso.
**Simulação**
Utilizar o sample caso de uso para avaliar a funcionalidade.
> feat(stepper): implementa tratamento de catchError ao canActiveNextStep

- CHANGELOG.md
- package.json
**Build**
**DTHFUI-3093**
N/A
N/A
**Simulação**
N/A
> build: release v1.28.0

- docs/guides/getting-started.md
**Documentação getting-started**
**DTHFUI-3154**
O documento não estava atualizado com a versão do Angular 9
Atualiza a documentação e as dependência
**Simulação**
Abrir a documentação no portal
> docs(getting-started): atualiza para a nova versão

- docs/guides/sync-get-started.md
**documentação sync-get-started**
**DTHFUI-3087**
O documento não estava atualizado com a versão do Angular 9
Atualiza a documentação e as dependências
**Simulação**
Abrir a documentação no portal
> docs(sync-get-started): atualiza para a nova versão

- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
**Po Table**
O componente não estava sendo renderizado e gerava erros no console.
- Erro ao utilizar o p-container
- também tinha um erro ao utilizar o table juntamente com o tabs (portal)
- Erro ao utilizar o p-height
O componente é renderizado normalmente no portal sem gerar erros.
**Simulação**
Abrir o componente no portal.
> fix(table): correção do componente para atualização v9

- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range.component.ts
**datepicker-range**
Estava gerando erro no console ao modificar valor de data no sample labs do portal.
Adicionada detecção de mudança ao modificar valor do model.
**Simulação**
Checar nos sample labs do portal
> fix(datepicker-range): corrige erro ao mudar valor

- projects/ui/src/lib/components/po-chart/po-chart-types/po-chart-circular/po-chart-circular.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-types/po-chart-circular/po-chart-circular.ts
**PO-CHART**
Apresenta erros no console ao passar o mouse por cima dos charts circulares e não exibe o tooltip.
Corrige erros no console e surgimento do tooltip ao passar o mouse por cima dos charts circulares.
**Simulação**
Samples do Portal.
> fix(chart): corrige erros no console

- package.json
- projects/code-editor/src/lib/components/po-code-editor/po-code-editor-base.component.spec.ts
- projects/code-editor/src/lib/components/po-code-editor/po-code-editor-base.component.ts
- projects/code-editor/src/lib/components/po-code-editor/po-code-editor.component.spec.ts
- projects/code-editor/src/lib/components/po-code-editor/po-code-editor.component.ts
**components**
**DTHFUI-3085**
O componente tinha baixa cobertura de código.
Os testes foram revisados e, aumentada a cobertura. A exceção foi no carregamento do componente externo monaco pois é um código terceiro.
PS: 
**Simulação**
Basta rodar os testes.
> test(code-editor): criação de testes para code-editor

- projects/templates/src/lib/components/po-modal-password-recovery/po-modal-password-recovery.component.spec.ts
- projects/templates/src/lib/components/po-page-blocked-user/po-page-blocked-user-reason/po-page-blocked-user-reason.component.spec.ts
- projects/templates/src/lib/components/po-page-change-password/po-page-change-password.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-login/po-page-login.component.spec.ts
**templates**
**DTHFUI-3243**
O componente tinha baixa cobertura de código.
Os testes foram revisados e, aumentada a cobertura.
PS: 
**Simulação**
Basta rodar os testes.
> test(templates): criação de testes para projeto de templates

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature.md
- projects/code-editor/package.json
- projects/storage/package.json
- projects/sync/package.json
- projects/sync/src/lib/models/po-data-message.model.ts
- projects/sync/src/lib/models/po-data-transform.model.ts
- projects/sync/src/lib/services/po-schema/po-schema-util/po-schema-util.model.spec.ts
- projects/sync/src/lib/services/po-sync/interfaces/po-sync-config.interface.ts
- projects/templates/package.json
- projects/templates/src/lib/components/po-page-blocked-user/po-page-blocked-user-base.component.ts
- projects/ui/package.json
- projects/ui/schematics/ng-generate/po-page-list/schema.json
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.ts
- projects/ui/src/lib/components/po-grid/samples/sample-po-grid-basic/sample-po-grid-basic.component.ts
- projects/ui/src/lib/components/po-menu/po-menu-base.component.ts
- projects/ui/src/lib/components/po-menu/samples/sample-po-menu-basic/sample-po-menu-basic.component.html
- projects/ui/src/lib/pipes/po-time/po-time.pipe.ts
**DTHFUI-3089**
refactor(samples): altera referências ao pacote depreciado.
> refactor(samples): altera referências ao pacote depreciado

- CHANGELOG.md
- docs/guides/migration-poui-v2.md
> build: release v2.0.0-beta.1

- docs/guides/migration-poui-v2.md
- projects/ui/schematics/README.md
- projects/ui/schematics/ng-update/index.ts
**SCHEMATICS UPDATE**
**DTHFUI-3273**
O schematics update @po-ui/ng-components alterava apenas a primeira ocorrência encontrada
Agora passa a alterar todas as ocorrências encontradas, não apenas a primeira.
**Simulação**
Testar a migração com varias ocorrências que contenham p-focus, X-PORTINARI-NO-MESSAGE.
> fix(schematics): altera todas ocorrencias encontradas no update

- projects/templates/src/lib/components/po-page-dynamic-detail/po-page-dynamic-detail.component.ts
- projects/templates/src/lib/components/po-page-dynamic-detail/samples/sample-po-page-dynamic-detail-user/sample-po-page-dynamic-detail-user.component.html
- projects/templates/src/lib/components/po-page-dynamic-detail/samples/sample-po-page-dynamic-detail-user/sample-po-page-dynamic-detail-user.component.ts
**page-dynamic-detail**
**DTHFUI-2667**
A url do serviço aponta para a api anterior
Atualização da url dos serviços dos samples. Note que o sample não exibe nenhum registro, afinal a api espera um id e isso só será possível com a tarefa relacionada ao sample com Stackblitz. A api já está atualizada para receber uma requisição por id.
**Simulação**
Favor checar no portal e também o retorno [na api](https://github.com/po-ui/po-sample-api) (master).
> docs(page-dynamic-detail): atualiza url no sample

- projects/code-editor/README.md
- projects/storage/README.md
- projects/sync/README.md
- projects/templates/README.md
- projects/ui/README.md
**packages**
**DTHFUI-3265**
Os links dos pacotes no npm não possuem conteúdo indicativo para instalação
Criados arquivos README contendo informações sobre instalação dos pacotes ui, templates, sync, storage e code-editor
**Simulação**
Revisar textos dos respectivos arquivos.
> docs(packages): adiciona README nos pacotes

- CHANGELOG.md
- package.json
- projects/ui/package.json
- projects/ui/schematics/migrations.json
**DTHFUI-3313**
build: release v2.0.0-beta.2
> build: release v2.0.0-beta.3

- docs/guides/sync-get-started.md
**Po Sync**
**DTHFUI-2835**
Estava dando erro ao seguir o tutorial, pois estava sendo referenciada uma versão inexistente do @ionic/angular.
E também tinha parte da documentação que estava desatualizada. 
Atualiza a versão do @ionic/angular para a versão latest.
E ajustes na documentação de acordo com a nova versão do Ionic.
**Simulação**
Seguir a documentação para validar.
> docs(sync-get-started): atualiza versão @ionic/angular

- CHANGELOG.md
- package.json
- projects/sync/schematics/utils/package-config.ts
- projects/ui/schematics/utils/package-config.ts
Definido a versão do TSLINT como 2.0 no schematics.
> build: release v2.1.0

- projects/templates/src/lib/components/po-modal-password-recovery/samples/sample-po-modal-password-recovery-request/sample-po-modal-password-recovery-request.component.ts
**modal-password-recovery**
**DTHFUI-2663**
A url do serviço apontava para o serviço antigo.
Atualização da url dos serviço do sample.
**Simulação**
Validar a [PR da api ](https://github.com/po-ui/po-sample-api/pull/11)e testar em conjunto com o sample **PO Modal Password Recovery Request**.
> docs(modal-password-recovery): atualiza url no sample

- projects/ui/src/lib/components/po-chart/po-chart-types/po-chart-circular/po-chart-circular.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-types/po-chart-circular/po-chart-circular.ts
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-coffee-ranking/sample-po-chart-coffee-ranking.component.ts
**chart**
**DTHFUI-3048**
Ao executar o fonte do sample Coffee Ranking está gerando erro  NS_ERROR_FAILURE no Firefox.
Erro tratado e validado nos browsers suportados. 
Ajuste também de tipagem para a série do tipo Donut no sample Coffee Ranking.
**Simulação**
Validar no portal
> fix(chart): corrige erro no Firefox

- CHANGELOG.md
- package.json
> build: release v2.1.1

- .travis.yml
- projects/ui/src/lib/components/po-accordion/po-accordion-item-header/po-accordion-item-header.component.spec.ts
- projects/ui/src/lib/components/po-tag/po-tag.component.html
- projects/ui/src/lib/components/po-tag/po-tag.component.spec.ts
- projects/ui/src/lib/components/po-tag/po-tag.component.ts
Atualização para a versão LTS do Travis
> build(): atualização da versão do node

- CHANGELOG.md
- package.json
> build: release v2.2.0

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/samples/sample-po-dynamic-form-register/sample-po-dynamic-form-register.component.ts
**DYNAMIC FORM**
**DTHFUI-3281**
N/A
Implementa a propriedade `PoDynamicFormField.Format` para os campos
do tipo Date e DateTime.
**Simulação**
- Gerar o Portal, e;
- Utilizar o SamplePoDynamicFormRegisterComponent
> feat(dynamic-form): implementa a propriedade `PoDynamicFormField.Format`

- docs/guides/schematics.md
**Schematics**
**DTHFUI-3486**
Não estava mostrando os links corretamente dos schematics atuais.
Melhora a exibição dos links dos schematics disponíveis.
**Simulação**
Rodar o portal e verificar o link http://localhost:4200/guides/schematics
> docs(schematics): melhora exibição dos links dos schematics disponíveis

- CHANGELOG.md
- package.json
**RELEASE**
**DTHFUI-3451**
N/A
N/A
**Simulação**
N/A
> build: release v2.3.0

- CHANGELOG.md
- package.json
**RELEASE V2.4.0**
**DTHFUI-3452>**
N/A
N/A
**Simulação**
N/A
> build: release v2.4.0

- CHANGELOG.md
- package.json
> build: release v2.4.1

- CHANGELOG.md
- package.json
**Build**
**DTHFUI-3520**
N/A
N/A
**Simulação**
N/A
> build: release v2.5.0

- CHANGELOG.md
- README.md
- package.json
> build: release v2.6.0

- projects/ui/src/lib/components/po-avatar/po-avatar.component.spec.ts
- projects/ui/src/lib/components/po-avatar/po-avatar.component.ts
**Avatar**
-
Adiciona ChangeDetectionStrategy.OnPush no componente para que
a detecção de mudança ocorra apenas quando
input/output do próprio componente for alterado/disparado.
**Simulação**
- Utilizar samples do Avatar;
- É possível avaliar a diferença utilizando os passos abaixo, comparar a master com a branch (onpush).
Com a branch master, digite no campo input, verifique que é disparado verificações de mudança no PoAvatar, mesmo não tendo necessidade, faça o mesmo teste com a branch avatar/onpush.
avatar.component.ts
```
get check() {
console.log('check avatar');
return '';
```
avatar.component.html
`
{{ check }} 
` …
> perf(avatar): adiciona ChangeDetectionStrategy.OnPush

- CHANGELOG.md
- package.json
**Build**
**DTHFUI-3584**
**Simulação**
> build: release v2.7.0

- projects/ui/src/lib/components/po-table/index.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table-cell-template/po-table-cell-template.directive.spec.ts
- projects/ui/src/lib/components/po-table/po-table-cell-template/po-table-cell-template.directive.ts
- projects/ui/src/lib/components/po-table/po-table-column-template/po-table-column-template.directive.spec.ts
- projects/ui/src/lib/components/po-table/po-table-column-template/po-table-column-template.directive.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-table/po-table.module.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-components/sample-po-table-components.component.css
- projects/ui/src/lib/components/po-table/samples/sample-po-table-components/sample-po-table-components.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-components/sample-po-table-components.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-components/sample-po-table-components.service.ts
**PO-TABLE**
**DTHFUI-3581**
Não é possível aplicar templates nas celulas da tabela
Cria as directivas p-table-cell-template e p-table-column-template
para possibilitar a customização de células da Po-Table, através de
templates.
**Simulação**
**BRANCH: po-table/DTHFUI-3595-**
Testando **p-table-cell-template**
```
<ng-template p-table-cell-template let-column="column" let-row="row">
<div *ngIf="column.property === 'status' && row.status === 'CANCELED'">
<h1 [style.background]="'red'">CANCELADA</h1>
<span (click)="onClick()"><small>clique aqui</small></span>
</div>
<h1 *ngIf="column.property === 'status' && row.status === 'FINISHED'" …
```
> feat(table): adiciona templates de colunas

- projects/ui/src/lib/components/po-avatar/po-avatar-base.component.spec.ts
- projects/ui/src/lib/components/po-avatar/po-avatar-base.component.ts
- projects/ui/src/lib/components/po-avatar/po-avatar.component.html
- projects/ui/src/lib/components/po-avatar/po-avatar.component.spec.ts
- projects/ui/src/lib/components/po-avatar/samples/sample-po-avatar-business-card/sample-po-avatar-business-card.component.html
- projects/ui/src/lib/components/po-avatar/samples/sample-po-avatar-business-card/sample-po-avatar-business-card.component.ts
**AVATAR**
**DTHFUI-1873**
Não possui evento de clique.
Adiciona o evento p-click, que será disparado ao clicar no avatar.
**PR STYLE:** https://github.com/po-ui/po-style/pull/117
**Simulação**
Utilizar sample business card no portal.
> feat(avatar): adiciona evento de clique

- CHANGELOG.md
- package.json
> build: release v2.8.0

- CHANGELOG.md
- package.json
**build: release v2.9.0**
**DTHFUI-3648**
N/A
N/A
**Simulação**
N/A
> build: release v2.9.0

- .travis.yml
- CONTRIBUTING.md
Adequação para uso da branch dev
> build: adequação do repo para desenvolvimento na branch dev

- projects/ui/src/lib/components/po-disclaimer-group/samples/sample-po-disclaimer-group-sw-planets/sample-po-disclaimer-group-sw-planets.service.ts
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-sw-films/sample-po-lookup-sw-films.service.ts
**Lookup e Disclaimer Group**
Está apontando para uma API que não está no ar.
Passa apontar para a nova API.
**Simulação**
Abrir a página dos componentes no portal.
> Samples/swapi: atualiza API dos samples de Star Wars

- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-literals.ts
**Rich Text**
Só existe suporte para os idiomas português, inglês e espanhol.
Adiciona suporte para o idioma russo.
**Simulação**
Mudar o idioma do browser para russo ou injetar o serviço do i18n e configurar o idioma russo como padrão.
> feat(rich-text): adiciona literais em russo

- CHANGELOG.md
- package.json
> build: release v2.10.0

- .github/ISSUE_TEMPLATE/bug_report.md
Melhoria no template de abertura de issue (bug).
> doc(issues): melhora o template de abertura de issue

- CHANGELOG.md
- package.json
> build: release 3.0.0-beta.1

- projects/ui/src/lib/components/po-field/po-select/samples/sample-po-select-customer-registration/sample-po-select-customer-registration.component.html
- projects/ui/src/lib/components/po-field/po-select/samples/sample-po-select-customer-registration/sample-po-select-customer-registration.component.ts
- projects/ui/src/lib/components/po-field/po-select/samples/sample-po-select-customer-registration/sample-po-select-customer-registration.service.ts
**PO-SELECT**
**DTHFUI-3826**
Ao abrir o sample do po-select no portal, ocorre um erro na chamada da api e ao tentar acessar outro componente ocorre um outro erro que impossibilita o acesso ao novo componente.
Foi corrigido o sample no portal incluindo uma trataviva no método onDestroy e também foram ajustados os endpoints que estavam errados. Não ocorre mais erros.
**Simulação**
Ao abrir o sample do po-select no portal não deve estourar erros no console assim como não deve impossibilitar o usuário de visitar outro componente.
> fix(select): corrige erro no sample customer registration

- docs/guides/migration-poui-v3.md
**Documentação**
**DTHFUI-3836**
Correção ortográfica e outros ajustes na documentação de migração.
**Simulação**
Abrir a documentação no Portal
> docs(migration): corrige ortografia da documentação

- gulpfile.js
**SONARQUBE**
Atualização da tarefa do gulp para receber os parametros do sonarqube (endereço, token e id do projeto)
> feat(gulp): atualização da tarefa do Sonarqube

- projects/ui/src/lib/services/po-notification/samples/sample-po-notification-sales/sample-po-notification-sales.component.ts
**NOTIFICATION**
**DTHFUI-3859**
Ocorre um erro ao adicionar um item no carrinho no Sample Sales
Corrigido erro e agora é possível incluir itens no carrinho sem erros.
**Simulação**
Sample Sales no Portal.
> docs(notification): corrige erro no Sample Sales

- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
**PO-TABLE**
**DTHFUI-3798**
O ícone de ordenação de colunas esta na direita no final do header da coluna
Ícone de ordenação esta junto ao texto ao lado direito
**Simulação**
Adicionar o a propriedade `p-sort` na tabela, também testar juntamente com o `p-height` e `p-hide-text-overflow`
> feat(table): altera a posição do icone sort

- projects/sync/src/lib/services/po-schema/po-schema.service.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.ts
- projects/ui/src/lib/services/po-i18n/po-i18n-base.service.ts
**Lint**
**DTHFUI-3909**
Não estava atendendo a nova regra `bool-param-default`.
Adaptação do fonte para funcionar com a nova regra do `@po-ui/ng-tslint`
**Simulação**
Validar em conjunto com [PR do tslint](https://github.com/po-ui/po-tslint/pull/11)
Para simular:
```
cd ~/projects/po-tslint          # seu repo local com o po-tslint na branch do PR acima
npm link                         # cria o link simbólico global
cd ~/projects/po-angular     # entra no seu repo local do po-angular
npm link @po-ui/ng-tslint    # coloca o link simbólico no seu projeto
npm run lint
```
Por fim executar o portal para ver se ocorreu conforme o …
> feat(ng-tslint): nova regra `bool-param-default`

- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-basic/sample-po-lookup-basic.component.html
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-labs/sample-po-lookup-labs.component.html
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-labs/sample-po-lookup-labs.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup.service.ts
**Po Lookup**
**DTHFUI-2672**
Os samples estavam com o endpoint antigo e não estavam funcionando corretamente.
Atualização dos endpoints dos samples e adaptação para funcionar corretamente.
**Simulação**
- Subir o endpoint da PR: https://github.com/po-ui/po-sample-api/pull/15
- Substituir: https://po-sample-api.herokuapp.com/v1/heroes por: http://localhost:3000/v1/heroes
- E abrir os samples no Portal
> docs(lookup): atualiza endpoint dos samples

- CHANGELOG.md
> docs(changelog): atualiza informações dos commits

- projects/ui/src/lib/components/po-popover/po-popover.component.spec.ts
**PO-POPOVER**
**DTHFUI-3943**
Ao executar os testes de forma geral com npm run test, tem testes falhando de forma intermitente do componente po-popover.
Corrigida a chamada dos spies dos testes
**Simulação**
Executar build do travis 5 vezes.
> test(popover): correção para erros intermitentes

- CHANGELOG.md
- package.json
> build: release v3.1.0

- gulpfile.js
- package.json
- projects/portal/docs/index.js
- projects/portal/docs/processors/helpers/file-writer.js
**Portal**
O pacote fs-path esta com vulnerabilidade e não possui uma correção para tal.
Remove a dependencia fs-path que esta com vulnerabilidade;
Remove o projeto Portal do coverage do Sonar;
**Simulação**
npm i 
> refactor(portal): remove a dependencia fs-path

- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
- projects/ui/src/lib/components/po-field/po-select/po-select-base.component.ts
- projects/ui/src/lib/components/po-field/po-select/samples/sample-po-select-labs/sample-po-select-labs.component.ts
**Select**
**DTHFUI-3981**
N/A
Adiciona informação sobre imutabilidade para a propriedade `p-option`.
**Simulação**
N/A
> docs(select): melhora descrição da propriedade `p-options`

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/samples/sample-po-dynamic-form-register/sample-po-dynamic-form-register.component.ts
**DTHFUI-3863**
Não está disparando o método validate para campos do tipo lookup.
Passa a disparar o evento da maneira correta.
**Simulação**
Checar o disparado do evento validate ao alterar o valor do campo do tipo lookup.
No exemplo _Register_, alterar o campo _Favorite hero_.
> fix(dynamic-form): corrige o método validade para campos do tipo lookup

- projects/ui/src/lib/components/po-field/po-number/po-number-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-number/po-number-base.component.ts
- projects/ui/src/lib/components/po-field/po-number/po-number.component.html
- projects/ui/src/lib/components/po-field/po-number/po-number.component.spec.ts
- projects/ui/src/lib/components/po-field/po-number/po-number.component.ts
**number**
**DTHFUI-3968**
Quando sai do campo e o mesmo contém um valor inválido nenhum feedback é dado ao usuário.
Se houver valor inválido na saída do campo, o mesmo fica inválido e o usuário recebe o feedback
**Simulação**
Sample labs do portal
> fix(number): valida campo no evento blur

- projects/portal/src/styles.css
**PO NAVBAR**
**DTHFUI-2633**
O Portal possui tratamento css para um problema do componente navbar.
Foi realizada a correção no css do navbar no po-style e foi removido o tratamento do portal.
**Simulação**
- [PR no po-style](https://github.com/po-ui/po-style/pull/149)
```
<po-navbar
p-logo="https://i.pinimg.com/736x/45/fd/23/45fd23068e0a98a7024b55012583ca24.jpg"
p-menu="userMenu"
p-shadow="true" >
</po-navbar>
<div class="po-wrapper">
<po-menu #userMenu [p-menus]="[{ label: 'PO UI - Angular Framework', link: '/' }]"></po-menu>
<po-page-default p-title="Nordy">
<p> AppName page </p>
</div>
``` …
> fix(navbar): corrige scrollbar vertical desnecessário

- projects/ui/src/lib/components/po-field/po-field-container/po-field-container-bottom/po-field-container-bottom.component.spec.ts
- projects/ui/src/lib/components/po-field/po-field-container/po-field-container-bottom/po-field-container-bottom.component.ts
- projects/ui/src/lib/components/po-field/po-field-container/po-field-container.component.spec.ts
- projects/ui/src/lib/components/po-field/po-field-container/po-field-container.component.ts
**Field Container**
O componente que é usado internamente possuia detecção de
mudança padrão
Passa a utilizar OnPush tornando-o mais performatico,
checando seus bindings apenas quando algum dos seus input/evento for disparado.
**Simulação**
- Utilizar componentes de entrada no portal.
> perf(field-container): implementa ChangeDetectionStrategy.OnPush

- projects/ui/src/lib/components/po-page/index.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide-base.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide-base.component.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide.component.html
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide.component.ts
- projects/ui/src/lib/components/po-page/po-page-slide/samples/sample-po-page-slide-basic/sample-po-page-slide-basic.component.html
- projects/ui/src/lib/components/po-page/po-page-slide/samples/sample-po-page-slide-basic/sample-po-page-slide-basic.component.ts
- projects/ui/src/lib/components/po-page/po-page-slide/samples/sample-po-page-slide-configuration/sample-po-page-slide-configuration.component.html
- projects/ui/src/lib/components/po-page/po-page-slide/samples/sample-po-page-slide-configuration/sample-po-page-slide-configuration.component.ts
- projects/ui/src/lib/components/po-page/po-page-slide/samples/sample-po-page-slide-labs/sample-po-page-slide-labs.component.html
- projects/ui/src/lib/components/po-page/po-page-slide/samples/sample-po-page-slide-labs/sample-po-page-slide-labs.component.ts
- projects/ui/src/lib/components/po-page/po-page.module.ts
- projects/ui/src/lib/utils/util.ts
**PO PAGE SLIDE**
**#283**
Criação do componente `po-page-slide`.
**Simulação**
```html
<po-page-slide
p-title="Title"
p-subtitle="Subtitle"
p-size="md"
p-click-out="true"
p-hide-close="false">
</po-page-slide>
```
> feat(page-slide): cria o componente po-page-slide

- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/services/po-lookup-filter.service.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/services/po-lookup-filter.service.ts
**PO-LOOKUP**
**DTHFUI-4078**
Ao usar o valor com "/" diretamente no input e realizar a busca com a tecla TAB, o mesmo é concatenado a url do serviço e enviado para o backend, o mesmo interpreta como um endpoint diferente pois não há tratamento para caracteres especiais.
Inclui encoding de caracteres especiais ao realizar uma busca rápida com o `TAB` no componente.
**Simulação**
No sample basic do Portal, verificar a aplicação do encoding para caracteres especiais na URL da requisição através da aba Network na Ferramenta do desenvolvedor no browser.
> fix(lookup): inclui encoding de caracteres especiais no filtro rápido

- projects/ui/src/lib/components/po-dropdown/po-dropdown.component.spec.ts
- projects/ui/src/lib/components/po-dropdown/po-dropdown.component.ts
- projects/ui/src/lib/components/po-popup/po-popup.component.html
- projects/ui/src/lib/components/po-popup/po-popup.component.spec.ts
- projects/ui/src/lib/components/po-popup/po-popup.component.ts
**POPUP**
**DTHFUI-3837**
PR stlye https://github.com/po-ui/po-style/pull/156
Caso o componente possuir muitos itens e não era possível exibi-los, pois estava se perdendo na abertura do componente.
Ativa scroll quando o elemento chegar na altura máxima, que é 300px, fazendo que o controle de exibição funcione corretamente.
**Simulação**
app.component.ts
```
<po-navbar
[p-items]="[{ label: 'ITEM 1'}, { label: 'ITEM 2'}]">
</po-navbar>
<div class="po-wrapper">
<po-toolbar
[p-title]="'TITULO'"
p-actions-icon="po-icon-settings"
[p-notification-actions]="notificationsActions"
[p-notification-number]="5">
</po-toolbar>
<po-menu …
```
> fix(popup): ativa scroll quando o elemento chegar na altura máxima

- .github/workflows/publish_po_angular_ci.yml
- angular.json
- projects/portal/src/web.config
**build**
**DTHFUI-4137**
N/A
Adiciona no github actions uma ação para publicar o portal de forma automatizada.
Apenas acione a ação de PO-UI Publish.
**Simulação**
Para chegar em um teste mais próximo, pode ser utilizado o repositório [para testes](https://github.com/alvarocamillont/po-angular/actions). Utilize esse repositório para subir o portal. O portal atualizado aparece na mensagem de sucesso da action
Acesse abra a aba actions do repositório, clique em `PO-UI - publish`, posteriormente em `Run Workflow` veja a execução do fluxo de trabalho.
Verificar também nossa [doc sobre o processo de …
> build: criada action para o build e deploy do portal

- .github/workflows/publish_po_angular_ci.yml
**build**
Portal não está sendo gerado corretamente pela action
A action faz o clone do styles e do lint para o build do portal ser gerado corretamente.
**Simulação**
Para chegar em um teste mais próximo, pode ser utilizado o repositório [para testes](https://github.com/alvarocamillont/po-angular/actions). Utilize esse repositório para subir o portal. O portal atualizado aparece na mensagem de sucesso da action
Acesse abra a aba actions do repositório, clique em `PO-UI - publish`, posteriormente em `Run Workflow` veja a execução do fluxo de trabalho.
**Não altere a versão do package no fork do portal**
> build(portal): correção da geração do portal

- projects/ui/src/lib/components/po-button/po-button-base.component.ts
- projects/ui/src/lib/components/po-button/po-button.component.spec.ts
- projects/ui/src/lib/components/po-button/po-button.component.ts
**po-button**
**DTHFUI-1536**
-
Permite que usuário defina foco no elemento button ao inicializar.
**Simulação**
```
<h1 class="po-page-header-title po-pb-5">Resumo de registro</h1>
</div>
<div class="po-md-8">
<po-info p-label="Processo" p-orientation="horizontal" p-value="DERL2343-12"></po-info>
<po-info p-label="Periodicidade" p-orientation="horizontal" p-value="única"></po-info>
<po-info p-label="Recorrente" p-orientation="horizontal" p-value="Não"></po-info>
</div>
<po-widget class="po-pt-1 po-pb-1 po-md-8" p-title="Parâmetros">
<po-info …
```
> feat(button): adiciona propriedade p-auto-focus

- docs/guides/sync-fundamentals.md
- docs/guides/sync-get-started.md
- projects/storage/package.json
- projects/sync/package.json
- projects/templates/package.json
- projects/ui/package.json
**po-sync**
**DTHFUI-3358**
A documentação atual aponta para uma API inexistente.
Corrigida doc
**Simulação**
Fazer o passo a passo do guia Começando com o PO Sync
> doc: atualiza doc do sync com a nova api

- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor-base.service.spec.ts
- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor-base.service.ts
- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor-detail/po-http-interceptor-detail.component.spec.ts
- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor-detail/po-http-interceptor-detail.component.ts
- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor-literals.ts
- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor.service.spec.ts
- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor.service.ts
**INTERCEPTOR**
**MDO-36**
- [ X ] Código
Interceptor utiliza idioma do browser para os literais
Interceptor utilizará o LanguaService para os literais dos idiomas suportados
**Simulação**
> feat(Interceptor) - Traduzir literais utilizadas para os idiomas suportados

- projects/ui/src/lib/services/po-notification/po-toaster/po-toaster.component.html
Ajuste no componente po-notification devido alteraçoes de estilo.
Fixes TIS-2
**po-notification**
**TIS-2**
Ícone e botão estão quebrados quando a mensagem ultrapassa o tamanho da linha. Não está pegando o comportamento responsivo.
Altera espaçamentos laterais e centralização dos itens.
**Simulação**
Digite um texto grande, para ultrapassar uma linha, adicionar Action para apresentar o botão.
> feat(notification): atualiza espaçamentos

- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-line/po-chart-line.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-line/po-chart-line.component.svg
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-line/po-chart-line.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-line/po-chart-path/po-chart-path.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-line/po-chart-path/po-chart-path.component.svg
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-line/po-chart-path/po-chart-path.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-line/po-chart-series-point/po-chart-series-point.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-line/po-chart-series-point/po-chart-series-point.component.svg
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-line/po-chart-series-point/po-chart-series-point.component.ts
**po-chart**
**DTHFUI-4399**
O gráfico do tipo linha é plotado instantaneamente.
Agora há uma animação de desenho da linha no carregamento e na inclusão de novas séries.
**Simulação**
Testar em conjunto com a [PR de style](https://github.com/po-ui/po-style/pull/171)
Sample labs.
> feat(chart): define animação para gráfico de linha 

- projects/ui/src/lib/interceptors/po-http-interceptor/po-http-interceptor-detail/po-http-interceptor-detail-literals.interface.ts
**http-interceptor**
____________________________________________________________________________
- [ x] Código
Corrected close button translation in russian
Corrected CAPS in russian
**Simulação**
> fix(http-interceptor): corrected close button translation in russian

- projects/ui/src/lib/components/po-chart/enums/po-chart-type.enum.ts
- projects/ui/src/lib/components/po-chart/helpers/po-chart-default-values.constant.ts
- projects/ui/src/lib/components/po-chart/index.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-bar-coordinates.interface.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-column-series.interface.ts
- projects/ui/src/lib/components/po-chart/po-chart-base.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-axis/po-chart-axis.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-axis/po-chart-axis.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-bar-base.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-bar-base.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-bar-path/po-chart-bar-path.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-bar-path/po-chart-bar-path.component.svg
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-bar-path/po-chart-bar-path.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-bar.component.svg
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-column/po-chart-column.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-column/po-chart-column.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-container.component.html
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-container.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-line/po-chart-line.component.ts
- projects/ui/src/lib/components/po-chart/po-chart.component.ts
- projects/ui/src/lib/components/po-chart/po-chart.module.ts
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-coffee-ranking/sample-po-chart-coffee-ranking.component.html
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-coffee-ranking/sample-po-chart-coffee-ranking.component.ts
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-labs/sample-po-chart-labs.component.ts
- projects/ui/src/lib/components/po-chart/services/po-chart-maths.service.spec.ts
- projects/ui/src/lib/components/po-chart/services/po-chart-maths.service.ts
**Chart Column**
**DTHFUI-1754**
Não possuímos o gráfico do tipo `column`.
Inclui um novo tipo de gráfico do tipo `Column`.
**Simulação**
É possível simular através dos samples do portal.
> feat(chart): inclui gráfico do tipo coluna

- .github/workflows/publish_po_angular_ci.yml
> build: update deprecated env

- docs/guides/migration-poui-v4.md
- projects/sync/schematics/README.md
- projects/sync/schematics/migrations.json
- projects/sync/schematics/ng-update/v4/changes.ts
- projects/sync/schematics/ng-update/v4/index.ts
- projects/ui/schematics/README.md
- projects/ui/schematics/migrations.json
- projects/ui/schematics/ng-update/v4/changes.ts
- projects/ui/schematics/ng-update/v4/index.ts
**Migração**
**DTHFUI-4461**
Cria documento de migração para v4 e implementa
schematics ng update para migração automatica nos pacotes
ng-sync e ng-components.
**Simulação**
- Buildar os pacotes com a versão 4.0.0-next.1 e publica-los localmente com verdaccio. (não esqueça de publicar style e tslint na mesma versão para não dar erro na hora de migrar o projeto).
- Utilizar o Po Conference Web para migrar da v3x para v4x utilizando a documentação.
> feat(components|sync): implementa ng update para v4

- projects/ui/src/lib/directives/po-tooltip/samples/sample-po-tooltip-new-user/sample-po-tooltip-new-user.component.ts
**PO-TOOLTIP**
**DTHFUI-4563**
É exibida uma mensagem porém não fica muito claro para o usuário como preencher corretamente o campo de email do sample New User.
Ajusta a mensagem exibida no tooltip do campo de email do Sample New User.
**Simulação**
Simular através do próprio sample New User do Tooltip.
> docs(tooltip): ajusta usabilidade do sample New User

- projects/templates/src/lib/components/po-page-dynamic-search/samples/sample-po-page-dynamic-search-hiring-processes/sample-po-page-dynamic-search-hiring-processes.component.ts
- projects/templates/src/lib/components/po-page-dynamic-search/samples/sample-po-page-dynamic-search-hiring-processes/sample-po-page-dynamic-search-hiring-processes.service.ts
**PO-PAGE-DYNAMIC-SEARCH**
**DTHFUI-4568**
No Sample Hiring Processes há um botão de ação da Página com o rótulo `Find on Google` e o mesmo não executa ação alguma ao clicar.
Incluída ação para o botão.
**Simulação**
Simular através do Sample Hiring Processes no portal
> docs(page-dynamic-search): corrige botão sem action no sample

- projects/ui/src/lib/components/po-field/po-field.module.ts
**po-field-container**
**MDO-43**
- [ X ] Código
No módulo **PoFieldModule**, atualmente o módulo **PoFieldContainerModule** está privado.
No módulo **PoFieldModule**, devemos exportar o modulo **PoFieldContainerModule** para que seja possível seu uso.
**Simulação**
> feat(field-container): exporta o módulo PoFieldContainerModule

- projects/ui/src/lib/components/po-chart/enums/po-chart-type.enum.ts
- projects/ui/src/lib/components/po-chart/index.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-axis-options.interface.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-bar-series.interface.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-column-series.interface.ts
- projects/ui/src/lib/components/po-chart/po-chart-base.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-axis/po-chart-axis-label/po-chart-axis-label.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-axis/po-chart-axis-label/po-chart-axis-label.component.svg
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-axis/po-chart-axis-label/po-chart-axis-label.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-axis/po-chart-axis.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-axis/po-chart-axis.component.svg
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-axis/po-chart-axis.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-bar-base.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-bar-path/po-chart-bar-path.component.svg
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-bar.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-bar.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-bar/po-chart-column/po-chart-column.component.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-container.component.html
- projects/ui/src/lib/components/po-chart/po-chart.module.ts
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-coffee-ranking/sample-po-chart-coffee-ranking.component.html
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-coffee-ranking/sample-po-chart-coffee-ranking.component.ts
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-labs/sample-po-chart-labs.component.ts
**po-chart**
**DTHFUI-1755**
Não há.
Criado novo gráfico do tipo `Bar`.
**Simulação**
Simular através dos samples do portal. Usar em conjunto com a [PR do Style](https://github.com/po-ui/po-style/pull/176)
> feat(chart): adiciona gráfico do tipo `bar`

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/samples/sample-po-dynamic-form-register/sample-po-dynamic-form-register.component.ts
Fixes DTHFUI-2670
**Simulação**
> docs(dynamic-form): corrige endpoint no sample

- projects/ui/src/lib/interceptors/po-http-request/samples/sample-po-http-request-interceptor-labs.component.html
Altera o link no help que é utilizado de exemplo no sample.
Fixes DTHFUI-2693
**http-request-interceptor**
**DTHFUI-2693**
Link da API antigo
Inclusão do link novo da API
**Simulação**
> docs(http-request-interceptor): atualiza link da API no sample

- projects/ui/src/lib/interceptors/po-http-interceptor/samples/sample-po-http-interceptor-labs.component.ts
Altera a URL do endpoint messages utilizado no sample.
Fixes DTHFUI-2692
**http-interceptor**
**DTHFUI-2692**
URL antiga para requisição
URL da nova API
**Simulação**
> docs(http-interceptor): altera endpoint utilizado no sample

- README.md
- docs/guides/getting-started.md
- docs/guides/migration-poui-v3.md
- docs/guides/sync-get-started.md
- projects/code-editor/package.json
- projects/storage/package.json
- projects/sync/package.json
- projects/templates/package.json
- projects/ui/package.json
build: atualiza versão do angular nos pacotes
docs: atualiza README e documentos com a versão v11.1.x
**Simulação**
- Seguir getting started/reame do UI e Sync
> docs: atualiza documentos com versões do angular v11

- package.json
- projects/ui/src/lib/components/po-chart/directives/po-resize-observer.directive.spec.ts
- projects/ui/src/lib/components/po-chart/directives/po-resize-observer.directive.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-circular/po-chart-circular-path/po-chart-tooltip.directive.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart.component.html
- projects/ui/src/lib/components/po-chart/po-chart.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart.component.ts
- projects/ui/src/lib/components/po-chart/po-chart.module.ts
**po-chart**
**DTHFUI-4580**
Quando o gráfico interagia com outro elemento
como o menu, o resize não erá feito, causando distorção do gráfico
Corrigida situação
Aprovar PR https://github.com/po-ui/po-style/pull/193
**Simulação**
Simular pelo portal e também nesse app
[app.zip](https://github.com/po-ui/po-angular/files/5822767/app.zip)
> feat(chart): corrige resize do gráfico com elementos externos

- projects/portal/src/app/home/home-colorful/home-colorful.component.html
- projects/portal/src/app/home/home-colorful/home-colorful.component.ts
- projects/portal/src/app/home/home-colorful/home-colorful.service.ts
- projects/portal/src/app/home/home.module.ts
**PORTAL**
**N/A**
A cada release se faz necessário atualizar o número de estrelas no `HomeColorfulComponent`
As estrelas são atualizadas a cada refresh da página por conta de uma service consumindo a api do Github.
**Simulação**
Rodar o portal
> feat(portal): automatiza a atualização de estrelas do projeto

- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-airfare/sample-po-table-airfare.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-airfare/sample-po-table-airfare.component.ts
**< TABLE >**
**< DTHFUI-4854 >**
---
Adiciona o método unselectRows para desmarcar as linhas selecionadas na tabela.
**Simulação**
Utilizar o Sample Airfare no Portal.
>  feat(table): adiciona o método unselectRows 

- docs/guides/deprecations.md
- docs/guides/releases.md
- projects/sync/src/lib/services/po-network/po-network.service.spec.ts
**Releases e Depreciações**
**DTHFUI-4496**
não possui documento de release e depreciações.
Adiciona documento de release e depreciações.
**Simulação**
na parte de guias do Portal verificar as novas docs de Releases e Depreciações.
> docs: adiciona documento de releases e depreciações

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/samples/sample-po-dynamic-form-register/sample-po-dynamic-form-register.component.ts
Ajuste para utilização de placeholder em campos do form dinâmico
dynamic-form
Não permite o uso do placeholder para campos do  form dinâmico
Permite o uso do placeholder para campos do form dinâmico
**Simulação**
Gerar o portal e verificar o sample, ou
```
value = {};
fields = [
{ property: 'name', placeholder: 'DIGITE O SEU NOME' }
];
<po-dynamic-form [p-fields]="fields" [p-value]="value"></po-dynamic-form>
```
> feat(dynamic-form): adiciona placeholder

- CHANGELOG.md
- docs/guides/getting-started.md
- docs/guides/migration-poui.md
- docs/guides/sync-get-started.md
- package.json
- projects/sync/schematics/migrations.json
- projects/ui/schematics/migrations.json
**Release 5.0**
**DTHFUI-5033**
**Simulação**
> build: release v5.0.0

- projects/ui/src/lib/components/po-popup/po-popup-action.interface.ts
- projects/ui/src/lib/components/po-popup/po-popup.component.html
- projects/ui/src/lib/components/po-popup/po-popup.module.ts
- projects/ui/src/lib/components/po-popup/samples/sample-po-popup-labs/sample-po-popup-labs.component.ts
**PO-POPUP**
**DTHFUI-4906**
Permite a utilização de outras fontes de ícones no componente `po-popup`
**Simulação**
Possui PR no [po-style](https://github.com/po-ui/po-style/pull/219).
Sample do Portal, ou utilizar o código abaixo no app:
```
<div class="po-xl-4 po-lg-4 po-md-12 po-sm-12">
<span #poTarget class="po-clickable po-icon po-icon-help" (click)="poPopup.toggle()"></span>PO Icon
<po-popup #poPopup [p-actions]="[{ label: 'PO Popup', icon: 'po-icon-device-tablet', action: next.bind(this) }]" [p-target]="poTarget"> </po-popup> …
```
> feat(popup): adiciona possibilidade de informar outras fontes de ícones

- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
**< LOOKUP / COMBO >**
____________________________________________
fix(combo): realiza tratamento no placeholder caso informar undefined …
fix(lookup): realiza tratamento no placeholder caso informar undefined 
**Simulação**
```
<po-dynamic-form [p-fields]="fields" [p-value]="value"></po-dynamic-form>
```
```
fields = [
{
property: 'favoriteHero',
gridColumns: 6,
gridSmColumns: 12,
label: 'Favorite hero',
optional: true,
searchService: 'https://po-sample-api.herokuapp.com/v1/heroes',
columns: [
{ property: 'nickname', label: 'Hero' },
{ property: 'label', label: 'Name' }
],
format: ['id', 'nickname'],
fieldLabel: 'nickname',
fieldValue: 'email'
},
{
property: 'people',
gridColumns: 6,
gridSmColumns: 12, …
```
> fix(combo | lookup): realiza tratamento no placeholder caso informar undefined 

- projects/ui/src/lib/components/po-dropdown/samples/sample-po-dropdown-labs/sample-po-dropdown-labs.component.ts
- projects/ui/src/lib/components/po-page/po-page-default/samples/sample-po-page-default-labs/sample-po-page-default-labs.component.ts
- projects/ui/src/lib/components/po-page/po-page-list/samples/sample-po-page-list-labs/sample-po-page-list-labs.component.ts
- projects/ui/src/lib/components/po-toolbar/samples/sample-po-toolbar-labs/sample-po-toolbar-labs.component.html
- projects/ui/src/lib/components/po-toolbar/samples/sample-po-toolbar-labs/sample-po-toolbar-labs.component.ts
**DROPDOWN, PAGE-LIST, PAGE-DEFAULT E TOOLBAR**
Não possui sample com outras fontes de ícones.
Incluídos exemplos com outras fontes de ícones nos labs dos componentes.
**Simulação**
Samples Labs do portal
> Docs samples icons

- CHANGELOG.md
- package.json
**RELEASE**
**DTHFUI-5068**
N/A.
N/A.
**Simulação**
N/A.
> build: release v5.2.0

- CHANGELOG.md
- package.json
**RELEASE**
**DTHFUI-5093**
N/A.
N/A.
**Simulação**
N/A.
> build: release v5.2.1

- projects/templates/src/lib/components/po-page-background/po-page-background.component.spec.ts
- projects/templates/src/lib/components/po-page-background/po-page-background.component.ts
**PAGE-LOGIN**
**DTHFUI-5048**
O componente po-page-login não está atualizando as linguagens quando utiliza um endpoint ou qualquer forma assíncrona de atribuição.
O componente foi corrigido e agora atualiza as linguagens através de um endpoint ou de qualquer forma assíncrona.
**Simulação**
Simular o código abaixo no app.
```
<po-page-login
[p-languages]="languages"
</po-page-login>
```
`app.component.ts`
```
languages:any;
constructor() {
setTimeout(() => {
this.languages = [{ description: 'English', language: 'en' },
{ description: 'Español', language: 'es' },
{ description: 'Português', language: 'pt' }];
}, …
```
> fix(page-login): corrigido método coleta de linguagens

- CHANGELOG.md
- package.json
**RELEASE**
**DTHFUI-5232**
N/A.
N/A.
**Simulação**
N/A.
> build: release v5.4.0

- CHANGELOG.md
- package.json
**Release**
**DTHFUI-5155**
**Simulação**
> build: release v5.5.0

- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
PO-COMBO
DTHFUI-2273
Ao selecionar um item do combo via click ou teclado(Enter) os outros itens(estáticos ou vindos de um serviço) não aparecerão na listagem. Caso o usuário queira escolher outro item, deve apagar o valor do input para aparecer novamente os outros itens.
Ao selecionar um item do combo via click ou teclado(Enter) os outros itens(estáticos ou vindos de um serviço) permanecerão visíveis no combo.
**Simulação**
```
<po-combo
class="po-lg-6"
name="heroName"
[(ngModel)]="heroName"
p-field-label="name"
p-field-value="name"
p-filter-service="https://po-sample-api.herokuapp.com/v1/hero …
```
> feat(combo): adiciona condicional para listar os itens do combo

- projects/portal/src/styles.css
- projects/ui/src/lib/components/po-menu/samples/sample-po-menu-human-resources/sample-po-menu-human-resources.service.ts
- projects/ui/src/lib/components/po-menu/samples/sample-po-menu-labs/sample-po-menu-labs.component.html
**Atualiza os links das apis do sample**
**DTHFUI-2687**
Link da api: https://thf.totvs.com.br/sample/api/menus
Visualização do sample com altura incorreta impedindo o uso do botão do collpase e em algumas resoluções o form do sample também não era exibido por completo.
Link da api: https://po-sample-api.herokuapp.com/v1/menus
Ajuste na altura do sample para melhor visualização em tela respeitando suas propriedades.
**Simulação**
`npm run build:portal`
`ng serve portal`
> docs(menu): atualiza os links das apis do sample

- CHANGELOG.md
- package.json
**RELEASE**
**DTHFUI-5187**
N/A.
N/A.
**Simulação**
N/A.
> build: release v5.7.0

- CHANGELOG.md
- package.json
- projects/templates/karma.conf.js
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-content/po-page-content.component.spec.ts
> build: release v5.8.0

- projects/ui/src/lib/components/po-table/po-table-column-icon/po-table-column-icon.interface.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.ts
- projects/ui/src/lib/components/po-table/po-table-icon/po-table-icon.component.html
- projects/ui/src/lib/components/po-table/po-table-icon/po-table-icon.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-icon/po-table-icon.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.module.ts
**< PO-TABLE >**
**< DTHFUI-5138 >**
Permite a utilização de outras fontes de ícones no componente `po-table`.
**Simulação**
PR po-style : 
https://github.com/po-ui/po-style/pull/239
```
<ng-template #iconTemplateIonicAdd>
<ion-icon name="add-outline" style="font-size: inherit;"></ion-icon>
</ng-template>
<ng-template #iconTemplateIonicTrash>
<ion-icon name="trash-outline" style="font-size: inherit;"></ion-icon>
</ng-template>
<ng-template #iconTemplateIonicCopy>
<ion-icon name="copy-outline" style="font-size: inherit;"></ion-icon>
</ng-template> …
```
> feat(table): adiciona compatibilidade com outras fontes de ícones

- CHANGELOG.md
- package.json
**RELEASE**
**DTHFUI-5224**
N/A
N/A
**Simulação**
N/A
> build: release v5.9.0

- projects/templates/src/lib/services/po-page-customization/po-page-customization.service.ts
**< PageDynamicTable >**
**< DTHFUI-3394 >**
A propriedade quickSearchWidth não é atualizada via serviceLoadApi.
A propriedade é inicializada como `undefined` e ao ser filtrada permanece inalterada.
A propriedade quickSearchWidth é atualizada via serviceLoadApi.
A propriedade é inicalizada como `null` e ao ser filtrada recebe um novo valor.
**Simulação**
```
<router-outlet></router-outlet>
```
`app.module.ts`
```
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router'; …
```
> fix(page-dynamic-table): atualiza propriedade via serviceLoadApi

- CHANGELOG.md
- package.json
**Release v5.10.0**
**DTHFUI-5232**
N/A
N/A
**Simulação**
N/A
> build: release v5.10.0

- CHANGELOG.md
- package.json
**BUILD: RELEASE**
**DTHFUI-5236**
N/A.
N/A.
**Simulação**
N/A.
> build: release v5.11.0

- CHANGELOG.md
- package.json
**RELEASE**
**DTHFUI-5304**
N/A.
N/A.
**Simulação**
N/A.
> build: release v5.12.0

- CHANGELOG.md
- package.json
**RELEASE**
**DTHFUI-5330**
N/A.
N/A.
**Simulação**
N/A.
> build: release v5.13.0

- projects/portal/src/app/app.component.ts
Adiciona notificação ao carregar a aplicação do portal,
para incentivar os usuarios a participarem da review.
**Simulação**
Rodar artefato enviado em conjunto com esta PR, dentro de "Checks"
> docs(portal): adiciona notificacao de pesquisa de review

- docs/pull-request-template.md
Atualiza checklist no template da PR;
Para termos um processo a ser visto, facilitando a revisão.
> docs: atualiza checklist no template de PR

- CHANGELOG.md
- package.json
> build: release v5.13.1

- projects/ui/src/lib/components/po-field/po-input-generic/po-input-generic.ts
- projects/ui/src/lib/components/po-field/po-input/po-input-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-input/po-input-base.component.ts
- projects/ui/src/lib/components/po-field/po-input/po-input.component.spec.ts
- projects/ui/src/lib/components/po-field/po-input/po-input.component.ts
**Input**
**DTHFUI-5279**
O component Input utiliza o ChangeDetectionStrategy.Default
O component Input utiliza o ChangeDetectionStrategy.OnPush
**Simulação**
Testar Input e DynamicForm. Pode utilizar o labs do portal
http://localhost:4200/documentation/po-input
> perf(input): implementa ChangeDetectionStrategy OnPush

- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.spec.ts
- projects/ui/src/lib/components/po-popup/po-popup.component.spec.ts
MULTISELECT , POPUP
DTHFUI-5284 
Ao realizar testes nos componentes os mesmo apresentam intermitências
Ao realizar testes nos componentes os mesmo deixam de ter intermitências 
**Simulação**
Rodar os testes manualmente , e rodar no CI.
> test: corrige testes intermitentes

- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-item/po-multiselect-item.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-item/po-multiselect-item.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-item/po-multiselect-item.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-literals.interface.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-search/po-multiselect-search.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/samples/sample-po-multiselect-labs/sample-po-multiselect-labs.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/samples/sample-po-multiselect-labs/sample-po-multiselect-labs.component.ts
**multiselect**
**DTHFUI-3437**
Não tem opção para selecionar todos os itens do multiselect.
Tem opção para selecionar todos os itens do multiselect.
**Simulação**
Build Style : https://github.com/po-ui/po-style/pull/250
`app.component.ts` : 
```
import { PoMultiselectOption } from '../../../ui/src/lib';
@Component({
})
multiselect: any;
multiselectServico: any;
options: Array<PoMultiselectOption> = [
{ value: 'poMultiselect1', label: 'PO Multiselect 1' },
{ value: 'poMultiselect2', label: 'PO …
```
> feat(multiselect): adiciona campo para selecionar todos os itens

- CHANGELOG.md
- package.json
**BUILD RELEASE**
**DTHFUI-5379**
N/A.
N/A.
**Simulação**
N/A.
> build: release v5.14.0

- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.ts
**DATEPICKER**
**DTHFUI-5368**
Ao selecionar uma data, apagar o "model" via programação e tentar selecionar a mesma data, o model não está sendo atualizado.
Ao selecionar uma data, apagar o "model" via programação e tentar selecionar a mesma data, o model está sendo atualizado.
**Simulação**
`component.html`
```
<po-page-default p-title="PO UI">
<po-datepicker p-format="dd/mm/yyyy" name="dtTeste" [(ngModel)]="dtTeste" p-clean p-label="Teste"
(p-change)="check($event)">
</po-datepicker>
{{dtTeste}}
<po-button p-label="Limpa" (p-click)="reset()">
</po-button>
```
`component.ts`
```
import { Component } from …
```
> fix(datepicker): corrige atualização do "model"

- CHANGELOG.md
- package.json
> build: release v5.15.0

- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.ts
Corrige problema de lint, anteriomente não estava sendo
implementado a interface DoCheck,
fazendo com que o lint reclamasse.
> refactor(lookup): corrige lint implementado DoCheck corretamente

- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-basic/sample-po-upload-basic.component.html
- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-labs/sample-po-upload-labs.component.ts
- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-resume-drag-drop/sample-po-upload-resume-drag-drop.component.html
- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-resume/sample-po-upload-resume.component.html
- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-rs/sample-po-upload-rs.component.html
**UPLOAD**
**DTHFUI-2686**
Altera URL para realizar upload de arquivo
**Simulação**
1 - Checkout na branch do po-sample-api: https://github.com/po-ui/po-sample-api/pull/25
2 - npm install
3 - npm run start:dev
4 - alterar a URL : `https://po-sample-api.herokuapp.com/v1/uploads/addFile` para `http://localhost:3000/v1/uploads/addFile` nos seguintes arquivos do PO-UI:
- sample-po-upload-basic.component.html
- sample-po-upload-labs.component.ts
- sample-po-upload-resume-drag-drop.component.html
- sample-po-upload-resume.component.html
- sample-po-upload-rs.component.html
5- testar upload no portal
> docs(upload): altera url de upload

- projects/templates/schematics/ng-generate/po-page-dynamic-detail/files/__path__/__name@dasherize__/__name@dasherize__.component.html.template
- projects/templates/schematics/ng-generate/po-page-dynamic-edit/files/__path__/__name@dasherize__/__name@dasherize__.component.html.template
- projects/templates/schematics/ng-generate/po-page-dynamic-search/files/__path__/__name@dasherize__/__name@dasherize__.component.html.template
- projects/templates/schematics/ng-generate/po-page-dynamic-table/files/__path__/__name@dasherize__/__name@dasherize__.component.html.template
Remove comentário desnecessario, quando criado componente,
via schematics.
> refactor(template): remove comentario desnecessario no schematic

- CHANGELOG.md
- package.json
**Release**
**DTHFUI-5528**
N/A
N/A
**Simulação**
N/A
> build: release v5.20.0

- projects/templates/karma.conf.js
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-base.component.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-execution/po-page-job-scheduler-execution.component.html
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-execution/po-page-job-scheduler-execution.component.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-execution/po-page-job-scheduler-execution.component.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-summary/po-page-job-scheduler-summary.component.html
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-summary/po-page-job-scheduler-summary.component.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.html
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.ts
**job-scheduler**
**DTHFUI-5426**
Não possibilita passar diretamente as propriedades para o componente.
Possibilita passar diretamente as propriedades e assim evitando requisição para a rota "parameters"
**Simulação**
app.html:
```
<po-page-job-scheduler
p-service-api="https://po-sample-api.herokuapp.com/v1/scheduler"
p-title="Background Process Scheduler"
[p-breadcrumb]="breadcrumb"
[p-parameters]="parametros"
>
</po-page-job-scheduler>
```
app.ts: 
```
import { PoBreadcrumb, PoDynamicFormField } from '../../../ui/src/lib';
@Component({
templateUrl: …
```
> feat(job-scheduler): adiciona propriedade p-parameters

- CHANGELOG.md
- package.json
**RELEASE**
**DTHFUI-5549**
N/A
N/A
**Simulação**
N/A
> build: release v5.21.0

- projects/ui/src/lib/components/po-calendar/po-calendar-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-email/po-email.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.spec.ts
- projects/ui/src/lib/components/po-field/po-url/po-url.component.spec.ts
**DTHFUI-5553**
n/a
n/a
**Simulação**
> Corrige testes intermitentes

- CHANGELOG.md
- package.json
> build: release v5.22.0

- projects/ui/src/lib/components/po-table/interfaces/po-table-column.interface.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-components/sample-po-table-components.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-components/sample-po-table-components.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-components/sample-po-table-components.service.ts
**TABLE**
**DTHFUI-2229**
Não permite utilizar objetos aninhados.
É possível utilizar objetos aninhados.
**Simulação**
app.component.html
```
<po-table [p-items]="items" [p-columns]="columns"  > </po-table> 
```
app.component.ts
```
@Component({
})
columns = [{ property: 'name' }, { property: 'address.street', label: 'Rua'},{property:'currency.real', label:'dinheiro', type:'currency'}];
items = [
{
name: 'John Doe',
address: {
street: 'Rua dos Alfeneiros, nº 4'
},
currency: {
real: 200.50
},
}
]; …
```
> feat(table): permite utilizar objetos aninhados

- docs/guides/migration-poui.md
- projects/sync/schematics/migrations.json
- projects/sync/schematics/ng-update/v6/changes.ts
- projects/sync/schematics/ng-update/v6/index.ts
- projects/ui/schematics/migrations.json
- projects/ui/schematics/ng-update/v6/changes.ts
- projects/ui/schematics/ng-update/v6/index.ts
**SCHEMATICS**
**DTHFUI-5485**
N/A
Atualização para o Angular v13.
Documentação do processo de atualização do PO-UI.
**Simulação**
> feat(migration): adiciona ngUpdate e atualiza documentação para v6

- CHANGELOG.md
- package.json
> build: release v6.0.0-rc.1

- projects/ui/src/lib/components/po-field/po-checkbox-group/po-checkbox-group-base.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-select/po-select.component.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.component.ts
**Combo, Select, Checkbox-group e upload**
**DTHFUI-5602**
Insere documentação referente a utilização de ngModel
**Simulação**
Subir portal e ver documentação
> docs(fields): não aceita instrução ngModel no HTML

- CHANGELOG.md
- package.json
- projects/schematics/src/build-component/build-component.ts
- projects/schematics/src/build-file/build-file.ts
- projects/sync/schematics/migrations.json
- projects/ui/schematics/migrations.json
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.spec.ts
**release**
**DTHFUI-5634**
N/A.
N/A.
**Simulação**
N/A.
> build: release v6.0.0

- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text.component.spec.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text.component.ts
**rich-text**
**DTHFUI-5517**
**Simulação**
Simular componente no portal e app:
[app.zip](https://github.com/po-ui/po-angular/files/7780497/app.zip)
> perf(rich-text): implementa ChangeDetectionStrategy.OnPush

- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.ts
**lookup**
**DTHFUI-5516**
Componente utiliza o ChangeDetectionStrategy.Onpush
**Simulação**
Testar sample, labs e app:
[app.zip](https://github.com/po-ui/po-angular/files/7828761/app.zip)
> perf(lookup): implementa ChangeDetectionStrategy.OnPush

- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.ts
**Upload**
**DTHFUI-5518**
**Simulação**
Testar samples e lab do portal e app:
html:
```
<po-upload name="upload" [(ngModel)]="uploadModel" p-label="PO Upload" p-url="https://po-sample-api.herokuapp.com/v1/uploads/addFile">
</po-upload>
{{uploadModel | json}}
```
> perf(upload): implementa ChangeDetectionStrategy.OnPush

- CHANGELOG.md
- package.json
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search-base.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.ts
> Build/dthf UI 5689

- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-search/po-multiselect-search.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-search/po-multiselect-search.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.spec.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.ts
**Combo, Multiselect**
**DTHFUI-5515**
**Simulação**
Testar samples e lab do portal e app:
[app.zip](https://github.com/po-ui/po-angular/files/7790151/app.zip)
> perf(combo, multiselect) : implementa ChangeDetectionStrategy.OnPush

- CHANGELOG.md
- package.json
- projects/ui/src/lib/components/po-menu/po-menu.component.spec.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.ts
> Build/dthf UI 5723

- projects/ui/src/lib/components/po-button/po-button-base.component.ts
**BUTTON**
**DTHFUI-5716**
Ver docs no portal
> feat(button): deprecia propriedade `p-autofocus`

- projects/code-editor/schematics/ng-add/index.spec.ts
- projects/storage/schematics/ng-add/index.spec.ts
- projects/sync/schematics/ng-add/index.spec.ts
- projects/sync/schematics/ng-generate/schema/index.spec.ts
- projects/templates/schematics/ng-add/index.spec.ts
- projects/templates/schematics/ng-generate/po-page-blocked-user/index.spec.ts
- projects/templates/schematics/ng-generate/po-page-change-password/index.spec.ts
- projects/templates/schematics/ng-generate/po-page-dynamic-detail/index.spec.ts
- projects/templates/schematics/ng-generate/po-page-dynamic-edit/index.spec.ts
- projects/templates/schematics/ng-generate/po-page-dynamic-search/index.spec.ts
- projects/templates/schematics/ng-generate/po-page-dynamic-table/index.spec.ts
- projects/templates/schematics/ng-generate/po-page-job-scheduler/index.spec.ts
- projects/templates/schematics/ng-generate/po-page-login/index.spec.ts
- projects/ui/schematics/ng-add/index.spec.ts
- projects/ui/schematics/ng-generate/po-page-default/index.spec.ts
- projects/ui/schematics/ng-generate/po-page-detail/index.spec.ts
- projects/ui/schematics/ng-generate/po-page-edit/index.spec.ts
- projects/ui/schematics/ng-generate/po-page-list/index.spec.ts
- projects/ui/schematics/ng-generate/sidemenu/index.spec.ts
**DTHFUI-5682**
**Simulação**
rodar `npm run test:schematics`
> test(schematics): habilita testes comentados

- CHANGELOG.md
- package.json
> build: release 6.4.0

- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.ts
**LOOKUP-MODAL**
**DTHFUI-5751**
**Simulação**
Testar sample, labs e app:
[app.zip](https://github.com/po-ui/po-angular/files/7828761/app.zip)
> perf(lookup-modal): implementa ChangeDetectionStrategy.OnPush

- projects/ui/src/lib/components/po-field/po-field.model.ts
**SELECT** e **SWITCH**
**DTHFUI-5757**
Ver docs no portal
> feat(field): deprecia propriedade `autofocus` no po-switch e po-select

- projects/ui/src/lib/components/po-field/po-select/po-select-option-template/po-select-option-template.directive.ts
- projects/ui/src/lib/components/po-field/po-select/po-select.component.ts
Fixes DTHFUI-5756
**SELECT**
**DTHFUI-5756**
Ver docs no portal
> feat(select): deprecia o PoSelectOptionTemplate

- projects/ui/src/lib/components/po-field/po-lookup/interfaces/po-lookup-column.interface.ts
> docs(lookup): inclui tipo dateTime nas colunas

- CHANGELOG.md
- package.json
> build: release v6.5.0

- CHANGELOG.md
- package.json
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.ts
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-sw-films/sample-po-lookup-sw-films.component.ts
> build: release v5.22.5

- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.ts
**LOOKUP**
**DTHFUI-5706**
O Registro não é encontrado após click em carregar mais resultados.
A paginação é resetada sempre que é fechado o modal de Advanced Search.
**Simulação**
Utilizar este [app](https://github.com/po-ui/po-angular/files/8209431/app.zip) ou utilizar no Portal com o exemplo `PO Lookup - Hero`, e seguir os seguintes passos abaixo:
1. Clique em Busca Avançada, e digite Peter Parker no Name;
2. Na tabela mostra os dados corretamente;
3. Limpar o filtro, e após clicar em Carregar mais resultados;
4. Repetindo a consulta do item 1.
> fix(lookup): ajusta pesquisa de filtro avançado

- CHANGELOG.md
- package.json
> build: release v6.5.1

- CHANGELOG.md
- package.json
- projects/ui/src/lib/components/po-calendar/po-calendar-wrapper/po-calendar-wrapper.component.html
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.ts
> build: release v5.22.6

- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/templates/src/lib/utils/util.spec.ts
- projects/templates/src/lib/utils/util.ts
**DTHFUI-5713**
Cria função que permite atualizar em mais momentos os dados da tabela
**Simulação**
app: 
1- subir local o po-sample api => npm run start.  https://github.com/po-ui/po-sample-api
2- testar app:
[app.zip](https://github.com/po-ui/po-angular/files/8248149/app.zip)
> feat(page-dynamic-table): cria função para atualizar a tabela

- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.html
**Combo**
**DTHFUI-5732**
Possibilita a seleção do item do combo clicando nas letras que estão filtradas no item
Não possibilita a seleção do item do combo clicando nas letras que estão filtradas no item
**Simulação**
Pode ser realizado pelos samples do portal
> fix(combo): possibilita a seleção do item pela palavra filtrada

- CHANGELOG.md
- package.json
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-serie.interface.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.html
- projects/ui/src/lib/services/po-color/po-color.service.spec.ts
- projects/ui/src/lib/services/po-color/po-color.service.ts
> build: release v5.22.7

- CHANGELOG.md
- package.json
> build: release v6.7.0

- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox-base.component.ts
- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox.component.html
- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox.component.spec.ts
- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox.component.ts
- projects/ui/src/lib/components/po-field/po-checkbox/samples/sample-po-checkbox-acceptance-term/sample-po-checkbox-acceptance-term.component.html
**checkbox**
**DTHFUI-5841**
**Simulação**
Testar portal e app :
[app.zip](https://github.com/po-ui/po-angular/files/8391586/app.zip)
Stlyle: https://github.com/po-ui/po-style/pull/294
theme-totvs:  https://github.com/totvs/po-theme-totvs/pull/143
Para testar Theme-totvs : 
1- npm install -g @po-ui/theme-cli (no angular)
2- alterar no angular json :
```
"styles": [
"./node_modules/@totvs/po-theme/css/po-theme-default.min.css",
"projects/app/src/styles.css"
],
```
3- npm run build na branch do theme-totvs e passar a dist pro angular
> feat(checkbox): melhora acessibilidade e contraste do componente

- CHANGELOG.md
- package.json
> build: release v6.8.0

- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-filter.service.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-filter.service.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.html
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-infinity-scroll/sample-po-combo-infinity-scroll.component.html
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-infinity-scroll/sample-po-combo-infinity-scroll.component.ts
**COMBO**
**DTHFUI-5400**
Não é possível usar paginação no combo.
Permite utilizar paginação no combo utilizando o infinite scroll.
**Simulação**
Utilizar o app abaixo:
```html
<form>
<po-combo
class="po-mt-1 po-md-12"
p-filter-service="https://po-sample-api.herokuapp.com/v1/people"
p-label="Heroes"
name="people"
[(ngModel)]="people"
(p-change)="changeModel($event)"
[p-infinite-scroll]="true"
p-field-label="name"
p-field-value="id"
></po-combo>
</form>
</div>
<span *ngIf="people">Escolhido -> {{ people }}</span>
</div> …
```
> feat(combo): adiciona paginação com `infinite-scroll`

- projects/ui/src/lib/directives/po-tooltip/po-tooltip-base.directive.ts
- projects/ui/src/lib/directives/po-tooltip/po-tooltip.directive.spec.ts
- projects/ui/src/lib/directives/po-tooltip/po-tooltip.directive.ts
**tooltip**
**DTHFUI-5860**
Não mostra a tooltip no foco do componente
Mostra a tooltip no foco do componente
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/8442799/app.zip)
> feat(tooltip): abre o tooltip no foco do componente

- CHANGELOG.md
- package.json
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
> build: release v6.9.0

- projects/ui/src/lib/components/po-button/po-button.component.html
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.component.html
**Button**
**DTHFUI-5850**
**Simulação**
Testar portal e app.
```
<po-divider p-label="Tamanho padrão"> </po-divider>
<po-button p-type="primary" p-label="Text"> </po-button>
<po-button p-label="Default"> </po-button>
<po-button p-type="link" p-label="Link"> </po-button>
<po-button p-type="danger" p-label="Danger"> </po-button>
<po-divider p-label="Tamanho padrão - Desabilitato"> </po-divider>
<po-button p-type="primary" p-label="Text disabled" p-disabled> </po-button>
<po-button p-label="Default disabled" p-disabled> </po-button>
<po-button p-type="link" p-label="Link disabled" p-disabled> </po-button>
<po-button p-type="danger" p-label="Danger" p-disabled> </po-button>
<po-divider …
```
> feat(button): aplica estilo definido pelo design system

- CHANGELOG.md
- package.json
- projects/portal/src/app/app.component.ts
> build: release v6.10.0

- CHANGELOG.md
- package.json
> build: release v6.10.1

- projects/templates/src/lib/components/po-page-dynamic-edit/samples/sample-po-page-dynamic-edit-user/sample-po-page-dynamic-edit-user.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic.util.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic.util.ts
Foi adicionado os atributos na interface PoDynamicField:
- offsetColumns
- offsetSmColumns
- offsetMdColumns
- offsetLgColumns
- offsetXlColumns
Fixes #1141
** Page Dynamic Edit **
** 1141 **
O componente não tinha o atributo offset
Foi adicionado o atributo na interface PoDynamicField e como esta interface é estendida por outras, quatro componentes forambeneficiado:
- **Page Dynamic Edit**
- **Page Dynamic Detail**
- **Dynamic Form**
- **Dynamic View**
**Simulação**
A simulação pode ser feita no componente **Page Dynamic Edit**.
> feat(page-dynamic-edit): adiciona atributo offset

- CHANGELOG.md
- package.json
> build: release v6.11.0

- CHANGELOG.md
- package.json
> build: release v6.12.0

- projects/portal/src/app/app.component.ts
> docs(portal): remove notification da pesquisa de review

- CHANGELOG.md
- package.json
> build: release v6.12.1

- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.html
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-airfare/sample-po-table-airfare.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-airfare/sample-po-table-airfare.component.ts
**Table**
**fixes DTHFUI-6147**
Não permite ordenar as colunas da tabela
Permite ordenar as colunas da tabela
**Simulação**
Style: https://github.com/po-ui/po-style/pull/311
App e testar todos os samples do portal :
[app.zip](https://github.com/po-ui/po-angular/files/8824884/app.zip)
> feat(table): permite ordernar colunas

- projects/ui/src/lib/components/po-button/po-button-base.component.spec.ts
- projects/ui/src/lib/components/po-button/po-button-base.component.ts
- projects/ui/src/lib/components/po-button/samples/sample-po-button-labs/sample-po-button-labs.component.html
- projects/ui/src/lib/components/po-button/samples/sample-po-button-labs/sample-po-button-labs.component.ts
**BUTTON**
**DTHFUI-6002**
Não permite utilizar o botão primário com o danger habilitado
Permite utilizar o botão primário com o danger habilitado
**Simulação** 
app.html
```
<po-page-default p-title="PO Page Default">
<po-button p-label="Primary" p-kind="primary"> </po-button> &nbsp; &nbsp;
<po-button p-label="Secondary " p-kind="secondary" > </po-button> &nbsp; &nbsp;
<po-button p-label="Tertiary" p-kind="tertiary"> </po-button> &nbsp; &nbsp;
<hr>
<po-button p-label="Primary Danger" p-kind="primary" [p-danger]="true"> </po-button> &nbsp; &nbsp;
<po-button p-label="Secondary Danger" p-kind="secondary" [p-danger]="true"> …
```
> feat(button): inclui estilo kind primary danger

- CHANGELOG.md
- package.json
> build: release v6.13.0

- CHANGELOG.md
- package.json
> build: release v6.13.1

- CHANGELOG.md
- package.json
> build: release v6.14.0

- docs/guides/migration-poui.md
- projects/code-editor/schematics/ng-add/schema.json
- projects/storage/schematics/ng-add/schema.json
- projects/sync/schematics/migrations.json
- projects/sync/schematics/ng-add/schema.json
- projects/sync/schematics/ng-update/v14/changes.ts
- projects/sync/schematics/ng-update/v14/index.ts
- projects/templates/schematics/ng-add/schema.json
- projects/ui/schematics/migrations.json
- projects/ui/schematics/ng-add/schema.json
- projects/ui/schematics/ng-update/v14/changes.ts
- projects/ui/schematics/ng-update/v14/index.ts
> feat(schematics): migração para v.14

- projects/ui/src/lib/components/po-field/po-input/samples/sample-po-input-labs/sample-po-input-labs.component.html
- projects/ui/src/lib/components/po-field/po-lookup/samples/sample-po-lookup-labs/sample-po-lookup-labs.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/samples/sample-po-multiselect-labs/sample-po-multiselect-labs.component.html
- projects/ui/src/lib/components/po-field/po-radio-group/samples/sample-po-radio-group-labs/sample-po-radio-group-labs.component.html
- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-rs/sample-po-upload-rs.component.html
**po-button, po-combo, po-checkbox-group, po-datepicker-range, po-multiselect, po-switch**
**po-radio-group, po-textarea, po-info, po-dropdown, po-input, po-lookup, po-select, po-upload**
**DTHFUI-5852**
Componentes possuem redimensionamento.
Componentes deixam de ter redimensionamento.
**Simulação**
PORTAL e validar samples | => https://github.com/po-ui/po-style/pull/318
> refactor(components): remove redimensionamentos

- CHANGELOG.md
- package.json
> build: release v14.0.0-next.0

- CHANGELOG.md
- docs/guides/getting-started.md
- docs/guides/sync-get-started.md
- package.json
> build: release v14.0.0-rc.0

- projects/templates/src/lib/components/po-page-login/po-page-login.component.spec.ts
- projects/ui/src/lib/components/po-button/po-button-base.component.ts
- projects/ui/src/lib/components/po-button/po-button.component.html
- projects/ui/src/lib/components/po-button/po-button.component.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.spec.ts
- projects/ui/src/lib/components/po-modal/po-modal.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-detail/po-page-detail.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-edit/po-page-edit.component.spec.ts
- projects/ui/src/lib/services/po-dialog/po-dialog.service.spec.ts
**DTHFUI-6075**
Inclusão de global e brand tokens e possibilidade de customização utilizando variáveis padronizadas.
**Simulação**
STYLE: https://github.com/po-ui/po-style/pull/321
THEME-TOTVS:https://github.com/totvs/po-theme-totvs/pull/159
**Desabilitar cache do angular**
testar portal e app : 
[app.zip](https://github.com/po-ui/po-angular/files/9029885/app.zip)
para testar theme totvs:
1- build no style
2- repasse a dist do style para o theme-totvs
3- build theme-totvs
4- repassar a dist do theme-totvs para o po-ui
5- alterar angular.json
```
"styles": [
"./node_modules/@totvs/po-theme/css/po-theme-default-variables.min.css", …
```
> Inclui global e brand tokens no botão

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form.component.html
** DTHFUI-6185**
Não possui a propriedade OnModelChange em alguns componentes
Possui a propriedade OnModelChange em alguns componentes
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/9074321/app.zip)
> feat(dynamic-form): cria a propriedade `p-validate-on-input`

- CHANGELOG.md
- package.json
- projects/sync/schematics/migrations.json
- projects/ui/schematics/migrations.json
> build: release v14.0.0

- CHANGELOG.md
- docs/guides/getting-started.md
- docs/guides/migration-poui.md
- docs/guides/sync-get-started.md
- package.json
> build: release v14.1.0

- .github/workflows/publish_po_angular_ci.yml
build: ajusta versão do node no workflow de publish
> build: ajusta versão do node no workflow de publish

- CHANGELOG.md
- package.json
> build: release v14.2.0

- CHANGELOG.md
- package.json
- projects/portal/src/app/app.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
> build: release v14.2.1

- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.spec.ts
- projects/ui/karma.conf.js
- projects/ui/src/lib/components/po-field/po-lookup/services/po-lookup-filter.service.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.service.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.service.ts
> Test-fix-angular 14

- projects/ui/src/lib/components/po-widget/po-widget-base.component.ts
- projects/ui/src/lib/components/po-widget/po-widget.component.html
- projects/ui/src/lib/components/po-widget/po-widget.component.spec.ts
**WIDGET**
**DTHFUI-6256**
Ao ser utilizado mais de uma vez na mesma tela o componente apresenta mensagem (ID attribute values must be unique) no axe DevTools.
Componente não apresenta mensagem (ID attribute values must be unique) no axe DevTools.
**Simulação**
Rodar build do portal e testar samples com axe DevTools.
> feat(widget): adiciona UUID

- projects/ui/src/lib/components/po-field/po-checkbox-group/po-checkbox-group.component.html
- projects/ui/src/lib/components/po-field/po-checkbox-group/po-checkbox-group.component.spec.ts
- projects/ui/src/lib/components/po-field/po-checkbox-group/po-checkbox-group.module.ts
- projects/ui/src/lib/components/po-field/po-checkbox-group/samples/sample-po-checkbox-group-labs/sample-po-checkbox-group-labs.component.html
- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox-base.component.ts
- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox.component.html
- projects/ui/src/lib/components/po-field/po-checkbox/po-checkbox.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.html
**Checkbox-group**
**DTHFUI-6248**
Reutiliza checkbox interno no checkbox-group
**Simulação**
Testar labs e sample do portal
style: https://github.com/po-ui/po-style/pull/330
> Checkbox group - Utiliza po-checkbox 

- projects/ui/src/lib/components/po-field/po-switch/po-switch.component.html
- projects/ui/src/lib/components/po-field/po-switch/po-switch.component.spec.ts
- projects/ui/src/lib/components/po-field/po-switch/po-switch.component.ts
**SWITCH**
**DTHFUI-6352**
O componente não apresenta o estilo definido pelo design system e não segue as regras de acessibilidade.
O componente apresenta novo estilo definido pelo design system e segue as regras de acessibilidade.
**Simulação**
Simular no APP e no portal.
[app.zip](https://github.com/po-ui/po-angular/files/9312261/app.zip)
**Style**
> https://github.com/po-ui/po-style/pull/332
**Theme Totvs**
> https://github.com/totvs/po-theme-totvs/pull/166
> feat(switch): aplica estilo definido pelo DS

- projects/ui/src/lib/components/po-loading/po-loading-overlay/po-loading-overlay-base.component.spec.ts
- projects/ui/src/lib/components/po-loading/po-loading-overlay/po-loading-overlay-base.component.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
**po-loading-overlay po-table**
**Sem issue aberta**
__________________________________________________________________________
Traducao errada погрузка
Traducao certa Загрузка
**Simulação**
> fix(translation): corrected translation russian

- CHANGELOG.md
- package.json
> build: release v14.4.0

- projects/ui/src/lib/components/po-tag/po-tag-base.component.spec.ts
- projects/ui/src/lib/components/po-tag/po-tag-base.component.ts
- projects/ui/src/lib/components/po-tag/po-tag.component.html
- projects/ui/src/lib/components/po-tag/po-tag.component.ts
- projects/ui/src/lib/components/po-tag/samples/sample-po-tag-labs/sample-po-tag-labs.component.html
- projects/ui/src/lib/components/po-tag/samples/sample-po-tag-labs/sample-po-tag-labs.component.ts
**TAG**
**DTHFUI-6089**
não possibilita customizar cor da TAG
possibilita customizar cor da TAG
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/9566289/app.zip)
e portal
> feat(tag): possibilita customização de cores

- projects/ui/src/lib/components/po-field/po-checkbox-group/po-checkbox-group.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.html
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.ts
- projects/ui/src/lib/components/po-table/po-table-list-manager/po-table-list-manager.component.html
- projects/ui/src/lib/components/po-table/po-table-list-manager/po-table-list-manager.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-list-manager/po-table-list-manager.component.ts
- projects/ui/src/lib/components/po-table/po-table.module.ts
**Table**
**DTHFUI-6386**
**Simulação**
style: https://github.com/po-ui/po-style/pull/344
App: 
[app.zip](https://github.com/po-ui/po-angular/files/9607947/app.zip)
e portal
> fix(table): corrige posicionamento do gerenciador

- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.html
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range.component.html
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.html
- projects/ui/src/lib/components/po-field/po-decimal/po-decimal.component.html
- projects/ui/src/lib/components/po-field/po-input/po-input.component.html
- projects/ui/src/lib/components/po-field/po-login/po-login.component.html
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.html
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-search/po-multiselect-search.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.html
- projects/ui/src/lib/components/po-field/po-number/po-number.component.html
- projects/ui/src/lib/components/po-field/po-password/po-password.component.html
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.html
Inclui definições do design system nos seguintes componentes:
po-input
po-url
po-password
po-number
po-multiselect
po-lookup
po-login
po-email
po-decimal
po-datepicker
po-datepicker-range
po-combo
fixes DTHFUI-6339
**Simulação**
style: https://github.com/po-ui/po-style/pull/339
theme-totvs: https://github.com/totvs/po-theme-totvs/pull/175
para testar no theme-totvs:
```
"styles": [
"./node_modules/@totvs/po-theme/css/po-theme-default-variables.min.css",
"./node_modules/@totvs/po-theme/css/po-theme-default.min.css",
"./node_modules/@po-ui/style/css/po-theme-core.min.css",
"projects/app/src/styles.css"
],
```
Testar app e portal : …
> feat(fields): inclui definições do AnimaliaDS

- projects/ui/src/lib/components/po-field/po-select/po-select.component.html
- projects/ui/src/lib/components/po-field/po-select/po-select.component.spec.ts
- projects/ui/src/lib/components/po-field/po-select/po-select.component.ts
**SELECT**
**DTHFUI-6443**
O componente não apresenta o estilo definido pelo design system e não segue as regras de acessibilidade.
O componente apresenta novo estilo definido pelo design system e segue as regras de acessibilidade.
**Simulação**
Simular no APP e no portal.
[app.zip](https://github.com/po-ui/po-angular/files/9492034/app.zip)
**po-style**
[style](https://github.com/po-ui/po-style/pull/341)
**po-theme-totvs**
[theme-totvs](https://github.com/totvs/po-theme-totvs/pull/177)
> feat(select): aplica estilo definido pelo DS

- CHANGELOG.md
- package.json
> build: release v14.5.0

- CHANGELOG.md
- package.json
- projects/portal/src/app/app.component.ts
> build: release v14.6.0

- projects/ui/src/lib/components/components.module.ts
- projects/ui/src/lib/components/index.ts
- projects/ui/src/lib/components/po-link/index.ts
- projects/ui/src/lib/components/po-link/po-link-base.component.spec.ts
- projects/ui/src/lib/components/po-link/po-link-base.component.ts
- projects/ui/src/lib/components/po-link/po-link.component.html
- projects/ui/src/lib/components/po-link/po-link.component.spec.ts
- projects/ui/src/lib/components/po-link/po-link.component.ts
- projects/ui/src/lib/components/po-link/po-link.module.ts
- projects/ui/src/lib/components/po-link/samples/sample-po-link-basic/sample-po-link-basic.component.html
- projects/ui/src/lib/components/po-link/samples/sample-po-link-basic/sample-po-link-basic.component.ts
- projects/ui/src/lib/components/po-link/samples/sample-po-link-heroes/sample-po-link-heroes.component.html
- projects/ui/src/lib/components/po-link/samples/sample-po-link-heroes/sample-po-link-heroes.component.ts
- projects/ui/src/lib/components/po-link/samples/sample-po-link-labs/sample-po-link-labs.component.html
- projects/ui/src/lib/components/po-link/samples/sample-po-link-labs/sample-po-link-labs.component.ts
**LINK**
**DTHFUI-6508**
Não possui componente de link.
Criado componente de link seguindo as definições do AnimaliaDS.
**Simulação**
Samples do Portal e o app abaixo:
```html
Para maiores informações acesse nosso <po-link  p-label="changelod" p-url="https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md" p-open-new-tab></po-link> ou acesse nossas <po-link p-label="redes sociais" p-url="https://linktr.ee/pouidev"></po-link>.
```
**PRs Adicionais:**
- https://github.com/po-ui/po-style/pull/348
- https://github.com/totvs/po-theme-totvs/pull/181
> feat(link): cria novo componente po-link

- CHANGELOG.md
- package.json
> build: release v14.7.0

- projects/ui/src/lib/components/po-table/po-table-icon/po-table-icon.component.html
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
DTHFUI-6521
**TABLE**
**DTHFUI-6521**
tooltip não fica alinhada com o elemento quando utilizada a table com altura
tooltip fica alinhada com o elemento quando utilizada a table com altura
**Simulação**
Testar labs do portal com altura definida e propriedade Hide text overflow habilitada
> fix(table): corrige posicionamento da tooltip

- CHANGELOG.md
- package.json
> build: release 14.7.1

- projects/ui/src/lib/components/po-widget/po-widget-base.component.ts
- projects/ui/src/lib/components/po-widget/po-widget.component.html
- projects/ui/src/lib/components/po-widget/po-widget.component.spec.ts
- projects/ui/src/lib/components/po-widget/po-widget.component.ts
**WIDGET**
**DTHFUI-6575**
O componente não tinha as definições de acessibilidade e estilo definidos pelo AnimaliaDS.
O componente agora está de acordo com as definições de acessibilidade e estilo definidos pelo AnimaliaDS.
**Simulação**
Sample do Portal e o seguinte [app.zip](https://github.com/po-ui/po-angular/files/9824366/app.zip)
**PR Relacionados**
- https://github.com/po-ui/po-style/pull/354
- https://github.com/totvs/po-theme-totvs/pull/187
> feat(widget): implementa definições do AnimaliaDS

- CHANGELOG.md
- package.json
> build: release v14.8.0

- projects/portal/src/app/app.component.ts
remove notification sobre o NPS 2022 do portal.
> docs(portal): remove notification sobre o NPS 2022

- projects/ui/src/lib/components/po-field/po-select/po-select.component.html
- projects/ui/src/lib/components/po-field/po-select/po-select.component.spec.ts
- projects/ui/src/lib/components/po-field/po-select/po-select.component.ts
**Select**
**DTHFUI-6588**
componente não está renderizando a opção correta ao utilizar formulario reativo
componente está renderizando a opção correta ao utilizar formulario reativo
**Simulação**
style: https://github.com/po-ui/po-style/pull/356
portal e  app: 
[app.zip](https://github.com/po-ui/po-angular/files/9863182/app.zip)
> fix(select): corrige renderização de conteúdo

- projects/ui/src/lib/components/po-page/po-page-list/samples/sample-po-page-list-labs/sample-po-page-list-labs.component.html
docs(page-list): atualiza url base da API
> docs(page-list): atualiza url base da API

- projects/ui/src/lib/components/po-stepper/samples/sample-po-stepper-active/sample-po-stepper-active.service.ts
docs(stepper): atualiza url base da API
> docs(stepper): atualiza url base da API

- projects/ui/src/lib/interceptors/po-http-interceptor/samples/sample-po-http-interceptor-labs.component.ts
docs(http-interceptor): atualiza url base da API
> docs(http-interceptor): atualiza url base da API

- projects/ui/src/lib/components/po-field/po-switch/po-switch.component.ts
**< Switch >**
Fixes #1424 
**< #1424  >**
Não estava clara a informação sobre a propriedade p-label-position
Melhoria na documentação para melhor entendimento dessa propriedade.
**Simulação**
npm run build:portal && ng serve portal
> docs(switch): alteração da documentação da  propriedade p-label-position

- CHANGELOG.md
- package.json
**RELEASE**
**DTHFUI-6753**
N/A
N/A
**Simulação**
N/A
> build: release v14.8.1

- projects/ui/src/lib/components/po-container/po-container-base.component.spec.ts
- projects/ui/src/lib/components/po-container/po-container-base.component.ts
- projects/ui/src/lib/components/po-container/po-container.component.html
- projects/ui/src/lib/components/po-container/po-container.component.spec.ts
- projects/ui/src/lib/components/po-container/samples/sample-po-container-labs/sample-po-container-labs.component.html
- projects/ui/src/lib/components/po-container/samples/sample-po-container-labs/sample-po-container-labs.component.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.html
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.ts
- projects/ui/src/lib/components/po-tree-view/po-tree-view.component.html
**CONTAINER**
**DTHFUI-6665**
O componente não tinha as definições de acessibilidade e estilo definidos pelo AnimaliaDS.
O componente agora está de acordo com as definições de acessibilidade e estilo definidos pelo AnimaliaDS.
**Simulação**
Utilizar os samples do Portal ou este [App.zip](https://github.com/po-ui/po-angular/files/9883043/App.zip).
**PR Relacionados**
- https://github.com/po-ui/po-style/pull/360
- https://github.com/totvs/po-theme-totvs/pull/190
> feat(container): implementa definições do AnimaliaDS

- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/samples/sample-po-dynamic-view-employee-on-load/sample-po-dynamic-view-employee-on-load.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/samples/sample-po-dynamic-view-employee/sample-po-dynamic-view-employee.component.ts
- projects/ui/src/lib/components/po-tag/po-tag-base.component.spec.ts
- projects/ui/src/lib/components/po-tag/po-tag-base.component.ts
- projects/ui/src/lib/components/po-tag/po-tag.component.html
- projects/ui/src/lib/components/po-tag/po-tag.component.spec.ts
- projects/ui/src/lib/components/po-tag/po-tag.component.ts
- projects/ui/src/lib/components/po-tag/po-tag.module.ts
- projects/ui/src/lib/components/po-tag/samples/sample-po-tag-bank-account/sample-po-tag-bank-account.component.html
- projects/ui/src/lib/components/po-tag/samples/sample-po-tag-bank-account/sample-po-tag-bank-account.component.ts
- projects/ui/src/lib/components/po-tag/samples/sample-po-tag-labs/sample-po-tag-labs.component.html
- projects/ui/src/lib/components/po-tag/samples/sample-po-tag-labs/sample-po-tag-labs.component.ts
**TAG**
**DTHFUI-6664**
**Simulação**
style: https://github.com/po-ui/po-style/pull/362
theme: https://github.com/totvs/po-theme-totvs/pull/193
testar app, portal e customização:
[app.zip](https://github.com/po-ui/po-angular/files/9910552/app.zip)
> feat(tag): aplica estilo definido pelo DS

- CHANGELOG.md
- package.json
- projects/ui/src/lib/components/po-container/po-container-base.component.ts
> build: release v14.9.0

- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
**DTHFUI-6493**
Apresenta erro no console ao interagir com gerenciador de colunas
Não apresenta erro no console ao interagir com gerenciador de colunas
**Simulação**
`App`  [app.zip](https://github.com/po-ui/po-angular/files/9964711/app.zip)
> fix(dynamic-form): corrige erro no console

- CHANGELOG.md
- package.json
> build: release v14.9.1

- projects/ui/src/lib/components/po-loading/interfaces/po-loading-literals.interface.ts
- projects/ui/src/lib/components/po-loading/po-loading-base.component.spec.ts
- projects/ui/src/lib/components/po-loading/po-loading-base.component.ts
- projects/ui/src/lib/components/po-loading/po-loading.component.spec.ts
**Po-loading**
**1505**
Mostra o string fixo "Carregando" independente do locale selecionado
Mostra o string "Carregando" no idioma correto
**Simulação**
> fix(po-loading): added translations

- projects/ui/src/lib/components/po-link/po-link-base.component.ts
- projects/ui/src/lib/components/po-link/po-link.component.html
- projects/ui/src/lib/components/po-link/po-link.component.spec.ts
- projects/ui/src/lib/components/po-link/po-link.component.ts
- projects/ui/src/lib/components/po-link/samples/sample-po-link-heroes/sample-po-link-heroes.component.html
- projects/ui/src/lib/components/po-link/samples/sample-po-link-heroes/sample-po-link-heroes.component.ts
**Link**
**DTHFUI-6763**
adiciona funcionalidade para permitir execução de action
**Simulação**
testar app e portal:
html:
```
<button>um</button>
<br />
<po-link p-label="PO Link url e action" (p-action)="teste()" p-url="https://po-ui.io" [p-open-new-tab]="true"></po-link>
<br />
<button>dois</button>
<br />
<po-link p-label="PO Link url" p-url="https://po-ui.io" [p-open-new-tab]="true"></po-link>
<br />
<button>tres</button>
<br />
<po-link p-label="PO Link action" (p-action)="teste()"></po-link>
```
app: 
```
teste() {
console.log('click')
}
```
> feat(link): adiciona action no componente

- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search-base.component.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.html
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.html
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list-base.component.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.html
**dynamic-table**
**DTHFUI-4279**
Cria input `p-quick-search-value` para setar o valor da busca rápida na inicialização do componente
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/9990391/app.zip)
> feat(dynamic-table): cria input para setar busca rápida

- CHANGELOG.md
- package.json
> build: release v14.10.0

- projects/ui/src/lib/services/po-language/po-language.service.ts
**LANGUAGE**
**DTHFUI-6810**
**Realiza rollback de contribuição: - https://github.com/po-ui/po-angular/commit/96c2a9a1d50886c39feeb56866ed2208a4e9177d**
> fix(language): ajusta configuração de linguagem

- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.html
**DATEPICKER**
**#1551**
Após aplicar as definições do AnimaliaDS no PoDatepicker, o PoRichText apresentou problema na apresentação visual.
Após corrigir a estrutura do componente PoDatepicker o componente PoRichText passou a ser apesentado corretamente.
**Simulação**
Portal.
> fix(datepicker): ajuste estrutural

- CHANGELOG.md
- package.json
> build: release v14.11.0

- projects/templates/src/lib/components/po-page-dynamic-edit/samples/sample-po-page-dynamic-edit-user/sample-po-page-dynamic-edit-user.component.ts
- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-labs/sample-po-upload-labs.component.ts
- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-resume-drag-drop/sample-po-upload-resume-drag-drop.component.html
- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-resume/sample-po-upload-resume.component.html
- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-rs/sample-po-upload-rs.component.html
- projects/ui/src/lib/components/po-link/samples/sample-po-link-heroes/sample-po-link-heroes.component.html
- projects/ui/src/lib/components/po-menu/samples/sample-po-menu-human-resources/sample-po-menu-human-resources.service.ts
- projects/ui/src/lib/components/po-menu/samples/sample-po-menu-labs/sample-po-menu-labs.component.html
- projects/ui/src/lib/components/po-page/po-page-detail/samples/sample-po-page-detail-labs/sample-po-page-detail-labs.component.html
- projects/ui/src/lib/components/po-page/po-page-edit/samples/sample-po-page-edit-labs/sample-po-page-edit-labs.component.html
> docs: muda url base da api

- projects/ui/src/lib/components/po-disclaimer-group/po-disclaimer-group-base.component.spec.ts
- projects/ui/src/lib/components/po-disclaimer-group/po-disclaimer-group-base.component.ts
- projects/ui/src/lib/components/po-disclaimer-group/po-disclaimer-group.component.spec.ts
- projects/ui/src/lib/components/po-disclaimer-group/po-disclaimer-group.component.ts
- projects/ui/src/lib/components/po-disclaimer-group/po-disclaimer-group.module.ts
- projects/ui/src/lib/components/po-disclaimer-group/po-disclaimer-remove/po-disclaimer-remove.component.html
- projects/ui/src/lib/components/po-disclaimer-group/po-disclaimer-remove/po-disclaimer-remove.component.spec.ts
- projects/ui/src/lib/components/po-disclaimer/po-disclaimer.component.html
- projects/ui/src/lib/components/po-disclaimer/po-disclaimer.component.spec.ts
- projects/ui/src/lib/components/po-disclaimer/po-disclaimer.component.ts
- projects/ui/src/lib/components/po-disclaimer/po-disclaimer.module.ts
**DISCLAIMER**
**DTHFUI-6732**
Atualmente o componente não possui as configurações de estilo e acessibilidade do AnimaliaDS
Agora o componente possui as configurações de estilo e acessibilidade do AnimaliaDS
**Simulação**
Usar os Samples do Portal ou o APP abaixo:
```html
<po-disclaimer-group [p-disclaimers]="disclaimers"></po-disclaimer-group>
<po-multiselect name="multiselect" p-label="PO Multiselect" p-filter-service="https://po-sample-api.herokuapp.com/v1/heroes"> </po-multiselect>
<po-disclaimer p-value="disclaimer disclaimer disclaimer disclaimer disclaimer disclaimer disclaimer" …
```
> feat(disclaimer): implementa definições Animalia DS

- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.html
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range.component.html
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.html
- projects/ui/src/lib/components/po-field/po-decimal/po-decimal.component.html
- projects/ui/src/lib/components/po-field/po-field-container/po-field-container-bottom/po-field-container-bottom.component.html
- projects/ui/src/lib/components/po-field/po-field-container/po-field-container-bottom/po-field-container-bottom.component.spec.ts
- projects/ui/src/lib/components/po-field/po-field-container/po-field-container-bottom/po-field-container-bottom.component.ts
- projects/ui/src/lib/components/po-field/po-field-container/po-field-container.module.ts
- projects/ui/src/lib/components/po-field/po-input/po-input.component.html
- projects/ui/src/lib/components/po-field/po-login/po-login.component.html
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.html
- projects/ui/src/lib/components/po-field/po-number/po-number.component.html
- projects/ui/src/lib/components/po-field/po-password/po-password.component.html
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text.component.html
- projects/ui/src/lib/components/po-field/po-select/po-select.component.html
- projects/ui/src/lib/components/po-field/po-switch/po-switch.component.html
- projects/ui/src/lib/components/po-field/po-textarea/po-textarea.component.html
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.html
**FIELD**
**DTHFUI-6804**
Atualmente o componente não possui as configurações de estilo e acessibilidade do AnimaliaDS
Agora o componente possui as configurações de estilo e acessibilidade do AnimaliaDS
**Simulação**
Portal nos componentes que possuem help-text e/ou text-error
**PRs Adicionais:**
- https://github.com/po-ui/po-style/pull/370
- https://github.com/totvs/po-theme-totvs/pull/200
> feat(fields): implementa definições do AnimaliaDS 

- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-circular/po-chart-circular-path/po-chart-tooltip.directive.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-circular/po-chart-circular-path/po-chart-tooltip.directive.ts
- projects/ui/src/lib/directives/po-tooltip/po-tooltip.directive.spec.ts
- projects/ui/src/lib/directives/po-tooltip/po-tooltip.directive.ts
**Tooltip**
**DTHFUI-6805**
**Simulação**
style: https://github.com/po-ui/po-style/pull/371
theme: https://github.com/totvs/po-theme-totvs/pull/199
Testar app e portal:
[app.zip](https://github.com/po-ui/po-angular/files/10135271/app.zip)
customização: 
```
/* novas */
.po-tooltip {
/* --color: red; */
/* --border-radius: 5px; */
/* --font-family: 'Courier New', Courier, monospace; */
/* --text-color: blue; */
}
/* antigas */
/* .po-tooltip {
--color-tooltip-background-color-balloon: red;
--color-tooltip-color-text-balloon: blue;
} */
```
> feat(tooltip): implementa definições do AnimaliaDS

- CHANGELOG.md
- package.json
> build: release v14.12.0

- CHANGELOG.md
- package.json
**build: release v14.12.1**
**Simulação**
> build: release v14.12.1

- projects/code-editor/src/lib/components/po-code-editor/samples/sample-po-code-editor-terraform/sample-po-code-editor-terraform.module.ts
- projects/portal/src/app/app.module.ts
- projects/portal/src/app/shared/shared.module.ts
- projects/sync/src/lib/po-sync.module.ts
- projects/templates/src/lib/components/po-modal-password-recovery/po-modal-password-recovery.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-advanced-filter/po-advanced-filter.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-search/po-page-dynamic-search.component.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-execution/po-page-job-scheduler-execution.component.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-parameters/po-page-job-scheduler-parameters.component.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-summary/po-page-job-scheduler-summary.component.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.spec.ts
- projects/templates/src/lib/components/po-page-login/samples/sample-po-page-login-human-resources/sample-po-page-login-human-resources.module.ts
- projects/templates/src/lib/services/po-page-customization/po-page-customization.module.ts
- projects/templates/src/lib/services/po-page-dynamic/po-page-dynamic.module.ts
- projects/ui/karma.conf.js
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form.component.spec.ts
- projects/ui/src/lib/components/po-field/po-field.module.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/services/po-lookup-modal.service.spec.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-image-modal/po-rich-text-image-modal.component.spec.ts
- projects/ui/src/lib/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.component.spec.ts
- projects/ui/src/lib/components/po-navbar/po-navbar.component.spec.ts
- projects/ui/src/lib/services/po-i18n/po-i18n-base.service.spec.ts
- projects/ui/src/lib/services/po-i18n/po-i18n.module.ts
**build**
**DTHFUI-6620**
**Simulação**
> Remove `HttpClientModule` da Biblioteca.

- CHANGELOG.md
- package.json
> build: release v15.0.0-next.0

- CHANGELOG.md
- package.json
> build: release v15.0.0-next.1

- projects/ui/src/lib/components/po-field/po-field.module.ts
**DTHFUI-6965**
O estado `disabled` está com o comportamento errado
O estado `disabled` está com o comportamento certo
**Simulação**
Testar labs do portal e testar app de exemplo :
[app.zip](https://github.com/po-ui/po-angular/files/10354384/app.zip)
> fix(fields): adiciona configuração no field module

- projects/ui/src/lib/services/po-i18n/po-i18n-base.service.ts
**i18n**
Apresentando erro no console e não exibindo a documentação do componente `po-page-login`.
Não apresenta erro no console e a documentação do componente `po-page-login` está ativa normalmente.
**Simulação**
Portal
> fix(i18n): corrige erro no console

- projects/ui/src/lib/components/po-modal/po-modal.literals.ts
**po-modal**
**1568**
Traducao errada
Traducao correta
**Simulação**
> fix(modal): corrige string em russo #1568

- CHANGELOG.md
- package.json
- projects/app/src/app/app.module.ts
> build: release v15.0.0-rc.0

- docs/guides/deprecations.md
- docs/guides/migration-poui.md
- projects/ui/schematics/migrations.json
- projects/ui/schematics/ng-update/v15/changes.ts
- projects/ui/schematics/ng-update/v15/index.ts
- projects/ui/src/lib/components/po-button/po-button-base.component.spec.ts
- projects/ui/src/lib/components/po-button/po-button-base.component.ts
- projects/ui/src/lib/components/po-button/po-button-kind.enum.ts
- projects/ui/src/lib/components/po-button/po-button-type.enum.ts
- projects/ui/src/lib/services/po-notification/po-toaster/po-toaster.component.html
feat(schematics): implementa ng update
testar: 
- inclusão do HttpModule.
- inclusão das dependências do theme/totvs no angular.json (caso tenha theme totvs instalado no projeto)
- alteração de p-type para p-kind em um seletor do tipo po-button : 
para testar:
```
<po-button p-type="default" p-label="anything">
</po-button>
<po-button p-label="anything" p-type="default">
</po-button>
<po-button p-type="primary"  p-label="anything">
</po-button>
<po-button p-label="anything" p-type="primary">
</po-button>
<po-button p-type="danger" p-label="anything">
</po-button>
<po-button p-label="anything" p-type="danger">
</po-button>
<po-button p-type="link" p-label="anything">
</po-button>
<po-button p-label="anything" p-type="link">
</po-button>
<div p-type="default">
</div>
<div p-type="primary"> …
```
> feat(schematics): implementa ng update

- .github/workflows/ci.yml
- .github/workflows/publish_po_angular_ci.yml
- CHANGELOG.md
- README.md
- docs/guides/getting-started.md
- docs/guides/migration-poui.md
- docs/guides/sync-get-started.md
- package.json
> build: release v15.0.0

- projects/templates/src/lib/components/po-page-change-password/samples/sample-po-page-change-password-request/sample-po-page-change-password-request.component.html
altera url base nos samples dos componentes:
po-page-change-password
po-upload
**Simulação**
> docs(samples): altera url base da API

- .github/workflows/ci.yml
- .github/workflows/publish_po_angular_ci.yml
**Atualiza versões do GitHub Actions.**
| Before  | After |
| ------------- |:-------------:|
| actions/checkout@v2      | actions/checkout@v3     |
| actions/upload-artifact@v2      | actions/upload-artifact@v3     |
| actions/setup-node@v1      | actions/setup-node@v2     |
[GitHub Blog](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)
**DTHFUI-6888**
**Simulação**
> build: atualiza o github actions

- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-basic/sample-po-upload-basic.component.html
altera url base no sample do componente:
po-upload
**Simulação**
> docs(sample): altera url base da API

- .github/workflows/publish_po_angular_ci.yml
build: desfaz o ajuste do publish
> build: desfaz o ajuste do publish

- projects/ui/src/lib/components/po-image/po-image-base.component.spec.ts
- projects/ui/src/lib/components/po-image/po-image-base.component.ts
- projects/ui/src/lib/components/po-image/po-image.component.html
- projects/ui/src/lib/components/po-image/po-image.module.ts
- projects/ui/src/lib/utils/util.spec.ts
- projects/ui/src/lib/utils/util.ts
**IMAGE**
**DTHFUI-7013**
Componente não possuia diretiva `NgOptimizedImage`
Componente passa a ter diretiva `NgOptimizedImage`
**Simulação**
Utilizar esse [app.zip](https://github.com/po-ui/po-angular/files/10539318/app.zip)
**PR's adicionais**
- https://github.com/po-ui/po-style/pull/387
> feat(image): implementa diretiva `NgOptimizedImage`

- projects/portal/src/app/app-routing.module.ts
- projects/portal/src/app/app.component.html
- projects/portal/src/app/app.component.ts
- projects/portal/src/app/theme-builder/theme-builder-routing.module.ts
- projects/portal/src/app/theme-builder/theme-builder.component.css
- projects/portal/src/app/theme-builder/theme-builder.component.html
- projects/portal/src/app/theme-builder/theme-builder.component.ts
- projects/portal/src/app/theme-builder/theme-builder.module.ts
- projects/ui/src/lib/components/po-field/po-input/po-input.component.ts
Theme builder
Adiciona Theme-builder no portal 
**Simulação**
Simulação no portal na aba `Contrutor de temas`
> theme-builder - portal

- README.md
- docs/guides/getting-started.md
Adiciona devDependencies para avitar erro no ng-add.
**Simulação**
> docs(guides): adiciona devDependencies para avitar erro no ng-add

- CHANGELOG.md
- package.json
> build: release v15.1.0

- CHANGELOG.md
- package.json
> build: release v15.1.1

- docs/guides/sync-get-started.md
- projects/sync/schematics/migrations.json
- projects/sync/schematics/ng-update/v15/changes.ts
- projects/sync/schematics/ng-update/v15/index.ts
implementa ng update do po-sync
Teste: 
1 - criar uma aplicacao utilizando angular 14  e po-sync na v14
2 - realizar o update para o angular 15
3 - depois realizar update do po-sync para v15
> feat(schematics): implementa ng update do po-sync

- CHANGELOG.md
- package.json
> build: release v15.2.0

- projects/ui/src/lib/components/po-button/po-button-base.component.ts
- projects/ui/src/lib/components/po-button/po-button.component.html
- projects/ui/src/lib/components/po-modal/po-modal-base.component.ts
- projects/ui/src/lib/components/po-modal/po-modal.component.html
- projects/ui/src/lib/components/po-modal/po-modal.component.spec.ts
- projects/ui/src/lib/components/po-modal/po-modal.module.ts
- projects/ui/src/lib/components/po-modal/samples/sample-po-modal-labs/sample-po-modal-labs.component.html
- projects/ui/src/lib/components/po-modal/samples/sample-po-modal-labs/sample-po-modal-labs.component.ts
- projects/ui/src/lib/services/po-dialog/po-dialog.service.spec.ts
Implementa definições de estilo e acessibilidade definidos pelo AnimaliaDS
**Modal**
**DTHFUI-6806**
implementa definições do AnimaliaDS
**Simulação**
testar samples do portal e customização
Style: https://github.com/po-ui/po-style/pull/394
theme: https://github.com/totvs/po-theme-totvs/pull/216
> feat(modal): implementa definições do AnimaliaDS

- projects/ui/src/lib/components/po-menu-panel/po-menu-panel.component.spec.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.spec.ts
Arruma testes comentados da ultima versão
fixes DTHFUI-7127
> test(menu): arruma testes comentados

- CHANGELOG.md
- package.json
> build: release v15.3.0

- CHANGELOG.md
- package.json
> build: release v15.4.0

- projects/portal/src/app/theme-builder/theme-builder.component.css
- projects/portal/src/app/theme-builder/theme-builder.component.html
- projects/portal/src/app/theme-builder/theme-builder.component.ts
- projects/ui/src/lib/components/po-link/po-link.component.html
- projects/ui/src/lib/components/po-link/po-link.component.ts
- projects/ui/src/lib/components/po-modal/po-modal.component.html
- projects/ui/src/lib/components/po-modal/po-modal.component.ts
- projects/ui/src/lib/components/po-popup/po-popup.component.html
- projects/ui/src/lib/components/po-popup/po-popup.component.ts
**THEME BUILDER**
**DTHFUI-7126**
Componentes `Datepicker` `Tooltip`  `Link`  `Popup`  `Modal`, não estão inclusos no construtor de temas
Componentes `Datepicker` `Tooltip`  `Link`  `Popup`  `Modal`, estão inclusos no construtor de temas
**Simulação**
Portal
> feat(theme-builder): inclui componentes

- CHANGELOG.md
- package.json
> build: release v15.5.0

- projects/portal/src/app/theme-builder/theme-builder.component.html
- projects/portal/src/app/theme-builder/theme-builder.component.ts
**CHECKBOX**
**DTHFUI-7130**
Componente não permitia customização via design-tokens
Componente passa a permitir  customização via design-tokens
**Simulação**
Testar samples, customização e construtor de temas.
style:  https://github.com/po-ui/po-style/pull/401
theme: https://github.com/totvs/po-theme-totvs/pull/222
> feat(checkbox): implementa definições do AnimaliaDS

- projects/ui/src/lib/components/po-list-view/po-list-view.component.html
- projects/ui/src/lib/components/po-list-view/po-list-view.module.ts
**list-view**
**DTHFUI-6999**
**Simulação**
style: https://github.com/po-ui/po-style/pull/403
testar app e portal :
[app.zip](https://github.com/po-ui/po-angular/files/11151651/app.zip)
> feat(list-view): melhora contraste do componente

- projects/ui/src/lib/components/po-listbox/po-listbox.component.spec.ts
- projects/ui/src/lib/components/po-listbox/po-listbox.component.ts
**popup**
**DTHFUI-7156**
**Simulação**
realizar build:portal antes
Testar o mesmo app da task :  https://github.com/po-ui/po-angular/pull/1671
Testar sample relatado na issue : https://github.com/po-ui/po-angular/issues/1677
> fix(popup): corrige emissão de evento

- CHANGELOG.md
- package.json
> build: release v15.6.0

- CHANGELOG.md
- package.json
> build: release v15.6.1

- .eslintrc.json
- projects/ui/src/lib/components/po-field/po-upload/po-upload-base.component.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.html
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.spec.ts
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.ts
- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-labs/sample-po-upload-labs.component.html
- projects/ui/src/lib/components/po-field/po-upload/samples/sample-po-upload-labs/sample-po-upload-labs.component.ts
**UPLOAD**
**DTHFUI-7172**
Componente não permite selecionar arquivos se não for passado uma URL.
Componente permite selecionar arquivos mesmo não tendo passado uma URL.
**Simulação**
[Portal](http://localhost:4200/documentation/po-upload) samples.
e app
HTML 
```
<div class="po-md-6">
<po-upload
name="upload"
p-label="PO Upload - Passando URL"
p-url="https://po-sample-api.fly.dev/v1/uploads/addFile"
></po-upload>
<po-divider></po-divider>
<po-upload
name="upload"
p-auto-upload="true"
p-label="PO Upload - Passando URL com auto-upload" …
```
> feat(upload): habilita botão `selecionar arquivo`

- CHANGELOG.md
- package.json
> build: release v15.7.0

- projects/ui/src/lib/components/po-list-view/po-list-view.component.html
**list-view**
**DTHFUI-7215**
**Simulação**
Testar no portal
> feat(list-view): utiliza o pobutton para exibir os detalhes

- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
**lookup**
**DTHFUI-7255**
**Simulação**
Simular o resultado esperado utilizando o stackblitz do cliente reportado na issue de apoio.
https://stackblitz.com/edit/angular-sr2jvq
> feat(lookup): implementa método para exposição de propriedade protegida

- projects/ui/src/lib/components/po-field/index.ts
> feat(upload): exporta PoUploadFile e uploadStatusEnum

- CHANGELOG.md
- package.json
> build: release v15.18.0

- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.ts
**LOOKUP**
**DTHFUI-7205**
Ao realizar a pesquisa através do botão "enter", a tela de loading/carregando não aparece.
Ao realizar a pesquisa através do botão "enter", a tela de loading/carregando agora é renderizada
**Simulação**
[PORTAL](https://po-ui.io/documentation/po-lookup)
> fix(lookup): corrige loading

- CHANGELOG.md
- package.json
> build: release v15.8.1

- CHANGELOG.md
- package.json
> build: release v15.8.2

- CHANGELOG.md
- package.json
> build: release v15.9.0

- CHANGELOG.md
- package.json
> build: release v15.9.1

- CHANGELOG.md
- package.json
> build: release v15.9.2

- projects/ui/src/lib/components/components.module.ts
- projects/ui/src/lib/components/index.ts
- projects/ui/src/lib/components/po-field/index.ts
- projects/ui/src/lib/components/po-field/po-field.module.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.html
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.ts
- projects/ui/src/lib/components/po-field/po-switch/index.ts
- projects/ui/src/lib/components/po-field/po-switch/po-switch.component.html
- projects/ui/src/lib/components/po-field/po-switch/po-switch.component.ts
- projects/ui/src/lib/components/po-field/po-switch/po-switch.module.ts
- projects/ui/src/lib/components/po-page/index.ts
- projects/ui/src/lib/components/po-page/po-page-slide/index.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide.component.html
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide.module.ts
- projects/ui/src/lib/components/po-page/po-page.module.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.html
- projects/ui/src/lib/components/po-table/po-table-list-manager/po-table-list-manager.component.html
- projects/ui/src/lib/components/po-table/po-table-list-manager/po-table-list-manager.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-list-manager/po-table-list-manager.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-table/po-table.module.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-airfare/sample-po-table-airfare.service.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-components/sample-po-table-components.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.ts
**TABLE**
**DTHFUI-7225**
componente `table` sem Implementações definidas pelo AnimaliaDS.
componente `table` passa a ter Implementações definidas pelo AnimaliaDS.
**Simulação**
Para testar `table` com Customizações: 
Style
[https://github.com/po-ui/po-style/pull/422](https://github.com/po-ui/po-style/pull/422)
Theme-Totvs
[https://github.com/totvs/po-theme-totvs/pull/236](https://github.com/totvs/po-theme-totvs/pull/236)
App
[app.zip](https://github.com/po-ui/po-angular/files/11681761/app.zip)
Customizações:
[style.app.txt](https://github.com/po-ui/po-angular/files/11681773/style.app.txt)
> feat(table): implementa definições do AnimaliaDS

- CHANGELOG.md
- package.json
> build: release v15.10.0

- projects/portal/src/app/app.component.html
- projects/portal/src/app/theme-builder/theme-builder.component.css
- projects/portal/src/app/theme-builder/theme-builder.component.html
- projects/portal/src/app/theme-builder/theme-builder.component.ts
THEME-BUILDER
fixes DTHFUI-7377
N/A
N/A
**Simulação**
> feat(theme-builder): implementa criação do novo construtor de temas

- CHANGELOG.md
- package.json
- projects/portal/src/app/app.component.html
- projects/portal/src/app/home/home.component.html
> build: release v15.11.0

- CHANGELOG.md
- package.json
> build: release v15.12.0

- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide-base.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide-base.component.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.html
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.ts
Table e Page Slide
DTHFUI-7465
Propriedade (p-change-visible-columns) não está sendo executada após mudança nas colunas visíveis da tabela
Propriedade (p-change-visible-columns) está sendo executada após mudança nas colunas visíveis da tabela
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/12018507/app.zip)
> fix(table): ajusta funcionamento da propriedade p-change-visible-columns

- CHANGELOG.md
- package.json
Este PR marca a nova versão 15.12.1 do nosso projeto.
> build: release v15.12.1

- projects/portal/src/styles.css
- projects/ui/src/lib/components/po-menu/po-menu-base.component.ts
- projects/ui/src/lib/components/po-menu/po-menu-filter/po-menu-filter.component.html
- projects/ui/src/lib/components/po-menu/po-menu-filter/po-menu-filter.component.ts
- projects/ui/src/lib/components/po-menu/po-menu-item/po-menu-item.component.html
- projects/ui/src/lib/components/po-menu/po-menu-item/po-menu-item.component.spec.ts
- projects/ui/src/lib/components/po-menu/po-menu-item/po-menu-item.component.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.html
- projects/ui/src/lib/components/po-menu/po-menu.component.spec.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.ts
- projects/ui/src/lib/components/po-menu/samples/sample-po-menu-human-resources/sample-po-menu-human-resources.service.ts
- projects/ui/src/lib/components/po-menu/samples/sample-po-menu-labs/sample-po-menu-labs.component.html
**menu**
**DTHFUI-7226**
**Simulação**
Testar no Samples e customização.
Style: https://github.com/po-ui/po-style/pull/421
Themes: https://github.com/totvs/po-theme-totvs/pull/235
> feat(menu): implementa definições do AnimaliaDS

- CHANGELOG.md
- package.json
- projects/portal/src/app/theme-builder/theme-builder.component.html
Este PR marca a nova versão v15.13.0 do nosso projeto.
> build: release v15.13.0

- CHANGELOG.md
- package.json
- projects/sync/src/lib/services/po-event-sourcing/po-event-sourcing.service.spec.ts
> build: release v15.13.1

- projects/ui/src/lib/components/po-field/index.ts
- projects/ui/src/lib/components/po-field/po-select/po-select-option-group.interface.ts
- projects/ui/src/lib/components/po-field/po-select/po-select.component.html
- projects/ui/src/lib/components/po-field/po-select/po-select.component.spec.ts
- projects/ui/src/lib/components/po-field/po-select/po-select.component.ts
- projects/ui/src/lib/components/po-field/po-select/samples/sample-po-select-companies/sample-po-select-companies.component.ts
- projects/ui/src/lib/components/po-field/po-select/samples/sample-po-select-labs/sample-po-select-labs.component.html
- projects/ui/src/lib/components/po-field/po-select/samples/sample-po-select-labs/sample-po-select-labs.component.ts
SELECT
fixed DTHFUI-2193
Select lista somente itens desagrupados
Select lista opções de itens agrupados e desagrupados
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/12245271/app.zip)
> feat(select): possibilita o uso de sub itens

- projects/portal/src/app/home/home.component.html
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-list-base.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.html
- projects/ui/src/lib/components/components.module.ts
- projects/ui/src/lib/components/index.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.html
- projects/ui/src/lib/components/po-search/enum/po-search-filter-mode.enum.ts
- projects/ui/src/lib/components/po-search/index.ts
- projects/ui/src/lib/components/po-search/literals/po-search-literals.ts
- projects/ui/src/lib/components/po-search/po-search-base.component.spec.ts
- projects/ui/src/lib/components/po-search/po-search-base.component.ts
- projects/ui/src/lib/components/po-search/po-search-filter-mode.enum.ts
- projects/ui/src/lib/components/po-search/po-search.component.html
- projects/ui/src/lib/components/po-search/po-search.component.spec.ts
- projects/ui/src/lib/components/po-search/po-search.component.ts
- projects/ui/src/lib/components/po-search/po-search.module.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-table/po-table.module.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-basic/sample-po-table-basic.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-components/sample-po-table-components.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.html
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-labs/sample-po-table-labs.service.ts
- projects/ui/src/lib/enums/po-filter-mode.enum.ts
**SEARCH**
**DTHFUI-7318**
Componente `table`não possui campo de pesquisa
Componente `table` passa a possuir campo de pesquisa
**Simulação**
[Portal](https://po-ui.io/documentation/po-table) | **Samples** 
**Style | Theme-Totvs**
- https://github.com/po-ui/po-style/pull/433
- https://github.com/totvs/po-theme-totvs/pull/248
> feat(search): implementa busca na tabela

- CHANGELOG.md
- package.json
> build: release v15.15.0

- CHANGELOG.md
- package.json
> build: release v16.0.0-next.1

- CHANGELOG.md
- package.json
> build: release v16.0.0-next.2

- projects/ui/src/lib/components/po-field/po-combo/interfaces/po-combo-literals-default.interface.ts
- projects/ui/src/lib/components/po-field/po-combo/interfaces/po-combo-literals.interface.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.html
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
- projects/ui/src/lib/components/po-field/po-combo/samples/sample-po-combo-scheduling/sample-po-combo-scheduling.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.spec.ts
- projects/ui/src/lib/components/po-listbox/enums/po-item-list-filter-mode.enum.ts
- projects/ui/src/lib/components/po-listbox/po-item-list/po-item-list-base.component.ts
- projects/ui/src/lib/components/po-listbox/po-item-list/po-item-list.component.html
- projects/ui/src/lib/components/po-listbox/po-item-list/po-item-list.component.spec.ts
- projects/ui/src/lib/components/po-listbox/po-item-list/po-item-list.component.ts
- projects/ui/src/lib/components/po-listbox/po-listbox-base.component.spec.ts
- projects/ui/src/lib/components/po-listbox/po-listbox-base.component.ts
- projects/ui/src/lib/components/po-listbox/po-listbox.component.html
- projects/ui/src/lib/components/po-listbox/po-listbox.component.spec.ts
- projects/ui/src/lib/components/po-listbox/po-listbox.component.ts
- projects/ui/src/lib/components/po-menu/po-menu.component.spec.ts
- projects/ui/src/lib/components/po-modal/po-modal-footer/po-modal-footer.component.spec.ts
**Combo**
**DTHFUI-7314**
`po-combo` utiliza o componente `po-listbox`
**Simulação**
App: [app.zip](https://github.com/po-ui/po-angular/files/12369606/app.zip)
Simular também no portal
[Style](https://github.com/po-ui/po-style/pull/445)
> feat(combo): implementa uso do listbox

- CHANGELOG.md
- package.json
> build: release v16.0.0

- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-tag/po-tag.component.spec.ts
**table**
**DTHFUI-7608**
não faz ordenação em tabela sem altura
faz ordenação em tabela sem altura
**Simulação**
Testar samples do portal
> fix(table): corrige ordenação

- .github/workflows/ci.yml
- projects/templates/src/lib/components/po-page-login/po-page-login.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.html
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-field.module.ts
**combo**
**DTHFUI-7582**
lista do combo não fica com o posicionamento correto dentro de uma tabela com altura
lista do combo fica com o posicionamento correto dentro de uma tabela com altura
**Simulação**
Testar todos os samples do combo no portal e testar app com bug reportado:
[app.zip](https://github.com/po-ui/po-angular/files/12609091/app.zip)
> fix(combo): corrige posicionamento

- .github/workflows/publish_po_angular_ci.yml
- CHANGELOG.md
- package.json
> build: release v16.1.0

- .github/workflows/publish_po_angular_ci.yml
> build: ajusta publicacao do CI

- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal-base.component.ts
**Lookup**
**1810**
Traducoes erradas para o russo
Traducoes corretas
**Simulação**
Fixes #1810
> fix(lookup): traducoes russo

- CHANGELOG.md
- package.json
> build: release v16.2.0

- .github/workflows/publish_po_angular_ci.yml
build
Ajusta arquivo yaml para validar teste de publicação.
> build(cd): ignora condicao que valida versao

- .github/workflows/publish_po_angular_ci.yml
> build(cd): realiza publish npm com checkout@v4

- CHANGELOG.md
- package.json
> build: release v16.2.1

- CHANGELOG.md
- package.json
> build: release 16.3.0

- CHANGELOG.md
- package.json
> build: release v16.4.0

- CHANGELOG.md
- package.json
> build: release v16.4.1

- CHANGELOG.md
- package.json
> build: release v16.5.0

- CHANGELOG.md
- package.json
> build: release v16.6.0

- projects/ui/src/lib/components/po-button/po-button.component.html
- projects/ui/src/lib/components/po-loading/po-loading-icon/po-loading-icon-size-enum.ts
- projects/ui/src/lib/components/po-loading/po-loading-icon/po-loading-icon.component.html
- projects/ui/src/lib/components/po-loading/po-loading-icon/po-loading-icon.component.spec.ts
- projects/ui/src/lib/components/po-loading/po-loading-icon/po-loading-icon.component.ts
- projects/ui/src/lib/components/po-loading/po-loading.component.html
- projects/ui/src/lib/components/po-menu/po-menu-filter/po-menu-filter.component.html
- projects/ui/src/lib/components/po-search/po-search.component.html
**loading-icon**
**DTHFUI-7807**
**Simulação**
style: https://github.com/po-ui/po-style/pull/468
theme: https://github.com/totvs/po-theme-totvs/pull/270
[app.zip](https://github.com/po-ui/po-angular/files/13297268/app.zip)
custom:
```
/* po-loading, po-loading-icon {
--color-loading-icon-color-neutral: green;
} */
/* po-loading-icon {
--color: green;
} */
```
> feat(loading-icon): implementa definições do AnimaliaDS

- projects/templates/src/lib/components/po-page-dynamic-detail/po-page-dynamic-detail.component.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
**< PO-PAGE-DYNAMIC-TABLE >**
**< PO-PAGE-DYNAMIC-EDIT >**
**< PO-PAGE-DYNAMIC-DETAIL >**
Documentação com baixa riqueza de detalhes. 
Documentação com detalhes da inclusão das propriedades de rotas para estes componentes.
> Page-Dynamic:  otimiza os exemplos de utilização via rota.

- CHANGELOG.md
- package.json
> build: release v16.7.0

- projects/ui/src/lib/components/po-progress/enums/po-progress-size.enum.ts
- projects/ui/src/lib/components/po-progress/index.ts
- projects/ui/src/lib/components/po-progress/literals/po-progress.literals.ts
- projects/ui/src/lib/components/po-progress/po-progress-bar/po-progress-bar.component.html
- projects/ui/src/lib/components/po-progress/po-progress-bar/po-progress-bar.component.spec.ts
- projects/ui/src/lib/components/po-progress/po-progress-base.component.spec.ts
- projects/ui/src/lib/components/po-progress/po-progress-base.component.ts
- projects/ui/src/lib/components/po-progress/po-progress.component.html
- projects/ui/src/lib/components/po-progress/po-progress.component.spec.ts
- projects/ui/src/lib/components/po-progress/po-progress.component.ts
- projects/ui/src/lib/components/po-progress/po-progress.module.ts
- projects/ui/src/lib/components/po-progress/samples/sample-po-progress-labs/sample-po-progress-labs.component.html
- projects/ui/src/lib/components/po-progress/samples/sample-po-progress-labs/sample-po-progress-labs.component.ts
- projects/ui/src/lib/components/po-progress/samples/sample-po-progress-publication/sample-po-progress-publication.component.html
**progress**
**DTHFUI-7808**
**Simulação**
testar app e samples do portal
app: 
[app.zip](https://github.com/po-ui/po-angular/files/13378019/app.zip)
style: https://github.com/po-ui/po-style/pull/472
theme: https://github.com/totvs/po-theme-totvs/pull/274
custom:
```
@import url('https://fonts.googleapis.com/css2?family=Lumanosimo&family=Playfair+Display+SC&display=swap');
/* po-progress {
--font-family: 'Lumanosimo', cursive;
--text-color: blue;
--text-color-error: green;
--color-icon-error: yellow;
} */
/* po-progress-bar {
--background-color-tray: rgb(255, 0, 174);
--background-color-indicator: red;
} */
/* :root {
--color-progress-bar-background-color-bar: red; …
```
> feat(progress): implementa definições do animaliaDS

- CHANGELOG.md
- package.json
> build: release v16.9.0

- projects/ui/src/lib/components/po-search/po-search-base.component.spec.ts
- projects/ui/src/lib/components/po-search/po-search-base.component.ts
- projects/ui/src/lib/components/po-search/po-search.component.html
- projects/ui/src/lib/components/po-search/po-search.component.spec.ts
- projects/ui/src/lib/components/po-search/po-search.component.ts
- projects/ui/src/lib/components/po-search/po-search.module.ts
- projects/ui/src/lib/components/po-search/samples/sample-po-search-labs/sample-po-search-labs.component.html
- projects/ui/src/lib/components/po-search/samples/sample-po-search-labs/sample-po-search-labs.component.ts
**search**
**DTHFUI-7809**
**Simulação**
testar sample do portal alterando o labs para trigger
style: https://github.com/po-ui/po-style/pull/478
totvs: https://github.com/totvs/po-theme-totvs/pull/281
> feat(search): implementa modo trigger no componente

- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-base.component.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.ts
**JOB-SCHEDULER**
**dthfui-8099**
não emite evento ao realizar agendamento
emite evento ao realizar agendamento
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/13730342/app.zip)
> feat(job-scheduler): cria evento de erro e sucesso

- CHANGELOG.md
- package.json
- projects/portal/src/app/theme-builder/theme-builder.component.ts
> build: release v16.10.0

- CHANGELOG.md
- package.json
> build: release v16.11.0

- CHANGELOG.md
- package.json
> build: release v16.12.0

- .github/workflows/publish_po_angular_ci-portal.yml
Permite publicar o Portal do PO-UI
Fixes DTHFUI-8079
**Simulação**
> ci: permite publicar o portal

- CHANGELOG.md
- package.json
> build: release v16.13.0

- projects/ui/src/lib/components/po-dropdown/po-dropdown.component.spec.ts
- projects/ui/src/lib/components/po-dropdown/po-dropdown.component.ts
- projects/ui/src/lib/components/po-popup/po-popup.component.spec.ts
- projects/ui/src/lib/components/po-popup/po-popup.component.ts
**POPUP**
**DTHFUI-8152**
Lista não desaparece ao rolar a tela, quando existem muitos itens associados
Lista desaparece ao rolar a tela, quando existem muitos itens associados.
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/14065943/app.zip)
& Portal
> fix(popup): ajusta lista ao acionar `scroll`

- projects/sync/schematics/migrations.json
- projects/sync/schematics/ng-update/v17/changes.ts
- projects/sync/schematics/ng-update/v17/index.ts
- projects/ui/schematics/migrations.json
- projects/ui/schematics/ng-update/v17/changes.ts
- projects/ui/schematics/ng-update/v17/index.ts
schematics de update para v.17
> feat(schematics): migração para v.17

- projects/ui/src/lib/components/po-page/po-page-default/po-page-default-base.component.ts
- projects/ui/src/lib/components/po-page/po-page-default/po-page-default.component.html
- projects/ui/src/lib/components/po-page/po-page-default/samples/sample-po-page-default-labs/sample-po-page-default-labs.component.html
- projects/ui/src/lib/components/po-page/po-page-default/samples/sample-po-page-default-labs/sample-po-page-default-labs.component.ts
- projects/ui/src/lib/components/po-page/po-page-detail/po-page-detail-base.component.ts
- projects/ui/src/lib/components/po-page/po-page-detail/po-page-detail.component.html
- projects/ui/src/lib/components/po-page/po-page-detail/samples/sample-po-page-detail-labs/sample-po-page-detail-labs.component.html
- projects/ui/src/lib/components/po-page/po-page-detail/samples/sample-po-page-detail-labs/sample-po-page-detail-labs.component.ts
- projects/ui/src/lib/components/po-page/po-page-edit/po-page-edit-base.component.ts
- projects/ui/src/lib/components/po-page/po-page-edit/po-page-edit.component.html
- projects/ui/src/lib/components/po-page/po-page-edit/samples/sample-po-page-edit-labs/sample-po-page-edit-labs.component.html
- projects/ui/src/lib/components/po-page/po-page-edit/samples/sample-po-page-edit-labs/sample-po-page-edit-labs.component.ts
- projects/ui/src/lib/components/po-page/po-page-header/po-page-header-base.component.ts
- projects/ui/src/lib/components/po-page/po-page-header/po-page-header.component.html
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list-base.component.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.html
- projects/ui/src/lib/components/po-page/po-page-list/samples/sample-po-page-list-labs/sample-po-page-list-labs.component.html
- projects/ui/src/lib/components/po-page/po-page-list/samples/sample-po-page-list-labs/sample-po-page-list-labs.component.ts
**PO-PAGE-DEFAULT**
**DTHFUI-8292**
Não existe hoje Propriedade de Subtitulo
Tem a opção de envio do subtitulo
**Simulação**
Esta correção pode ser validada utilizando o sample labs no portal
> feat(page-default): inclusão do subtitle

- CHANGELOG.md
- package.json
> build: release v16.15.0

- STYLEGUIDE.md
- docs/guides/deprecations.md
- projects/portal/src/app/tools/tools-dynamic-form/tools-dynamic-form.component.html
- projects/portal/src/app/tools/tools-dynamic-view/tools-dynamic-view.component.html
- projects/templates/src/lib/components/po-page-background/po-page-background.component.spec.ts
- projects/ui/src/lib/components/po-button-group/po-button-group-base.component.spec.ts
- projects/ui/src/lib/components/po-button-group/po-button-group-base.component.ts
- projects/ui/src/lib/components/po-button-group/po-button-group.component.html
- projects/ui/src/lib/components/po-button/po-button-base.component.spec.ts
- projects/ui/src/lib/components/po-button/po-button-base.component.ts
- projects/ui/src/lib/components/po-button/po-button.component.html
- projects/ui/src/lib/components/po-button/po-button.component.spec.ts
- projects/ui/src/lib/components/po-button/samples/sample-po-button-labs/sample-po-button-labs.component.e2e-spec.ts
- projects/ui/src/lib/components/po-button/samples/sample-po-button-labs/sample-po-button-labs.component.po.ts
- projects/ui/src/lib/components/po-container/po-container-base.component.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-default/po-page-default-base.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list-base.component.spec.ts
- projects/ui/src/lib/components/po-search/po-search-base.component.spec.ts
- projects/ui/src/lib/components/po-stepper/po-stepper-step/po-stepper-step.component.ts
- projects/ui/src/lib/components/po-table/interfaces/po-table-column.interface.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table-column-label/po-table-column-label.interface.ts
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-airfare/sample-po-table-airfare.component.html
- projects/ui/src/lib/utils/util.spec.ts
- projects/ui/src/lib/utils/util.ts
**components**
**DTHFUI-8043**
Componentes possuem propriedades depreciadas v17.x.x
Componentes perde propriedades depreciadas v17.x.x
**Simulação**
Portal
[style](https://github.com/po-ui/po-style/pull/498)
> refactor(components): remove propriedades depreciadas

- CHANGELOG.md
- package.json
> build: release v17.0.0-next.0

- projects/ui/src/lib/components/po-field/po-switch/po-switch.component.html
realiza alterações visuais para o smart-ui
fixes DTHFUI-8117
**Simulação**
STYLE: https://github.com/po-ui/po-style/pull/485
THEME:  https://github.com/totvs/po-theme-totvs/pull/287
> feat(smart): realiza alterações visuais

- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.ts
Corrigido problema de ordenação dos campos do PageDynamicDetail quando passado com um delay de serviço.
**< po-dynamic-view >**
**< DTHFUI-8299 >**
Quando enviado os campos no po-page-dynamic-detail, sendo alguns via serviço e esse está com delay, a ordenação não esta ocorrendo da forma correta
é criado o campo na tela somente com a label e preenchido o valor apos a busca dos dados via serviço, desta forma existe um melhor feedback para o usuário e não quebra a ordenação
**Simulação**
Código para teste no app de exemplo:
*PRECISA BUILDAR ANTES DE TESTAR*
app.component.htm
```
<po-page-default p-title="PO UI"> …
```
> fix(dynamic-view): corrigido problema de ordenação dos campos

- CHANGELOG.md
- package.json
**Build release v16.16.0**
**DTHFUI-8427**
> build: release v16.16.0

- CHANGELOG.md
- package.json
**build: release v17.0.0-rc.0**
**DTHFUI-8427**
> build: release v17.0.0-rc.0

- CHANGELOG.md
- README.md
- package.json
> build: release v17.0.0

- docs/guides/getting-started.md
- docs/guides/migration-poui.md
- docs/guides/schematics.md
- docs/guides/sync-get-started.md
Remove a tag `@next` da documetanção
Fixes DTHFUI-8466
**Simulação**
> doc: remove `@next` do documentacao

- docs/guides/migration-poui.md
Adiciona item de verificação após a atualização
via `ng update @angular`
Fixes DTHFUI-8478
**Simulação**
> docs(migration): ajusta doc migracao

- README.md
- docs/guides/getting-started.md
- docs/guides/sync-get-started.md
- projects/ui/src/lib/components/po-tabs/po-tabs-base.component.ts
**TABS**
**DTHFUI-8336**
Não possui documentação dos tokens customizáveis do componente Tabs
Adicionado documentação sobre os respectivos tokens.
**Simulação**
Portal, componente Tabs
> doc(tabs): inclui documentação de customização dos tokens css

- CHANGELOG.md
- package.json
> build: release v17.1.0

- package.json
build: atualiza para o Angular 17@latest
> build: atualiza para o Angular 17@latest

- .github/workflows/ci.yml
- .github/workflows/publish_po_angular_ci-beta.yml
- scripts/update-version.js
**Ajusta a publicação na tag @beta do NPM**
**DTHFUI-8276**
**Simulação**
> ci: ajusta a publicacao da tag @beta

- docs/guides/migration-poui.md
Solicita instalação das dependências obrigatórias para a migração
DTHFUI-8422
**Simulação**
> docs(migration): solicita instalação

- .github/workflows/ci.yml
integração via webhook com o discord do core team
DTHFUI-7986
**< CI.yml>**
> feat(ci): realiza integração com o discord

- CHANGELOG.md
- package.json
> build: release v17.2.0

- CHANGELOG.md
- package.json
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide.component.spec.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide.component.ts
> build: release 

- CHANGELOG.md
- package.json
> build: release v17.3.0

- CHANGELOG.md
- package.json
> build: release v17.4.0

- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.spec.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.ts
> Revert "fix(combo): Altera para `null` 'selectedValue' e 'selectedOption'"

- CHANGELOG.md
- package.json
> build: release v17.5.0

- CHANGELOG.md
- package.json
> build: release v17.6.0

- CHANGELOG.md
- package.json
> build: release v17.8.0

- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-base.component.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-parameters/po-job-scheduler-parameters-template/po-job-scheduler-parameters-template.directive.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-parameters/po-page-job-scheduler-parameters.component.html
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-parameters/po-page-job-scheduler-parameters.component.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler-summary/po-page-job-scheduler-summary.component.html
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.html
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.spec.ts
- projects/templates/src/lib/components/po-page-job-scheduler/po-page-job-scheduler.component.ts
Adiciona a possibilidade de inclsuão de várias etapas no po-job-scheduler
fixes DTHFUI-8604
**Page Job Scheduler**
**DTHFUI-8604**
Atualmente o Page Job Scheduler permite apenas um step 'Parametrização'
Permite adicionar várias apas de 'Parametrização' através 'Job Scheduler Parameters Template'
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/15264570/app.zip)
> feat: adiciona possibilidade de inclusao de varias etapas

- projects/ui/src/lib/components/po-table/po-table-column-label/po-table-column-label.component.html
- projects/ui/src/lib/components/po-table/po-table-column-label/po-table-column-label.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table-column-label/po-table-column-label.component.ts
**table**
**8785**
label não aparece após atualizar ou mudar de página na tabela
label aparece após atualizar ou mudar de página na tabela
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/15263158/app.zip)
> fix(table): corrige coluna do tipo label

- CHANGELOG.md
- package.json
> build: release v17.9.0

- CHANGELOG.md
- package.json
> release v17.10.0

- CHANGELOG.md
- package.json
> build: release v17.10.0

- projects/templates/src/lib/components/po-page-dynamic-detail/po-page-dynamic-detail.component.ts
- projects/templates/src/lib/components/po-page-dynamic-edit/po-page-dynamic-edit.component.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.spec.ts
- projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-table.component.ts
- projects/ui/src/lib/components/po-page/po-page-default/po-page-default.component.html
- projects/ui/src/lib/components/po-page/po-page-detail/po-page-detail.component.html
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list.component.html
**DTHFUI-8204**
nos componentes que possibilitam a escolha entre o botão "danger" ou "default", não estava sendo respeitado o "danger"
nos componentes que possibilitam a escolha entre o botão "danger" ou "default", está sendo respeitado o "danger"
**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/15295938/app.zip)
> fix(page): corrige type das actions

- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.ts
**DTHFUI-8884**
não esta renderizando o titulo do container
está  renderizando o titulo do container
**Simulação**
BUILDAR O PROJETO ANTES DE TESTAR
app: 
[app.zip](https://github.com/po-ui/po-angular/files/15393699/app.zip)
> fix(page-dynamic): corrige container sem titulo

- CHANGELOG.md
- package.json
> build: release 17.15.0

- CHANGELOG.md
- package.json
> build: release 17.15.1

- CHANGELOG.md
- package.json
> build: release 17.15.2

- CHANGELOG.md
- package.json
- projects/ui/src/lib/components/po-tabs/po-tabs.component.spec.ts
- projects/ui/src/lib/components/po-tabs/po-tabs.component.ts
> build: release v17.15.2

- CHANGELOG.md
- package.json
> build: release 17.17.0

- CHANGELOG.md
- package.json
> Build/dthf UI 929

- projects/ui/src/lib/components/po-listbox/po-listbox.component.ts
- projects/ui/src/lib/components/po-tabs/po-tab-dropdown/po-tab-dropdown.component.html
- projects/ui/src/lib/components/po-tabs/po-tab-dropdown/po-tab-dropdown.component.spec.ts
- projects/ui/src/lib/components/po-tabs/po-tab-dropdown/po-tab-dropdown.component.ts
- projects/ui/src/lib/components/po-tabs/po-tabs.component.html
- projects/ui/src/lib/components/po-tabs/po-tabs.component.spec.ts
- projects/ui/src/lib/components/po-tabs/po-tabs.component.ts
**TAB-DROPDOWN**
**DTHFUI-8917**
Alinhamento do listbox incorreto afetando visibilidade dos itens
Melhor linhamento do listbox melhorando visibilidade dos itens
**Simulação**
[8917-app.zip](https://github.com/user-attachments/files/16035822/8917-app.zip)
PR style
- https://github.com/po-ui/po-style/pull/577
> fix(tab-dropdown): corrige posicionamento

- CHANGELOG.md
- package.json
build: release v17.18.0
**DTHFUI-9343**
> build: release v17.18.0

- CHANGELOG.md
- package.json
> build: release 17.18.1

- projects/ui/src/lib/components/po-table/po-table.component.ts
**Table**
**9354**
ocorre erro no console
não ocorre erro no console
**Simulação**
testar sample no portal
> Table/dthf UI 9354

- docs/guides/development-flow.md
Ajusta documentação de contribuição que ainda referencia o TS Lint
> docs: update development-flow.md

- CHANGELOG.md
- package.json
> build: release 17.19.0

- CHANGELOG.md
- package.json
> build: release 18.0.0-next.0

- .github/workflows/publish_po_angular_ci-next.yml
- .github/workflows/publish_po_angular_ci-portal.yml
build(cd): realiza instalação corretamente das deps
> build(cd): realiza instalação corretamente das deps

- CHANGELOG.md
- package.json
> build: release 17.20.0

- projects/ui/src/lib/components/po-field/index.ts
Torna publico o `po-mask`
Fixes DTHFUI-9153
**PO-MASK**
**DTHFUI-9153**
**Simulação**
> feat(mask): disponibiliza `po-mask`

- CHANGELOG.md
- package.json
> build: release 17.21.0

- .github/workflows/publish_po_angular_ci-latest.yml
build(ci): ajusta build tag latest
> build(ci): ajusta build tag latest

- .github/workflows/publish_po_angular_ci-portal.yml
build(ci): ajusta publish portal
> build(ci): ajusta publish portal

- CHANGELOG.md
Desconsiderar este commit na lista do próximo changelog.
**Simulação**
> docs(changelog): ajuste p-small

- projects/ui/schematics/ng-update/v18/index.ts
> fix(schematics): corrige update em sub diretorios

- CHANGELOG.md
- package.json
> build: release 18.1.0

- projects/ui/src/lib/components/po-field/po-select/po-select.component.ts
> docs(select): inclui documentação de tokens

- CHANGELOG.md
- package.json
build: release 17.22.0 - DTHFUI-9626
> build: release 17.22.0 - DTHFUI-9626

- .github/workflows/publish_po_angular_ci-17.yml
> ci(lts): realiza a publicação de versões LTS

- CHANGELOG.md
- package.json
> build: release 18.2.0

- .gitignore
- package.json
- scripts/sonar.js
**< Scripts Sonar>**
**< DTHFUI-9609>**
O Sonar atual da master foi descontinuado, não temos a análise real do projeto po-angular.
Implementa a nova análise da platarforma Sonar compatível com o Angular@18
**Simulação**
> feat(sonar): habilita análise Sonar Totvs

- CHANGELOG.md
- package.json
> build: release 18.7.0

- CHANGELOG.md
- package.json
> build: release 17.26.1

- CHANGELOG.md
- package.json
> build: release 18.8.0

- projects/templates/src/lib/components/po-page-change-password/po-page-change-password-base.component.ts
- projects/templates/src/lib/components/po-page-change-password/po-page-change-password.component.html
- projects/templates/src/lib/components/po-page-login/po-page-login-base.component.ts
- projects/ui/src/lib/components/po-field/po-input/po-input-base.component.ts
- projects/ui/src/lib/components/po-field/po-login/po-login.component.spec.ts
- projects/ui/src/lib/components/po-field/po-login/po-login.component.ts
- projects/ui/src/lib/components/po-field/po-password/po-password.component.spec.ts
- projects/ui/src/lib/components/po-field/po-password/po-password.component.ts
> Autocomplete/dthf UI 9841

- projects/templates/src/lib/components/po-page-change-password/po-page-change-password-base.component.ts
- projects/templates/src/lib/components/po-page-change-password/po-page-change-password.component.html
- projects/templates/src/lib/components/po-page-login/po-page-login-base.component.ts
- projects/ui/src/lib/components/po-field/po-input/po-input-base.component.ts
- projects/ui/src/lib/components/po-field/po-login/po-login.component.spec.ts
- projects/ui/src/lib/components/po-field/po-login/po-login.component.ts
- projects/ui/src/lib/components/po-field/po-password/po-password.component.spec.ts
- projects/ui/src/lib/components/po-field/po-password/po-password.component.ts
> Autocomplete17/dthf UI 9841

- projects/ui/src/lib/components/po-field/po-input/po-input-base.component.ts
- projects/ui/src/lib/components/po-modal/po-modal-base.component.ts
- projects/ui/src/lib/components/po-page/po-page-default/po-page-default-base.component.ts
- projects/ui/src/lib/components/po-page/po-page-slide/po-page-slide-base.component.ts
- projects/ui/src/lib/components/po-tabs/po-tabs-base.component.ts
fixes: DTHFUI-9691
**Simulação**
[app.zip](https://github.com/user-attachments/files/17249504/app.zip)
Style:
https://github.com/po-ui/po-style/pull/628
theme-tvs:
https://github.com/totvs/po-theme-totvs/pull/384
```
/* token do modal de padding interno */
/* po-modal {
--padding-header: 3px 48px;
--padding-body: 18px 44px;
} */
/* margin laterais do po-tabs container */
/* po-tabs,
po-tab-button {
--margin-tabs-container-left: -4px;
--margin-tabs-container-right: -4px;
} */
/* padding interno do page-default */
/* po-page-content {
--padding-content: 90px;
} */
/* token do page-slide de padding interno */
/* po-page-slide {
--padding-header: …
```
> feat(components): permite melhor alinhamento

- CHANGELOG.md
- package.json
> build: release 17.26.2

- CHANGELOG.md
- package.json
> build: release 18.9.0

- CHANGELOG.md
- package.json
> build: release 17.26.3

- CHANGELOG.md
- package.json
> build: release 18.10.0

- projects/templates/src/lib/components/po-page-login/po-page-login-base.component.ts
- projects/templates/src/lib/components/po-page-login/po-page-login.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
- projects/ui/src/lib/components/po-field/po-switch/po-switch.component.html
- projects/ui/src/lib/components/po-field/po-switch/po-switch.component.ts
- projects/ui/src/lib/components/po-field/po-switch/samples/sample-po-switch-labs/sample-po-switch-labs.component.html
- projects/ui/src/lib/components/po-field/po-switch/samples/sample-po-switch-labs/sample-po-switch-labs.component.ts
- projects/ui/src/lib/components/po-table/po-table-list-manager/po-table-list-manager.component.html
> Page login17/dthf UI 9751

- projects/templates/src/lib/components/po-page-login/po-page-login-base.component.ts
- projects/templates/src/lib/components/po-page-login/po-page-login.component.html
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-fields/po-dynamic-form-fields.component.html
- projects/ui/src/lib/components/po-field/po-switch/po-switch.component.html
- projects/ui/src/lib/components/po-field/po-switch/po-switch.component.ts
- projects/ui/src/lib/components/po-field/po-switch/samples/sample-po-switch-labs/sample-po-switch-labs.component.html
- projects/ui/src/lib/components/po-field/po-switch/samples/sample-po-switch-labs/sample-po-switch-labs.component.ts
- projects/ui/src/lib/components/po-table/po-table-list-manager/po-table-list-manager.component.html
**Simulação**
STYLE: https://github.com/po-ui/po-style/pull/645
APP: 
[app.zip](https://github.com/user-attachments/files/17401419/app.zip)
> Page login/dthf UI 9751

- CHANGELOG.md
- package.json
> build: release 17.26.4

- CHANGELOG.md
- package.json
> build: release 18.11.0

- projects/ui/src/lib/components/po-container/po-container-base.component.ts
- projects/ui/src/lib/components/po-container/po-container.component.html
- projects/ui/src/lib/components/po-container/po-container.component.spec.ts
- projects/ui/src/lib/components/po-container/samples/sample-po-container-labs/sample-po-container-labs.component.html
- projects/ui/src/lib/components/po-container/samples/sample-po-container-labs/sample-po-container-labs.component.ts
- projects/ui/src/lib/components/po-disclaimer/po-disclaimer-base.component.spec.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-container/po-dynamic-container.component.html
- projects/ui/src/lib/components/po-field/po-upload/po-upload.component.spec.ts
**PO-CONTAINER**
**DTHFUI-9918**
Componente po-container não possibilita a adicão de titulo.
Adicionado propriedade `p-title` e tokens customizados para o titulo em `po-container`
**Simulação**
- buildar o style em: https://github.com/po-ui/po-style/pull/649 e adicionar no projeto
- app simulação funcionando: [simulação.zip](https://github.com/user-attachments/files/17466524/simulacao.zip)
> feat(container): adicionado titulo ao po-container

- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.html
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.spec.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.component.ts
- projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker.module.ts
**DATEPICKER**
**DTHFUI-10027**
**Simulação**
Portal e samples.
> fix(datepicker): corrige posicionamento do calendar

- package.json
- projects/ui/src/lib/utils/util.spec.ts
- projects/ui/src/lib/utils/util.ts
**UTIL**
**DTHFUI-10148**
Vulnerabilidades apontadas pelo Github a respeito da biblioteca `rollup`
Deixam de apontar vulnerabilidades apontadas pelo Github a respeito da biblioteca `rollup`
> fix: corrige vulnerabilidades mapeadas pelo sonar

- projects/ui/src/lib/components/po-field/po-input/po-mask.spec.ts
- projects/ui/src/lib/components/po-field/po-input/po-mask.ts
Corrige erro ao focar no botão e pressionar teclas diferentes de `enter` e `space`
DTHFUI-9908
**Simulação**
teste no portal
> fix(date-picker): corrige erro no console

- CHANGELOG.md
- package.json
> build: release 17.26.7

- CHANGELOG.md
- package.json
> build: release 18.14.0

- CHANGELOG.md
- package.json
> build: release v18.15.0

- CHANGELOG.md
- package.json
> build: release 17.26.8

- CHANGELOG.md
- package.json
> build: release 18.16.0

- CHANGELOG.md
- package.json
> build: release 18.17.0

- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-custom-action.interface.ts
- projects/templates/src/lib/components/po-page-dynamic-table/interfaces/po-page-dynamic-table-custom-table-action.interface.ts
- projects/ui/src/lib/components/po-badge/po-badge-base.component.ts
- projects/ui/src/lib/components/po-button-group/po-button-group-item.interface.ts
- projects/ui/src/lib/components/po-button/po-button-base.component.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
- projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-field.interface.ts
- projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts
- projects/ui/src/lib/components/po-field/po-input/po-input-base.component.ts
- projects/ui/src/lib/components/po-icon/po-icon.component.ts
- projects/ui/src/lib/components/po-listbox/po-item-list/interfaces/po-item-list-action.interface.ts
- projects/ui/src/lib/components/po-menu-panel/po-menu-panel-item/po-menu-panel-item.interface.ts
- projects/ui/src/lib/components/po-menu/po-menu-item.interface.ts
- projects/ui/src/lib/components/po-modal/po-modal-base.component.ts
- projects/ui/src/lib/components/po-navbar/interfaces/po-navbar-icon-action.interface.ts
- projects/ui/src/lib/components/po-page/po-page-list/po-page-list-base.component.ts
- projects/ui/src/lib/components/po-popup/po-popup-action.interface.ts
- projects/ui/src/lib/components/po-stepper/po-step/po-step.component.ts
- projects/ui/src/lib/components/po-stepper/po-stepper-base.component.ts
- projects/ui/src/lib/components/po-table/po-table-base.component.ts
- projects/ui/src/lib/components/po-table/po-table-column-icon/po-table-column-icon.interface.ts
- projects/ui/src/lib/components/po-table/po-table-column-label/po-table-column-label.interface.ts
- projects/ui/src/lib/components/po-tag/po-tag-base.component.ts
- projects/ui/src/lib/components/po-toolbar/po-toolbar-base.component.ts
Atualiza rotas para Biblioteca de ícones.
Atualiza descrição da propriedade `property`.
Fixes DTHFUI-9772
> docs: atualiza rotas para Biblioteca de ícones e atualiza descrição da propriedade property PoTableColumn

- .gitignore
- projects/app/src/app/app.module.ts
- projects/portal/src/app/app.component.ts
- projects/portal/src/app/theme-builder/theme-builder.component.css
- projects/portal/src/app/theme-builder/theme-builder.component.html
- projects/ui/src/lib/components/po-field/po-combo/po-combo.component.html
- projects/ui/src/lib/components/po-field/po-datepicker-range/po-datepicker-range.component.html
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup.component.html
- projects/ui/src/lib/po.module.ts
- projects/ui/src/lib/services/po-theme/enum/po-theme-a11y.enum.ts
- projects/ui/src/lib/services/po-theme/enum/po-theme-type.enum.ts
- projects/ui/src/lib/services/po-theme/helpers/accessibilities/po-theme-default-aa.constant.ts
- projects/ui/src/lib/services/po-theme/helpers/accessibilities/po-theme-default-aaa.constant.ts
- projects/ui/src/lib/services/po-theme/helpers/po-theme-poui.constant.ts
- projects/ui/src/lib/services/po-theme/helpers/types/po-theme-dark-defaults.constant.ts
- projects/ui/src/lib/services/po-theme/helpers/types/po-theme-light-defaults.constant.ts
- projects/ui/src/lib/services/po-theme/index.ts
- projects/ui/src/lib/services/po-theme/interfaces/po-theme.interface.ts
- projects/ui/src/lib/services/po-theme/po-theme.service.spec.ts
- projects/ui/src/lib/services/po-theme/po-theme.service.ts
- projects/ui/src/lib/services/po-theme/samples/sample-po-theme-labs/sample-po-theme-labs.component.ts
**Tema**
**DTHFUI-9037**
Adicionado possibilidade de passar mais de uma opção de tema de acessibilidade como exemplo: ‘AA’ e ‘AAA’.
**Simulação**
> feat(theme): adicionado melhoria no tema para diferentes acessibilidades

- CHANGELOG.md
- package.json
> build: release 18.20.0

- CHANGELOG.md
- package.json
> build: release v18.23.0

- CHANGELOG.md
> build: release 19.0.0-next.0

- CHANGELOG.md
- package.json
> build: release 17.26.11

- CHANGELOG.md
- package.json
> build: release 18.23.1

- CHANGELOG.md
- package.json
> build: release 19.0.0-rc.0

- CHANGELOG.md
- package.json
> build: release 17.26.12

- CHANGELOG.md
- package.json
> build: release 18.24.0

- .github/workflows/publish_po_angular_ci-portal.yml
fix(cd-portal): adiciona pasta de build do portal
> build(cd-portal): adiciona pasta de build do portal

- CHANGELOG.md
docs(changelog): configura html de exemplo
> docs(changelog): configura html de exemplo

- CHANGELOG.md
- package.json
> build: release 19.1.0

- projects/ui/src/lib/components/po-modal/po-modal-base.component.ts
**< PO-MODAL >**
**< DTHFUI-10217>**
Descrição de largura máxima que não está de acordo com o comportamento atual.
Remove a descrição que não estava de acordo com o comportamento real.
**Simulação**
Documentação do portal
> docs(modal): remove descrição de largura máxima

- CHANGELOG.md
- package.json
> build: release 17.26.13

- CHANGELOG.md
- package.json
> build: release 19.2.0

- CHANGELOG.md
- package.json
> build: release 17.26.14

- CHANGELOG.md
- package.json
> build: release 19.3.0

- projects/ui/src/lib/components/po-stepper/po-stepper.component.spec.ts
- projects/ui/src/lib/components/po-stepper/po-stepper.component.ts
Corrigido o fluxo de emissão do evento canActiveNextStep, garantindo que ocorra apenas quando necessário. Isso evita impactos na experiência do usuário e nas validações do produto.
Fixes DTHFUI-10628
> fix(stepper): evita validação excessiva de canActiveNextStep

- CHANGELOG.md
- package.json
> build: release 17.26.16

- CHANGELOG.md
- package.json
> build: release 19.4.0

- CHANGELOG.md
> docs(stepper): adiciona changelog do stepper

- CHANGELOG.md
- package.json
> build: release v17.26.17

- CHANGELOG.md
- package.json
> build: release 19.5.0

- CHANGELOG.md
- package.json
> build: release 19.5.1

- projects/ui/src/lib/components/po-tabs/po-tabs-base.component.ts
fixes DTHFUI-10847
**Simulação**
> feat(tabs): adiciona tokens para customização de espaçamentos

- projects/ui/src/lib/services/po-theme/po-theme.service.ts
> feat(theme): adiciona novo metodo para resetar tema

- projects/app/src/environments/environment.prod.ts
- projects/app/src/environments/environment.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.html
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.ts
fixes DTHFUI-10358
**Simulação**
> fix(lookup): corrige seleção multipla

- projects/ui/src/lib/components/po-chart-new/po-chart-new-base.component.spec.ts
- projects/ui/src/lib/components/po-chart-new/po-chart-new-base.component.ts
- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.spec.ts
- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-axis-options.interface.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-options.interface.ts
- projects/ui/src/lib/components/po-chart/po-chart-container/po-chart-circular/po-chart-circular-path/po-chart-tooltip.directive.spec.ts
- projects/ui/src/lib/services/po-color/po-color.service.spec.ts
Implementa propriedades para o grafico;
Implementa testes unitários.
Fixes DTHFUI-11041
**Simulação**
> feat(chart): implementa grafico tipo linha

- package.json
Os pacotes custom-idle-queue e @angular-devkit/build-angular dependem de uma versão vulnerável do @babel/runtime. Adiciona o override em ambos os pacotes para utilizar o @babel/runtime ~7.26.10, primeira versão com a vulnerabilidade corrigida.
Fixes: DTHFUI-11004
**storage**
**DTHFUI-11004**
Dois pacotes do po-ui, "custom-idle-queue" e "@angular-devkit/build-angular" dependem da biblioteca @babel/runtime em uma [versão vulnerável](https://github.com/advisories/GHSA-968p-4wvh-cqc8), sendo acusado no comando "npm audit" e em processos de análise de código:
Com a definição de dois overrides no "package.json" do projeto, a …
> fix(storage): sobrescreve dependência vulnerável @babel/runtime

- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.html
- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.spec.ts
- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-axis-options.interface.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-header-options.interface.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-options.interface.ts
- projects/ui/src/lib/directives/po-tooltip/po-tooltip.directive.spec.ts
- projects/ui/src/lib/services/po-color/po-color.service.spec.ts
- projects/ui/src/lib/services/po-color/po-color.service.ts
- projects/ui/src/lib/services/po-theme/helpers/po-theme-poui.constant.ts
- projects/ui/src/lib/services/po-theme/helpers/types/po-theme-dark-defaults.constant.ts
- projects/ui/src/lib/services/po-theme/helpers/types/po-theme-light-defaults.constant.ts
- projects/ui/src/lib/services/po-theme/interfaces/po-theme-color.interface.ts
- projects/ui/src/lib/services/po-theme/po-theme.service.ts
feat(charts): implementa chart do tipo area
> feat(charts): implementa chart do tipo area

- projects/ui/src/lib/components/po-chart-new/po-chart-new-base.component.ts
- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.html
- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.spec.ts
- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-axis-options.interface.ts
- projects/ui/src/lib/directives/po-tooltip/po-tooltip-base.directive.ts
- projects/ui/src/lib/directives/po-tooltip/po-tooltip.directive.spec.ts
- projects/ui/src/lib/directives/po-tooltip/po-tooltip.directive.ts
**Simulação**
[app.zip](https://github.com/user-attachments/files/19850793/app.zip)
> feat(charts): implementa chart do tipo column

- projects/ui/src/lib/components/po-chart-new/po-chart-grid-utils.ts
- projects/ui/src/lib/components/po-chart-new/po-chart-grid.utils.spec.ts
- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.html
- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.spec.ts
- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.ts
> feat(charts): implementa chart do tipo bar

- projects/ui/src/lib/components/po-chart-new/po-chart-grid-utils.ts
- projects/ui/src/lib/components/po-chart-new/po-chart-grid.utils.spec.ts
- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.html
- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.spec.ts
- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-axis-options.interface.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-options.interface.ts
Implementa bottom e top.
Fixes DTHFUI-11194
**Simulação**
> feat(chart): graph bar

- projects/ui/ng-package.json
- projects/ui/package.json
- projects/ui/src/lib/components/index.ts
- projects/ui/src/lib/components/po-chart-new/index.ts
- projects/ui/src/lib/components/po-chart-new/po-chart-grid-utils.ts
- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.spec.ts
- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.ts
- projects/ui/src/lib/services/po-color/po-color.service.ts
> feat(charts): ordenação dos styles

- projects/ui/src/lib/components/po-chart-new/po-chart-grid-utils.ts
- projects/ui/src/lib/components/po-chart-new/po-chart-grid.utils.spec.ts
- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.spec.ts
- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-options.interface.ts
**Simulação**
[app.zip](https://github.com/user-attachments/files/20189520/app.zip)
> feat(charts): implementa chart do tipo donut

- projects/ui/src/lib/components/po-chart-new/po-chart-grid-utils.ts
- projects/ui/src/lib/components/po-chart-new/po-chart-grid.utils.spec.ts
- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.ts
> fix(charts): ajusta importação do charts

- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.spec.ts
- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.ts
> feat(chart): implementa testes unitarios e ajustes

- CHANGELOG.md
- package.json
> build: release v19.12.0

- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.html
- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-options.interface.ts
- projects/ui/src/lib/services/po-theme/po-theme.service.ts
> feat(chart): corrige bugs terciarios

- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.spec.ts
- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.ts
> feat(chart): adiciona teste unitario para bug terciario

- projects/ui/src/lib/components/po-chart-new/po-chart-new-base.component.ts
- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-axis-options.interface.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-header-options.interface.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-literals.interface.ts
- projects/ui/src/lib/components/po-chart/interfaces/po-chart-options.interface.ts
> feat(chart): oculta novas propriedades

- projects/portal/docs/processors/helpers/functions.js
- projects/ui/src/lib/components/po-chart-new/po-chart-new.component.html
> feat(chart): implementa ajuste na documentacao

- projects/ui/src/lib/components/po-chart/po-chart.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart.component.ts
> feat(chart): implementa correção de bug no chart

- projects/ui/src/lib/components/po-chart/po-chart.component.ts
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-labs/sample-po-chart-labs.component.html
- projects/ui/src/lib/components/po-chart/samples/sample-po-chart-labs/sample-po-chart-labs.component.ts
> feat: gaugue atualizado e ajustes apontados do arthur

- projects/ui/src/lib/components/po-chart/po-chart-base.component.ts
- projects/ui/src/lib/components/po-chart/po-chart.component.spec.ts
- projects/ui/src/lib/components/po-chart/po-chart.component.ts
> feat(chart): implementa migração do po-chart-new para po-chart 3

- projects/ui/src/lib/components/po-chart/po-chart-grid-utils.spec.ts
> feat(chart): implementa migração do po-chart-new para po-chart 6

- projects/storage/tsconfig.lib.prod.json
- projects/sync/tsconfig.lib.prod.json
- projects/templates/tsconfig.lib.prod.json
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.html
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.spec.ts
- projects/ui/src/lib/components/po-field/po-lookup/po-lookup-modal/po-lookup-modal.component.ts
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-dropdown/po-multiselect-dropdown.component.ts
- projects/ui/src/lib/components/po-table/po-table-column-manager/po-table-column-manager.component.ts
- projects/ui/tsconfig.lib.prod.json
> build: define compilação partial para compatibilidade Angular 19+

- projects/ui/src/lib/components/po-disclaimer/po-disclaimer-base.component.ts
- projects/ui/src/lib/components/po-disclaimer/po-disclaimer.component.html
- projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect.component.html
- projects/ui/src/lib/components/po-tag/po-tag-base.component.ts
- projects/ui/src/lib/components/po-tag/po-tag.component.html
> fix(tag): cria propriedade interna

- .github/workflows/ci.yml
- .github/workflows/issue.yml
- projects/ui/src/lib/components/po-listbox/po-listbox.component.html
- projects/ui/src/lib/components/po-listbox/po-listbox.component.spec.ts
- projects/ui/src/lib/components/po-listbox/po-listbox.component.ts
- projects/ui/src/lib/components/po-popup/po-popup.component.html
> Integration toolbar/dthf UI 10678

- CHANGELOG.md
- package.json
> build: release v19.17.0

- CHANGELOG.md
- package.json
> build: release v19.18.0

- CHANGELOG.md
- package.json
> build: release v17.26.26

- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-components/sample-po-table-components.component.ts
**PO-TABLE**
**DTHFUI-11613**
**Simulação**
> fix(table): corrige alinhamento do ícone e label da ação única e alinhamento das colunas e mensagens sem itens

- projects/ui/src/lib/components/po-table/po-table.component.html
- projects/ui/src/lib/components/po-table/po-table.component.spec.ts
- projects/ui/src/lib/components/po-table/po-table.component.ts
- projects/ui/src/lib/components/po-table/samples/sample-po-table-components/sample-po-table-components.component.ts
**PO-TABLE**
**DTHFUI-11613**
**Simulação**
> fix(table): corrige alinhamento das colunas e mensagens sem itens

- CHANGELOG.md
- package.json
> build: release 17.26.27

- CHANGELOG.md
- package.json
> build: release 19.21.0

- CHANGELOG.md
- package.json
> build: release 19.25.0
